import AbelFormalization.AbelSmoothGenerators
import AbelFormalization.PolynomialEvaluationDerivative
import Mathlib.Analysis.Analytic.Polynomial
import Mathlib.Analysis.Calculus.Deriv.Inv

/-!
# The concrete geometric family generated by the Abel jets

`AbelNumerator A n` is the literal finite expression class generated by
multivariable polynomials, scalar affine functions, affine pullbacks of the
global Abel jets `Cr A r`, addition, multiplication, and affine substitution.
The scalar-affine constructor is only a convenient degree-at-most-one
polynomial constructor.  There is deliberately no constructor asserting
smoothness, closure under differentiation, or regular-zero finiteness.

`abelGeometricFamily A n` is its localization at the numerator expressions
which are nowhere zero.  Thus every member is represented by one finite
expression tree and one nowhere-zero finite expression tree, exactly as in
the manuscript's `H_n[D_n^{-1}]` construction.
-/

noncomputable section

open Set Function
open scoped ContDiff

namespace AbelFormalization

set_option autoImplicit false

/-- Finite numerator expressions generated by polynomials and affine Abel-jet
pullbacks.  The dimension is part of the inductive index. -/
inductive AbelNumerator (A : ℝ → ℝ) :
    (n : ℕ) → RealEuclideanFunction n → Prop
  | polynomial {n : ℕ} (P : MvPolynomial (Fin n) ℝ) :
      AbelNumerator A n (fun x ↦ MvPolynomial.eval x P)
  | affine {n : ℕ} (ℓ : RealEuclidean n →ᵃ[ℝ] ℝ) :
      AbelNumerator A n ℓ
  | crAffine {n : ℕ} (r : ℕ) (ℓ : RealEuclidean n →ᵃ[ℝ] ℝ) :
      AbelNumerator A n (Cr A r ∘ ℓ)
  | add {n : ℕ} {f g : RealEuclideanFunction n} :
      AbelNumerator A n f → AbelNumerator A n g → AbelNumerator A n (f + g)
  | mul {n : ℕ} {f g : RealEuclideanFunction n} :
      AbelNumerator A n f → AbelNumerator A n g → AbelNumerator A n (f * g)
  | affineComp {m n : ℕ} {f : RealEuclideanFunction n} :
      AbelNumerator A n f → (ℓ : RealEuclidean m →ᵃ[ℝ] RealEuclidean n) →
        AbelNumerator A m (f ∘ ℓ)

/-- The explicit degree-at-most-one polynomial representing a scalar affine
functional. -/
def affinePolynomial {n : ℕ} (ℓ : RealEuclidean n →ᵃ[ℝ] ℝ) :
    MvPolynomial (Fin n) ℝ :=
  MvPolynomial.C (ℓ 0) +
    ∑ i, MvPolynomial.C (ℓ.linear (Pi.single i 1)) * MvPolynomial.X i

/-- Evaluation of `affinePolynomial` is the original affine functional.  This
shows that the `AbelNumerator.affine` constructor is a syntactic convenience,
not an enlargement of the generated function class. -/
theorem eval_affinePolynomial {n : ℕ}
    (ℓ : RealEuclidean n →ᵃ[ℝ] ℝ) (x : RealEuclidean n) :
    MvPolynomial.eval x (affinePolynomial ℓ) = ℓ x := by
  classical
  rw [ℓ.decomp]
  simp only [affinePolynomial, map_add, MvPolynomial.eval_C, map_sum,
    map_mul, MvPolynomial.eval_X, Pi.add_apply]
  rw [add_comm]
  congr 1
  rw [← Finset.univ_sum_single x, map_sum]
  apply Finset.sum_congr rfl
  intro i _
  have hi : Pi.single i (x i) = x i • Pi.single i (1 : ℝ) := by
    ext k
    by_cases hki : k = i <;> simp [hki]
  rw [hi, map_smul]
  simp [mul_comm]

namespace AbelNumerator

variable {A : ℝ → ℝ}

/-- Membership respects equality of the represented functions. -/
theorem congr_of_eq {n : ℕ} {f g : RealEuclideanFunction n}
    (hf : AbelNumerator A n f) (hfg : f = g) : AbelNumerator A n g := by
  subst g
  exact hf

theorem const {n : ℕ} (c : ℝ) :
    AbelNumerator A n (fun _ : RealEuclidean n ↦ c) := by
  simpa only [MvPolynomial.eval_C] using
    (AbelNumerator.polynomial (A := A) (n := n) (MvPolynomial.C c))

/-- The affine constructor can always be replaced by the polynomial
constructor with `affinePolynomial`. -/
theorem affine_from_polynomial {n : ℕ}
    (ℓ : RealEuclidean n →ᵃ[ℝ] ℝ) : AbelNumerator A n ℓ := by
  refine (AbelNumerator.polynomial (A := A) (affinePolynomial ℓ)).congr_of_eq ?_
  funext x
  exact eval_affinePolynomial ℓ x

theorem zero {n : ℕ} : AbelNumerator A n (0 : RealEuclideanFunction n) := by
  change AbelNumerator A n (fun _ : RealEuclidean n ↦ 0)
  exact const 0

theorem one {n : ℕ} : AbelNumerator A n (1 : RealEuclideanFunction n) := by
  change AbelNumerator A n (fun _ : RealEuclidean n ↦ 1)
  exact const 1

theorem neg {n : ℕ} {f : RealEuclideanFunction n}
    (hf : AbelNumerator A n f) : AbelNumerator A n (-f) := by
  have h := AbelNumerator.mul (const (n := n) (-1)) hf
  exact h.congr_of_eq (by funext x; simp)

theorem sub {n : ℕ} {f g : RealEuclideanFunction n}
    (hf : AbelNumerator A n f) (hg : AbelNumerator A n g) :
    AbelNumerator A n (f - g) := by
  simpa only [sub_eq_add_neg] using AbelNumerator.add hf hg.neg

theorem pow {n : ℕ} {f : RealEuclideanFunction n}
    (hf : AbelNumerator A n f) : ∀ k : ℕ, AbelNumerator A n (f ^ k)
  | 0 => by simpa using (one (A := A) (n := n))
  | k + 1 => by
      simpa only [pow_succ] using AbelNumerator.mul (pow hf k) hf

theorem finset_sum {n : ℕ} {ι : Type*} (s : Finset ι)
    (f : ι → RealEuclideanFunction n)
    (hf : ∀ i ∈ s, AbelNumerator A n (f i)) :
    AbelNumerator A n (∑ i ∈ s, f i) := by
  classical
  induction s using Finset.induction_on with
  | empty => simpa using (zero (A := A) (n := n))
  | @insert i s hi ih =>
      rw [Finset.sum_insert hi]
      exact AbelNumerator.add (hf i (Finset.mem_insert_self i s))
        (ih fun j hj ↦ hf j (Finset.mem_insert_of_mem hj))

/-- Every finite numerator expression is globally smooth. -/
theorem contDiff (hA : IsAbel A) {n : ℕ} {f : RealEuclideanFunction n}
    (hf : AbelNumerator A n f) : ContDiff ℝ ∞ f := by
  induction hf with
  | polynomial P => exact (AnalyticOnNhd.eval_mvPolynomial P).contDiff
  | affine ℓ =>
      exact (continuousAffineMapOfRealEuclidean ℓ).contDiff
  | crAffine r ℓ => exact hA.contDiff_Cr_comp_affine r ℓ
  | add _ _ ihf ihg => exact ihf.add ihg
  | mul _ _ ihf ihg => exact ihf.mul ihg
  | affineComp _ ℓ ih =>
      exact ih.comp (continuousAffineMapOfRealEuclidean ℓ).contDiff

/-- The derivative of a scalar function in the `j`th coordinate direction. -/
def coordinateFDeriv {n : ℕ} (f : RealEuclideanFunction n) (j : Fin n) :
    RealEuclideanFunction n :=
  fun x ↦ fderiv ℝ f x (Pi.single j 1)

/-- Coordinate differentiation can be eliminated inside the finite numerator
syntax.  In the affine-substitution case the chain rule becomes the explicit
finite sum over the source coordinates. -/
theorem coordinateFDeriv_mem (hA : IsAbel A)
    {n : ℕ} {f : RealEuclideanFunction n} (hf : AbelNumerator A n f) :
    ∀ j : Fin n, AbelNumerator A n (coordinateFDeriv f j) := by
  induction hf with
  | polynomial P =>
      intro j
      classical
      refine (AbelNumerator.polynomial (A := A)
        (MvPolynomial.pderiv j P)).congr_of_eq ?_
      funext x
      simp [coordinateFDeriv, fderiv_polynomial_eval_apply, Pi.single_apply]
  | affine ℓ =>
      intro j
      refine (const (A := A) (ℓ.linear (Pi.single j 1))).congr_of_eq ?_
      funext x
      simp [coordinateFDeriv, fderiv_realEuclideanAffineMap_apply]
  | @crAffine n r ℓ =>
      intro j
      let c : ℝ := 2 * ℓ.linear (Pi.single j 1)
      have hc : AbelNumerator A n (fun _ : RealEuclidean n ↦ c) := const c
      have hprod := AbelNumerator.mul
        (AbelNumerator.mul hc (AbelNumerator.affine (A := A) ℓ))
        (AbelNumerator.crAffine (A := A) (r + 1) ℓ)
      refine hprod.congr_of_eq ?_
      funext x
      change c * ℓ x * Cr A (r + 1) (ℓ x) =
        fderiv ℝ (Cr A r ∘ ℓ) x (Pi.single j 1)
      rw [hA.fderiv_Cr_comp_affine_single,
        fderiv_realEuclideanAffineMap_apply]
      dsimp [c]
      ring
  | @add n f g hf hg ihf ihg =>
      intro j
      refine (AbelNumerator.add (ihf j) (ihg j)).congr_of_eq ?_
      funext x
      change coordinateFDeriv _ j x + coordinateFDeriv _ j x =
        coordinateFDeriv (_ + _) j x
      unfold coordinateFDeriv
      rw [fderiv_add
        ((hf.contDiff hA).differentiable (by simp)).differentiableAt
        ((hg.contDiff hA).differentiable (by simp)).differentiableAt]
      rfl
  | @mul n f g hf hg ihf ihg =>
      intro j
      have hsum := AbelNumerator.add
        (AbelNumerator.mul hf (ihg j))
        (AbelNumerator.mul hg (ihf j))
      refine hsum.congr_of_eq ?_
      funext x
      change f x * coordinateFDeriv g j x +
          g x * coordinateFDeriv f j x =
        coordinateFDeriv (f * g) j x
      unfold coordinateFDeriv
      rw [fderiv_mul
        ((hf.contDiff hA).differentiable (by simp)).differentiableAt
        ((hg.contDiff hA).differentiable (by simp)).differentiableAt]
      rfl
  | @affineComp m n f hf ℓ ih =>
      intro j
      let c : Fin n → ℝ := fun i ↦ ℓ.linear (Pi.single j 1) i
      let term : Fin n → RealEuclideanFunction m := fun i x ↦
        c i * coordinateFDeriv f i (ℓ x)
      have hterm : ∀ i ∈ Finset.univ, AbelNumerator A m (term i) := by
        intro i _
        have hc : AbelNumerator A m (fun _ : RealEuclidean m ↦ c i) := const (c i)
        have hd : AbelNumerator A m (coordinateFDeriv f i ∘ ℓ) :=
          AbelNumerator.affineComp (ih i) ℓ
        exact (AbelNumerator.mul hc hd).congr_of_eq (by rfl)
      have hsum : AbelNumerator A m (∑ i ∈ Finset.univ, term i) :=
        finset_sum Finset.univ term hterm
      refine hsum.congr_of_eq ?_
      funext x
      have hfDiff : DifferentiableAt ℝ f (ℓ x) :=
        ((hf.contDiff hA).differentiable (by simp)).differentiableAt
      have hℓDiff : DifferentiableAt ℝ ℓ x :=
        (analyticAt_realEuclideanAffineMap ℓ x).differentiableAt
      unfold coordinateFDeriv
      rw [fderiv_comp (𝕜 := ℝ) (f := (ℓ : RealEuclidean m → RealEuclidean n))
        (g := f) x hfDiff hℓDiff]
      simp only [ContinuousLinearMap.comp_apply,
        fderiv_realEuclideanAffineMap_apply]
      simp only [Finset.sum_apply]
      dsimp [term, c, coordinateFDeriv]
      let D := fderiv ℝ f (ℓ x)
      let v := ℓ.linear (Pi.single j 1)
      change (∑ i, v i * D (Pi.single i 1)) = D v
      calc
        (∑ i, v i * D (Pi.single i 1)) =
            D (∑ i, Pi.single i (v i)) := by
          rw [map_sum]
          apply Finset.sum_congr rfl
          intro i _
          have hi : Pi.single i (v i) = v i • Pi.single i (1 : ℝ) := by
            ext k
            by_cases hki : k = i <;> simp [hki]
          rw [hi, map_smul]
          rfl
        _ = D v := by rw [Finset.univ_sum_single]

end AbelNumerator

/-- The actual set of numerator functions represented by the finite syntax. -/
def abelNumeratorFamily (A : ℝ → ℝ) (n : ℕ) :
    Set (RealEuclideanFunction n) :=
  {f | AbelNumerator A n f}

/-- Localization of the finite numerator class at its everywhere-nonzero
members. -/
def abelGeometricFamily (A : ℝ → ℝ) (n : ℕ) :
    Set (RealEuclideanFunction n) :=
  {f | ∃ P Q : RealEuclideanFunction n,
    AbelNumerator A n P ∧ AbelNumerator A n Q ∧
      (∀ x, Q x ≠ 0) ∧ f = P / Q}

theorem mem_abelGeometricFamily_iff {A : ℝ → ℝ} {n : ℕ}
    {f : RealEuclideanFunction n} :
    f ∈ abelGeometricFamily A n ↔
      ∃ P Q : RealEuclideanFunction n,
        AbelNumerator A n P ∧ AbelNumerator A n Q ∧
          (∀ x, Q x ≠ 0) ∧ f = P / Q :=
  Iff.rfl

namespace AbelNumerator

variable {A : ℝ → ℝ}

/-- A numerator expression embeds in the localization using denominator one. -/
theorem mem_abelGeometricFamily {n : ℕ} {f : RealEuclideanFunction n}
    (hf : AbelNumerator A n f) : f ∈ abelGeometricFamily A n := by
  refine ⟨f, 1, hf, one, ?_, ?_⟩
  · intro x
    simp
  · funext x
    simp

end AbelNumerator

theorem abelGeometricFamily_add {A : ℝ → ℝ} {n : ℕ}
    {f g : RealEuclideanFunction n}
    (hf : f ∈ abelGeometricFamily A n)
    (hg : g ∈ abelGeometricFamily A n) :
    f + g ∈ abelGeometricFamily A n := by
  rcases hf with ⟨P, Q, hP, hQ, hQ0, rfl⟩
  rcases hg with ⟨R, S, hR, hS, hS0, rfl⟩
  refine ⟨P * S + R * Q, Q * S,
    AbelNumerator.add (AbelNumerator.mul hP hS) (AbelNumerator.mul hR hQ),
    AbelNumerator.mul hQ hS, ?_, ?_⟩
  · intro x
    exact mul_ne_zero (hQ0 x) (hS0 x)
  · funext x
    change P x / Q x + R x / S x =
      (P x * S x + R x * Q x) / (Q x * S x)
    field_simp [hQ0 x, hS0 x]

theorem abelGeometricFamily_mul {A : ℝ → ℝ} {n : ℕ}
    {f g : RealEuclideanFunction n}
    (hf : f ∈ abelGeometricFamily A n)
    (hg : g ∈ abelGeometricFamily A n) :
    f * g ∈ abelGeometricFamily A n := by
  rcases hf with ⟨P, Q, hP, hQ, hQ0, rfl⟩
  rcases hg with ⟨R, S, hR, hS, hS0, rfl⟩
  refine ⟨P * R, Q * S, AbelNumerator.mul hP hR,
    AbelNumerator.mul hQ hS, ?_, ?_⟩
  · intro x
    exact mul_ne_zero (hQ0 x) (hS0 x)
  · funext x
    change (P x / Q x) * (R x / S x) =
      (P x * R x) / (Q x * S x)
    field_simp [hQ0 x, hS0 x]

theorem abelGeometricFamily_inv {A : ℝ → ℝ} {n : ℕ}
    {f : RealEuclideanFunction n}
    (hf : f ∈ abelGeometricFamily A n) (hf0 : ∀ x, f x ≠ 0) :
    f⁻¹ ∈ abelGeometricFamily A n := by
  rcases hf with ⟨P, Q, hP, hQ, hQ0, rfl⟩
  have hP0 : ∀ x, P x ≠ 0 := by
    intro x hPx
    apply hf0 x
    simp [hPx]
  refine ⟨Q, P, hQ, hP, hP0, ?_⟩
  funext x
  change (P x / Q x)⁻¹ = Q x / P x
  field_simp [hP0 x, hQ0 x]

theorem abelGeometricFamily_polynomial {A : ℝ → ℝ} {n : ℕ}
    (P : MvPolynomial (Fin n) ℝ) :
    (fun x ↦ MvPolynomial.eval x P) ∈ abelGeometricFamily A n :=
  (AbelNumerator.polynomial P).mem_abelGeometricFamily

theorem abelGeometricFamily_affine_comp {A : ℝ → ℝ} {m n : ℕ}
    {f : RealEuclideanFunction n} (hf : f ∈ abelGeometricFamily A n)
    (ℓ : RealEuclidean m →ᵃ[ℝ] RealEuclidean n) :
    f ∘ ℓ ∈ abelGeometricFamily A m := by
  rcases hf with ⟨P, Q, hP, hQ, hQ0, rfl⟩
  refine ⟨P ∘ ℓ, Q ∘ ℓ, AbelNumerator.affineComp hP ℓ,
    AbelNumerator.affineComp hQ ℓ, ?_, ?_⟩
  · intro x
    exact hQ0 (ℓ x)
  · rfl

/-- The localization is a geometric function family.  This algebraic fact
does not require the Abel hypotheses. -/
theorem isGeometricFunctionFamily_abelGeometricFamily (A : ℝ → ℝ) :
    IsGeometricFunctionFamily (abelGeometricFamily A) where
  add hf hg := abelGeometricFamily_add hf hg
  mul hf hg := abelGeometricFamily_mul hf hg
  inv hf h0 := abelGeometricFamily_inv hf h0
  polynomial P := abelGeometricFamily_polynomial P
  affine_comp hf ℓ := abelGeometricFamily_affine_comp hf ℓ

namespace IsAbel

variable {A : ℝ → ℝ} (hA : IsAbel A)

include hA

/-- Every member of the localized family is globally smooth. -/
theorem isEverywhereSmooth_abelGeometricFamily :
    IsEverywhereSmoothFunctionFamily (abelGeometricFamily A) := by
  intro n f hf
  rcases hf with ⟨P, Q, hP, hQ, hQ0, hPQ⟩
  rw [hPQ]
  exact (hP.contDiff hA).div (hQ.contDiff hA) hQ0

omit hA in
/-- Directional Fréchet form of the scalar quotient rule. -/
theorem fderiv_div_apply_direction {n : ℕ}
    {P Q : RealEuclideanFunction n} {x v : RealEuclidean n}
    (hP : DifferentiableAt ℝ P x) (hQ : DifferentiableAt ℝ Q x)
    (hQ0 : Q x ≠ 0) :
    fderiv ℝ (P / Q) x v =
      (Q x * fderiv ℝ P x v - P x * fderiv ℝ Q x v) / Q x ^ 2 := by
  have hInv : HasFDerivAt (fun y ↦ (Q y)⁻¹)
      ((-(Q x ^ 2)⁻¹) • fderiv ℝ Q x) x :=
    (hasDerivAt_inv hQ0).comp_hasFDerivAt x hQ.hasFDerivAt
  have hDiv : HasFDerivAt (fun y ↦ P y * (Q y)⁻¹)
      (P x • ((-(Q x ^ 2)⁻¹) • fderiv ℝ Q x) +
        (Q x)⁻¹ • fderiv ℝ P x) x :=
    hP.hasFDerivAt.mul hInv
  change fderiv ℝ (fun y ↦ P y * (Q y)⁻¹) x v = _
  rw [hDiv.fderiv]
  simp only [add_apply, smul_apply, smul_eq_mul]
  field_simp [hQ0]
  ring

/-- The localized family is closed under every coordinate derivative. -/
theorem isCoordinateDerivativeClosed_abelGeometricFamily :
    IsCoordinateDerivativeClosedFunctionFamily (abelGeometricFamily A) := by
  intro n f hf j
  change AbelNumerator.coordinateFDeriv f j ∈ abelGeometricFamily A n
  rcases hf with ⟨P, Q, hP, hQ, hQ0, hPQ⟩
  rw [hPQ]
  refine ⟨Q * AbelNumerator.coordinateFDeriv P j -
      P * AbelNumerator.coordinateFDeriv Q j,
    Q ^ 2,
    AbelNumerator.sub
      (AbelNumerator.mul hQ (hP.coordinateFDeriv_mem hA j))
      (AbelNumerator.mul hP (hQ.coordinateFDeriv_mem hA j)),
    hQ.pow 2, ?_, ?_⟩
  · intro x
    exact pow_ne_zero 2 (hQ0 x)
  · funext x
    change fderiv ℝ (P / Q) x (Pi.single j 1) =
      (Q x * fderiv ℝ P x (Pi.single j 1) -
        P x * fderiv ℝ Q x (Pi.single j 1)) / Q x ^ 2
    exact fderiv_div_apply_direction
      ((hP.contDiff hA).differentiable (by simp) x)
      ((hQ.contDiff hA).differentiable (by simp) x) (hQ0 x)

/-- The three concrete structural properties required before applying a
uniform-fiber theorem. -/
theorem geometric_smooth_derivativeClosed_abelGeometricFamily :
    IsGeometricFunctionFamily (abelGeometricFamily A) ∧
      IsEverywhereSmoothFunctionFamily (abelGeometricFamily A) ∧
        IsCoordinateDerivativeClosedFunctionFamily (abelGeometricFamily A) :=
  ⟨isGeometricFunctionFamily_abelGeometricFamily A,
    hA.isEverywhereSmooth_abelGeometricFamily,
    hA.isCoordinateDerivativeClosed_abelGeometricFamily⟩

end IsAbel

/-- Every affine pullback of every Abel jet is a member of the localization. -/
theorem Cr_comp_affine_mem_abelGeometricFamily
    (A : ℝ → ℝ) {n : ℕ} (r : ℕ)
    (ℓ : RealEuclidean n →ᵃ[ℝ] ℝ) :
    Cr A r ∘ ℓ ∈ abelGeometricFamily A n :=
  (AbelNumerator.crAffine r ℓ).mem_abelGeometricFamily

/-- The sole coordinate on `ℝ¹`, as an affine functional. -/
def firstCoordinateAffine : RealEuclidean 1 →ᵃ[ℝ] ℝ :=
  AffineMap.proj 0

@[simp]
theorem firstCoordinateAffine_apply (x : RealEuclidean 1) :
    firstCoordinateAffine x = x 0 :=
  rfl

/-- The unary `C_r` generator, expressed on the project's `Fin 1` coordinate
space, belongs to the localized family. -/
theorem Cr_firstCoordinate_mem_abelGeometricFamily (A : ℝ → ℝ) (r : ℕ) :
    (fun x : RealEuclidean 1 ↦ Cr A r (x 0)) ∈ abelGeometricFamily A 1 := by
  change (Cr A r ∘ (firstCoordinateAffine : RealEuclidean 1 → ℝ)) ∈
    abelGeometricFamily A 1
  exact Cr_comp_affine_mem_abelGeometricFamily A r firstCoordinateAffine

/-- In particular the language generator `C0` belongs to the unary family. -/
theorem C0_firstCoordinate_mem_abelGeometricFamily (A : ℝ → ℝ) :
    (fun x : RealEuclidean 1 ↦ C0 A (x 0)) ∈ abelGeometricFamily A 1 := by
  simpa only [Cr_zero] using Cr_firstCoordinate_mem_abelGeometricFamily A 0

/-- An affine graph equation for an Abel jet is already a numerator, hence a
member of the localization. -/
theorem affine_sub_Cr_comp_affine_mem_abelGeometricFamily
    (A : ℝ → ℝ) {n : ℕ} (r : ℕ)
    (y ℓ : RealEuclidean n →ᵃ[ℝ] ℝ) :
    (fun x ↦ y x - Cr A r (ℓ x)) ∈ abelGeometricFamily A n := by
  have hy : AbelNumerator A n y := AbelNumerator.affine_from_polynomial y
  have hcr : AbelNumerator A n (Cr A r ∘ ℓ) := AbelNumerator.crAffine r ℓ
  have h := AbelNumerator.sub hy hcr
  exact h.congr_of_eq (by rfl) |>.mem_abelGeometricFamily

end AbelFormalization
