import AbelFormalization.AnalyticGermDomain
import Mathlib.Analysis.Analytic.IsolatedZeros
import Mathlib.RingTheory.DiscreteValuationRing.Basic
import Mathlib.RingTheory.KrullDimension.PID

/-! # One-variable analytic germs

The analytic order-of-vanishing theorem factors each nonzero real analytic
germ into a power of the local coordinate and a unit. Choosing the least
order in an ideal proves that every ideal is principal. Thus this actual
germ ring is Noetherian, a discrete valuation ring, and has dimension one.
-/

noncomputable section

open Filter Set
open scoped Topology

namespace AbelFormalization

/-- The local coordinate in the ring of germs at a real point. -/
def analyticGermParameter (x : ℝ) : AnalyticGermAt x :=
  analyticGermOf (fun y => y - x) (analyticAt_id.sub analyticAt_const)

@[simp]
theorem analyticGermValue_parameter (x : ℝ) :
    analyticGermValue x (analyticGermParameter x) = 0 := by
  simp [analyticGermParameter]

theorem analyticGermParameter_ne_zero (x : ℝ) : analyticGermParameter x ≠ 0 := by
  intro h
  have he : (fun y : ℝ => y - x) =ᶠ[𝓝 x] 0 :=
    (analyticGermOf_eq_zero_iff _).mp h
  have hd := he.deriv_eq
  simp at hd

/-- Every nonzero germ is a power of the local coordinate times a unit. -/
theorem analyticGerm_exists_parameter_pow_mul_unit {x : ℝ}
    (a : AnalyticGermAt x) (ha : a ≠ 0) :
    ∃ n : ℕ, ∃ u : AnalyticGermAt x, IsUnit u ∧
      a = analyticGermParameter x ^ n * u := by
  obtain ⟨f, hf, rfl⟩ := exists_analyticGerm_representative a
  have hfne : ¬ ∀ᶠ y in 𝓝 x, f y = 0 := by
    intro hz
    exact ha ((analyticGermOf_eq_zero_iff hf).mpr hz)
  obtain ⟨n, g, hg, hg0, he⟩ := hf.exists_eventuallyEq_pow_smul_nonzero_iff.mpr hfne
  refine ⟨n, analyticGermOf g hg, (isUnit_analyticGerm_iff _).mpr hg0, ?_⟩
  change analyticGermOf f hf =
    analyticGermOf (fun y => (y - x) ^ n * g y)
      (((analyticAt_id.sub analyticAt_const).pow n).mul hg)
  apply (analyticGermOf_eq_iff _ _).mpr
  exact he

/-- A nonzero ideal is generated by a power of the local coordinate. The
exponent is the least order occurring in that ideal. -/
theorem analyticGerm_ideal_eq_span_parameter_pow {x : ℝ}
    (I : Ideal (AnalyticGermAt x)) (hI : I ≠ ⊥) :
    ∃ n : ℕ, I = Ideal.span {analyticGermParameter x ^ n} := by
  classical
  have hex : ∃ n : ℕ, analyticGermParameter x ^ n ∈ I := by
    obtain ⟨a, haI, ha⟩ := (Submodule.ne_bot_iff I).mp hI
    obtain ⟨n, u, hu, he⟩ := analyticGerm_exists_parameter_pow_mul_unit a ha
    refine ⟨n, (I.mul_unit_mem_iff_mem hu).mp ?_⟩
    rwa [← he]
  let n := Nat.find hex
  have hn : analyticGermParameter x ^ n ∈ I := Nat.find_spec hex
  refine ⟨n, le_antisymm ?_ (Ideal.span_le.mpr (Set.singleton_subset_iff.mpr hn))⟩
  intro a haI
  by_cases ha : a = 0
  · simp [ha]
  obtain ⟨k, u, hu, he⟩ := analyticGerm_exists_parameter_pow_mul_unit a ha
  have hk : analyticGermParameter x ^ k ∈ I := (I.mul_unit_mem_iff_mem hu).mp (he ▸ haI)
  have hnk : n ≤ k := Nat.find_min' hex hk
  rw [Ideal.mem_span_singleton, he]
  exact dvd_mul_of_dvd_left (pow_dvd_pow _ hnk) _

instance analyticGermOneVariableIsPrincipalIdealRing (x : ℝ) :
    IsPrincipalIdealRing (AnalyticGermAt x) where
  principal I := by
    by_cases hI : I = ⊥
    · subst I
      infer_instance
    obtain ⟨n, hn⟩ := analyticGerm_ideal_eq_span_parameter_pow I hI
    exact ⟨⟨analyticGermParameter x ^ n, hn⟩⟩

theorem analyticGerm_one_variable_isNoetherian (x : ℝ) :
    IsNoetherianRing (AnalyticGermAt x) := inferInstance

theorem analyticGerm_one_variable_maximalIdeal_ne_bot (x : ℝ) :
    IsLocalRing.maximalIdeal (AnalyticGermAt x) ≠ ⊥ := by
  intro h
  have hp : analyticGermParameter x ∈ IsLocalRing.maximalIdeal (AnalyticGermAt x) := by
    rw [analyticGerm_mem_maximalIdeal_iff, analyticGermValue_parameter]
  rw [h, Ideal.mem_bot] at hp
  exact analyticGermParameter_ne_zero x hp

instance analyticGermOneVariableIsDiscreteValuationRing (x : ℝ) :
    IsDiscreteValuationRing (AnalyticGermAt x) where
  not_a_field' := analyticGerm_one_variable_maximalIdeal_ne_bot x

theorem analyticGerm_one_variable_ringKrullDim (x : ℝ) :
    ringKrullDim (AnalyticGermAt x) = 1 :=
  IsPrincipalIdealRing.ringKrullDim_eq_one _ (IsDiscreteValuationRing.not_isField _)

end AbelFormalization
