import AbelFormalization.AnalyticHadamard
import AbelFormalization.AnalyticGermDerivation
import Mathlib.RingTheory.Finiteness.Basic
import Mathlib.RingTheory.Ideal.Span

/-! # Coordinate generators of the analytic-germ maximal ideal

The convergent analytic Hadamard decomposition proves that the unique maximal
ideal of the actual real-analytic germ ring is generated by its coordinate
germs. This finite-generation result holds in every finite dimension and is
proved without assuming that the ring is Noetherian.
-/

noncomputable section

open Filter
open scoped Topology

namespace AbelFormalization

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]

/-- Formation of analytic germs commutes with finite sums of analytic
representatives. -/
theorem analyticGermOf_finset_sum {ι : Type*} (s : Finset ι) {x : E}
    (f : ι → E → ℝ) (hf : ∀ i, AnalyticAt ℝ (f i) x) :
    analyticGermOf (∑ i ∈ s, f i) (s.analyticAt_sum fun i _ => hf i) =
      ∑ i ∈ s, analyticGermOf (f i) (hf i) := by
  apply Subtype.ext
  change (Germ.coeRingHom (𝓝 x)) (∑ i ∈ s, f i) =
    (analyticGermSubring x).subtype (∑ i ∈ s, analyticGermOf (f i) (hf i))
  simp only [map_sum]
  rfl

/-- Every analytic germ vanishing at the origin is a linear combination of
the coordinate germs, with coefficients in the actual analytic germ ring. -/
theorem analyticGerm_exists_eq_sum_coordinates (p : ℕ) (f : RealAnalyticGerm p)
    (hf : analyticGermValue (0 : Fin p → ℝ) f = 0) :
    ∃ g : Fin p → RealAnalyticGerm p,
      f = ∑ i, analyticGermCoordinate p i * g i := by
  obtain ⟨f, hfa, rfl⟩ := exists_analyticGerm_representative f
  change f 0 = 0 at hf
  obtain ⟨g, hg, hEq⟩ := analyticAt_exists_sub_eq_sum_coordinates hfa
  let hcoord (i : Fin p) : AnalyticAt ℝ (fun x : Fin p → ℝ => x i) 0 :=
    (ContinuousLinearMap.proj i : (Fin p → ℝ) →L[ℝ] ℝ).analyticAt 0
  let hm (i : Fin p) : AnalyticAt ℝ (fun x : Fin p → ℝ => x i * g i x) 0 :=
    (hcoord i).fun_mul (hg i)
  refine ⟨fun i => analyticGermOf (g i) (hg i), ?_⟩
  have he : analyticGermOf f hfa =
      analyticGermOf (∑ i, fun x : Fin p → ℝ => x i * g i x)
        (Finset.univ.analyticAt_sum fun i _ => hm i) := by
    apply (analyticGermOf_eq_iff _ _).mpr
    filter_upwards [hEq] with x hx
    simpa only [hf, sub_zero, Finset.sum_apply] using hx
  rw [he, analyticGermOf_finset_sum Finset.univ (fun i (x : Fin p → ℝ) => x i * g i x) hm]
  apply Finset.sum_congr rfl
  intro i hi
  rfl

/-- The maximal ideal is exactly the ideal spanned by all coordinate germs. -/
theorem analyticGerm_maximalIdeal_eq_span_coordinates (p : ℕ) :
    IsLocalRing.maximalIdeal (RealAnalyticGerm p) =
      Ideal.span (Set.range (analyticGermCoordinate p)) := by
  apply le_antisymm
  · intro f hf
    obtain ⟨g, rfl⟩ := analyticGerm_exists_eq_sum_coordinates p f
      ((analyticGerm_mem_maximalIdeal_iff f).mp hf)
    apply Submodule.sum_mem
    intro i hi
    exact Ideal.mul_mem_right _ _ Ideal.mem_span_range_self
  · apply Ideal.span_le.mpr
    rintro f ⟨i, rfl⟩
    exact (analyticGerm_mem_maximalIdeal_iff (analyticGermCoordinate p i)).mpr rfl

/-- Finite generation of the analytic maximal ideal in every finite dimension
follows from analytic convergence, without a Noetherian hypothesis. -/
theorem analyticGerm_maximalIdeal_fg (p : ℕ) :
    (IsLocalRing.maximalIdeal (RealAnalyticGerm p)).FG := by
  rw [analyticGerm_maximalIdeal_eq_span_coordinates]
  exact Submodule.fg_span (Set.finite_range _)

end AbelFormalization
