import AbelFormalization.DerivationHeight
import AbelFormalization.PolynomialGermDerivations
import AbelFormalization.FullRankMinor

/-!
# The algebraic augmented Jacobian ideal

Adjoining an inverse of the squared-minor sum forces the ideal generated by
the functions and the inverse relation to have the required height. This
module works in the actual source ring with actual coefficient and symbol
derivations. It does not assume regularity of prime localizations.
-/

noncomputable section

namespace AbelFormalization

variable {K S : Type*} [Field K] [CharZero K] [CommRing S] [Algebra K S]
variable {n : ℕ}

/-- The added inverse relation is placed first in the generator tuple. -/
def polynomialUnitAugmentedTuple (f : Fin n → S) (d : S) : Fin (n + 1) → Polynomial S :=
  Fin.cons (Polynomial.X * Polynomial.C d - 1) (fun i => Polynomial.C (f i))

def polynomialUnitAugmentedIdeal (f : Fin n → S) (d : S) : Ideal (Polynomial S) :=
  Ideal.span (Set.range (polynomialUnitAugmentedTuple f d))

/-- The new variable derivative comes first, followed by coefficient
extensions of the given derivations. -/
def polynomialAugmentedDerivations (D : Fin n → Derivation K S S) :
    Fin (n + 1) → Derivation K (Polynomial S) (Polynomial S) :=
  Fin.cons polynomialSymbolDerivation (fun i => polynomialCoefficientDerivation (D i))

/-- A block determinant formula with the leading one-element block made
explicit on `Fin (n+1)`. -/
theorem det_fin_succ_of_first_row (A : Matrix (Fin (n + 1)) (Fin (n + 1)) S)
    (hrow : ∀ j : Fin n, A 0 j.succ = 0) :
    A.det = A 0 0 * (A.submatrix Fin.succ Fin.succ).det := by
  classical
  rw [Matrix.det_succ_row_zero, Fin.sum_univ_succ]
  simp [hrow, Fin.succAbove_zero]

omit [CharZero K] in
/-- The augmented derivation determinant is the coefficient image of the
old determinant multiplied by the inverted element. -/
theorem polynomialAugmentedDerivations_determinant
    (f : Fin n → S) (D : Fin n → Derivation K S S) (d : S) :
    Matrix.det (fun i j => polynomialAugmentedDerivations D i
      (polynomialUnitAugmentedTuple f d j)) =
        Polynomial.C (d * Matrix.det (fun i j => D i (f j))) := by
  classical
  let A : Matrix (Fin (n + 1)) (Fin (n + 1)) (Polynomial S) :=
    fun i j => polynomialAugmentedDerivations D i (polynomialUnitAugmentedTuple f d j)
  have hrow : ∀ j : Fin n, A 0 j.succ = 0 := by
    intro j
    simp [A, polynomialAugmentedDerivations, polynomialUnitAugmentedTuple]
  have h00 : A 0 0 = Polynomial.C d := by
    simp [A, polynomialAugmentedDerivations, polynomialUnitAugmentedTuple]
  have htail : A.submatrix Fin.succ Fin.succ =
      (fun i j => Polynomial.C (D i (f j))) := by
    funext i j
    change polynomialCoefficientDerivation (D i) (Polynomial.C (f j)) = _
    exact polynomialCoefficientDerivation_C (D i) (f j)
  let M : Matrix (Fin n) (Fin n) S := fun i j => D i (f j)
  have hmapEntries : (fun i j : Fin n => Polynomial.C (D i (f j))) =
      M.map Polynomial.C := rfl
  have hmap : Matrix.det (fun i j : Fin n => Polynomial.C (D i (f j))) =
      Polynomial.C (Matrix.det M) :=
    (congrArg Matrix.det hmapEntries).trans
      ((Polynomial.C : S →+* Polynomial S).map_det M).symm
  refine (det_fin_succ_of_first_row A hrow).trans ?_
  rw [h00, htail, hmap]
  exact ((Polynomial.C : S →+* Polynomial S).map_mul d _).symm

variable {ι : Type*} [Fintype ι]

/-- The conventional Jacobian has functions as rows and derivations as
columns, matching the matrix used in the ordinary chain rule. -/
def derivationJacobian (f : Fin n → S) (D : ι → Derivation K S S) :
    Matrix (Fin n) ι S := fun i j => D j (f i)

/-- The scalar used for the inverse relation is exactly the finite sum of
squares of all injectively selected formal column minors. -/
def derivationJacobianDenominator (f : Fin n → S) (D : ι → Derivation K S S) : S :=
  sumSquaresColumnMinors (derivationJacobian f D)

omit [CharZero K] [Fintype ι] in
theorem derivationJacobian_minor_transpose (f : Fin n → S)
    (D : ι → Derivation K S S) (c : Fin n ↪ ι) :
    Matrix.det (fun i j => D (c i) (f j)) =
      ((derivationJacobian f D).submatrix id c).det := by
  change (((derivationJacobian f D).submatrix id c).transpose).det = _
  exact Matrix.det_transpose _

/-- Adjoining the inverse squared-minor relation raises the required height
to the number of original equations plus one. No regularity or Noetherianity
is needed for this algebraic determinant argument. -/
theorem polynomialUnitAugmentedIdeal_height (f : Fin n → S)
    (D : ι → Derivation K S S) :
    ((n + 1 : ℕ) : ℕ∞) ≤
      (polynomialUnitAugmentedIdeal f (derivationJacobianDenominator f D)).height := by
  classical
  let d := derivationJacobianDenominator f D
  let J := polynomialUnitAugmentedIdeal f d
  change ((n + 1 : ℕ) : ℕ∞) ≤ J.height
  rw [J.height_eq_inf_minimalPrimes]
  refine le_iInf₂ fun p hp => ?_
  let : p.IsPrime := hp.isPrime
  have hgen : ∀ i, polynomialUnitAugmentedTuple f d i ∈ p := by
    intro i
    exact hp.le (Ideal.subset_span ⟨i, rfl⟩)
  have hd : Polynomial.C d ∉ p := by
    intro hCd
    have hXCd := p.mul_mem_left Polynomial.X hCd
    have hrel : Polynomial.X * Polynomial.C d - 1 ∈ p := hgen 0
    have hone := p.sub_mem hXCd hrel
    have h1 : (1 : Polynomial S) ∈ p := by
      convert hone using 1
      ring
    exact hp.isPrime.ne_top (p.eq_top_iff_one.mpr h1)
  have hc : ∃ c : Fin n ↪ ι,
      Polynomial.C (((derivationJacobian f D).submatrix id c).det) ∉ p := by
    by_contra! h
    apply hd
    change Polynomial.C (∑ c : Fin n ↪ ι,
      ((derivationJacobian f D).submatrix id c).det ^ 2) ∈ p
    rw [map_sum]
    apply Ideal.sum_mem
    intro c _
    rw [map_pow, pow_two]
    exact p.mul_mem_left _ (h c)
  obtain ⟨c, hc⟩ := hc
  have hdet : Matrix.det (fun i j =>
      polynomialAugmentedDerivations (fun i => D (c i)) i
        (polynomialUnitAugmentedTuple f d j)) ∉ p := by
    rw [polynomialAugmentedDerivations_determinant,
      derivationJacobian_minor_transpose, map_mul]
    exact hp.isPrime.mul_notMem hd hc
  exact height_ge_of_derivation_determinant (polynomialUnitAugmentedTuple f d)
    (polynomialAugmentedDerivations (fun i => D (c i))) p hgen hdet

end AbelFormalization
