import AbelFormalization.CentralLaurentContraction

set_option autoImplicit false

/-!
# The central polynomial-to-Laurent map is a localization

The central Laurent presentation first groups the independent variables over
the retained polynomial ring and then inverts those independent variables.
This file transports the existing finite Laurent localization instance across
that grouping equivalence.
-/

noncomputable section

namespace AbelFormalization

/-- The source submonoid generated by the independent variables, expressed as
the pullback of the standard variable submonoid after grouping variables. -/
def centralLaurentVariableSubmonoid
    (R : Type*) [CommRing R] (ι : Type*) (h : ℕ) :
    Submonoid (MvPolynomial (Fin h ⊕ ι) R) :=
  (laurentVariableSubmonoid (Fin h) (MvPolynomial ι R)).comap
    (MvPolynomial.sumAlgEquiv R (Fin h) ι).toRingEquiv.toMonoidHom

/-- Use the literal central Laurent map as the algebra structure map. -/
local instance centralLaurentPolynomialAlgebra
    (R : Type*) [CommRing R] (ι : Type*) (h : ℕ) :
    Algebra (MvPolynomial (Fin h ⊕ ι) R)
      (AddMonoidAlgebra (MvPolynomial ι R) (Fin h → ℤ)) :=
  (centralLaurentPolynomialMap R ι h).toAlgebra

/-- The central polynomial-to-Laurent inclusion is the localization which
inverts the independent variables. -/
theorem centralLaurentPolynomial_isLocalization
    (R : Type*) [CommRing R] (ι : Type*) (h : ℕ) :
    IsLocalization (centralLaurentVariableSubmonoid R ι h)
      (AddMonoidAlgebra (MvPolynomial ι R) (Fin h → ℤ)) := by
  apply IsLocalization.of_ringEquiv_left
    (R := MvPolynomial (Fin h ⊕ ι) R)
    (S := MvPolynomial (Fin h) (MvPolynomial ι R))
    (K := AddMonoidAlgebra (MvPolynomial ι R) (Fin h → ℤ))
    (M₁ := laurentVariableSubmonoid (Fin h) (MvPolynomial ι R))
    (M₂ := centralLaurentVariableSubmonoid R ι h)
    (MvPolynomial.sumAlgEquiv R (Fin h) ι).toRingEquiv
  · exact Submonoid.map_comap_eq_of_surjective
      (MvPolynomial.sumAlgEquiv R (Fin h) ι).surjective _
  · intro x
    rfl

end AbelFormalization
