import AbelFormalization.ClosedZeroSetCharbonnelBridge

/-!
# Linear-equivalence images in the literal-zero Charbonnel closure

This file proves Wilkie's WS4 clause for the Charbonnel closure generated by
literal zero sets.  A general real-linear equivalence does not preserve the
integer coefficients in an `IsIntegerAffineSet` description cut, so the
coordinate-reindexing induction from `CharbonnelDescriptionAlgebra` does not
apply directly.

Instead, an integer-affine cut is first represented by one literal polynomial
zero set.  Its image is again a literal zero set, and the existing closed-base
intersection construction combines it with the transformed inner description.
Consequently the proof needs global smoothness explicitly: that is precisely
the premise used by the closed-base intersection theorem.  No assertion that
arbitrary linear equivalences preserve integer-affine syntax is made.
-/

noncomputable section

open Set Function
open scoped BigOperators

namespace AbelFormalization

set_option autoImplicit false

/-! ## Integer-affine cuts as literal polynomial zero sets -/

/-- The sum-of-squares polynomial attached to a finite affine system. -/
def integerAffineSystemPolynomial {n r : ℕ}
    (coeff : Fin r → Fin n → ℤ) (constant : Fin r → ℤ) :
    MvPolynomial (Fin n) ℝ :=
  ∑ i : Fin r,
    ((∑ j : Fin n,
        MvPolynomial.C (coeff i j : ℝ) * MvPolynomial.X j) +
      MvPolynomial.C (constant i : ℝ)) ^ 2

@[simp]
theorem eval_integerAffineSystemPolynomial {n r : ℕ}
    (coeff : Fin r → Fin n → ℤ) (constant : Fin r → ℤ)
    (x : RealEuclidean n) :
    MvPolynomial.eval x (integerAffineSystemPolynomial coeff constant) =
      ∑ i : Fin r,
        ((∑ j : Fin n, (coeff i j : ℝ) * x j) +
          (constant i : ℝ)) ^ 2 := by
  classical
  simp only [integerAffineSystemPolynomial, map_sum, MvPolynomial.eval_pow,
    map_add, map_mul, MvPolynomial.eval_C, MvPolynomial.eval_X]

/-- Every integer-affine set is already a literal zero-set generator.  This
does not say that its image under an arbitrary real-linear equivalence is
integer-affine; the image is instead obtained from base-family WS4 below. -/
theorem IsIntegerAffineSet.mem_literalZeroSetFamily
    {G : (n : ℕ) → Set (RealEuclideanFunction n)}
    (hG : IsGeometricFunctionFamily G) {n : ℕ}
    {L : Set (RealEuclidean n)} (hL : IsIntegerAffineSet L) :
    L ∈ literalZeroSetFamily G n := by
  obtain ⟨r, coeff, constant, rfl⟩ := hL
  let P : MvPolynomial (Fin n) ℝ :=
    integerAffineSystemPolynomial coeff constant
  refine ⟨fun x ↦ MvPolynomial.eval x P, hG.polynomial P, ?_⟩
  ext x
  simp only [Set.mem_setOf_eq, P, eval_integerAffineSystemPolynomial]
  rw [Finset.sum_sq_eq_zero_iff]
  simp

/-! ## Extending a linear equivalence over hidden coordinates -/

/-- Apply a linear equivalence to an initial visible block and leave the final
hidden block fixed. -/
def realEuclideanVisibleBlockLinearEquiv {n : ℕ}
    (e : RealEuclidean n ≃ₗ[ℝ] RealEuclidean n) (q : ℕ) :
    RealEuclidean (n + q) ≃ₗ[ℝ] RealEuclidean (n + q) :=
  (realEuclideanAppendLinearEquiv n q).symm |>.trans
    (e.prodCongr (LinearEquiv.refl ℝ (RealEuclidean q))) |>.trans
      (realEuclideanAppendLinearEquiv n q)

@[simp]
theorem realEuclideanVisibleBlockLinearEquiv_append
    {n q : ℕ} (e : RealEuclidean n ≃ₗ[ℝ] RealEuclidean n)
    (x : RealEuclidean n) (z : RealEuclidean q) :
    realEuclideanVisibleBlockLinearEquiv e q (realEuclideanAppend x z) =
      realEuclideanAppend (e x) z := by
  let E := realEuclideanAppendLinearEquiv n q
  change E ((e.prodCongr (LinearEquiv.refl ℝ (RealEuclidean q)))
      (E.symm (realEuclideanAppend x z))) = realEuclideanAppend (e x) z
  have happend : realEuclideanAppend x z = E (x, z) := rfl
  rw [happend, E.symm_apply_apply]
  rfl

/-- Extending a visible linear equivalence by the identity on the hidden block
commutes with existential projection. -/
theorem realEuclideanExistentialProjection_visibleBlockLinearEquiv_image
    {n q : ℕ} (e : RealEuclidean n ≃ₗ[ℝ] RealEuclidean n)
    (A : Set (RealEuclidean (n + q))) :
    realEuclideanExistentialProjection
        (realEuclideanVisibleBlockLinearEquiv e q '' A) =
      e '' realEuclideanExistentialProjection A := by
  ext y
  simp only [realEuclideanExistentialProjection, Set.mem_setOf_eq]
  constructor
  · rintro ⟨z, u, hu, heu⟩
    refine ⟨realEuclideanTakeLeft u, ⟨realEuclideanTakeRight u, ?_⟩, ?_⟩
    · rw [realEuclideanAppend_takeLeft_takeRight]
      exact hu
    · have hmap :
          realEuclideanVisibleBlockLinearEquiv e q u =
            realEuclideanAppend (e (realEuclideanTakeLeft u))
              (realEuclideanTakeRight u) := by
        calc
          realEuclideanVisibleBlockLinearEquiv e q u =
              realEuclideanVisibleBlockLinearEquiv e q
                (realEuclideanAppend (realEuclideanTakeLeft u)
                  (realEuclideanTakeRight u)) := by
                    rw [realEuclideanAppend_takeLeft_takeRight]
          _ = realEuclideanAppend (e (realEuclideanTakeLeft u))
                (realEuclideanTakeRight u) :=
            realEuclideanVisibleBlockLinearEquiv_append e _ _
      have hvisible := congrArg
        (realEuclideanTakeLeft (n := n) (m := q)) (hmap.symm.trans heu)
      simpa using hvisible
  · rintro ⟨x, hx, rfl⟩
    obtain ⟨z, hxz⟩ := hx
    refine ⟨z, realEuclideanAppend x z, hxz, ?_⟩
    exact realEuclideanVisibleBlockLinearEquiv_append e x z

/-! ## Description and closure WS4 -/

/-- Every arbitrary real-linear image of a literal-zero Charbonnel
description has another description.  Rank is deliberately not claimed to be
preserved: in the integer-affine case the transformed cut is implemented by
the general description-intersection construction. -/
theorem CharbonnelDescription.exists_literalZeroSet_linearEquiv_image
    {G : (n : ℕ) → Set (RealEuclideanFunction n)}
    (hG : IsGeometricFunctionFamily G)
    (hsmooth : IsEverywhereSmoothFunctionFamily G)
    {n : ℕ}
    (description : CharbonnelDescription (literalZeroSetFamily G) n) :
    ∀ e : RealEuclidean n ≃ₗ[ℝ] RealEuclidean n,
      ∃ transformed : CharbonnelDescription (literalZeroSetFamily G) n,
        transformed.carrier = e '' description.carrier := by
  induction description with
  | @base n hn A hA =>
      intro e
      exact ⟨.base hn (e '' A)
        (literalZeroSetFamily_linearEquiv_image_mem hG hA e), rfl⟩
  | @union n left right ihleft ihright =>
      intro e
      obtain ⟨left', hleft'⟩ := ihleft e
      obtain ⟨right', hright'⟩ := ihright e
      refine ⟨.union left' right', ?_⟩
      simp only [CharbonnelDescription.carrier_union, hleft', hright',
        Set.image_union]
  | @integerAffineInter n inner L hL ih =>
      intro e
      obtain ⟨inner', hinner'⟩ := ih e
      have hLbase : L ∈ literalZeroSetFamily G n :=
        hL.mem_literalZeroSetFamily hG
      have heLbase : e '' L ∈ literalZeroSetFamily G n :=
        literalZeroSetFamily_linearEquiv_image_mem hG hLbase e
      let cut : CharbonnelDescription (literalZeroSetFamily G) n :=
        .base inner.positiveArity (e '' L) heLbase
      obtain ⟨transformed, htransformed, _hrank⟩ :=
        literalZeroSetFamily_exists_inter_description hG hsmooth inner' cut
      refine ⟨transformed, ?_⟩
      rw [htransformed, hinner']
      change (e '' inner.carrier) ∩ (e '' L) = e '' (inner.carrier ∩ L)
      exact (Set.image_inter e.injective).symm
  | @projection n q hn inner ih =>
      intro e
      let E := realEuclideanVisibleBlockLinearEquiv e q
      obtain ⟨inner', hinner'⟩ := ih E
      refine ⟨.projection hn inner', ?_⟩
      simp only [CharbonnelDescription.carrier_projection, hinner', E]
      exact
        realEuclideanExistentialProjection_visibleBlockLinearEquiv_image
          e inner.carrier
  | @topologicalClosure n inner ih =>
      intro e
      obtain ⟨inner', hinner'⟩ := ih e
      refine ⟨.topologicalClosure inner', ?_⟩
      simp only [CharbonnelDescription.carrier_topologicalClosure, hinner']
      exact (e.toContinuousLinearEquiv.image_closure inner.carrier).symm

/-- Wilkie WS4 for the Charbonnel closure over literal zero sets.  The
smoothness premise is explicit because it supplies the closed literal base
needed in the transformed integer-affine-cut case. -/
theorem literalZeroSet_charbonnelClosure_linearEquiv_image
    {G : (n : ℕ) → Set (RealEuclideanFunction n)}
    (hG : IsGeometricFunctionFamily G)
    (hsmooth : IsEverywhereSmoothFunctionFamily G)
    {n : ℕ} {A : Set (RealEuclidean n)}
    (hA : A ∈ charbonnelClosure (literalZeroSetFamily G) n)
    (e : RealEuclidean n ≃ₗ[ℝ] RealEuclidean n) :
    e '' A ∈ charbonnelClosure (literalZeroSetFamily G) n := by
  obtain ⟨description, hdescription⟩ := hA
  obtain ⟨transformed, htransformed⟩ :=
    description.exists_literalZeroSet_linearEquiv_image hG hsmooth e
  refine ⟨transformed, ?_⟩
  rw [htransformed, hdescription]

/-- The literal-zero Charbonnel closure satisfies all four positive-arity weak
structure clauses.  WS4 is the arbitrary linear-equivalence theorem above;
the other clauses reuse the existing closed-base and projected-zero bridges. -/
theorem literalZeroSet_charbonnelClosure_positiveArityWeakSetStructure
    {G : (n : ℕ) → Set (RealEuclideanFunction n)}
    (hG : IsGeometricFunctionFamily G)
    (hsmooth : IsEverywhereSmoothFunctionFamily G) :
    PositiveArityWeakSetStructure
      (charbonnelClosure (literalZeroSetFamily G)) := by
  refine
    { ws1_inter := ?_
      ws2_polynomialSign := ?_
      ws3_prod := ?_
      ws4_linearEquiv := ?_ }
  · intro n _hn A B hA hB
    exact literalZeroSet_charbonnelClosure_inter hG hsmooth hA hB
  · intro n hn A hA
    exact (hA.isProjectedZeroSet hG).mem_literalZeroSet_charbonnelClosure hn
  · intro n m _hn _hm A B hA hB
    exact literalZeroSet_charbonnelClosure_product hG hsmooth hA hB
  · intro n _hn A hA e
    exact literalZeroSet_charbonnelClosure_linearEquiv_image hG hsmooth hA e

end AbelFormalization
