import AbelFormalization.ProjectedZeroFirstOrderBridge

/-!
# Positive-arity descriptions for the Charbonnel closure

This file formalizes the syntactic closure construction used in the theorem
of the complement.  A description starts with a set in a positive-arity base
family and is built using the five operations in the source: binary union,
intersection with a `ℤ`-affine set, projection onto an initial coordinate
block, and topological closure.  Its rank has the source weights
`0`, `1`, `1`, `1`, and `4`, respectively.

This is only the description language and its elementary semantics.  It does
not assert that the closure is closed under complements, and it uses no
complement-principle hypothesis.
-/

noncomputable section

open Set
open scoped BigOperators

namespace AbelFormalization

set_option autoImplicit false

/-- A dimension-indexed family of subsets of finite real coordinate spaces.
Only its positive-dimensional entries are used below, as in the source. -/
abbrev EuclideanSetFamily :=
  (n : ℕ) → Set (Set (RealEuclidean n))

/-- A `ℤ`-affine set is the simultaneous zero set of finitely many affine
linear polynomials with integer coefficients. -/
def IsIntegerAffineSet {n : ℕ} (L : Set (RealEuclidean n)) : Prop :=
  ∃ (r : ℕ) (coeff : Fin r → Fin n → ℤ) (constant : Fin r → ℤ),
    L = {x | ∀ i, (∑ j, (coeff i j : ℝ) * x j) + (constant i : ℝ) = 0}

/-- A positive-arity description in the Charbonnel closure generated by
`S`.  The constructors are the generator clauses of the source definition. -/
inductive CharbonnelDescription (S : EuclideanSetFamily) : ℕ → Type
  | base {n : ℕ} (hn : 0 < n) (A : Set (RealEuclidean n)) (hA : A ∈ S n) :
      CharbonnelDescription S n
  | union {n : ℕ} (left right : CharbonnelDescription S n) :
      CharbonnelDescription S n
  | integerAffineInter {n : ℕ} (description : CharbonnelDescription S n)
      (L : Set (RealEuclidean n)) (hL : IsIntegerAffineSet L) :
      CharbonnelDescription S n
  | projection {n k : ℕ} (hn : 0 < n)
      (description : CharbonnelDescription S (n + k)) :
      CharbonnelDescription S n
  | topologicalClosure {n : ℕ} (description : CharbonnelDescription S n) :
      CharbonnelDescription S n

namespace CharbonnelDescription

variable {S : EuclideanSetFamily}

/-- The set denoted by a Charbonnel description. -/
def carrier : ∀ {n : ℕ}, CharbonnelDescription S n → Set (RealEuclidean n)
  | _, .base _ A _ => A
  | _, .union left right => carrier left ∪ carrier right
  | _, .integerAffineInter description L _ => carrier description ∩ L
  | _, .projection _ description =>
      realEuclideanExistentialProjection (carrier description)
  | _, .topologicalClosure description => closure (carrier description)

/-- The rank of a description, with the weights used in the complement
theorem's induction. -/
def rank : ∀ {n : ℕ}, CharbonnelDescription S n → ℕ
  | _, .base _ _ _ => 0
  | _, .union left right => 1 + max (rank left) (rank right)
  | _, .integerAffineInter description _ _ => 1 + rank description
  | _, .projection _ description => 1 + rank description
  | _, .topologicalClosure description => 4 + rank description

/-- Every description has positive ambient arity. -/
theorem positiveArity : ∀ {n : ℕ}, CharbonnelDescription S n → 0 < n
  | _, .base hn _ _ => hn
  | _, .union left _ => positiveArity left
  | _, .integerAffineInter description _ _ => positiveArity description
  | _, .projection hn _ => hn
  | _, .topologicalClosure description => positiveArity description

@[simp]
theorem carrier_base {n : ℕ} (hn : 0 < n) (A : Set (RealEuclidean n))
    (hA : A ∈ S n) :
    carrier (.base hn A hA) = A :=
  rfl

@[simp]
theorem carrier_union {n : ℕ}
    (left right : CharbonnelDescription S n) :
    carrier (.union left right) = carrier left ∪ carrier right :=
  rfl

@[simp]
theorem carrier_integerAffineInter {n : ℕ}
    (description : CharbonnelDescription S n)
    (L : Set (RealEuclidean n)) (hL : IsIntegerAffineSet L) :
    carrier (.integerAffineInter description L hL) =
      carrier description ∩ L :=
  rfl

@[simp]
theorem carrier_projection {n k : ℕ} (hn : 0 < n)
    (description : CharbonnelDescription S (n + k)) :
    carrier (.projection hn description) =
      realEuclideanExistentialProjection (carrier description) :=
  rfl

@[simp]
theorem carrier_topologicalClosure {n : ℕ}
    (description : CharbonnelDescription S n) :
    carrier (.topologicalClosure description) = closure (carrier description) :=
  rfl

@[simp]
theorem rank_base {n : ℕ} (hn : 0 < n) (A : Set (RealEuclidean n))
    (hA : A ∈ S n) :
    rank (.base hn A hA) = 0 :=
  rfl

@[simp]
theorem rank_union {n : ℕ}
    (left right : CharbonnelDescription S n) :
    rank (.union left right) = 1 + max (rank left) (rank right) :=
  rfl

@[simp]
theorem rank_integerAffineInter {n : ℕ}
    (description : CharbonnelDescription S n)
    (L : Set (RealEuclidean n)) (hL : IsIntegerAffineSet L) :
    rank (.integerAffineInter description L hL) = 1 + rank description :=
  rfl

@[simp]
theorem rank_projection {n k : ℕ} (hn : 0 < n)
    (description : CharbonnelDescription S (n + k)) :
    rank (.projection hn description) = 1 + rank description :=
  rfl

@[simp]
theorem rank_topologicalClosure {n : ℕ}
    (description : CharbonnelDescription S n) :
    rank (.topologicalClosure description) = 4 + rank description :=
  rfl

end CharbonnelDescription

/-- The Charbonnel closure is the family of sets denoted by finite
Charbonnel descriptions. -/
def charbonnelClosure (S : EuclideanSetFamily) : EuclideanSetFamily :=
  fun n => {A | ∃ description : CharbonnelDescription S n,
    description.carrier = A}

theorem mem_charbonnelClosure_iff
    {S : EuclideanSetFamily} {n : ℕ} {A : Set (RealEuclidean n)} :
    A ∈ charbonnelClosure S n ↔
      ∃ description : CharbonnelDescription S n,
        description.carrier = A :=
  Iff.rfl

/-- Positive-dimensional base sets embed into their Charbonnel closure. -/
theorem mem_charbonnelClosure_of_mem
    {S : EuclideanSetFamily} {n : ℕ} (hn : 0 < n)
    {A : Set (RealEuclidean n)} (hA : A ∈ S n) :
    A ∈ charbonnelClosure S n :=
  ⟨.base hn A hA, rfl⟩

/-- The generated closure is closed under binary union. -/
theorem charbonnelClosure_union
    {S : EuclideanSetFamily} {n : ℕ} {A B : Set (RealEuclidean n)}
    (hA : A ∈ charbonnelClosure S n)
    (hB : B ∈ charbonnelClosure S n) :
    A ∪ B ∈ charbonnelClosure S n := by
  obtain ⟨left, hleft⟩ := hA
  obtain ⟨right, hright⟩ := hB
  refine ⟨.union left right, ?_⟩
  simp only [CharbonnelDescription.carrier_union, hleft, hright]

/-- The generated closure is closed under intersection with a
`ℤ`-affine set. -/
theorem charbonnelClosure_integerAffineInter
    {S : EuclideanSetFamily} {n : ℕ} {A L : Set (RealEuclidean n)}
    (hA : A ∈ charbonnelClosure S n) (hL : IsIntegerAffineSet L) :
    A ∩ L ∈ charbonnelClosure S n := by
  obtain ⟨description, hdescription⟩ := hA
  refine ⟨.integerAffineInter description L hL, ?_⟩
  simp only [CharbonnelDescription.carrier_integerAffineInter,
    hdescription]

/-- The generated closure is closed under projection onto a positive-sized
initial coordinate block. -/
theorem charbonnelClosure_projection
    {S : EuclideanSetFamily} {n k : ℕ} (hn : 0 < n)
    {A : Set (RealEuclidean (n + k))}
    (hA : A ∈ charbonnelClosure S (n + k)) :
    realEuclideanExistentialProjection A ∈ charbonnelClosure S n := by
  obtain ⟨description, hdescription⟩ := hA
  refine ⟨.projection hn description, ?_⟩
  simp only [CharbonnelDescription.carrier_projection, hdescription]

/-- The generated closure is closed under topological closure. -/
theorem charbonnelClosure_topologicalClosure
    {S : EuclideanSetFamily} {n : ℕ} {A : Set (RealEuclidean n)}
    (hA : A ∈ charbonnelClosure S n) :
    closure A ∈ charbonnelClosure S n := by
  obtain ⟨description, hdescription⟩ := hA
  refine ⟨.topologicalClosure description, ?_⟩
  simp only [CharbonnelDescription.carrier_topologicalClosure,
    hdescription]

/-- There are no zero-arity descriptions: the source construction starts at
arity one. -/
theorem charbonnelClosure_zero (S : EuclideanSetFamily) :
    charbonnelClosure S 0 = ∅ := by
  ext A
  simp only [mem_charbonnelClosure_iff, Set.mem_empty_iff_false, iff_false]
  rintro ⟨description, _⟩
  exact (Nat.not_lt_zero 0 description.positiveArity)

/-- The projected-zero family, viewed as the base set family for the
Charbonnel construction. -/
def projectedZeroSetFamily
    (G : (n : ℕ) → Set (RealEuclideanFunction n)) : EuclideanSetFamily :=
  fun _n => {A | IsProjectedZeroSet G A}

/-- The Charbonnel closure generated by projected zero sets. -/
def projectedZeroCharbonnelClosure
    (G : (n : ℕ) → Set (RealEuclideanFunction n)) : EuclideanSetFamily :=
  charbonnelClosure (projectedZeroSetFamily G)

/-- A positive-arity projected zero set has a literal rank-zero base
description. -/
theorem IsProjectedZeroSet.exists_rank_zero_charbonnelDescription
    {G : (n : ℕ) → Set (RealEuclideanFunction n)}
    {n : ℕ} (hn : 0 < n) {A : Set (RealEuclidean n)}
    (hA : IsProjectedZeroSet G A) :
    ∃ description : CharbonnelDescription (projectedZeroSetFamily G) n,
      description.carrier = A ∧ description.rank = 0 := by
  refine ⟨.base hn A hA, rfl, ?_⟩
  rfl

/-- Every positive-arity projected zero set is a rank-zero member of the
corresponding Charbonnel closure. -/
theorem IsProjectedZeroSet.mem_projectedZeroCharbonnelClosure
    {G : (n : ℕ) → Set (RealEuclideanFunction n)}
    {n : ℕ} (hn : 0 < n) {A : Set (RealEuclidean n)}
    (hA : IsProjectedZeroSet G A) :
    A ∈ projectedZeroCharbonnelClosure G n :=
  mem_charbonnelClosure_of_mem hn hA

end AbelFormalization
