import AbelFormalization.CharbonnelMaxwellClosureBound

/-!
# Affine-section component bounds by Charbonnel rank induction

This file completes the numeric rank induction for the WS5 clause of the
Charbonnel closure generated by literal zero sets.  The non-elementary
topological-closure case is exactly
`CharbonnelDescription.hasAffineSectionComponentBound_topologicalClosure`;
the remaining constructors are handled here.

The conclusion is deliberately only WS5.  No complement closure, closed-lift
clause, or full weak-structure package is asserted.
-/

noncomputable section

open Set Function

namespace AbelFormalization

set_option autoImplicit false

/-! ## Literal generators as projected zero sets -/

/-- A literal zero set is a projected zero set with a zero-dimensional
witness block. -/
theorem IsLiteralZeroSet.isProjectedZeroSet
    {G : (n : ℕ) → Set (RealEuclideanFunction n)}
    {n : ℕ} {A : Set (RealEuclidean n)}
    (hA : IsLiteralZeroSet G A) :
    IsProjectedZeroSet G A := by
  obtain ⟨f, hf, rfl⟩ := hA
  refine ⟨0, f, hf, ?_⟩
  ext x
  simp

/-- UFF supplies the affine-section bound for a rank-zero literal base node. -/
theorem CharbonnelDescription.hasAffineSectionComponentBound_base
    {G : (n : ℕ) → Set (RealEuclideanFunction n)}
    (hG : IsGeometricFunctionFamily G)
    (hUFF : HasUniformFiberFiniteness G)
    {n : ℕ} (hn : 0 < n) (A : Set (RealEuclidean n))
    (hA : A ∈ literalZeroSetFamily G n) :
    (CharbonnelDescription.base hn A hA).HasAffineSectionComponentBound := by
  have hProjected : IsProjectedZeroSet G A :=
    (mem_literalZeroSetFamily_iff.mp hA).isProjectedZeroSet
  obtain ⟨N, hN⟩ :=
    hProjected.exists_affineSubspace_component_bound hG hUFF hn
  refine ⟨N, ?_⟩
  intro V
  exact hN V

/-! ## Binary unions -/

/-- Inclusion of the left member into a binary union. -/
def unionLeftInclusion {X : Type*} [TopologicalSpace X]
    (A B : Set X) : A → (A ∪ B : Set X) :=
  fun x ↦ ⟨x, Or.inl x.property⟩

/-- Inclusion of the right member into a binary union. -/
def unionRightInclusion {X : Type*} [TopologicalSpace X]
    (A B : Set X) : B → (A ∪ B : Set X) :=
  fun x ↦ ⟨x, Or.inr x.property⟩

theorem continuous_unionLeftInclusion
    {X : Type*} [TopologicalSpace X] (A B : Set X) :
    Continuous (unionLeftInclusion A B) := by
  apply Continuous.subtype_mk
  exact continuous_subtype_val

theorem continuous_unionRightInclusion
    {X : Type*} [TopologicalSpace X] (A B : Set X) :
    Continuous (unionRightInclusion A B) := by
  apply Continuous.subtype_mk
  exact continuous_subtype_val

/-- Each component of either member maps to the ambient component of their
union which contains it. -/
def connectedComponentsUnionMap
    {X : Type*} [TopologicalSpace X] (A B : Set X) :
    ConnectedComponents A ⊕ ConnectedComponents B →
      ConnectedComponents (A ∪ B : Set X)
  | .inl c =>
      Continuous.connectedComponentsMap
        (continuous_unionLeftInclusion A B) c
  | .inr c =>
      Continuous.connectedComponentsMap
        (continuous_unionRightInclusion A B) c

theorem connectedComponentsUnionMap_surjective
    {X : Type*} [TopologicalSpace X] (A B : Set X) :
    Function.Surjective (connectedComponentsUnionMap A B) := by
  intro c
  obtain ⟨x, rfl⟩ := ConnectedComponents.surjective_coe c
  rcases x.property with hxA | hxB
  · refine ⟨Sum.inl (ConnectedComponents.mk ⟨(x : X), hxA⟩), ?_⟩
    rw [connectedComponentsUnionMap,
      Continuous.connectedComponentsMap_mk]
    apply congrArg ConnectedComponents.mk
    apply Subtype.ext
    rfl
  · refine ⟨Sum.inr (ConnectedComponents.mk ⟨(x : X), hxB⟩), ?_⟩
    rw [connectedComponentsUnionMap,
      Continuous.connectedComponentsMap_mk]
    apply congrArg ConnectedComponents.mk
    apply Subtype.ext
    rfl

/-- The component count of a union is at most the sum of the component
counts of its two members. -/
theorem enatCard_connectedComponents_union_le
    {X : Type*} [TopologicalSpace X] (A B : Set X) :
    ENat.card (ConnectedComponents (A ∪ B : Set X)) ≤
      ENat.card (ConnectedComponents A) +
        ENat.card (ConnectedComponents B) := by
  calc
    ENat.card (ConnectedComponents (A ∪ B : Set X)) ≤
        ENat.card
          (ConnectedComponents A ⊕ ConnectedComponents B) :=
      ENat.card_le_card_of_injective
        (Function.injective_surjInv
          (connectedComponentsUnionMap_surjective A B))
    _ = ENat.card (ConnectedComponents A) +
          ENat.card (ConnectedComponents B) :=
      ENat.card_sum _ _

/-- The WS5 bound is preserved by a binary-union description node. -/
theorem CharbonnelDescription.HasAffineSectionComponentBound.union
    {S : EuclideanSetFamily} {n : ℕ}
    {left right : CharbonnelDescription S n}
    (hleft : left.HasAffineSectionComponentBound)
    (hright : right.HasAffineSectionComponentBound) :
    (CharbonnelDescription.union left right).HasAffineSectionComponentBound := by
  obtain ⟨Nleft, hNleft⟩ := hleft
  obtain ⟨Nright, hNright⟩ := hright
  refine ⟨Nleft + Nright, ?_⟩
  intro V
  rw [CharbonnelDescription.carrier_union,
    Set.union_inter_distrib_right]
  exact (enatCard_connectedComponents_union_le
      (left.carrier ∩ (V : Set (RealEuclidean n)))
      (right.carrier ∩ (V : Set (RealEuclidean n)))).trans
    (by
      simpa only [Nat.cast_add] using
        add_le_add (hNleft V) (hNright V))

/-! ## Integer-affine cuts -/

/-- The linear part of a finite system of integer-affine equations. -/
def integerAffineLinearMap {n r : ℕ}
    (coeff : Fin r → Fin n → ℤ) :
    RealEuclidean n →ₗ[ℝ] RealEuclidean r where
  toFun x i := ∑ j, (coeff i j : ℝ) * x j
  map_add' := by
    intro x y
    funext i
    simp only [Pi.add_apply]
    rw [← Finset.sum_add_distrib]
    apply Finset.sum_congr rfl
    intro j _hj
    ring
  map_smul' := by
    intro c x
    funext i
    simp only [Pi.smul_apply, smul_eq_mul, RingHom.id_apply]
    rw [Finset.mul_sum]
    apply Finset.sum_congr rfl
    intro j _hj
    ring

/-- The affine map whose zero fiber is a displayed integer-affine system. -/
def integerAffineEquationMap {n r : ℕ}
    (coeff : Fin r → Fin n → ℤ) (constant : Fin r → ℤ) :
    RealEuclidean n →ᵃ[ℝ] RealEuclidean r :=
  (integerAffineLinearMap coeff).toAffineMap +
    AffineMap.const ℝ (RealEuclidean n)
      (fun i ↦ (constant i : ℝ))

@[simp]
theorem integerAffineEquationMap_apply
    {n r : ℕ} (coeff : Fin r → Fin n → ℤ)
    (constant : Fin r → ℤ) (x : RealEuclidean n) (i : Fin r) :
    integerAffineEquationMap coeff constant x i =
      (∑ j, (coeff i j : ℝ) * x j) + (constant i : ℝ) :=
  rfl

/-- The affine subspace cut out by a displayed finite integer-affine system. -/
def integerAffineSolutionSubspace {n r : ℕ}
    (coeff : Fin r → Fin n → ℤ) (constant : Fin r → ℤ) :
    AffineSubspace ℝ (RealEuclidean n) :=
  ({0} : AffineSubspace ℝ (RealEuclidean r)).comap
    (integerAffineEquationMap coeff constant)

@[simp]
theorem mem_integerAffineSolutionSubspace_iff
    {n r : ℕ} (coeff : Fin r → Fin n → ℤ)
    (constant : Fin r → ℤ) (x : RealEuclidean n) :
    x ∈ integerAffineSolutionSubspace coeff constant ↔
      ∀ i, (∑ j, (coeff i j : ℝ) * x j) +
        (constant i : ℝ) = 0 := by
  change integerAffineEquationMap coeff constant x =
      (0 : RealEuclidean r) ↔ _
  constructor
  · intro h i
    have hi := congrFun h i
    simpa only [integerAffineEquationMap_apply, Pi.zero_apply] using hi
  · intro h
    funext i
    simpa only [integerAffineEquationMap_apply, Pi.zero_apply] using h i

/-- Every set accepted by the integer-affine syntax is the carrier of an
actual real affine subspace, including an inconsistent system. -/
theorem IsIntegerAffineSet.exists_affineSubspace
    {n : ℕ} {L : Set (RealEuclidean n)}
    (hL : IsIntegerAffineSet L) :
    ∃ V : AffineSubspace ℝ (RealEuclidean n),
      (V : Set (RealEuclidean n)) = L := by
  obtain ⟨r, coeff, constant, hL⟩ := hL
  refine ⟨integerAffineSolutionSubspace coeff constant, ?_⟩
  rw [hL]
  ext x
  simp only [SetLike.mem_coe, Set.mem_setOf_eq,
    mem_integerAffineSolutionSubspace_iff]

/-- The WS5 bound is preserved by intersection with an integer-affine set. -/
theorem CharbonnelDescription.HasAffineSectionComponentBound.integerAffineInter
    {S : EuclideanSetFamily} {n : ℕ}
    {inner : CharbonnelDescription S n}
    (hinner : inner.HasAffineSectionComponentBound)
    (L : Set (RealEuclidean n)) (hL : IsIntegerAffineSet L) :
    (CharbonnelDescription.integerAffineInter inner L hL).HasAffineSectionComponentBound := by
  obtain ⟨N, hN⟩ := hinner
  obtain ⟨W, hW⟩ := hL.exists_affineSubspace
  refine ⟨N, ?_⟩
  intro V
  have hsection :
      ((inner.carrier ∩ L) ∩ (V : Set (RealEuclidean n))) =
        inner.carrier ∩
          ((W ⊓ V : AffineSubspace ℝ (RealEuclidean n)) :
            Set (RealEuclidean n)) := by
    ext x
    simp only [AffineSubspace.coe_inf, Set.mem_inter_iff,
      SetLike.mem_coe, hW]
    tauto
  rw [CharbonnelDescription.carrier_integerAffineInter, hsection]
  exact hN (W ⊓ V)

/-! ## Projection through affine cylinders -/

/-- The inverse image of an affine subspace under projection to the first
coordinate block. -/
def realEuclideanAffineCylinderRight {n : ℕ}
    (V : AffineSubspace ℝ (RealEuclidean n)) (q : ℕ) :
    AffineSubspace ℝ (RealEuclidean (n + q)) :=
  V.comap (realEuclideanTakeLeftLinearMap n q).toAffineMap

@[simp]
theorem mem_realEuclideanAffineCylinderRight_iff
    {n q : ℕ} (V : AffineSubspace ℝ (RealEuclidean n))
    (v : RealEuclidean (n + q)) :
    v ∈ realEuclideanAffineCylinderRight V q ↔
      realEuclideanTakeLeft v ∈ V :=
  Iff.rfl

/-- Projection from an affine-cylinder section onto the corresponding
affine section of the existential projection. -/
def affineCylinderProjection
    {n q : ℕ} (A : Set (RealEuclidean (n + q)))
    (V : AffineSubspace ℝ (RealEuclidean n)) :
    (A ∩ (realEuclideanAffineCylinderRight V q :
        Set (RealEuclidean (n + q))) : Set (RealEuclidean (n + q))) →
      (realEuclideanExistentialProjection A ∩
        (V : Set (RealEuclidean n)) : Set (RealEuclidean n)) :=
  fun v ↦ ⟨realEuclideanTakeLeft
      (v : RealEuclidean (n + q)), by
    refine ⟨?_, ?_⟩
    · refine ⟨realEuclideanTakeRight
          (v : RealEuclidean (n + q)), ?_⟩
      rw [realEuclideanAppend_take]
      exact v.property.1
    · exact v.property.2⟩

theorem continuous_affineCylinderProjection
    {n q : ℕ} (A : Set (RealEuclidean (n + q)))
    (V : AffineSubspace ℝ (RealEuclidean n)) :
    Continuous (affineCylinderProjection A V) := by
  apply Continuous.subtype_mk
  exact (realEuclideanTakeLeftContinuousLinearMap n q).continuous.comp
    continuous_subtype_val

theorem surjective_affineCylinderProjection
    {n q : ℕ} (A : Set (RealEuclidean (n + q)))
    (V : AffineSubspace ℝ (RealEuclidean n)) :
    Function.Surjective (affineCylinderProjection A V) := by
  rintro ⟨x, hxprojection, hxV⟩
  obtain ⟨z, hxz⟩ := hxprojection
  refine ⟨⟨realEuclideanAppend x z, hxz, ?_⟩, ?_⟩
  · apply (mem_realEuclideanAffineCylinderRight_iff V _).mpr
    rw [realEuclideanTakeLeft_append]
    change x ∈ (V : Set (RealEuclidean n))
    exact hxV
  · apply Subtype.ext
    simp only [affineCylinderProjection, realEuclideanTakeLeft_append]

/-- Taking the first coordinate block cannot increase the number of
connected components of an affine-cylinder section. -/
theorem enatCard_connectedComponents_existentialProjection_affineSection_le
    {n q : ℕ} (A : Set (RealEuclidean (n + q)))
    (V : AffineSubspace ℝ (RealEuclidean n)) :
    ENat.card (ConnectedComponents
      ((realEuclideanExistentialProjection A ∩
          (V : Set (RealEuclidean n))) : Set (RealEuclidean n))) ≤
      ENat.card (ConnectedComponents
        ((A ∩ (realEuclideanAffineCylinderRight V q :
            Set (RealEuclidean (n + q)))) :
          Set (RealEuclidean (n + q)))) := by
  exact enatCard_connectedComponents_le_of_continuous_surjective
    (continuous_affineCylinderProjection A V)
    (surjective_affineCylinderProjection A V)

/-- The WS5 bound is preserved by existential projection onto a positive
initial coordinate block. -/
theorem CharbonnelDescription.HasAffineSectionComponentBound.projection
    {S : EuclideanSetFamily} {n q : ℕ} (hn : 0 < n)
    {inner : CharbonnelDescription S (n + q)}
    (hinner : inner.HasAffineSectionComponentBound) :
    (CharbonnelDescription.projection hn inner).HasAffineSectionComponentBound := by
  obtain ⟨N, hN⟩ := hinner
  refine ⟨N, ?_⟩
  intro V
  rw [CharbonnelDescription.carrier_projection]
  exact
    (enatCard_connectedComponents_existentialProjection_affineSection_le
      inner.carrier V).trans
        (hN (realEuclideanAffineCylinderRight V q))

/-! ## Strong induction on the numeric description rank -/

/-- Every literal-zero Charbonnel description has a uniform component bound
over all affine sections.  Strong induction on the numeric rank is essential:
the Maxwell replacement used at a closure node is lower-rank but is not a
structural subterm of that node. -/
theorem CharbonnelDescription.hasAffineSectionComponentBound
    {G : (n : ℕ) → Set (RealEuclideanFunction n)}
    (hG : IsGeometricFunctionFamily G)
    (hsmooth : IsEverywhereSmoothFunctionFamily G)
    (hUFF : HasUniformFiberFiniteness G)
    {n : ℕ}
    (description : CharbonnelDescription (literalZeroSetFamily G) n) :
    description.HasAffineSectionComponentBound := by
  have inductionStatement :
      ∀ r : ℕ, ∀ {m : ℕ}
        (d : CharbonnelDescription (literalZeroSetFamily G) m),
        d.rank = r → d.HasAffineSectionComponentBound := by
    intro r
    induction r using Nat.strong_induction_on with
    | h r ih =>
        intro m d hrank
        cases d with
        | base hm A hA =>
            exact
              CharbonnelDescription.hasAffineSectionComponentBound_base
                hG hUFF hm A hA
        | union left right =>
            have hleftRank : left.rank < r := by
              simp only [CharbonnelDescription.rank_union] at hrank
              omega
            have hrightRank : right.rank < r := by
              simp only [CharbonnelDescription.rank_union] at hrank
              omega
            exact (ih left.rank hleftRank left rfl).union
              (ih right.rank hrightRank right rfl)
        | integerAffineInter inner L hL =>
            have hinnerRank : inner.rank < r := by
              simp only [CharbonnelDescription.rank_integerAffineInter] at hrank
              omega
            exact (ih inner.rank hinnerRank inner rfl).integerAffineInter L hL
        | @projection visible hidden hvisible inner =>
            have hinnerRank : inner.rank < r := by
              simp only [CharbonnelDescription.rank_projection] at hrank
              omega
            exact
              CharbonnelDescription.HasAffineSectionComponentBound.projection
                hvisible (ih inner.rank hinnerRank inner rfl)
        | topologicalClosure inner =>
            apply
              CharbonnelDescription.hasAffineSectionComponentBound_topologicalClosure
                hG hsmooth inner
            intro k lower hlowerRank
            exact ih lower.rank (by
              rw [← hrank]
              exact hlowerRank) lower rfl
  exact inductionStatement description.rank description rfl

/-- WS5 for every positive-arity member of the Charbonnel closure generated
by literal zero sets.  This is the family-level form of the numeric rank
induction above. -/
theorem literalZeroSet_charbonnelClosure_ws5_affineSections
    {G : (n : ℕ) → Set (RealEuclideanFunction n)}
    (hG : IsGeometricFunctionFamily G)
    (hsmooth : IsEverywhereSmoothFunctionFamily G)
    (hUFF : HasUniformFiberFiniteness G) :
    ∀ {n : ℕ}, 0 < n →
      ∀ {A : Set (RealEuclidean n)},
        A ∈ charbonnelClosure (literalZeroSetFamily G) n →
          ∃ N : ℕ, ∀ V : AffineSubspace ℝ (RealEuclidean n),
            ENat.card (ConnectedComponents
              ((A ∩ (V : Set (RealEuclidean n))) :
                Set (RealEuclidean n))) ≤ (N : ℕ∞) := by
  intro n _hn A hA
  obtain ⟨description, hcarrier⟩ := hA
  obtain ⟨N, hN⟩ :=
    CharbonnelDescription.hasAffineSectionComponentBound
      hG hsmooth hUFF description
  refine ⟨N, ?_⟩
  intro V
  rw [← hcarrier]
  exact hN V

end AbelFormalization
