import AbelFormalization.CharbonnelDescriptionAlgebra

/-!
# Closed zero-set generators for the Charbonnel closure

This file separates the closed base used in the Berarducci--Servi product
lemma from the projected-zero weak structure.  For a geometric function
family `G`, the literal base consists of sets cut out by one equation
`f(x) = 0` with `f ∈ G`.  Global smoothness makes every such generator
closed.  The geometric-family operations make this base closed under
intersection, flat products, and coordinate reindexing, so it supplies the
exact `ClosedPositiveArityDescriptionBase` interface used by
`CharbonnelDescriptionAlgebra`.

Every projected zero set is then the existential projection of one literal
zero-set generator.  In positive visible arity this gives a Charbonnel
description of rank exactly one and hence an inclusion of projected zero sets
in the Charbonnel closure generated by the closed literal base.

Arbitrary real-linear equivalences preserve literal zero-set generators and
are recorded below.  Only finite coordinate reindexings are lifted through
arbitrary descriptions, because those, unlike general real-linear maps,
preserve the integer-affine syntax of description cuts.

No complement closure is asserted here.
-/

noncomputable section

open Set Function

namespace AbelFormalization

set_option autoImplicit false

/-! ## The literal zero-set family -/

/-- A literal zero set from `G` is the zero locus of one member of `G`, with
no hidden coordinates and no projection. -/
def IsLiteralZeroSet
    (G : (n : ℕ) → Set (RealEuclideanFunction n))
    {n : ℕ} (A : Set (RealEuclidean n)) : Prop :=
  ∃ f : RealEuclideanFunction n, f ∈ G n ∧ A = {x | f x = 0}

/-- The arity-indexed family of literal zero sets.  Its zero-arity entry is
harmless; Charbonnel descriptions use only positive arities. -/
def literalZeroSetFamily
    (G : (n : ℕ) → Set (RealEuclideanFunction n)) : EuclideanSetFamily :=
  fun _n => {A | IsLiteralZeroSet G A}

theorem mem_literalZeroSetFamily_iff
    {G : (n : ℕ) → Set (RealEuclideanFunction n)}
    {n : ℕ} {A : Set (RealEuclidean n)} :
    A ∈ literalZeroSetFamily G n ↔ IsLiteralZeroSet G A :=
  Iff.rfl

/-- Every polynomial equation is a literal generator.  This is an equality
zero-set statement; it does not put strict polynomial inequalities in the
closed base. -/
theorem literalZeroSet_polynomial_mem
    {G : (n : ℕ) → Set (RealEuclideanFunction n)}
    (hG : IsGeometricFunctionFamily G) {n : ℕ}
    (P : MvPolynomial (Fin n) ℝ) :
    {x : RealEuclidean n | MvPolynomial.eval x P = 0} ∈
      literalZeroSetFamily G n :=
  ⟨fun x ↦ MvPolynomial.eval x P, hG.polynomial P, rfl⟩

/-- Every literal zero set is closed when members of `G` are globally
smooth.  Positivity of the ambient arity is not needed for this fact. -/
theorem IsLiteralZeroSet.isClosed
    {G : (n : ℕ) → Set (RealEuclideanFunction n)}
    (hsmooth : IsEverywhereSmoothFunctionFamily G)
    {n : ℕ} {A : Set (RealEuclidean n)}
    (hA : IsLiteralZeroSet G A) : IsClosed A := by
  obtain ⟨f, hf, rfl⟩ := hA
  exact isClosed_singleton.preimage (hsmooth n f hf).continuous

/-- Global smoothness makes each positive-arity literal generator closed. -/
theorem literalZeroSetFamily_isClosed
    {G : (n : ℕ) → Set (RealEuclideanFunction n)}
    (hsmooth : IsEverywhereSmoothFunctionFamily G) :
    IsClosedPositiveAritySetFamily (literalZeroSetFamily G) := by
  intro n _hn A hA
  exact hA.isClosed hsmooth

/-! ## Base intersection and product -/

/-- Two literal zero sets in the same arity intersect in the zero set of the
sum of the squares of their defining functions. -/
theorem IsLiteralZeroSet.inter
    {G : (n : ℕ) → Set (RealEuclideanFunction n)}
    (hG : IsGeometricFunctionFamily G) {n : ℕ}
    {A B : Set (RealEuclidean n)}
    (hA : IsLiteralZeroSet G A) (hB : IsLiteralZeroSet G B) :
    IsLiteralZeroSet G (A ∩ B) := by
  obtain ⟨f, hf, rfl⟩ := hA
  obtain ⟨g, hg, rfl⟩ := hB
  refine ⟨fun x ↦ f x ^ 2 + g x ^ 2,
    hG.add (hG.sq_mem hf) (hG.sq_mem hg), ?_⟩
  ext x
  simp only [Set.mem_inter_iff, Set.mem_setOf_eq]
  exact (sq_add_sq_eq_zero (a := f x) (b := g x)).symm

/-- The first-coordinate block as a linear map. -/
def realEuclideanTakeLeftLinearMap (n m : ℕ) :
    RealEuclidean (n + m) →ₗ[ℝ] RealEuclidean n where
  toFun := realEuclideanTakeLeft
  map_add' := by
    intro x y
    rfl
  map_smul' := by
    intro c x
    rfl

/-- The second-coordinate block as a linear map. -/
def realEuclideanTakeRightLinearMap (n m : ℕ) :
    RealEuclidean (n + m) →ₗ[ℝ] RealEuclidean m where
  toFun := realEuclideanTakeRight
  map_add' := by
    intro x y
    rfl
  map_smul' := by
    intro c x
    rfl

@[simp]
theorem realEuclideanTakeLeftLinearMap_apply {n m : ℕ}
    (v : RealEuclidean (n + m)) :
    realEuclideanTakeLeftLinearMap n m v = realEuclideanTakeLeft v :=
  rfl

@[simp]
theorem realEuclideanTakeRightLinearMap_apply {n m : ℕ}
    (v : RealEuclidean (n + m)) :
    realEuclideanTakeRightLinearMap n m v = realEuclideanTakeRight v :=
  rfl

/-- The flat product of two literal zero sets is the zero set of the sum of
squares of the two defining functions pulled back from their blocks. -/
theorem IsLiteralZeroSet.prod
    {G : (n : ℕ) → Set (RealEuclideanFunction n)}
    (hG : IsGeometricFunctionFamily G) {n m : ℕ}
    {A : Set (RealEuclidean n)} {B : Set (RealEuclidean m)}
    (hA : IsLiteralZeroSet G A) (hB : IsLiteralZeroSet G B) :
    IsLiteralZeroSet G (realEuclideanSetProduct A B) := by
  obtain ⟨f, hf, rfl⟩ := hA
  obtain ⟨g, hg, rfl⟩ := hB
  let L := realEuclideanTakeLeftLinearMap n m
  let R := realEuclideanTakeRightLinearMap n m
  let F : RealEuclideanFunction (n + m) := f ∘ L
  let H : RealEuclideanFunction (n + m) := g ∘ R
  have hF : F ∈ G (n + m) := hG.affine_comp hf L.toAffineMap
  have hH : H ∈ G (n + m) := hG.affine_comp hg R.toAffineMap
  refine ⟨fun v ↦ F v ^ 2 + H v ^ 2,
    hG.add (hG.sq_mem hF) (hG.sq_mem hH), ?_⟩
  ext v
  simp only [realEuclideanSetProduct, Set.mem_setOf_eq]
  simpa [F, H, L, R, Function.comp_apply] using
    (sq_add_sq_eq_zero
      (a := f (realEuclideanTakeLeft v))
      (b := g (realEuclideanTakeRight v))).symm

theorem literalZeroSetFamily_inter_mem
    {G : (n : ℕ) → Set (RealEuclideanFunction n)}
    (hG : IsGeometricFunctionFamily G) {n : ℕ}
    {A B : Set (RealEuclidean n)}
    (hA : A ∈ literalZeroSetFamily G n)
    (hB : B ∈ literalZeroSetFamily G n) :
    A ∩ B ∈ literalZeroSetFamily G n :=
  hA.inter hG hB

theorem literalZeroSetFamily_prod_mem
    {G : (n : ℕ) → Set (RealEuclideanFunction n)}
    (hG : IsGeometricFunctionFamily G) {n m : ℕ}
    {A : Set (RealEuclidean n)} {B : Set (RealEuclidean m)}
    (hA : A ∈ literalZeroSetFamily G n)
    (hB : B ∈ literalZeroSetFamily G m) :
    realEuclideanSetProduct A B ∈ literalZeroSetFamily G (n + m) :=
  hA.prod hG hB

/-! ## Linear images and the coordinate syntax boundary -/

/-- Literal zero sets are preserved by every real-linear equivalence in a
fixed arity: pull the defining function back along the inverse equivalence. -/
theorem IsLiteralZeroSet.linearEquiv_image
    {G : (n : ℕ) → Set (RealEuclideanFunction n)}
    (hG : IsGeometricFunctionFamily G) {n : ℕ}
    {A : Set (RealEuclidean n)} (hA : IsLiteralZeroSet G A)
    (e : RealEuclidean n ≃ₗ[ℝ] RealEuclidean n) :
    IsLiteralZeroSet G (e '' A) := by
  obtain ⟨f, hf, rfl⟩ := hA
  let F : RealEuclideanFunction n := f ∘ e.symm
  have hF : F ∈ G n :=
    hG.affine_comp hf e.symm.toLinearMap.toAffineMap
  refine ⟨F, hF, ?_⟩
  ext y
  simp only [Set.mem_image, Set.mem_setOf_eq]
  constructor
  · rintro ⟨x, hx, rfl⟩
    simpa [F, Function.comp_apply] using hx
  · intro hy
    refine ⟨e.symm y, ?_, e.apply_symm_apply y⟩
    simpa [F, Function.comp_apply] using hy

theorem literalZeroSetFamily_linearEquiv_image_mem
    {G : (n : ℕ) → Set (RealEuclideanFunction n)}
    (hG : IsGeometricFunctionFamily G) {n : ℕ}
    {A : Set (RealEuclidean n)} (hA : A ∈ literalZeroSetFamily G n)
    (e : RealEuclidean n ≃ₗ[ℝ] RealEuclidean n) :
    e '' A ∈ literalZeroSetFamily G n :=
  hA.linearEquiv_image hG e

/-- Finite coordinate reindexing may change the displayed finite-coordinate
type.  It still preserves literal zero sets, again by inverse pullback. -/
theorem IsLiteralZeroSet.coordinateReindex_image
    {G : (n : ℕ) → Set (RealEuclideanFunction n)}
    (hG : IsGeometricFunctionFamily G) {n m : ℕ}
    {A : Set (RealEuclidean n)} (hA : IsLiteralZeroSet G A)
    (e : Fin m ≃ Fin n) :
    IsLiteralZeroSet G (realEuclideanCoordinateReindex e '' A) := by
  obtain ⟨f, hf, rfl⟩ := hA
  let E := realEuclideanCoordinateReindex e
  let F : RealEuclideanFunction m := f ∘ E.symm
  have hF : F ∈ G m :=
    hG.affine_comp hf E.symm.toLinearMap.toAffineMap
  refine ⟨F, hF, ?_⟩
  ext y
  simp only [Set.mem_image, Set.mem_setOf_eq]
  constructor
  · rintro ⟨x, hx, rfl⟩
    simpa [F, E, Function.comp_apply] using hx
  · intro hy
    refine ⟨E.symm y, ?_, E.apply_symm_apply y⟩
    simpa [F, E, Function.comp_apply] using hy

theorem literalZeroSetFamily_coordinateReindex_mem
    {G : (n : ℕ) → Set (RealEuclideanFunction n)}
    (hG : IsGeometricFunctionFamily G) {n m : ℕ}
    {A : Set (RealEuclidean n)} (hA : A ∈ literalZeroSetFamily G n)
    (e : Fin m ≃ Fin n) :
    realEuclideanCoordinateReindex e '' A ∈ literalZeroSetFamily G m :=
  hA.coordinateReindex_image hG e

/-- The block reassociation used in the product induction preserves the
literal base. -/
theorem literalZeroSetFamily_finAddAssoc_reindex_mem
    {G : (n : ℕ) → Set (RealEuclideanFunction n)}
    (hG : IsGeometricFunctionFamily G) {n m k : ℕ}
    {A : Set (RealEuclidean (n + (m + k)))}
    (hA : A ∈ literalZeroSetFamily G (n + (m + k))) :
    realEuclideanCoordinateReindex (finAddAssocCoordinateEquiv n m k) '' A ∈
      literalZeroSetFamily G ((n + m) + k) :=
  hA.coordinateReindex_image hG (finAddAssocCoordinateEquiv n m k)

/-- The block exchange used in the product induction preserves the literal
base. -/
theorem literalZeroSetFamily_finAddFlip_reindex_mem
    {G : (n : ℕ) → Set (RealEuclideanFunction n)}
    (hG : IsGeometricFunctionFamily G) {n m : ℕ}
    {A : Set (RealEuclidean (m + n))}
    (hA : A ∈ literalZeroSetFamily G (m + n)) :
    realEuclideanCoordinateReindex (@finAddFlip n m) '' A ∈
      literalZeroSetFamily G (n + m) :=
  hA.coordinateReindex_image hG (@finAddFlip n m)

/-! ## The closed description-base instance -/

/-- The literal base supplies the coordinate-reindexing interface without a
smoothness assumption. -/
theorem literalZeroSetFamily_descriptionReindexBase
    {G : (n : ℕ) → Set (RealEuclideanFunction n)}
    (hG : IsGeometricFunctionFamily G) :
    PositiveArityDescriptionReindexBase (literalZeroSetFamily G) := by
  refine { coordinateReindex := ?_ }
  intro n m _hn A hA e
  exact hA.coordinateReindex_image hG e

/-- A globally smooth geometric family gives precisely the closed-base input
used by the Charbonnel description product and intersection lemmas. -/
theorem literalZeroSetFamily_closedDescriptionBase
    {G : (n : ℕ) → Set (RealEuclideanFunction n)}
    (hG : IsGeometricFunctionFamily G)
    (hsmooth : IsEverywhereSmoothFunctionFamily G) :
    ClosedPositiveArityDescriptionBase (literalZeroSetFamily G) := by
  refine
    { toPositiveArityDescriptionReindexBase :=
        literalZeroSetFamily_descriptionReindexBase hG
      base_isClosed := literalZeroSetFamily_isClosed hsmooth
      base_prod := ?_ }
  intro n m _hn _hm A B hA hB
  exact hA.prod hG hB

/-- Coordinate reindexing acts on arbitrary descriptions over the literal
base without changing rank. -/
theorem literalZeroSetFamily_exists_coordinateReindex_description
    {G : (n : ℕ) → Set (RealEuclideanFunction n)}
    (hG : IsGeometricFunctionFamily G) {n m : ℕ}
    (description : CharbonnelDescription (literalZeroSetFamily G) n)
    (e : Fin m ≃ Fin n) :
    ∃ reindexed : CharbonnelDescription (literalZeroSetFamily G) m,
      reindexed.carrier =
          realEuclideanCoordinateReindex e '' description.carrier ∧
        reindexed.rank = description.rank :=
  (literalZeroSetFamily_descriptionReindexBase hG).exists_coordinateReindex_description
    description e

/-- Exact product and rank bound for descriptions over the closed literal
base. -/
theorem literalZeroSetFamily_exists_product_description
    {G : (n : ℕ) → Set (RealEuclideanFunction n)}
    (hG : IsGeometricFunctionFamily G)
    (hsmooth : IsEverywhereSmoothFunctionFamily G)
    {n m : ℕ} (left : CharbonnelDescription (literalZeroSetFamily G) n)
    (right : CharbonnelDescription (literalZeroSetFamily G) m) :
    ∃ product : CharbonnelDescription (literalZeroSetFamily G) (n + m),
      product.carrier =
          realEuclideanSetProduct left.carrier right.carrier ∧
        product.rank ≤ left.rank + right.rank :=
  (literalZeroSetFamily_closedDescriptionBase hG hsmooth).exists_product_description
    left right

/-- Exact diagonal/projection intersection and rank bound for descriptions
over the closed literal base. -/
theorem literalZeroSetFamily_exists_inter_description
    {G : (n : ℕ) → Set (RealEuclideanFunction n)}
    (hG : IsGeometricFunctionFamily G)
    (hsmooth : IsEverywhereSmoothFunctionFamily G)
    {n : ℕ} (left right :
      CharbonnelDescription (literalZeroSetFamily G) n) :
    ∃ intersection : CharbonnelDescription (literalZeroSetFamily G) n,
      intersection.carrier = left.carrier ∩ right.carrier ∧
        intersection.rank ≤ 2 + left.rank + right.rank :=
  (literalZeroSetFamily_closedDescriptionBase hG hsmooth).exists_inter_description
    left right

/-! ## Projected zero sets as one-step descriptions -/

/-- A projected zero set is exactly the existential projection of one
literal zero-set generator.  This statement needs no smoothness hypothesis;
smoothness is used below to identify the literal family as a closed base. -/
theorem IsProjectedZeroSet.exists_literalZeroSet_projection
    {G : (n : ℕ) → Set (RealEuclideanFunction n)}
    {n : ℕ} {A : Set (RealEuclidean n)}
    (hA : IsProjectedZeroSet G A) :
    ∃ (q : ℕ) (B : Set (RealEuclidean (n + q))),
      B ∈ literalZeroSetFamily G (n + q) ∧
        A = realEuclideanExistentialProjection B := by
  obtain ⟨q, f, hf, hA⟩ := hA
  refine ⟨q, {v | f v = 0}, ⟨f, hf, rfl⟩, ?_⟩
  rw [hA]
  rfl

/-- With global smoothness, the one literal generator in the preceding lift
is topologically closed. -/
theorem IsProjectedZeroSet.exists_closed_literalZeroSet_projection
    {G : (n : ℕ) → Set (RealEuclideanFunction n)}
    (hsmooth : IsEverywhereSmoothFunctionFamily G)
    {n : ℕ} {A : Set (RealEuclidean n)}
    (hA : IsProjectedZeroSet G A) :
    ∃ (q : ℕ) (B : Set (RealEuclidean (n + q))),
      B ∈ literalZeroSetFamily G (n + q) ∧ IsClosed B ∧
        A = realEuclideanExistentialProjection B := by
  obtain ⟨q, f, hf, hA⟩ := hA
  refine ⟨q, {v | f v = 0}, ⟨f, hf, rfl⟩, ?_, ?_⟩
  · exact isClosed_singleton.preimage (hsmooth (n + q) f hf).continuous
  · rw [hA]
    rfl

/-- In positive visible arity, one projected zero set has a Charbonnel
description consisting of one base node followed by one projection node. -/
theorem IsProjectedZeroSet.exists_rank_one_literalZero_description
    {G : (n : ℕ) → Set (RealEuclideanFunction n)}
    {n : ℕ} (hn : 0 < n) {A : Set (RealEuclidean n)}
    (hA : IsProjectedZeroSet G A) :
    ∃ description : CharbonnelDescription (literalZeroSetFamily G) n,
      description.carrier = A ∧ description.rank = 1 := by
  obtain ⟨q, B, hB, hprojection⟩ := hA.exists_literalZeroSet_projection
  let base : CharbonnelDescription (literalZeroSetFamily G) (n + q) :=
    .base (by omega) B hB
  let description : CharbonnelDescription (literalZeroSetFamily G) n :=
    .projection hn base
  refine ⟨description, ?_, ?_⟩
  · simp only [description, base,
      CharbonnelDescription.carrier_projection,
      CharbonnelDescription.carrier_base]
    exact hprojection.symm
  · simp only [description, base, CharbonnelDescription.rank_projection,
      CharbonnelDescription.rank_base]

/-- Positive-arity projected zero sets lie in the Charbonnel closure over the
literal zero-set base.  The witness is the rank-one description above. -/
theorem IsProjectedZeroSet.mem_literalZeroSet_charbonnelClosure
    {G : (n : ℕ) → Set (RealEuclideanFunction n)}
    {n : ℕ} (hn : 0 < n) {A : Set (RealEuclidean n)}
    (hA : IsProjectedZeroSet G A) :
    A ∈ charbonnelClosure (literalZeroSetFamily G) n := by
  obtain ⟨description, hcarrier, _hrank⟩ :=
    hA.exists_rank_one_literalZero_description hn
  exact ⟨description, hcarrier⟩

/-- Family-level form of the positive-arity containment. -/
theorem projectedZeroSetFamily_subset_literalZeroSet_charbonnelClosure
    {G : (n : ℕ) → Set (RealEuclideanFunction n)}
    {n : ℕ} (hn : 0 < n) :
    projectedZeroSetFamily G n ⊆
      charbonnelClosure (literalZeroSetFamily G) n := by
  intro A hA
  exact hA.mem_literalZeroSet_charbonnelClosure hn

/-- Combined bridge statement: for a globally smooth geometric family, the
literal generators form the closed description base and every projected zero
set of positive visible arity lies in its Charbonnel closure. -/
theorem projectedZeroSetFamily_closedLiteralCharbonnelBridge
    {G : (n : ℕ) → Set (RealEuclideanFunction n)}
    (hG : IsGeometricFunctionFamily G)
    (hsmooth : IsEverywhereSmoothFunctionFamily G)
    {n : ℕ} (hn : 0 < n) :
    ClosedPositiveArityDescriptionBase (literalZeroSetFamily G) ∧
      projectedZeroSetFamily G n ⊆
        charbonnelClosure (literalZeroSetFamily G) n :=
  ⟨literalZeroSetFamily_closedDescriptionBase hG hsmooth,
    projectedZeroSetFamily_subset_literalZeroSet_charbonnelClosure hn⟩

/-! ## Description-algebra consequences over the closed literal base -/

/-- Products in the Charbonnel closure over literal zero sets follow from the
closed-base product induction. -/
theorem literalZeroSet_charbonnelClosure_product
    {G : (n : ℕ) → Set (RealEuclideanFunction n)}
    (hG : IsGeometricFunctionFamily G)
    (hsmooth : IsEverywhereSmoothFunctionFamily G)
    {n m : ℕ} {A : Set (RealEuclidean n)} {B : Set (RealEuclidean m)}
    (hA : A ∈ charbonnelClosure (literalZeroSetFamily G) n)
    (hB : B ∈ charbonnelClosure (literalZeroSetFamily G) m) :
    realEuclideanSetProduct A B ∈
      charbonnelClosure (literalZeroSetFamily G) (n + m) :=
  (literalZeroSetFamily_closedDescriptionBase hG hsmooth).charbonnelClosure_product
    hA hB

/-- Binary intersections in the Charbonnel closure over literal zero sets are
obtained by product, integer-affine diagonal cut, and projection. -/
theorem literalZeroSet_charbonnelClosure_inter
    {G : (n : ℕ) → Set (RealEuclideanFunction n)}
    (hG : IsGeometricFunctionFamily G)
    (hsmooth : IsEverywhereSmoothFunctionFamily G)
    {n : ℕ} {A B : Set (RealEuclidean n)}
    (hA : A ∈ charbonnelClosure (literalZeroSetFamily G) n)
    (hB : B ∈ charbonnelClosure (literalZeroSetFamily G) n) :
    A ∩ B ∈ charbonnelClosure (literalZeroSetFamily G) n :=
  (literalZeroSetFamily_closedDescriptionBase hG hsmooth).charbonnelClosure_inter
    hA hB

end AbelFormalization
