import AbelFormalization.FiniteWeightHomogeneousSubtype
import AbelFormalization.FiniteWeightInvariantCoordinates
import Mathlib.Algebra.Module.Torsion.Basic

set_option autoImplicit false

/-!
# A principal coefficient quotient of a homogeneous finite product

Let `K` be a coordinatewise homogeneous submodule of a finite product and
let `b` be a scalar.  This file identifies

`K / (b)K`

with the product of the quotients of the coordinate submodules of `K` by
their respective `(b)`-multiples.  The map from `K` to this product is the
literal coordinatewise quotient map.  We record its kernel and
surjectivity, then descend any automorphism preserving `K` and conjugate it
to the coordinate quotient.

The quotient modules are regarded as modules over `R ⧸ Ideal.span {b}`.
-/

noncomputable section

namespace AbelFormalization

section Auxiliary

variable {R : Type*} [CommRing R]

/-- A linear equivalence carries `I • ⊤` onto `I • ⊤`. -/
theorem map_ideal_smul_top_linearEquiv
    {V W : Type*} [AddCommGroup V] [Module R V]
    [AddCommGroup W] [Module R W]
    (I : Ideal R) (e : V ≃ₗ[R] W) :
    (I • (⊤ : Submodule R V)).map e.toLinearMap =
      I • (⊤ : Submodule R W) := by
  rw [Submodule.map_smul'', Submodule.map_top, e.range]

/-- In a finite product, the submodule generated by multiplying all vectors
by `I` is the product of the corresponding coordinate submodules. -/
theorem ideal_smul_pi_top_eq_pi_ideal_smul_top
    {ι : Type*} [Fintype ι]
    {N : ι → Type*} [∀ i, AddCommGroup (N i)] [∀ i, Module R (N i)]
    (I : Ideal R) :
    I • (⊤ : Submodule R (∀ i, N i)) =
      Submodule.pi Set.univ
        (fun i => I • (⊤ : Submodule R (N i))) := by
  classical
  apply le_antisymm
  · apply Submodule.smul_le.mpr
    intro r hr x hx
    rw [Submodule.mem_pi]
    intro i hi
    change r • x i ∈ I • (⊤ : Submodule R (N i))
    exact Submodule.smul_mem_smul hr Submodule.mem_top
  · intro x hx
    rw [← LinearMap.sum_single_apply N x]
    apply Submodule.sum_mem
    intro i hi
    have hxi : x i ∈ I • (⊤ : Submodule R (N i)) :=
      (Submodule.mem_pi.mp hx) i (Set.mem_univ i)
    refine Submodule.smul_induction_on hxi ?_ ?_
    · intro r hr y hy
      change (LinearMap.single R N i) (r • y) ∈
        I • (⊤ : Submodule R (∀ i, N i))
      rw [map_smul]
      exact Submodule.smul_mem_smul hr Submodule.mem_top
    · intro y z hy hz
      change (LinearMap.single R N i) (y + z) ∈
        I • (⊤ : Submodule R (∀ i, N i))
      rw [map_add]
      exact Submodule.add_mem _ hy hz

/-- An `R`-linear equivalence induces an `R/I`-linear equivalence after
quotienting source and target by `I • ⊤`.

Mathlib's `Submodule.Quotient.equiv` supplies the underlying `R`-linear
equivalence.  The extra scalar law follows by quotient induction. -/
def quotientIdealSMulTopLinearEquiv
    {V W : Type*} [AddCommGroup V] [Module R V]
    [AddCommGroup W] [Module R W]
    (I : Ideal R) (e : V ≃ₗ[R] W) :
    (V ⧸ I • (⊤ : Submodule R V)) ≃ₗ[R ⧸ I]
      (W ⧸ I • (⊤ : Submodule R W)) where
  toFun := Submodule.Quotient.equiv
    (I • (⊤ : Submodule R V))
    (I • (⊤ : Submodule R W)) e
    (map_ideal_smul_top_linearEquiv I e)
  invFun := (Submodule.Quotient.equiv
    (I • (⊤ : Submodule R V))
    (I • (⊤ : Submodule R W)) e
    (map_ideal_smul_top_linearEquiv I e)).symm
  left_inv := (Submodule.Quotient.equiv
    (I • (⊤ : Submodule R V))
    (I • (⊤ : Submodule R W)) e
    (map_ideal_smul_top_linearEquiv I e)).left_inv
  right_inv := (Submodule.Quotient.equiv
    (I • (⊤ : Submodule R V))
    (I • (⊤ : Submodule R W)) e
    (map_ideal_smul_top_linearEquiv I e)).right_inv
  map_add' := (Submodule.Quotient.equiv
    (I • (⊤ : Submodule R V))
    (I • (⊤ : Submodule R W)) e
    (map_ideal_smul_top_linearEquiv I e)).map_add
  map_smul' := by
    rintro ⟨r⟩ ⟨x⟩
    change Submodule.Quotient.mk (e (r • x)) =
      Ideal.Quotient.mk I r • Submodule.Quotient.mk (e x)
    rw [e.map_smul]
    exact (Module.Quotient.mk_smul_mk W I r (e x)).symm

@[simp]
theorem quotientIdealSMulTopLinearEquiv_mk
    {V W : Type*} [AddCommGroup V] [Module R V]
    [AddCommGroup W] [Module R W]
    (I : Ideal R) (e : V ≃ₗ[R] W) (x : V) :
    quotientIdealSMulTopLinearEquiv I e (Submodule.Quotient.mk x) =
      Submodule.Quotient.mk (e x) := rfl

end Auxiliary

section RestrictedQuotient

variable {R : Type*} [CommRing R] {n : ℕ}
variable {M : Fin n → Type*}
variable [∀ i, AddCommGroup (M i)] [∀ i, Module R (M i)]

/-- The principal coefficient submodule `(b)K` inside the subtype `K`. -/
abbrev finiteWeightRestrictedKernel
    (K : Submodule R (∀ i, M i)) (b : R) : Submodule R K :=
  Ideal.span {b} • (⊤ : Submodule R K)

/-- The principal coefficient submodule in the `i`th coordinate submodule
of `K`. -/
abbrev finiteWeightRestrictedCoordinateKernel
    (K : Submodule R (∀ i, M i)) (b : R) (i : Fin n) :
    Submodule R (finiteWeightCoordinateSubmodule K i) :=
  Ideal.span {b} •
    (⊤ : Submodule R (finiteWeightCoordinateSubmodule K i))

/-- The quotient of the `i`th coordinate submodule of `K` by its
`(b)`-multiple. -/
abbrev finiteWeightRestrictedCoordinateQuotient
    (K : Submodule R (∀ i, M i)) (b : R) (i : Fin n) :=
  finiteWeightCoordinateSubmodule K i ⧸
    finiteWeightRestrictedCoordinateKernel K b i

/-- The coordinatewise quotient used after passing from `R` to `R/(b)`. -/
abbrev finiteWeightRestrictedQuotient
    (K : Submodule R (∀ i, M i)) (b : R) :=
  ∀ i, finiteWeightRestrictedCoordinateQuotient K b i

/-- The canonical map from a homogeneous `K` to the product of the
coordinate quotients.  It is semilinear for `R → R/(b)`. -/
def finiteWeightRestrictedQuotientMap
    (K : Submodule R (∀ i, M i))
    (hK : ∀ x ∈ K, ∀ i, Pi.single i (x i) ∈ K)
    (b : R) :
    K →ₛₗ[Ideal.Quotient.mk (Ideal.span {b})]
      finiteWeightRestrictedQuotient K b where
  toFun := fun x i => Submodule.Quotient.mk
    ((finiteWeightHomogeneousSubtypeEquiv K hK x) i)
  map_add' := by
    intro x y
    funext i
    rfl
  map_smul' := by
    intro r x
    funext i
    change Submodule.Quotient.mk
        (p := finiteWeightRestrictedCoordinateKernel K b i)
        (r • (finiteWeightHomogeneousSubtypeEquiv K hK x) i) =
      Ideal.Quotient.mk (Ideal.span {b}) r •
        Submodule.Quotient.mk
          (p := finiteWeightRestrictedCoordinateKernel K b i)
          ((finiteWeightHomogeneousSubtypeEquiv K hK x) i)
    exact (Module.Quotient.mk_smul_mk
      (finiteWeightCoordinateSubmodule K i) (Ideal.span {b}) r
      ((finiteWeightHomogeneousSubtypeEquiv K hK x) i)).symm

@[simp]
theorem finiteWeightRestrictedQuotientMap_apply
    (K : Submodule R (∀ i, M i))
    (hK : ∀ x ∈ K, ∀ i, Pi.single i (x i) ∈ K)
    (b : R) (x : K) (i : Fin n) :
    finiteWeightRestrictedQuotientMap K hK b x i =
      Submodule.Quotient.mk
        ((finiteWeightHomogeneousSubtypeEquiv K hK x) i) := rfl

/-- Membership in `(b)K` is detected in all coordinate submodules. -/
theorem mem_finiteWeightRestrictedKernel_iff
    (K : Submodule R (∀ i, M i))
    (hK : ∀ x ∈ K, ∀ i, Pi.single i (x i) ∈ K)
    (b : R) (x : K) :
    x ∈ finiteWeightRestrictedKernel K b ↔
      ∀ i, (finiteWeightHomogeneousSubtypeEquiv K hK x) i ∈
        finiteWeightRestrictedCoordinateKernel K b i := by
  let E := finiteWeightHomogeneousSubtypeEquiv K hK
  let I := Ideal.span {b}
  constructor
  · intro hx
    have hEx : E x ∈
        (I • (⊤ : Submodule R K)).map E.toLinearMap :=
      ⟨x, hx, rfl⟩
    rw [map_ideal_smul_top_linearEquiv,
      ideal_smul_pi_top_eq_pi_ideal_smul_top] at hEx
    exact fun i => (Submodule.mem_pi.mp hEx) i (Set.mem_univ i)
  · intro hx
    have hEx : E x ∈ Submodule.pi Set.univ
        (fun i => I •
          (⊤ : Submodule R (finiteWeightCoordinateSubmodule K i))) :=
      (Submodule.mem_pi).mpr fun i hi => hx i
    rw [← ideal_smul_pi_top_eq_pi_ideal_smul_top
        (N := fun i ↦ finiteWeightCoordinateSubmodule K i) I,
      ← map_ideal_smul_top_linearEquiv
        (V := K) (W := ∀ i, finiteWeightCoordinateSubmodule K i) I E] at hEx
    simpa only [Submodule.mem_map_equiv, LinearEquiv.symm_apply_apply]
      using hEx

/-- The canonical coordinate quotient map has kernel exactly `(b)K`. -/
theorem ker_finiteWeightRestrictedQuotientMap
    (K : Submodule R (∀ i, M i))
    (hK : ∀ x ∈ K, ∀ i, Pi.single i (x i) ∈ K)
    (b : R) :
    LinearMap.ker (finiteWeightRestrictedQuotientMap K hK b) =
      finiteWeightRestrictedKernel K b := by
  ext x
  rw [LinearMap.mem_ker, mem_finiteWeightRestrictedKernel_iff K hK b x]
  constructor
  · intro hx i
    have hxi := congrFun hx i
    change Submodule.Quotient.mk
      ((finiteWeightHomogeneousSubtypeEquiv K hK x) i) = 0 at hxi
    exact (Submodule.Quotient.mk_eq_zero _).mp hxi
  · intro hx
    funext i
    change Submodule.Quotient.mk
      ((finiteWeightHomogeneousSubtypeEquiv K hK x) i) = 0
    exact (Submodule.Quotient.mk_eq_zero _).mpr (hx i)

/-- The canonical coordinate quotient map is onto. -/
theorem finiteWeightRestrictedQuotientMap_surjective
    (K : Submodule R (∀ i, M i))
    (hK : ∀ x ∈ K, ∀ i, Pi.single i (x i) ∈ K)
    (b : R) :
    Function.Surjective (finiteWeightRestrictedQuotientMap K hK b) := by
  classical
  intro y
  choose z hz using fun i =>
    (finiteWeightRestrictedCoordinateKernel K b i).mkQ_surjective (y i)
  refine ⟨(finiteWeightHomogeneousSubtypeEquiv K hK).symm z, ?_⟩
  funext i
  rw [finiteWeightRestrictedQuotientMap_apply,
    (finiteWeightHomogeneousSubtypeEquiv K hK).apply_symm_apply]
  exact hz i

/-- The quotient map from `K/(b)K` to the coordinatewise quotient, now
viewed as a linear map over `R/(b)`. -/
def finiteWeightRestrictedQuotientLift
    (K : Submodule R (∀ i, M i))
    (hK : ∀ x ∈ K, ∀ i, Pi.single i (x i) ∈ K)
    (b : R) :
    (K ⧸ finiteWeightRestrictedKernel K b) →ₗ[R ⧸ Ideal.span {b}]
      finiteWeightRestrictedQuotient K b where
  toFun := (finiteWeightRestrictedKernel K b).liftQ
    (finiteWeightRestrictedQuotientMap K hK b)
    (ker_finiteWeightRestrictedQuotientMap K hK b).ge
  map_add' := ((finiteWeightRestrictedKernel K b).liftQ
    (finiteWeightRestrictedQuotientMap K hK b)
    (ker_finiteWeightRestrictedQuotientMap K hK b).ge).map_add
  map_smul' := by
    rintro ⟨r⟩ ⟨x⟩
    exact (finiteWeightRestrictedQuotientMap K hK b).map_smulₛₗ r x

@[simp]
theorem finiteWeightRestrictedQuotientLift_mk
    (K : Submodule R (∀ i, M i))
    (hK : ∀ x ∈ K, ∀ i, Pi.single i (x i) ∈ K)
    (b : R) (x : K) :
    finiteWeightRestrictedQuotientLift K hK b
      (Submodule.Quotient.mk x) =
        finiteWeightRestrictedQuotientMap K hK b x := rfl

theorem finiteWeightRestrictedQuotientLift_surjective
    (K : Submodule R (∀ i, M i))
    (hK : ∀ x ∈ K, ∀ i, Pi.single i (x i) ∈ K)
    (b : R) :
    Function.Surjective (finiteWeightRestrictedQuotientLift K hK b) := by
  intro y
  obtain ⟨x, hx⟩ := finiteWeightRestrictedQuotientMap_surjective K hK b y
  exact ⟨Submodule.Quotient.mk x, by simpa using hx⟩

theorem finiteWeightRestrictedQuotientLift_injective
    (K : Submodule R (∀ i, M i))
    (hK : ∀ x ∈ K, ∀ i, Pi.single i (x i) ∈ K)
    (b : R) :
    Function.Injective (finiteWeightRestrictedQuotientLift K hK b) := by
  intro x' y' hxy
  obtain ⟨x, rfl⟩ :=
    Submodule.Quotient.mk_surjective (finiteWeightRestrictedKernel K b) x'
  obtain ⟨y, rfl⟩ :=
    Submodule.Quotient.mk_surjective (finiteWeightRestrictedKernel K b) y'
  have hq : finiteWeightRestrictedQuotientMap K hK b x =
      finiteWeightRestrictedQuotientMap K hK b y := by
    simpa only [finiteWeightRestrictedQuotientLift_mk] using hxy
  apply (Submodule.Quotient.eq _).mpr
  rw [← ker_finiteWeightRestrictedQuotientMap K hK b,
    LinearMap.mem_ker, map_sub, sub_eq_zero]
  exact hq

/-- The concrete `R/(b)`-linear equivalence

`K/(b)K ≃ ∏ i, Kᵢ/(b)Kᵢ`.
-/
def finiteWeightRestrictedQuotientEquiv
    (K : Submodule R (∀ i, M i))
    (hK : ∀ x ∈ K, ∀ i, Pi.single i (x i) ∈ K)
    (b : R) :
    (K ⧸ finiteWeightRestrictedKernel K b) ≃ₗ[R ⧸ Ideal.span {b}]
      finiteWeightRestrictedQuotient K b :=
  LinearEquiv.ofBijective (finiteWeightRestrictedQuotientLift K hK b)
    ⟨finiteWeightRestrictedQuotientLift_injective K hK b,
      finiteWeightRestrictedQuotientLift_surjective K hK b⟩

@[simp]
theorem finiteWeightRestrictedQuotientEquiv_mk
    (K : Submodule R (∀ i, M i))
    (hK : ∀ x ∈ K, ∀ i, Pi.single i (x i) ∈ K)
    (b : R) (x : K) :
    finiteWeightRestrictedQuotientEquiv K hK b
      (Submodule.Quotient.mk x) =
        finiteWeightRestrictedQuotientMap K hK b x := rfl

end RestrictedQuotient

section InvariantAutomorphism

variable {R : Type*} [CommRing R] {n : ℕ}
variable {M : Fin n → Type*}
variable [∀ i, AddCommGroup (M i)] [∀ i, Module R (M i)]

/-- Restrict an ambient automorphism to an invariant homogeneous submodule.
Only invariance is needed for this construction. -/
def finiteWeightInvariantSubmoduleEquiv
    (J : (∀ i, M i) ≃ₗ[R] (∀ i, M i))
    (K : Submodule R (∀ i, M i))
    (hJK : K.map J.toLinearMap = K) : K ≃ₗ[R] K :=
  J.ofSubmodules K K hJK

@[simp]
theorem finiteWeightInvariantSubmoduleEquiv_coe
    (J : (∀ i, M i) ≃ₗ[R] (∀ i, M i))
    (K : Submodule R (∀ i, M i))
    (hJK : K.map J.toLinearMap = K) (x : K) :
    (finiteWeightInvariantSubmoduleEquiv J K hJK x : ∀ i, M i) = J x :=
  LinearEquiv.ofSubmodules_apply J hJK x

/-- The automorphism of `K/(b)K` induced by an automorphism preserving `K`.
-/
def finiteWeightInvariantSubmoduleQuotientEquiv
    (J : (∀ i, M i) ≃ₗ[R] (∀ i, M i))
    (K : Submodule R (∀ i, M i))
    (hJK : K.map J.toLinearMap = K) (b : R) :
    (K ⧸ finiteWeightRestrictedKernel K b) ≃ₗ[R ⧸ Ideal.span {b}]
      (K ⧸ finiteWeightRestrictedKernel K b) :=
  quotientIdealSMulTopLinearEquiv (Ideal.span {b})
    (finiteWeightInvariantSubmoduleEquiv J K hJK)

@[simp]
theorem finiteWeightInvariantSubmoduleQuotientEquiv_mk
    (J : (∀ i, M i) ≃ₗ[R] (∀ i, M i))
    (K : Submodule R (∀ i, M i))
    (hJK : K.map J.toLinearMap = K) (b : R) (x : K) :
    finiteWeightInvariantSubmoduleQuotientEquiv J K hJK b
      (Submodule.Quotient.mk x) =
        Submodule.Quotient.mk
          (finiteWeightInvariantSubmoduleEquiv J K hJK x) := rfl

/-- Conjugate the descended invariant automorphism into the product of the
coordinate quotients.  This is the automorphism to which the finite-weight
iteration theorem is applied over `R/(b)`. -/
def finiteWeightRestrictedEquivOfInvariant
    (J : (∀ i, M i) ≃ₗ[R] (∀ i, M i))
    (K : Submodule R (∀ i, M i))
    (hK : ∀ x ∈ K, ∀ i, Pi.single i (x i) ∈ K)
    (hJK : K.map J.toLinearMap = K) (b : R) :
    finiteWeightRestrictedQuotient K b ≃ₗ[R ⧸ Ideal.span {b}]
      finiteWeightRestrictedQuotient K b :=
  (finiteWeightRestrictedQuotientEquiv K hK b).symm.trans
    ((finiteWeightInvariantSubmoduleQuotientEquiv J K hJK b).trans
      (finiteWeightRestrictedQuotientEquiv K hK b))

/-- The transported automorphism commutes with the canonical quotient map.
This is the main application lemma for transporting invariance and the
triangular identity to the coordinate quotient. -/
@[simp]
theorem finiteWeightRestrictedEquivOfInvariant_apply_quotientMap
    (J : (∀ i, M i) ≃ₗ[R] (∀ i, M i))
    (K : Submodule R (∀ i, M i))
    (hK : ∀ x ∈ K, ∀ i, Pi.single i (x i) ∈ K)
    (hJK : K.map J.toLinearMap = K) (b : R) (x : K) :
    finiteWeightRestrictedEquivOfInvariant J K hK hJK b
        (finiteWeightRestrictedQuotientMap K hK b x) =
      finiteWeightRestrictedQuotientMap K hK b
        (finiteWeightInvariantSubmoduleEquiv J K hJK x) := by
  change finiteWeightRestrictedQuotientEquiv K hK b
      (finiteWeightInvariantSubmoduleQuotientEquiv J K hJK b
        ((finiteWeightRestrictedQuotientEquiv K hK b).symm
          (finiteWeightRestrictedQuotientMap K hK b x))) = _
  rw [← finiteWeightRestrictedQuotientEquiv_mk K hK b x,
    LinearEquiv.symm_apply_apply,
    finiteWeightInvariantSubmoduleQuotientEquiv_mk,
    finiteWeightRestrictedQuotientEquiv_mk]

end InvariantAutomorphism

end AbelFormalization

/-!
## Coordinate quotient map and triangular descent

The declarations above construct the quotient product from the subtype `K`.
For finite-weight iteration it is also useful to retain the literal product
of the coordinate submodules as the source.  The coordinatewise map below is
the `finiteWeightPiMap` of the individual quotient maps.  The final theorem
uses this map to descend the triangular identity.
-/

namespace AbelFormalization

section CoordinateQuotientMap

variable {R : Type*} [CommRing R] {n : ℕ}
variable {M : Fin n → Type*}
variable [∀ i, AddCommGroup (M i)] [∀ i, Module R (M i)]

/-- The quotient map on one coordinate submodule, bundled as a semilinear
map for `R → R/(b)`. -/
def finiteWeightRestrictedCoordinateQuotientMap
    (K : Submodule R (∀ i, M i)) (b : R) (i : Fin n) :
    finiteWeightCoordinateSubmodule K i →ₛₗ[
      Ideal.Quotient.mk (Ideal.span {b})]
      finiteWeightRestrictedCoordinateQuotient K b i where
  toFun := fun v => Submodule.Quotient.mk v
  map_add' := by
    intro x y
    rfl
  map_smul' := by
    intro r x
    exact (Module.Quotient.mk_smul_mk
      (finiteWeightCoordinateSubmodule K i) (Ideal.span {b}) r x).symm

@[simp]
theorem finiteWeightRestrictedCoordinateQuotientMap_apply
    (K : Submodule R (∀ i, M i)) (b : R) (i : Fin n)
    (v : finiteWeightCoordinateSubmodule K i) :
    finiteWeightRestrictedCoordinateQuotientMap K b i v =
      Submodule.Quotient.mk v := rfl

@[simp]
theorem ker_finiteWeightRestrictedCoordinateQuotientMap
    (K : Submodule R (∀ i, M i)) (b : R) (i : Fin n) :
    LinearMap.ker (finiteWeightRestrictedCoordinateQuotientMap K b i) =
      finiteWeightRestrictedCoordinateKernel K b i := by
  ext v
  change Submodule.Quotient.mk v = 0 ↔
    v ∈ finiteWeightRestrictedCoordinateKernel K b i
  exact Submodule.Quotient.mk_eq_zero _

theorem finiteWeightRestrictedCoordinateQuotientMap_surjective
    (K : Submodule R (∀ i, M i)) (b : R) (i : Fin n) :
    Function.Surjective
      (finiteWeightRestrictedCoordinateQuotientMap K b i) := by
  intro v
  obtain ⟨w, hw⟩ :=
    (finiteWeightRestrictedCoordinateKernel K b i).mkQ_surjective v
  exact ⟨w, hw⟩

/-- The product of the individual coordinate quotient maps. -/
def finiteWeightRestrictedPiQuotientMap
    (K : Submodule R (∀ i, M i)) (b : R) :
    (∀ i, finiteWeightCoordinateSubmodule K i) →ₛₗ[
      Ideal.Quotient.mk (Ideal.span {b})]
      finiteWeightRestrictedQuotient K b :=
  finiteWeightPiMap (finiteWeightRestrictedCoordinateQuotientMap K b)

@[simp]
theorem finiteWeightRestrictedPiQuotientMap_apply
    (K : Submodule R (∀ i, M i)) (b : R)
    (x : ∀ i, finiteWeightCoordinateSubmodule K i) (i : Fin n) :
    finiteWeightRestrictedPiQuotientMap K b x i =
      finiteWeightRestrictedCoordinateQuotientMap K b i (x i) := rfl

@[simp]
theorem finiteWeightRestrictedPiQuotientMap_single
    (K : Submodule R (∀ i, M i)) (b : R) (i : Fin n)
    (v : finiteWeightCoordinateSubmodule K i) :
    finiteWeightRestrictedPiQuotientMap K b (Pi.single i v) =
      Pi.single i (finiteWeightRestrictedCoordinateQuotientMap K b i v) := by
  exact finiteWeightPiMap_single
    (finiteWeightRestrictedCoordinateQuotientMap K b) i v

theorem finiteWeightRestrictedPiQuotientMap_prefix
    (K : Submodule R (∀ i, M i)) (b : R) (k : ℕ)
    (x : ∀ i, finiteWeightCoordinateSubmodule K i) :
    finiteWeightRestrictedPiQuotientMap K b
        (finiteWeightPrefixProjection R
          (fun i => finiteWeightCoordinateSubmodule K i) k x) =
      finiteWeightPrefixProjection (R ⧸ Ideal.span {b})
        (fun i => finiteWeightRestrictedCoordinateQuotient K b i) k
        (finiteWeightRestrictedPiQuotientMap K b x) := by
  exact finiteWeightPiMap_prefixProjection
    (finiteWeightRestrictedCoordinateQuotientMap K b) k x

theorem finiteWeightRestrictedPiQuotientMap_surjective
    (K : Submodule R (∀ i, M i)) (b : R) :
    Function.Surjective (finiteWeightRestrictedPiQuotientMap K b) := by
  exact finiteWeightPiMap_surjective
    (finiteWeightRestrictedCoordinateQuotientMap K b)
    (finiteWeightRestrictedCoordinateQuotientMap_surjective K b)

/-- The kernel of the product quotient map is exactly the product's
`(b)`-multiple. -/
theorem ker_finiteWeightRestrictedPiQuotientMap
    (K : Submodule R (∀ i, M i)) (b : R) :
    LinearMap.ker (finiteWeightRestrictedPiQuotientMap K b) =
      Ideal.span {b} •
        (⊤ : Submodule R
          (∀ i, finiteWeightCoordinateSubmodule K i)) := by
  ext x
  change x ∈ LinearMap.ker
      (finiteWeightPiMap
        (finiteWeightRestrictedCoordinateQuotientMap K b)) ↔ _
  rw [mem_ker_finiteWeightPiMap_iff]
  simp_rw [ker_finiteWeightRestrictedCoordinateQuotientMap]
  rw [ideal_smul_pi_top_eq_pi_ideal_smul_top
    (N := fun i => finiteWeightCoordinateSubmodule K i)
    (Ideal.span {b})]
  constructor
  · intro hx
    exact (Submodule.mem_pi).mpr fun i hi => hx i
  · intro hx i
    exact (Submodule.mem_pi.mp hx) i (Set.mem_univ i)

/-- The product quotient map composed with the homogeneous-subtype
equivalence is the previously defined canonical quotient map from `K`. -/
@[simp]
theorem finiteWeightRestrictedPiQuotientMap_homogeneousSubtypeEquiv
    (K : Submodule R (∀ i, M i))
    (hK : ∀ x ∈ K, ∀ i, Pi.single i (x i) ∈ K)
    (b : R) (x : K) :
    finiteWeightRestrictedPiQuotientMap K b
        (finiteWeightHomogeneousSubtypeEquiv K hK x) =
      finiteWeightRestrictedQuotientMap K hK b x := rfl

/-- The same compatibility, in the direction used to choose a coordinate
lift of a quotient vector. -/
@[simp]
theorem finiteWeightRestrictedQuotientMap_homogeneousSubtypeEquiv_symm
    (K : Submodule R (∀ i, M i))
    (hK : ∀ x ∈ K, ∀ i, Pi.single i (x i) ∈ K)
    (b : R) (x : ∀ i, finiteWeightCoordinateSubmodule K i) :
    finiteWeightRestrictedQuotientMap K hK b
        ((finiteWeightHomogeneousSubtypeEquiv K hK).symm x) =
      finiteWeightRestrictedPiQuotientMap K b x := by
  rw [← finiteWeightRestrictedPiQuotientMap_homogeneousSubtypeEquiv
      K hK b ((finiteWeightHomogeneousSubtypeEquiv K hK).symm x),
    (finiteWeightHomogeneousSubtypeEquiv K hK).apply_symm_apply]

end CoordinateQuotientMap

section CoordinateInvariantAutomorphism

variable {R : Type*} [CommRing R] {n : ℕ}
variable {M : Fin n → Type*}
variable [∀ i, AddCommGroup (M i)] [∀ i, Module R (M i)]

/-- The coordinate quotient map intertwines the coordinate restriction of
an invariant automorphism with the descended quotient automorphism. -/
theorem finiteWeightRestrictedPiQuotientMap_intertwines
    (J : (∀ i, M i) ≃ₗ[R] (∀ i, M i))
    (K : Submodule R (∀ i, M i))
    (hK : ∀ x ∈ K, ∀ i, Pi.single i (x i) ∈ K)
    (hJK : K.map J.toLinearMap = K) (b : R)
    (x : ∀ i, finiteWeightCoordinateSubmodule K i) :
    finiteWeightRestrictedEquivOfInvariant J K hK hJK b
        (finiteWeightRestrictedPiQuotientMap K b x) =
      finiteWeightRestrictedPiQuotientMap K b
        (finiteWeightInvariantCoordinateEquiv J K hK hJK x) := by
  let E := finiteWeightHomogeneousSubtypeEquiv K hK
  let JK := finiteWeightInvariantSubmoduleEquiv J K hJK
  calc
    finiteWeightRestrictedEquivOfInvariant J K hK hJK b
        (finiteWeightRestrictedPiQuotientMap K b x) =
      finiteWeightRestrictedEquivOfInvariant J K hK hJK b
        (finiteWeightRestrictedQuotientMap K hK b (E.symm x)) :=
          congrArg (finiteWeightRestrictedEquivOfInvariant J K hK hJK b)
            (finiteWeightRestrictedQuotientMap_homogeneousSubtypeEquiv_symm
              K hK b x).symm
    _ = finiteWeightRestrictedQuotientMap K hK b (JK (E.symm x)) :=
      finiteWeightRestrictedEquivOfInvariant_apply_quotientMap
        J K hK hJK b (E.symm x)
    _ = finiteWeightRestrictedPiQuotientMap K b (E (JK (E.symm x))) :=
      (finiteWeightRestrictedPiQuotientMap_homogeneousSubtypeEquiv
        K hK b (JK (E.symm x))).symm
    _ = finiteWeightRestrictedPiQuotientMap K b
        (finiteWeightInvariantCoordinateEquiv J K hK hJK x) := rfl

/-- A triangular invariant automorphism remains triangular on the product
of coordinate quotients over `R/(b)`. -/
theorem finiteWeightRestrictedEquivOfInvariant_triangular
    (J : (∀ i, M i) ≃ₗ[R] (∀ i, M i))
    (htri : ∀ i (v : M i),
      J (Pi.single i v) = Pi.single i v +
        finiteWeightPrefixProjection R M i.val (J (Pi.single i v)))
    (K : Submodule R (∀ i, M i))
    (hK : ∀ x ∈ K, ∀ i, Pi.single i (x i) ∈ K)
    (hJK : K.map J.toLinearMap = K) (b : R) :
    ∀ i (v : finiteWeightRestrictedCoordinateQuotient K b i),
      finiteWeightRestrictedEquivOfInvariant J K hK hJK b
          (Pi.single i v) =
        Pi.single i v +
          finiteWeightPrefixProjection (R ⧸ Ideal.span {b})
            (fun i => finiteWeightRestrictedCoordinateQuotient K b i)
            i.val
            (finiteWeightRestrictedEquivOfInvariant J K hK hJK b
              (Pi.single i v)) := by
  classical
  intro i v
  obtain ⟨w, rfl⟩ :=
    finiteWeightRestrictedCoordinateQuotientMap_surjective K b i v
  let A := finiteWeightInvariantCoordinateEquiv J K hK hJK
  let q := finiteWeightRestrictedPiQuotientMap K b
  have hsingle : q (Pi.single i w) =
      Pi.single i (finiteWeightRestrictedCoordinateQuotientMap K b i w) :=
    finiteWeightRestrictedPiQuotientMap_single K b i w
  have hintertwine :
      finiteWeightRestrictedEquivOfInvariant J K hK hJK b
          (Pi.single i
            (finiteWeightRestrictedCoordinateQuotientMap K b i w)) =
        q (A (Pi.single i w)) := by
    rw [← hsingle]
    exact finiteWeightRestrictedPiQuotientMap_intertwines
      J K hK hJK b (Pi.single i w)
  have hA := finiteWeightInvariantCoordinateEquiv_triangular
    J htri K hK hJK i w
  have hprefix := finiteWeightRestrictedPiQuotientMap_prefix
    K b i.val (A (Pi.single i w))
  calc
    finiteWeightRestrictedEquivOfInvariant J K hK hJK b
        (Pi.single i
          (finiteWeightRestrictedCoordinateQuotientMap K b i w)) =
      q (A (Pi.single i w)) := hintertwine
    _ = q (Pi.single i w +
        finiteWeightPrefixProjection R
          (fun i => finiteWeightCoordinateSubmodule K i) i.val
          (A (Pi.single i w))) := congrArg q hA
    _ = q (Pi.single i w) +
        q (finiteWeightPrefixProjection R
          (fun i => finiteWeightCoordinateSubmodule K i) i.val
          (A (Pi.single i w))) := q.map_add _ _
    _ = Pi.single i
          (finiteWeightRestrictedCoordinateQuotientMap K b i w) +
        finiteWeightPrefixProjection (R ⧸ Ideal.span {b})
          (fun i => finiteWeightRestrictedCoordinateQuotient K b i)
          i.val (q (A (Pi.single i w))) := by
      rw [hsingle, hprefix]
    _ = Pi.single i
          (finiteWeightRestrictedCoordinateQuotientMap K b i w) +
        finiteWeightPrefixProjection (R ⧸ Ideal.span {b})
          (fun i => finiteWeightRestrictedCoordinateQuotient K b i)
          i.val
          (finiteWeightRestrictedEquivOfInvariant J K hK hJK b
            (Pi.single i
              (finiteWeightRestrictedCoordinateQuotientMap K b i w))) := by
      rw [hintertwine]

end CoordinateInvariantAutomorphism

end AbelFormalization
