import AbelFormalization.LaurentIdealTools
import Mathlib.Algebra.MonoidAlgebra.Grading
import Mathlib.RingTheory.GradedAlgebra.Homogeneous.Ideal

/-!
# Homogeneous ideals in a Laurent polynomial ring

The coefficient ring has weight zero and the Laurent variable has weight one.
Every homogeneous ideal is extended from its coefficient contraction. No
domain or Noetherian assumption is needed for this extension statement.
Noetherianity is used only for equality of ideal heights.
-/

noncomputable section

namespace AbelFormalization

variable {R : Type*} [CommRing R]

/-- Multiplication by an inverse Laurent monomial normalizes a homogeneous
monomial to its coefficient. This identity is valid over rings with zero
divisors as well. -/
theorem laurent_inverse_monomial_mul_single (n : ℤ) (a : R) :
    LaurentPolynomial.T (-n) * AddMonoidAlgebra.single n a =
      LaurentPolynomial.C a := by
  change AddMonoidAlgebra.single (-n) (1 : R) * AddMonoidAlgebra.single n a =
    AddMonoidAlgebra.single 0 a
  simp

/-- A homogeneous Laurent polynomial is exactly a single Laurent monomial. -/
theorem laurent_homogeneous_iff_single (f : LaurentPolynomial R) :
    SetLike.IsHomogeneousElem (AddMonoidAlgebra.grade R) f ↔
      ∃ n : ℤ, ∃ a : R, AddMonoidAlgebra.single n a = f := by
  constructor
  · rintro ⟨n, hn⟩
    obtain ⟨a, ha⟩ := (AddMonoidAlgebra.mem_grade_iff' R n f).mp hn
    exact ⟨n, a, ha⟩
  · rintro ⟨n, a, rfl⟩
    exact ⟨n, AddMonoidAlgebra.single_mem_grade n a⟩

/-- Normalizing a homogeneous element of an ideal gives an element of its
coefficient contraction, and hence of the extension of that contraction. -/
theorem laurent_homogeneous_mem_map_comap (K : Ideal (LaurentPolynomial R))
    {f : LaurentPolynomial R}
    (hhom : SetLike.IsHomogeneousElem (AddMonoidAlgebra.grade R) f)
    (hf : f ∈ K) :
    f ∈ (K.comap LaurentPolynomial.C).map LaurentPolynomial.C := by
  obtain ⟨n, a, rfl⟩ := (laurent_homogeneous_iff_single f).mp hhom
  have ha : LaurentPolynomial.C a ∈ K := by
    simpa only [laurent_inverse_monomial_mul_single] using
      K.mul_mem_left (LaurentPolynomial.T (-n)) hf
  rw [LaurentPolynomial.single_eq_C_mul_T]
  exact ((K.comap LaurentPolynomial.C).map LaurentPolynomial.C).mul_mem_right
    (LaurentPolynomial.T n) (Ideal.mem_map_of_mem LaurentPolynomial.C ha)

/-- A homogeneous Laurent ideal is generated by its actual coefficient
contraction. The generators come from every homogeneous element of the ideal.
There is no finite-generation or domain hypothesis. -/
theorem laurent_homogeneousIdeal_eq_map_comap (K : Ideal (LaurentPolynomial R))
    (hK : K.IsHomogeneous (AddMonoidAlgebra.grade R)) :
    K = (K.comap LaurentPolynomial.C).map LaurentPolynomial.C := by
  obtain ⟨s, hs⟩ := (Ideal.IsHomogeneous.iff_exists (AddMonoidAlgebra.grade R) K).mp hK
  apply le_antisymm
  · calc
      K = Ideal.span ((↑) '' s) := hs
      _ ≤ (K.comap LaurentPolynomial.C).map LaurentPolynomial.C := by
        apply Ideal.span_le.mpr
        rintro f ⟨g, hg, rfl⟩
        apply laurent_homogeneous_mem_map_comap K g.property
        rw [hs]
        exact Ideal.subset_span ⟨g, hg, rfl⟩
  · exact Ideal.map_comap_le

/-- Every coefficient of a homogeneous Laurent ideal belongs to its
coefficient contraction. -/
theorem laurent_homogeneousIdeal_coeff_mem (K : Ideal (LaurentPolynomial R))
    (hK : K.IsHomogeneous (AddMonoidAlgebra.grade R))
    {f : LaurentPolynomial R} (hf : f ∈ K) (n : ℤ) :
    f.coeff n ∈ K.comap LaurentPolynomial.C := by
  rw [laurent_homogeneousIdeal_eq_map_comap K hK] at hf
  exact (laurentPolynomial_mem_map_C_iff _ f).mp hf n

/-- The homogeneous monomial projection of an element stays in the ideal. -/
theorem laurent_homogeneousIdeal_single_coeff_mem (K : Ideal (LaurentPolynomial R))
    (hK : K.IsHomogeneous (AddMonoidAlgebra.grade R))
    {f : LaurentPolynomial R} (hf : f ∈ K) (n : ℤ) :
    AddMonoidAlgebra.single n (f.coeff n) ∈ K := by
  have hc : LaurentPolynomial.C (f.coeff n) ∈ K :=
    laurent_homogeneousIdeal_coeff_mem K hK hf n
  rw [LaurentPolynomial.single_eq_C_mul_T]
  exact K.mul_mem_right (LaurentPolynomial.T n) hc

/-- A homogeneous ideal in a one-variable Laurent extension has the same
height as its contraction to the weight-zero coefficient ring. -/
theorem laurent_homogeneousIdeal_height [IsNoetherianRing R]
    (K : Ideal (LaurentPolynomial R))
    (hK : K.IsHomogeneous (AddMonoidAlgebra.grade R)) :
    K.height = (K.comap LaurentPolynomial.C).height := by
  calc
    K.height = ((K.comap LaurentPolynomial.C).map LaurentPolynomial.C).height :=
      congrArg Ideal.height (laurent_homogeneousIdeal_eq_map_comap K hK)
    _ = (K.comap LaurentPolynomial.C).height :=
      laurentPolynomialIdeal_height_map_C _

end AbelFormalization
