import AbelFormalization.IdealHeight

/-!
# Height after adjoining invertible polynomial variables

The Laurent polynomial ring is realized as the localization of the polynomial
ring at the multiplicative set generated by its variables. Coefficient-extended
ideals are saturated under this multiplicative set. Together with localization
and polynomial extension invariance, this proves the Laurent extension height
step in the proof of the paper's Lemma `lem:height`.
-/

noncomputable section

namespace AbelFormalization

open Ideal

variable {R ι : Type*} [CommRing R]

/-- The monomials inverted to adjoin inverses of all polynomial variables. -/
def laurentVariableSubmonoid (ι R : Type*) [CommRing R] :
    Submonoid (MvPolynomial ι R) :=
  Submonoid.closure (Set.range MvPolynomial.X)

/-- Multiplication by a product of variables can be cancelled from membership
in a coefficient-extended ideal. -/
theorem mvPolynomial_extension_cancel_monomial (I : Ideal R) {s : MvPolynomial ι R}
    (hs : s ∈ laurentVariableSubmonoid ι R) :
    ∀ f : MvPolynomial ι R, s * f ∈ I.map MvPolynomial.C → f ∈ I.map MvPolynomial.C := by
  induction hs using Submonoid.closure_induction with
  | mem s hs =>
      obtain ⟨i, rfl⟩ := hs
      intro f hf
      rw [MvPolynomial.mem_map_C_iff] at hf ⊢
      intro d
      exact (congrArg (fun r : R => r ∈ I) (MvPolynomial.coeff_X_mul d i f)).mp
        (hf (Finsupp.single i 1 + d))
  | one =>
      intro f hf
      simpa only [one_mul] using hf
  | mul a b ha hb iha ihb =>
      intro f hf
      apply ihb f
      apply iha (b * f)
      simpa only [mul_assoc] using hf

/-- Extending a coefficient ideal to a Laurent localization and contracting
back recovers its polynomial extension. No Noetherian hypothesis is needed. -/
theorem mvPolynomial_extension_under_laurent_localization (I : Ideal R)
    {S : Type*} [CommRing S] [Algebra (MvPolynomial ι R) S]
    [IsLocalization (laurentVariableSubmonoid ι R) S] :
    ((I.map MvPolynomial.C).map (algebraMap (MvPolynomial ι R) S)).comap
      (algebraMap (MvPolynomial ι R) S) = I.map MvPolynomial.C := by
  ext f
  rw [Ideal.mem_comap, IsLocalization.algebraMap_mem_map_algebraMap_iff
    (laurentVariableSubmonoid ι R) S]
  constructor
  · rintro ⟨s, hs, hsf⟩
    exact mvPolynomial_extension_cancel_monomial I hs f hsf
  · intro hf
    exact ⟨1, Submonoid.one_mem _, by simpa only [one_mul] using hf⟩

variable [IsNoetherianRing R] [Finite ι]

/-- Adjoining finitely many invertible variables preserves the height of
every ideal of the coefficient ring. The target may be any realization of
the relevant Laurent localization. -/
theorem laurentIdealHeight_map (I : Ideal R)
    {S : Type*} [CommRing S] [Algebra (MvPolynomial ι R) S]
    [IsLocalization (laurentVariableSubmonoid ι R) S] :
    (I.map ((algebraMap (MvPolynomial ι R) S).comp MvPolynomial.C)).height = I.height := by
  rw [← Ideal.map_map]
  calc
    ((I.map MvPolynomial.C).map (algebraMap (MvPolynomial ι R) S)).height =
        (((I.map MvPolynomial.C).map (algebraMap (MvPolynomial ι R) S)).comap
          (algebraMap (MvPolynomial ι R) S)).height :=
      (idealHeight_localization_under (laurentVariableSubmonoid ι R) _).symm
    _ = (I.map (MvPolynomial.C (σ := ι))).height := by
      rw [mvPolynomial_extension_under_laurent_localization]
    _ = I.height := mvPolynomial_height_map_C I

/-- The same height equality using a compatible coefficient-algebra map. -/
theorem laurentIdealHeight_map_algebraMap (I : Ideal R)
    {S : Type*} [CommRing S] [Algebra (MvPolynomial ι R) S] [Algebra R S]
    [IsScalarTower R (MvPolynomial ι R) S]
    [IsLocalization (laurentVariableSubmonoid ι R) S] :
    (I.map (algebraMap R S)).height = I.height := by
  rw [IsScalarTower.algebraMap_eq R (MvPolynomial ι R) S, MvPolynomial.algebraMap_eq]
  exact laurentIdealHeight_map I

/-- Canonical simultaneous Laurent polynomial extension of the coefficient
ring, represented by a localization. -/
abbrev LaurentExtension (ι R : Type*) [CommRing R] :=
  Localization (laurentVariableSubmonoid ι R)

/-- Height preservation for the canonical Laurent extension. -/
theorem laurentExtension_height_map (I : Ideal R) :
    (I.map ((algebraMap (MvPolynomial ι R) (LaurentExtension ι R)).comp
      MvPolynomial.C)).height = I.height :=
  laurentIdealHeight_map I

end AbelFormalization
