import AbelFormalization.LexicographicInitialForms
import AbelFormalization.WeightedInitialComponents
import AbelFormalization.WeightedInitialLifting

/-!
# Full lexicographic initial ideals and their height

The definition uses the actual least lexicographic component of every ideal
element. Its equality with successive scalar initial operations follows by
decomposing an arbitrary first-initial-ideal member into homogeneous pieces
and lifting each piece. No domain assumption or choice of generators is used.
-/

noncomputable section

namespace AbelFormalization

variable {R ι : Type*} [CommRing R] {h : ℕ}

/-- The full ideal generated by actual least lexicographic components. -/
def lexicographicInitialIdeal (ω : ι → Fin h → ℤ)
    (I : Ideal (MvPolynomial ι R)) : Ideal (MvPolynomial ι R) :=
  Ideal.span (lexicographicInitialForm ω '' (I : Set (MvPolynomial ι R)))

theorem lexicographicInitialForm_mem_initialIdeal (ω : ι → Fin h → ℤ)
    (I : Ideal (MvPolynomial ι R)) {f : MvPolynomial ι R} (hf : f ∈ I) :
    lexicographicInitialForm ω f ∈ lexicographicInitialIdeal ω I :=
  Ideal.subset_span ⟨f, hf, rfl⟩

/-- A nonzero specified component at a support lower bound identifies the
actual lexicographic minimum. -/
theorem lexicographicMinimumWeight_eq_of_component_ne_zero
    (ω : ι → Fin h → ℤ) (f : MvPolynomial ι R) (β : Lex (Fin h → ℤ))
    (hbound : ∀ d ∈ f.support, β ≤ Finsupp.weight (fun i => toLex (ω i)) d)
    (hne : MvPolynomial.weightedHomogeneousComponent (fun i => toLex (ω i)) β f ≠ 0) :
    lexicographicMinimumWeight ω f = β := by
  classical
  have hf : f ≠ 0 := by
    intro hz
    apply hne
    rw [hz, map_zero]
  apply le_antisymm
  · obtain ⟨d, hd⟩ := MvPolynomial.exists_coeff_ne_zero hne
    have hweight : Finsupp.weight (fun i => toLex (ω i)) d = β :=
      MvPolynomial.weightedHomogeneousComponent_isWeightedHomogeneous β f hd
    have hfd : f.coeff d ≠ 0 := by
      simpa only [MvPolynomial.coeff_weightedHomogeneousComponent, ite_eq_left hweight] using hd
    exact (lexicographicMinimumWeight_le ω f
      (MvPolynomial.mem_support_iff.mpr hfd)).trans_eq hweight
  · obtain ⟨d, hd, hweight⟩ := exists_support_lexicographicWeight_eq_minimum ω hf
    exact (hbound d hd).trans_eq hweight

/-- A nonzero head component of a tail initial is the tail initial of the
corresponding head component of the original polynomial. -/
theorem lexicographicInitialForm_of_component
    (ω : ι → ℤ) (ν : ι → Fin h → ℤ) (α : ℤ) (g : MvPolynomial ι R)
    (hne : MvPolynomial.weightedHomogeneousComponent ω α
      (lexicographicInitialForm ν g) ≠ 0) :
    lexicographicInitialForm ν (MvPolynomial.weightedHomogeneousComponent ω α g) =
      MvPolynomial.weightedHomogeneousComponent ω α (lexicographicInitialForm ν g) := by
  classical
  let p := MvPolynomial.weightedHomogeneousComponent ω α g
  let β := lexicographicMinimumWeight ν g
  have hcomm : MvPolynomial.weightedHomogeneousComponent (fun i => toLex (ν i)) β p =
      MvPolynomial.weightedHomogeneousComponent ω α (lexicographicInitialForm ν g) := by
    exact weightedHomogeneousComponents_commute (fun i => toLex (ν i)) ω β α g
  have hbound : ∀ d ∈ p.support, β ≤ Finsupp.weight (fun i => toLex (ν i)) d := by
    intro d hd
    have hsupport : p.support ⊆ g.support := by
      change (MvPolynomial.weightedHomogeneousComponent ω α g).support ⊆ g.support
      rw [MvPolynomial.support_weightedHomogeneousComponent]
      exact Finset.filter_subset _ _
    exact lexicographicMinimumWeight_le ν g (hsupport hd)
  have hmin : lexicographicMinimumWeight ν p = β :=
    lexicographicMinimumWeight_eq_of_component_ne_zero ν p β hbound
      (by rwa [hcomm])
  change MvPolynomial.weightedHomogeneousComponent (fun i => toLex (ν i))
    (lexicographicMinimumWeight ν p) p = _
  rw [hmin]
  exact hcomm

/-- Full lexicographic initial formation agrees with first taking the head
initial ideal, then taking the full initial ideal for the remaining weights. -/
theorem lexicographicInitialIdeal_cons (ω : ι → ℤ) (ν : ι → Fin h → ℤ)
    (I : Ideal (MvPolynomial ι R)) :
    lexicographicInitialIdeal (fun i => Fin.cons (ω i) (ν i)) I =
      lexicographicInitialIdeal ν (weightedInitialIdeal ω I) := by
  classical
  apply le_antisymm
  · apply Ideal.span_le.mpr
    rintro _ ⟨f, hf, rfl⟩
    rw [lexicographicInitialForm_cons]
    apply lexicographicInitialForm_mem_initialIdeal
    exact Ideal.subset_span ⟨f, hf, rfl⟩
  · apply Ideal.span_le.mpr
    rintro _ ⟨g, hg, rfl⟩
    rw [← sum_weightedHomogeneousComponent_support ω (lexicographicInitialForm ν g)]
    apply Ideal.sum_mem
    intro α hα
    by_cases hzero : MvPolynomial.weightedHomogeneousComponent ω α
        (lexicographicInitialForm ν g) = 0
    · rw [hzero]
      exact (lexicographicInitialIdeal (fun i => Fin.cons (ω i) (ν i)) I).zero_mem
    · let p := MvPolynomial.weightedHomogeneousComponent ω α g
      have hp : p ∈ weightedInitialIdeal ω I := weightedInitialIdeal_component_mem ω I hg α
      have hhom : p.IsWeightedHomogeneous ω α :=
        MvPolynomial.weightedHomogeneousComponent_isWeightedHomogeneous α g
      have heq : lexicographicInitialForm ν p =
          MvPolynomial.weightedHomogeneousComponent ω α (lexicographicInitialForm ν g) :=
        lexicographicInitialForm_of_component ω ν α g hzero
      have hpne : p ≠ 0 := by
        intro hp0
        apply hzero
        rw [← heq, hp0, lexicographicInitialForm_zero]
      obtain ⟨f, hf, hfne, hmin, hproj⟩ :=
        exists_initial_form_lift_weightedInitialIdeal ω I hp hhom hpne
      have hform : lexicographicInitialForm (fun i => Fin.cons (ω i) (ν i)) f =
          MvPolynomial.weightedHomogeneousComponent ω α (lexicographicInitialForm ν g) := by
        rw [lexicographicInitialForm_cons, hproj]
        exact heq
      rw [← hform]
      exact lexicographicInitialForm_mem_initialIdeal _ I hf

@[simp]
theorem lexicographicInitialIdeal_zero_dim (ω : ι → Fin 0 → ℤ)
    (I : Ideal (MvPolynomial ι R)) : lexicographicInitialIdeal ω I = I := by
  unfold lexicographicInitialIdeal
  have hform : lexicographicInitialForm ω = (id : MvPolynomial ι R → MvPolynomial ι R) := by
    funext f
    exact lexicographicInitialForm_zero_dim ω f
  rw [hform, Set.image_id, Ideal.span_eq]

/-- The full initial ideal for any finite tuple of signed integer weights
cannot have smaller height than the original ideal. -/
theorem lexicographicInitialIdeal_height [IsNoetherianRing R] [Finite ι] :
    ∀ {h : ℕ} (ω : ι → Fin h → ℤ) (I : Ideal (MvPolynomial ι R)),
      I.height ≤ (lexicographicInitialIdeal ω I).height := by
  intro h
  induction h with
  | zero =>
      intro ω I
      rw [lexicographicInitialIdeal_zero_dim]
  | succ h ih =>
      intro ω I
      have hω : ω = fun i => Fin.cons (ω i 0) (Fin.tail (ω i)) := by
        funext i
        exact (Fin.cons_self_tail (ω i)).symm
      rw [hω, lexicographicInitialIdeal_cons]
      exact (weightedInitialIdeal_height (fun i => ω i 0) I).trans
        (ih (fun i => Fin.tail (ω i)) (weightedInitialIdeal (fun i => ω i 0) I))

end AbelFormalization
