import AbelFormalization.LexicographicInitialIdeals
import AbelFormalization.WeightedGroupEvaluation

set_option autoImplicit false

/-!
# Components of full lexicographic initial ideals

The full ideal generated by least lexicographic forms is homogeneous for the
same vector grading.  Consequently all of its actual weight components stay
in the ideal, and initial formation fixes an already homogeneous ideal.
-/

noncomputable section

namespace AbelFormalization

variable {R ι : Type*} [CommRing R] {h : ℕ}

attribute [local instance] MvPolynomial.weightedGradedAlgebra

/-- The full all-elements lexicographic initial ideal is homogeneous for its
vector weight grading. -/
theorem lexicographicInitialIdeal_isHomogeneous
    (ω : ι → Fin h → ℤ) (I : Ideal (MvPolynomial ι R)) :
    (lexicographicInitialIdeal ω I).IsHomogeneous
      (MvPolynomial.weightedHomogeneousSubmodule R
        (fun i => toLex (ω i))) := by
  classical
  apply Ideal.homogeneous_span
  rintro _ ⟨f, _hf, rfl⟩
  exact ⟨lexicographicMinimumWeight ω f,
    MvPolynomial.weightedHomogeneousComponent_mem
      (fun i => toLex (ω i)) f (lexicographicMinimumWeight ω f)⟩

/-- Every vector-weight component of a member of the full lexicographic
initial ideal belongs to that ideal. -/
theorem lexicographicInitialIdeal_component_mem
    (ω : ι → Fin h → ℤ) (I : Ideal (MvPolynomial ι R))
    {g : MvPolynomial ι R} (hg : g ∈ lexicographicInitialIdeal ω I)
    (β : Lex (Fin h → ℤ)) :
    MvPolynomial.weightedHomogeneousComponent
        (fun i => toLex (ω i)) β g ∈
      lexicographicInitialIdeal ω I :=
  MvPolynomial.weightedHomogeneousComponent_mem_of_mem R
    (fun i => toLex (ω i))
    (lexicographicInitialIdeal_isHomogeneous ω I) hg β

/-- A nonzero polynomial homogeneous for the vector weight has that weight
as its actual lexicographic minimum. -/
theorem lexicographicMinimumWeight_of_homogeneous
    (ω : ι → Fin h → ℤ) {β : Lex (Fin h → ℤ)}
    {f : MvPolynomial ι R}
    (hf : f.IsWeightedHomogeneous (fun i => toLex (ω i)) β)
    (hne : f ≠ 0) :
    lexicographicMinimumWeight ω f = β := by
  obtain ⟨d, hd, hweight⟩ :=
    exists_support_lexicographicWeight_eq_minimum ω hne
  exact hweight.symm.trans (hf (MvPolynomial.mem_support_iff.mp hd))

/-- Full lexicographic initial formation fixes ideals already homogeneous for
the complete vector grading. -/
theorem lexicographicInitialIdeal_eq_of_homogeneous
    (ω : ι → Fin h → ℤ) (I : Ideal (MvPolynomial ι R))
    (hI : I.IsHomogeneous
      (MvPolynomial.weightedHomogeneousSubmodule R
        (fun i => toLex (ω i)))) :
    lexicographicInitialIdeal ω I = I := by
  classical
  apply le_antisymm
  · apply Ideal.span_le.mpr
    rintro _ ⟨f, hf, rfl⟩
    exact MvPolynomial.weightedHomogeneousComponent_mem_of_mem R
      (fun i => toLex (ω i)) hI hf _
  · intro f hf
    rw [← sum_weightedHomogeneousComponent_support
      (fun i => toLex (ω i)) f]
    apply Ideal.sum_mem
    intro β hβ
    let g := MvPolynomial.weightedHomogeneousComponent
      (fun i => toLex (ω i)) β f
    have hg : g ∈ I :=
      MvPolynomial.weightedHomogeneousComponent_mem_of_mem R
        (fun i => toLex (ω i)) hI hf β
    by_cases hzero : g = 0
    · change g ∈ lexicographicInitialIdeal ω I
      rw [hzero]
      exact (lexicographicInitialIdeal ω I).zero_mem
    · have hhom : g.IsWeightedHomogeneous
          (fun i => toLex (ω i)) β :=
        MvPolynomial.weightedHomogeneousComponent_isWeightedHomogeneous β f
      have hmin := lexicographicMinimumWeight_of_homogeneous ω hhom hzero
      have heq : lexicographicInitialForm ω g = g := by
        change MvPolynomial.weightedHomogeneousComponent
          (fun i => toLex (ω i)) (lexicographicMinimumWeight ω g) g = g
        rw [hmin]
        exact hhom.weightedHomogeneousComponent_same
      change g ∈ lexicographicInitialIdeal ω I
      rw [← heq]
      exact lexicographicInitialForm_mem_initialIdeal ω I hg

/-! ## Lifting a prescribed vector-weight component -/

/-- Filtering by a head integer weight and then by the remaining vector
weight is the same as filtering once by the corresponding `Fin.cons`
vector weight. -/
theorem weightedHomogeneousComponent_finCons
    (ω : ι → ℤ) (ν : ι → Fin h → ℤ)
    (a : ℤ) (β : Lex (Fin h → ℤ)) (f : MvPolynomial ι R) :
    MvPolynomial.weightedHomogeneousComponent
        (fun i => toLex (Fin.cons (ω i) (ν i)))
        (toLex ((Fin.cons a (ofLex β : Fin h → ℤ)) :
          Fin (h + 1) → ℤ)) f =
      MvPolynomial.weightedHomogeneousComponent
        (fun i => toLex (ν i)) β
        (MvPolynomial.weightedHomogeneousComponent ω a f) := by
  classical
  ext d
  simp only [MvPolynomial.coeff_weightedHomogeneousComponent,
    lexicographicWeight_cons, toLex_inj, Fin.cons_inj]
  by_cases hhead : Finsupp.weight ω d = a
  · simp [hhead]
  · simp [hhead]

/-- A homogeneous vector-weight component of the full lexicographic initial
ideal has an actual lift in the original ideal with no monomial below the
specified lexicographic weight.  This includes the zero component. -/
theorem exists_component_lift_lexicographicInitialIdeal :
    ∀ {h : ℕ} (ω : ι → Fin h → ℤ)
      (I : Ideal (MvPolynomial ι R))
      {β : Lex (Fin h → ℤ)} {g : MvPolynomial ι R},
      g ∈ lexicographicInitialIdeal ω I →
      g.IsWeightedHomogeneous (fun i => toLex (ω i)) β →
      ∃ f ∈ I,
        (∀ d ∈ f.support,
          β ≤ Finsupp.weight (fun i => toLex (ω i)) d) ∧
        MvPolynomial.weightedHomogeneousComponent
          (fun i => toLex (ω i)) β f = g := by
  intro h
  induction h with
  | zero =>
      intro ω I β g hg hhom
      have hgI : g ∈ I := by
        simpa only [lexicographicInitialIdeal_zero_dim] using hg
      refine ⟨g, hgI, ?_, hhom.weightedHomogeneousComponent_same⟩
      intro d hd
      exact (Subsingleton.elim
        (β : Lex (Fin 0 → ℤ))
        (Finsupp.weight (fun i => toLex (ω i)) d)).le
  | succ h ih =>
      intro ω I β g hg hhom
      classical
      let head : ι → ℤ := fun i => ω i 0
      let tail : ι → Fin h → ℤ := fun i => Fin.tail (ω i)
      let a : ℤ := ofLex β 0
      let βtail : Lex (Fin h → ℤ) := toLex (Fin.tail (ofLex β))
      have hω : ω = fun i => Fin.cons (head i) (tail i) := by
        funext i
        exact (Fin.cons_self_tail (ω i)).symm
      have hβ : β = toLex (Fin.cons a (ofLex βtail)) := by
        apply ofLex.injective
        rw [ofLex_toLex]
        exact (Fin.cons_self_tail (ofLex β)).symm
      have hg' : g ∈ lexicographicInitialIdeal tail
          (weightedInitialIdeal head I) := by
        rw [hω, lexicographicInitialIdeal_cons] at hg
        exact hg
      have hhomTail : g.IsWeightedHomogeneous
          (fun i => toLex (tail i)) βtail := by
        intro d hd
        dsimp only [tail, βtail]
        apply ofLex.injective
        funext j
        rw [lexicographicWeight_apply, ofLex_toLex]
        change Finsupp.weight (fun i => ω i j.succ) d = ofLex β j.succ
        have hw := congrArg
          (fun q : Lex (Fin (h + 1) → ℤ) => ofLex q j.succ) (hhom hd)
        simpa only [lexicographicWeight_apply] using hw
      obtain ⟨p, hp, hpbound, hpcomponent⟩ :=
        ih tail (weightedInitialIdeal head I) hg' hhomTail
      let q := MvPolynomial.weightedHomogeneousComponent head a p
      have hqmem : q ∈ weightedInitialIdeal head I :=
        weightedInitialIdeal_component_mem head I hp a
      have hqhom : q.IsWeightedHomogeneous head a :=
        MvPolynomial.weightedHomogeneousComponent_isWeightedHomogeneous a p
      have hqtail : MvPolynomial.weightedHomogeneousComponent
          (fun i => toLex (tail i)) βtail q = g := by
        change MvPolynomial.weightedHomogeneousComponent
          (fun i => toLex (tail i)) βtail
            (MvPolynomial.weightedHomogeneousComponent head a p) = g
        rw [weightedHomogeneousComponents_commute]
        rw [hpcomponent]
        have hhomHead : g.IsWeightedHomogeneous head a := by
          intro d hd
          have hw := congrArg
            (fun q : Lex (Fin (h + 1) → ℤ) => ofLex q 0) (hhom hd)
          simpa only [head, a, lexicographicWeight_apply] using hw
        exact hhomHead.weightedHomogeneousComponent_same
      obtain ⟨f, hfI, hfbound, hfcomponent⟩ :=
        exists_component_lift_weightedInitialIdeal head I hqmem hqhom
      refine ⟨f, hfI, ?_, ?_⟩
      · intro d hd
        rw [hω, hβ, lexicographicWeight_cons, finLex_cons_le_iff]
        have hhead : a ≤ Finsupp.weight head d := hfbound d hd
        rcases hhead.lt_or_eq with hlt | heq
        · exact Or.inl hlt
        · right
          refine ⟨heq, ?_⟩
          have hqcoeff : q.coeff d ≠ 0 := by
            rw [← hfcomponent]
            rw [MvPolynomial.coeff_weightedHomogeneousComponent,
              ite_eq_left heq.symm]
            exact MvPolynomial.mem_support_iff.mp hd
          have hpcoeff : p.coeff d ≠ 0 := by
            rw [MvPolynomial.coeff_weightedHomogeneousComponent,
              ite_eq_left heq.symm] at hqcoeff
            exact hqcoeff
          exact hpbound d (MvPolynomial.mem_support_iff.mpr hpcoeff)
      · rw [hω, hβ, weightedHomogeneousComponent_finCons,
          hfcomponent]
        exact hqtail

end AbelFormalization
