import AbelFormalization.LionGenericBoundFlatBridge
import AbelFormalization.LionLemma4RadialSelectionTheorem
import AbelFormalization.HermiteRankCanonicalSeparatedContradiction

/-!
# Lion's uniform fiber-finiteness theorem

The radial selection theorem discharges the final premise of the numerical
Theorem 7' and flat-compactification pipeline.  Thus the four standing family
hypotheses imply uniform fiber finiteness, with no residual Lion assumption.
The completed regular-zero theorem then specializes this endpoint to the
concrete family generated by every Abel function.
-/

noncomputable section

namespace AbelFormalization

set_option autoImplicit false

/-- The standing geometric, smoothness, derivative-closure, and zero-regularity
hypotheses imply uniform fiber finiteness. -/
theorem hasUniformFiberFiniteness_of_standingFamilyHypotheses
    {G : (d : ℕ) → Set (RealEuclideanFunction d)}
    (hG : IsGeometricFunctionFamily G)
    (hsmooth : IsEverywhereSmoothFunctionFamily G)
    (hderiv : IsCoordinateDerivativeClosedFunctionFamily G)
    (hzero : IsZeroRegularFunctionFamily G) :
    HasUniformFiberFiniteness G :=
  hasUniformFiberFiniteness_of_radialSelections
    hG hsmooth hderiv hzero
      (hasLionLemma4RadialSelections hG hsmooth hderiv)

/-- Every Abel function's concrete geometric family has uniform fiber
finiteness. -/
theorem IsAbel.hasUniformFiberFiniteness
    {A : ℝ → ℝ} (hA : IsAbel A) :
    HasUniformFiberFiniteness (abelGeometricFamily A) := by
  obtain ⟨hG, hsmooth, hderiv⟩ :=
    hA.geometric_smooth_derivativeClosed_abelGeometricFamily
  exact hasUniformFiberFiniteness_of_standingFamilyHypotheses
    hG hsmooth hderiv
      hA.isZeroRegular_abelGeometricFamily_of_canonicalBackwardPropagation

end AbelFormalization
