import Mathlib.Order.WellFoundedSet
import Mathlib.Order.UpperLower.Closure
import Mathlib.Order.WithBot
import Mathlib.Data.Fin.Tuple.Basic
import Mathlib.Data.List.OfFn

/-!
# Finite boxes and reverse-inclusion well-quasi-ordering of monomial upper sets

All orders on exponent vectors are
coordinatewise. Mathlib's bundled UpperSet order is reverse inclusion.

Dickson supplies a finite set of minimal exponents. The complement of its
upper closure is a finite union of boxes with endpoints in WithTop ℕ.
Higman on lists of these endpoints then gives Maclagan's antichain assertion.
Ascending-chain stabilization alone is not used as an antichain argument.
-/

noncomputable section

set_option autoImplicit false

namespace AbelFormalization

variable {n : ℕ}

/-- A box of natural exponent vectors, with possibly infinite upper bounds. -/
def monomialNatBox (b : Fin n → WithTop ℕ) : Set (Fin n → ℕ) :=
  {x | ∀ i, (x i : WithTop ℕ) < b i}

/-- A finite union of boxes, represented by a list of endpoints. -/
def monomialNatBoxList (l : List (Fin n → WithTop ℕ)) : Set (Fin n → ℕ) :=
  {x | ∃ b ∈ l, x ∈ monomialNatBox b}

theorem monomialNatBox_mono {b c : Fin n → WithTop ℕ} (h : b ≤ c) :
    monomialNatBox b ⊆ monomialNatBox c :=
  fun _ hx i => (hx i).trans_le (h i)

@[simp] theorem monomialNatBox_top :
    monomialNatBox (fun _ : Fin n => (⊤ : WithTop ℕ)) = Set.univ := by
  ext x
  simp [monomialNatBox]

theorem monomialNatBox_inf (b c : Fin n → WithTop ℕ) (x : Fin n → ℕ) :
    x ∈ monomialNatBox (b ⊓ c) ↔
      x ∈ monomialNatBox b ∧ x ∈ monomialNatBox c := by
  simp [monomialNatBox, forall_and]

/-- The endpoint vector of a single coordinate slab xᵢ < gᵢ. -/
def monomialAxisCap (g : Fin n → ℕ) (i : Fin n) : Fin n → WithTop ℕ :=
  fun j => if j = i then (g i : WithTop ℕ) else ⊤

theorem monomialNatBox_axisCap (g : Fin n → ℕ) (i : Fin n) (x : Fin n → ℕ) :
    x ∈ monomialNatBox (monomialAxisCap g i) ↔ x i < g i := by
  constructor
  · intro hx
    simpa [monomialAxisCap] using hx i
  · intro hx j
    by_cases hj : j = i
    · subst j
      simpa [monomialAxisCap] using hx
    · simp [monomialAxisCap, hj]

/-- Intersect a finite box union with the complement of the principal upper
set generated by g. This is a finite list operation, including n=0. -/
def monomialExcludeGenerator (g : Fin n → ℕ) (l : List (Fin n → WithTop ℕ)) :
    List (Fin n → WithTop ℕ) :=
  l.flatMap (fun b => List.ofFn (fun i : Fin n => b ⊓ monomialAxisCap g i))

theorem monomialNatBoxList_excludeGenerator (g : Fin n → ℕ)
    (l : List (Fin n → WithTop ℕ)) (x : Fin n → ℕ) :
    x ∈ monomialNatBoxList (monomialExcludeGenerator g l) ↔
      x ∈ monomialNatBoxList l ∧ ¬g ≤ x := by
  constructor
  · rintro ⟨c, hc, hxc⟩
    obtain ⟨b, hb, hbc⟩ := List.mem_flatMap.mp hc
    obtain ⟨i, rfl⟩ := List.mem_ofFn.mp hbc
    obtain ⟨hxb, hxi⟩ := (monomialNatBox_inf _ _ x).mp hxc
    refine ⟨⟨b, hb, hxb⟩, ?_⟩
    intro hle
    exact ((monomialNatBox_axisCap g i x).mp hxi).not_ge (hle i)
  · rintro ⟨⟨b, hb, hxb⟩, hnot⟩
    obtain ⟨i, hi⟩ := not_forall.mp hnot
    refine ⟨b ⊓ monomialAxisCap g i, ?_, ?_⟩
    · exact List.mem_flatMap.mpr ⟨b, hb, List.mem_ofFn.mpr ⟨i, rfl⟩⟩
    · exact (monomialNatBox_inf _ _ x).mpr
        ⟨hxb, (monomialNatBox_axisCap g i x).mpr (lt_of_not_ge hi)⟩

/-- Explicit finite-box complement of a finite list of upper-set generators. -/
def monomialUpperComplementBoxes : List (Fin n → ℕ) → List (Fin n → WithTop ℕ)
  | [] => [fun _ => ⊤]
  | g :: gs => monomialExcludeGenerator g (monomialUpperComplementBoxes gs)

theorem monomialUpperComplementBoxes_spec (gs : List (Fin n → ℕ)) (x : Fin n → ℕ) :
    x ∈ monomialNatBoxList (monomialUpperComplementBoxes gs) ↔
      ∀ g ∈ gs, ¬g ≤ x := by
  induction gs with
  | nil => simp [monomialUpperComplementBoxes, monomialNatBoxList, monomialNatBox]
  | cons g gs ih =>
      rw [monomialUpperComplementBoxes, monomialNatBoxList_excludeGenerator, ih]
      simp [and_comm]

/-- Dickson's lemma gives finite generators for every actual upper set. -/
theorem monomialUpperSet_exists_finset_generators (U : UpperSet (Fin n → ℕ)) :
    ∃ s : Finset (Fin n → ℕ), ∀ x, x ∈ U ↔ ∃ a ∈ s, a ≤ x := by
  classical
  have hpwo : (U : Set (Fin n → ℕ)).IsPWO := Set.isPWO_of_wellQuasiOrderedLE _
  have hfinite : {x : Fin n → ℕ | Minimal (· ∈ U) x}.Finite :=
    (setOfPred_minimal_antichain (· ∈ U)).finite_of_wellQuasiOrdered wellQuasiOrdered_le
  refine ⟨hfinite.toFinset, fun x => ?_⟩
  constructor
  · intro hx
    obtain ⟨a, hax, ha⟩ := hpwo.exists_le_minimal hx
    exact ⟨a, by simpa using ha, hax⟩
  · rintro ⟨a, ha, hax⟩
    have hamin : Minimal (· ∈ U) a := by simpa using ha
    exact U.upper hax hamin.1

/-- Every complement of an upper set in ℕⁿ has a finite-box representation. -/
theorem monomialUpperSet_exists_boxes (U : UpperSet (Fin n → ℕ)) :
    ∃ l : List (Fin n → WithTop ℕ), ∀ x, x ∉ U ↔ x ∈ monomialNatBoxList l := by
  classical
  obtain ⟨s, hs⟩ := monomialUpperSet_exists_finset_generators U
  refine ⟨monomialUpperComplementBoxes s.toList, fun x => ?_⟩
  rw [monomialUpperComplementBoxes_spec]
  constructor
  · intro hx a ha hax
    exact hx ((hs x).mpr ⟨a, by simpa using ha, hax⟩)
  · intro hx hxU
    obtain ⟨a, ha, hax⟩ := (hs x).mp hxU
    exact hx a (by simpa using ha) hax

/-- Adjoining a greatest element preserves the particular WQO of ℕ. -/
theorem withTopNat_wellQuasiOrdered :
    WellQuasiOrdered (fun a b : WithTop ℕ => a ≤ b) := by
  have hn : (Set.univ : Set ℕ).IsPWO := Set.isPWO_of_wellQuasiOrderedLE _
  have hc : Monotone (fun a : ℕ => (a : WithTop ℕ)) :=
    fun _ _ h => WithTop.coe_le_coe.mpr h
  have hr : (Set.range (fun a : ℕ => (a : WithTop ℕ))).IsPWO := by
    simpa only [Set.image_univ] using hn.image_of_monotone hc
  have he : (Set.univ : Set (WithTop ℕ)) =
      Set.range (fun a : ℕ => (a : WithTop ℕ)) ∪ {⊤} := by
    ext a
    constructor
    · intro _
      by_cases ha : a = ⊤
      · exact Or.inr ha
      · exact Or.inl (WithTop.ne_top_iff_exists.mp ha)
    · intro _
      trivial
  apply Set.partiallyWellOrderedOn_univ_iff.mp
  rw [he]
  exact hr.union (Set.isPWO_singleton ⊤)

/-- Higman's list embedding relation implies inclusion of finite box unions. -/
theorem monomialNatBoxList_mono {l₁ l₂ : List (Fin n → WithTop ℕ)}
    (h : List.SublistForall₂ (· ≤ ·) l₁ l₂) :
    monomialNatBoxList l₁ ⊆ monomialNatBoxList l₂ := by
  induction h with
  | nil =>
      rintro x ⟨b, hb, _⟩
      cases hb
  | cons hab h ih =>
      rintro x ⟨c, hc, hxc⟩
      rcases List.mem_cons.mp hc with rfl | hc
      · exact ⟨_, by simp, monomialNatBox_mono hab hxc⟩
      · obtain ⟨d, hd, hxd⟩ := ih ⟨c, hc, hxc⟩
        exact ⟨d, List.mem_cons_of_mem _ hd, hxd⟩
  | cons_right h ih =>
      intro x hx
      obtain ⟨d, hd, hxd⟩ := ih hx
      exact ⟨d, List.mem_cons_of_mem _ hd, hxd⟩

/-- Maclagan's precise combinatorial statement: actual upper sets in ℕⁿ are
well-quasi-ordered by reverse inclusion. -/
theorem monomialUpperSet_wellQuasiOrdered (n : ℕ) :
    WellQuasiOrdered (fun U V : UpperSet (Fin n → ℕ) => (V : Set (Fin n → ℕ)) ⊆ U) := by
  have hcaps : WellQuasiOrdered (fun b c : Fin n → WithTop ℕ => b ≤ c) :=
    WellQuasiOrdered.pi (fun _ => withTopNat_wellQuasiOrdered)
  have hcapset := Set.partiallyWellOrderedOn_of_wellQuasiOrdered hcaps Set.univ
  have hlists := Set.PartiallyWellOrderedOn.partiallyWellOrderedOn_sublistForall₂
    (fun b c : Fin n → WithTop ℕ => b ≤ c) hcapset
  intro U
  choose l hl using fun j => monomialUpperSet_exists_boxes (U j)
  obtain ⟨i, j, hij, hlist⟩ := hlists.exists_lt (f := l) (fun _ => by simp)
  refine ⟨i, j, hij, ?_⟩
  intro x hxj
  by_contra hxi
  have hboxi := (hl i x).mp hxi
  have hboxj := monomialNatBoxList_mono hlist hboxi
  exact ((hl j x).mpr hboxj) hxj

/-- The bundled UpperSet order is already reverse inclusion. -/
theorem monomialUpperSet_wellQuasiOrderedLE (n : ℕ) :
    WellQuasiOrderedLE (UpperSet (Fin n → ℕ)) :=
  ⟨monomialUpperSet_wellQuasiOrdered n⟩

/-- In particular, there is no infinite antichain of monomial upper sets. -/
theorem monomialUpperSet_antichain_finite (n : ℕ)
    {S : Set (UpperSet (Fin n → ℕ))} (hS : IsAntichain (· ≤ ·) S) :
    S.Finite :=
  hS.finite_of_wellQuasiOrdered (monomialUpperSet_wellQuasiOrdered n)

/-- Finite componentwise families of actual exponent upper sets retain
the reverse-inclusion well-quasi-order. -/
theorem monomialUpperSetFamily_wellQuasiOrdered (n : ℕ)
    (κ : Type*) [Finite κ] :
    WellQuasiOrdered (fun U V : κ → UpperSet (Fin n → ℕ) => U ≤ V) := by
  let := monomialUpperSet_wellQuasiOrderedLE n
  exact wellQuasiOrdered_le

/-- Every antichain of finite componentwise upper-set families is finite. -/
theorem monomialUpperSetFamily_antichain_finite (n : ℕ)
    (κ : Type*) [Finite κ]
    {S : Set (κ → UpperSet (Fin n → ℕ))} (hS : IsAntichain (· ≤ ·) S) :
    S.Finite :=
  hS.finite_of_wellQuasiOrdered (monomialUpperSetFamily_wellQuasiOrdered n κ)

end AbelFormalization
