import AbelFormalization.WeightedDeformationGenerators
import Mathlib.Algebra.MvPolynomial.Degrees

/-!
# Literal ordinary homogenization

The new ordinary polynomial variable is the homogenizing parameter. A
monomial of total degree `k` receives parameter exponent `totalDegree f - k`.
This is exactly the minimum-weight normalization for constant weight `-1`.
The zero polynomial uses the usual mathlib total degree convention `0`.
-/

noncomputable section

namespace AbelFormalization

variable {R ι : Type*}

section Semiring

variable [CommSemiring R]

/-- The literal ordinary homogenization, retaining the original variables in
the coefficient ring and using the outer polynomial variable as parameter. -/
def ordinaryHomogenize (f : MvPolynomial ι R) : Polynomial (MvPolynomial ι R) := by
  classical
  exact ∑ d ∈ f.support,
    Polynomial.monomial (f.totalDegree - d.sum (fun _ n => n))
      (MvPolynomial.monomial d (f.coeff d))

@[simp]
theorem ordinaryHomogenize_zero : ordinaryHomogenize (0 : MvPolynomial ι R) = 0 := by
  simp [ordinaryHomogenize]

/-- Constant integer weight `-1` is minus the usual monomial total degree. -/
theorem finsupp_weight_neg_one (d : ι →₀ ℕ) :
    Finsupp.weight (fun _ : ι => (-1 : ℤ)) d =
      -((d.sum (fun _ n => n) : ℕ) : ℤ) := by
  simp [Finsupp.weight_apply, Finsupp.sum, Finset.sum_neg_distrib]

/-- The minimum negative total degree is minus the largest total degree,
including for the zero polynomial. -/
theorem minimumSupportWeight_neg_one (f : MvPolynomial ι R) :
    minimumSupportWeight (fun _ : ι => (-1 : ℤ)) f = -(f.totalDegree : ℤ) := by
  classical
  by_cases hf : f = 0
  · subst f
    simp
  have hs : f.support.Nonempty := MvPolynomial.support_nonempty.mpr hf
  obtain ⟨d, hd, hdegree⟩ :=
    Finset.exists_mem_eq_sup f.support hs (fun d : ι →₀ ℕ => d.sum (fun _ n => n))
  have hdegree' : d.sum (fun _ n => n) = f.totalDegree := by
    exact hdegree.symm
  apply le_antisymm
  · have hmin := minimumSupportWeight_le (fun _ : ι => (-1 : ℤ)) f hd
    simpa only [finsupp_weight_neg_one, hdegree'] using hmin
  · obtain ⟨e, he, hweight⟩ :=
      exists_support_weight_eq_minimum (fun _ : ι => (-1 : ℤ)) hf
    rw [← hweight, finsupp_weight_neg_one]
    exact neg_le_neg (Nat.cast_le.mpr (MvPolynomial.le_totalDegree he))

/-- The weighted construction at weight `-1` agrees term by term with the
literal formula for ordinary homogenization. -/
theorem weightedNormalize_neg_one (f : MvPolynomial ι R) :
    weightedNormalize (fun _ : ι => (-1 : ℤ)) f = ordinaryHomogenize f := by
  classical
  rw [weightedNormalize, ordinaryHomogenize]
  apply Finset.sum_congr rfl
  intro d hd
  rw [finsupp_weight_neg_one, minimumSupportWeight_neg_one]
  have hcast :
      -((d.sum (fun _ n => n) : ℕ) : ℤ) - -(f.totalDegree : ℤ) =
        ((f.totalDegree - d.sum (fun _ n => n) : ℕ) : ℤ) := by
    rw [sub_neg_eq_add, Nat.cast_sub (MvPolynomial.le_totalDegree hd), sub_eq_add_neg]
    exact add_comm _ _
  rw [hcast, Int.toNat_natCast]

/-- The ordinary homogenization is the literal Laurent substitution
`τ^D f(τ⁻¹ z)`, where `D` is the actual total degree of `f`. -/
theorem ordinaryHomogenize_toLaurent (f : MvPolynomial ι R) :
    Polynomial.toLaurent (ordinaryHomogenize f) =
      LaurentPolynomial.T (f.totalDegree : ℤ) *
        laurentWeightRescaling (fun _ : ι => (-1 : ℤ)) (LaurentPolynomial.C f) := by
  rw [← weightedNormalize_neg_one, weightedNormalize_toLaurent,
    minimumSupportWeight_neg_one, neg_neg]

/-- Setting the homogenizing parameter equal to one recovers the original
polynomial, with no nonzero or degree hypothesis. -/
@[simp]
theorem ordinaryHomogenize_eval_one (f : MvPolynomial ι R) :
    (ordinaryHomogenize f).eval 1 = f := by
  classical
  simp [ordinaryHomogenize, Polynomial.eval_finsetSum]

@[simp]
theorem ordinaryHomogenize_eq_zero_iff (f : MvPolynomial ι R) :
    ordinaryHomogenize f = 0 ↔ f = 0 := by
  rw [← weightedNormalize_neg_one, weightedNormalize_eq_zero_iff]

/-- Full ordinary homogenization uses the homogenizations of every element
of the ideal, independently of a selected generating set. -/
def fullOrdinaryHomogenization (I : Ideal (MvPolynomial ι R)) :
    Ideal (Polynomial (MvPolynomial ι R)) :=
  Ideal.span (ordinaryHomogenize '' (I : Set (MvPolynomial ι R)))

theorem ordinaryHomogenize_mem_fullOrdinaryHomogenization
    (I : Ideal (MvPolynomial ι R)) {f : MvPolynomial ι R} (hf : f ∈ I) :
    ordinaryHomogenize f ∈ fullOrdinaryHomogenization I :=
  Ideal.subset_span ⟨f, hf, rfl⟩

end Semiring

section Ring

variable [CommRing R]

/-- The ideal generated by all literal ordinary homogenizations is exactly
the Laurent contraction. This identifies the full operation, rather than
only the homogenizations of a selected finite generating list. -/
theorem fullOrdinaryHomogenization_eq_contraction
    (I : Ideal (MvPolynomial ι R)) :
    fullOrdinaryHomogenization I = ordinaryHomogenizationContraction I := by
  unfold fullOrdinaryHomogenization ordinaryHomogenizationContraction
  rw [weightedDeformationIdeal_eq_span_normalize]
  have hnorm : weightedNormalize (fun _ : ι => (-1 : ℤ)) =
      (ordinaryHomogenize : MvPolynomial ι R → Polynomial (MvPolynomial ι R)) := by
    funext f
    exact weightedNormalize_neg_one f
  rw [hnorm]

/-- Saturation in the homogenizing parameter follows for the actual full
ideal from its proved contraction presentation. -/
theorem fullOrdinaryHomogenization_cancel_X (I : Ideal (MvPolynomial ι R))
    (f : Polynomial (MvPolynomial ι R))
    (hf : Polynomial.X * f ∈ fullOrdinaryHomogenization I) :
    f ∈ fullOrdinaryHomogenization I := by
  rw [fullOrdinaryHomogenization_eq_contraction] at hf ⊢
  exact ordinaryHomogenizationContraction_cancel_X I f hf

/-- Full ordinary homogenization preserves the height of every ideal over a
Noetherian coefficient ring in finitely many original variables. -/
theorem fullOrdinaryHomogenization_height [IsNoetherianRing R] [Finite ι]
    (I : Ideal (MvPolynomial ι R)) :
    (fullOrdinaryHomogenization I).height = I.height := by
  rw [fullOrdinaryHomogenization_eq_contraction]
  exact ordinaryHomogenizationContraction_height I

/-- The inequality stated for full ordinary homogenization follows from the
stronger height equality. -/
theorem le_fullOrdinaryHomogenization_height [IsNoetherianRing R] [Finite ι]
    (I : Ideal (MvPolynomial ι R)) :
    I.height ≤ (fullOrdinaryHomogenization I).height :=
  (fullOrdinaryHomogenization_height I).ge

end Ring

end AbelFormalization
