import AbelFormalization.RestrictedRankEliminationTraceBoundary
import AbelFormalization.RestrictedOrderedClusterPartition
import AbelFormalization.ClusterAlgebraicReduction

set_option autoImplicit false

/-!
# Currying one separated cluster out of the retained rank variables

This file isolates the algebraic reindexing used after the Hermite step in
the separated-cluster argument.  An ambient family of Hermite blocks is split
into the active cluster and the already-retained coefficient blocks.  The
resulting polynomial ring is then curried into a polynomial ring in exactly
the variables expected by `ClusterAlgebraicReductionCertificate`, over the
polynomial coefficient ring generated by the retained blocks.

The construction is purely a relabeling.  In particular, it does not identify
the raw selected Abel jets in `PaperRankRetainedSymbols` with Hermite
coefficients; that analytic polynomialization is a separate preceding step.
-/

noncomputable section

namespace AbelFormalization

universe u v w

/-- The variables used by one cluster operation: the auxiliary `q` variables,
then the positive derivative variables and retained time variables. -/
abbrev ClusterOperationSymbol (Block : Type v) (d : Block → ℕ) :=
  Block ⊕ CentralPolynomialIndex Block d Block

/-- All block variables before currying: active and retained blocks occur in
each of the three syntactic variable positions. -/
abbrev SplitClusterBlockSymbol
    (Active : Type v) (Coeff : Type w)
    (dActive : Active → ℕ) (dCoeff : Coeff → ℕ) :=
  (Active ⊕ Coeff) ⊕
    CentralPolynomialIndex (Active ⊕ Coeff)
      (Sum.elim dActive dCoeff) (Active ⊕ Coeff)

/-- Canonically put every active-cluster variable on the left and every
retained coefficient variable on the right. -/
def splitClusterBlockSymbolEquiv
    (Active : Type v) (Coeff : Type w)
    (dActive : Active → ℕ) (dCoeff : Coeff → ℕ) :
    SplitClusterBlockSymbol Active Coeff dActive dCoeff ≃
      ClusterOperationSymbol Active dActive ⊕
        ClusterOperationSymbol Coeff dCoeff where
  toFun
    | Sum.inl (Sum.inl a) => Sum.inl (Sum.inl a)
    | Sum.inl (Sum.inr c) => Sum.inr (Sum.inl c)
    | Sum.inr (Sum.inl ⟨Sum.inl a, r⟩) =>
        Sum.inl (Sum.inr (Sum.inl ⟨a, r⟩))
    | Sum.inr (Sum.inl ⟨Sum.inr c, r⟩) =>
        Sum.inr (Sum.inr (Sum.inl ⟨c, r⟩))
    | Sum.inr (Sum.inr (Sum.inl a)) =>
        Sum.inl (Sum.inr (Sum.inr a))
    | Sum.inr (Sum.inr (Sum.inr c)) =>
        Sum.inr (Sum.inr (Sum.inr c))
  invFun
    | Sum.inl (Sum.inl a) => Sum.inl (Sum.inl a)
    | Sum.inl (Sum.inr (Sum.inl ⟨a, r⟩)) =>
        Sum.inr (Sum.inl ⟨Sum.inl a, r⟩)
    | Sum.inl (Sum.inr (Sum.inr a)) =>
        Sum.inr (Sum.inr (Sum.inl a))
    | Sum.inr (Sum.inl c) => Sum.inl (Sum.inr c)
    | Sum.inr (Sum.inr (Sum.inl ⟨c, r⟩)) =>
        Sum.inr (Sum.inl ⟨Sum.inr c, r⟩)
    | Sum.inr (Sum.inr (Sum.inr c)) =>
        Sum.inr (Sum.inr (Sum.inr c))
  left_inv := by
    rintro ((a | c) | (⟨a | c, r⟩ | (a | c))) <;> rfl
  right_inv := by
    rintro ((a | (⟨a, r⟩ | a)) | (c | (⟨c, r⟩ | c))) <;> rfl

/-- Syntactic recognition of variables belonging to the retained coefficient
blocks.  It covers coefficient `q`, positive derivative, and time variables. -/
def IsClusterCoefficientVariable
    {Active : Type v} {Coeff : Type w}
    {dActive : Active → ℕ} {dCoeff : Coeff → ℕ} :
    SplitClusterBlockSymbol Active Coeff dActive dCoeff → Prop
  | Sum.inl (Sum.inl _) => False
  | Sum.inl (Sum.inr _) => True
  | Sum.inr (Sum.inl ⟨Sum.inl _, _⟩) => False
  | Sum.inr (Sum.inl ⟨Sum.inr _, _⟩) => True
  | Sum.inr (Sum.inr (Sum.inl _)) => False
  | Sum.inr (Sum.inr (Sum.inr _)) => True

/-- The syntactic coefficient predicate is exactly membership in the right
summand under the canonical cluster split. -/
theorem isClusterCoefficientVariable_iff
    {Active : Type v} {Coeff : Type w}
    {dActive : Active → ℕ} {dCoeff : Coeff → ℕ}
    (z : SplitClusterBlockSymbol Active Coeff dActive dCoeff) :
    IsClusterCoefficientVariable z ↔
      ∃ c : ClusterOperationSymbol Coeff dCoeff,
        splitClusterBlockSymbolEquiv Active Coeff dActive dCoeff z =
          Sum.inr c := by
  rcases z with (a | c) | (⟨a | c, r⟩ | (a | c)) <;>
    simp [IsClusterCoefficientVariable, splitClusterBlockSymbolEquiv]

/-- Curry the retained coefficient variables into the coefficient ring. -/
def splitClusterCurryAlgEquiv
    (R : Type u) [CommSemiring R]
    (Active : Type v) (Coeff : Type w)
    (dActive : Active → ℕ) (dCoeff : Coeff → ℕ) :
    MvPolynomial (SplitClusterBlockSymbol Active Coeff dActive dCoeff) R ≃ₐ[R]
      MvPolynomial (ClusterOperationSymbol Active dActive)
        (MvPolynomial (ClusterOperationSymbol Coeff dCoeff) R) :=
  (MvPolynomial.renameEquiv R
      (splitClusterBlockSymbolEquiv Active Coeff dActive dCoeff)).trans
    (MvPolynomial.sumAlgEquiv R
      (ClusterOperationSymbol Active dActive)
      (ClusterOperationSymbol Coeff dCoeff))

@[simp]
theorem splitClusterCurryAlgEquiv_X_active
    (R : Type u) [CommSemiring R]
    (Active : Type v) (Coeff : Type w)
    (dActive : Active → ℕ) (dCoeff : Coeff → ℕ)
    (z : ClusterOperationSymbol Active dActive) :
    splitClusterCurryAlgEquiv R Active Coeff dActive dCoeff
        (MvPolynomial.X
          ((splitClusterBlockSymbolEquiv Active Coeff dActive dCoeff).symm
            (Sum.inl z))) =
      MvPolynomial.X z := by
  simp [splitClusterCurryAlgEquiv]

@[simp]
theorem splitClusterCurryAlgEquiv_X_coefficient
    (R : Type u) [CommSemiring R]
    (Active : Type v) (Coeff : Type w)
    (dActive : Active → ℕ) (dCoeff : Coeff → ℕ)
    (z : ClusterOperationSymbol Coeff dCoeff) :
    splitClusterCurryAlgEquiv R Active Coeff dActive dCoeff
        (MvPolynomial.X
          ((splitClusterBlockSymbolEquiv Active Coeff dActive dCoeff).symm
            (Sum.inr z))) =
      MvPolynomial.C (MvPolynomial.X z) := by
  simp [splitClusterCurryAlgEquiv]

/-- The input ideal after extracting the active cluster into the outer
polynomial variables. -/
def splitClusterCurriedIdeal
    (R : Type u) [CommSemiring R]
    (Active : Type v) (Coeff : Type w)
    (dActive : Active → ℕ) (dCoeff : Coeff → ℕ)
    (I : Ideal
      (MvPolynomial (SplitClusterBlockSymbol Active Coeff dActive dCoeff) R)) :
    Ideal (MvPolynomial (ClusterOperationSymbol Active dActive)
      (MvPolynomial (ClusterOperationSymbol Coeff dCoeff) R)) :=
  I.map (splitClusterCurryAlgEquiv R Active Coeff dActive dCoeff).toRingHom

theorem splitClusterCurriedIdeal_height
    (R : Type u) [CommRing R]
    (Active : Type v) (Coeff : Type w)
    (dActive : Active → ℕ) (dCoeff : Coeff → ℕ)
    (I : Ideal
      (MvPolynomial (SplitClusterBlockSymbol Active Coeff dActive dCoeff) R)) :
    (splitClusterCurriedIdeal R Active Coeff dActive dCoeff I).height =
      I.height :=
  (splitClusterCurryAlgEquiv R Active Coeff dActive dCoeff).toRingEquiv.height_map I

/-- Evaluating before the split agrees with first evaluating coefficient
blocks and then evaluating the active-cluster polynomial.  This is the
literal evaluated identity needed to transport a finite generating family
through the currying equivalence. -/
theorem eval₂Hom_splitClusterCurryAlgEquiv
    {R : Type u} {S : Type*} [CommSemiring R] [CommSemiring S]
    (c : R →+* S)
    (Active : Type v) (Coeff : Type w)
    (dActive : Active → ℕ) (dCoeff : Coeff → ℕ)
    (activeValue : ClusterOperationSymbol Active dActive → S)
    (coefficientValue : ClusterOperationSymbol Coeff dCoeff → S)
    (P : MvPolynomial
      (SplitClusterBlockSymbol Active Coeff dActive dCoeff) R) :
    MvPolynomial.eval₂Hom c
        (fun z => Sum.elim activeValue coefficientValue
          (splitClusterBlockSymbolEquiv Active Coeff dActive dCoeff z)) P =
      MvPolynomial.eval₂Hom
        (MvPolynomial.eval₂Hom c coefficientValue) activeValue
        (splitClusterCurryAlgEquiv R Active Coeff dActive dCoeff P) := by
  let e := splitClusterBlockSymbolEquiv Active Coeff dActive dCoeff
  let lhs :
      MvPolynomial
          (SplitClusterBlockSymbol Active Coeff dActive dCoeff) R →+* S :=
    MvPolynomial.eval₂Hom c
      (fun z => Sum.elim activeValue coefficientValue (e z))
  let rhs :
      MvPolynomial
          (SplitClusterBlockSymbol Active Coeff dActive dCoeff) R →+* S :=
    (MvPolynomial.eval₂Hom
        (MvPolynomial.eval₂Hom c coefficientValue) activeValue).comp
      (splitClusterCurryAlgEquiv
        R Active Coeff dActive dCoeff).toRingHom
  have hhom : lhs = rhs := by
    apply MvPolynomial.ringHom_ext
    · intro r
      simp [lhs, rhs, splitClusterCurryAlgEquiv]
    · intro z
      generalize hz : e z = y
      rcases y with a | b
      · have hzeq : z = e.symm (Sum.inl a) := by
          rw [← hz]
          exact (e.symm_apply_apply z).symm
        subst z
        simp [lhs, rhs, e, splitClusterCurryAlgEquiv]
      · have hzeq : z = e.symm (Sum.inr b) := by
          rw [← hz]
          exact (e.symm_apply_apply z).symm
        subst z
        simp [lhs, rhs, e, splitClusterCurryAlgEquiv]
  exact DFunLike.congr_fun hhom P

/-! ## The retained paper symbols and Hermite blockification -/

/-- The representative block to which a retained paper symbol belongs.
For a selected Abel jet this is read from the actual finite jet enumeration,
then transported by the representative map used in the restricted base. -/
def paperRankRetainedRepresentative
    {ι : Type*} {m : ℕ} (representative : ι → Fin m)
    (S : Finset (ι × ℕ)) :
    PaperRankRetainedSymbols m S.card → Fin m
  | Sum.inl i => i
  | Sum.inr j => representative (restrictedJetEnumeration S j).1

@[simp]
theorem paperRankRetainedRepresentative_free
    {ι : Type*} {m : ℕ} (representative : ι → Fin m)
    (S : Finset (ι × ℕ)) (i : Fin m) :
    paperRankRetainedRepresentative representative S (Sum.inl i) = i :=
  rfl

@[simp]
theorem paperRankRetainedRepresentative_jet
    {ι : Type*} {m : ℕ} (representative : ι → Fin m)
    (S : Finset (ι × ℕ)) (j : Fin S.card) :
    paperRankRetainedRepresentative representative S (Sum.inr j) =
      representative (restrictedJetEnumeration S j).1 :=
  rfl

/-- A retained rank variable is a coefficient variable at one cluster stage
exactly when its representative belongs to the retained side of the chosen
block relabeling. -/
def IsPaperRankClusterCoefficientVariable
    {ι : Type*} {m : ℕ} (representative : ι → Fin m)
    (S : Finset (ι × ℕ)) {Active : Type v} {Coeff : Type w}
    (blockEquiv : Fin m ≃ Active ⊕ Coeff)
    (z : PaperRankRetainedSymbols m S.card) : Prop :=
  match blockEquiv (paperRankRetainedRepresentative representative S z) with
  | Sum.inl _ => False
  | Sum.inr _ => True

theorem isPaperRankClusterCoefficientVariable_iff
    {ι : Type*} {m : ℕ} (representative : ι → Fin m)
    (S : Finset (ι × ℕ)) {Active : Type v} {Coeff : Type w}
    (blockEquiv : Fin m ≃ Active ⊕ Coeff)
    (z : PaperRankRetainedSymbols m S.card) :
    IsPaperRankClusterCoefficientVariable representative S blockEquiv z ↔
      ∃ c : Coeff,
        blockEquiv
          (paperRankRetainedRepresentative representative S z) = Sum.inr c := by
  generalize hblock : blockEquiv
      (paperRankRetainedRepresentative representative S z) = block
  rcases block with a | c
  · simp [IsPaperRankClusterCoefficientVariable, hblock]
  · simp [IsPaperRankClusterCoefficientVariable, hblock]

/-- Substitute the raw selected Abel-jet variables by their Hermite block
polynomials while merely relabeling each representative variable.  The
`jetPolynomial` argument is the exact output still required from the
Hermite polynomialization step; no invertibility is asserted or needed. -/
def paperRankClusterBlockificationHom
    (R : Type u) [CommSemiring R]
    {m b : ℕ} (Active : Type v) (Coeff : Type w)
    (dActive : Active → ℕ) (dCoeff : Coeff → ℕ)
    (blockEquiv : Fin m ≃ Active ⊕ Coeff)
    (jetPolynomial : Fin b →
      MvPolynomial
        (SplitClusterBlockSymbol Active Coeff dActive dCoeff) R) :
    MvPolynomial (PaperRankRetainedSymbols m b) R →ₐ[R]
      MvPolynomial
        (SplitClusterBlockSymbol Active Coeff dActive dCoeff) R :=
  MvPolynomial.aeval fun z =>
    Sum.elim
      (fun i => MvPolynomial.X (Sum.inl (blockEquiv i)))
      jetPolynomial z

@[simp]
theorem paperRankClusterBlockificationHom_X_representative
    (R : Type u) [CommSemiring R]
    {m b : ℕ} (Active : Type v) (Coeff : Type w)
    (dActive : Active → ℕ) (dCoeff : Coeff → ℕ)
    (blockEquiv : Fin m ≃ Active ⊕ Coeff)
    (jetPolynomial : Fin b →
      MvPolynomial
        (SplitClusterBlockSymbol Active Coeff dActive dCoeff) R)
    (i : Fin m) :
    paperRankClusterBlockificationHom R Active Coeff dActive dCoeff
        blockEquiv jetPolynomial
        (MvPolynomial.X (Sum.inl i)) =
      MvPolynomial.X (Sum.inl (blockEquiv i)) := by
  simp [paperRankClusterBlockificationHom]

@[simp]
theorem paperRankClusterBlockificationHom_X_jet
    (R : Type u) [CommSemiring R]
    {m b : ℕ} (Active : Type v) (Coeff : Type w)
    (dActive : Active → ℕ) (dCoeff : Coeff → ℕ)
    (blockEquiv : Fin m ≃ Active ⊕ Coeff)
    (jetPolynomial : Fin b →
      MvPolynomial
        (SplitClusterBlockSymbol Active Coeff dActive dCoeff) R)
    (j : Fin b) :
    paperRankClusterBlockificationHom R Active Coeff dActive dCoeff
        blockEquiv jetPolynomial
        (MvPolynomial.X (Sum.inr j)) = jetPolynomial j := by
  simp [paperRankClusterBlockificationHom]

/-- The single algebra homomorphism from the retained rank ring to the
active-cluster polynomial ring over the retained coefficient ring. -/
def paperRankClusterCurryHom
    (R : Type u) [CommSemiring R]
    {m b : ℕ} (Active : Type v) (Coeff : Type w)
    (dActive : Active → ℕ) (dCoeff : Coeff → ℕ)
    (blockEquiv : Fin m ≃ Active ⊕ Coeff)
    (jetPolynomial : Fin b →
      MvPolynomial
        (SplitClusterBlockSymbol Active Coeff dActive dCoeff) R) :
    MvPolynomial (PaperRankRetainedSymbols m b) R →ₐ[R]
      MvPolynomial (ClusterOperationSymbol Active dActive)
        (MvPolynomial (ClusterOperationSymbol Coeff dCoeff) R) :=
  (splitClusterCurryAlgEquiv
      R Active Coeff dActive dCoeff).toAlgHom.comp
    (paperRankClusterBlockificationHom
      R Active Coeff dActive dCoeff blockEquiv jetPolynomial)

/-- Evaluation of a retained rank polynomial after Hermite blockification
is exactly evaluation of its curried active-cluster image. -/
theorem eval₂Hom_paperRankClusterCurryHom
    {R : Type u} {S : Type*} [CommSemiring R] [CommSemiring S]
    (c : R →+* S)
    {m b : ℕ} (Active : Type v) (Coeff : Type w)
    (dActive : Active → ℕ) (dCoeff : Coeff → ℕ)
    (blockEquiv : Fin m ≃ Active ⊕ Coeff)
    (jetPolynomial : Fin b →
      MvPolynomial
        (SplitClusterBlockSymbol Active Coeff dActive dCoeff) R)
    (activeValue : ClusterOperationSymbol Active dActive → S)
    (coefficientValue : ClusterOperationSymbol Coeff dCoeff → S)
    (P : MvPolynomial (PaperRankRetainedSymbols m b) R) :
    MvPolynomial.eval₂Hom c
        (Sum.elim
          (fun i => Sum.elim activeValue coefficientValue
            (splitClusterBlockSymbolEquiv Active Coeff dActive dCoeff
              (Sum.inl (blockEquiv i))))
          (fun j => MvPolynomial.eval₂Hom c
            (fun z => Sum.elim activeValue coefficientValue
              (splitClusterBlockSymbolEquiv Active Coeff dActive dCoeff z))
            (jetPolynomial j))) P =
      MvPolynomial.eval₂Hom
        (MvPolynomial.eval₂Hom c coefficientValue) activeValue
        (paperRankClusterCurryHom R Active Coeff dActive dCoeff
          blockEquiv jetPolynomial P) := by
  let e := splitClusterBlockSymbolEquiv Active Coeff dActive dCoeff
  let flatValue :
      SplitClusterBlockSymbol Active Coeff dActive dCoeff → S :=
    fun z => Sum.elim activeValue coefficientValue (e z)
  let blockify := paperRankClusterBlockificationHom
    R Active Coeff dActive dCoeff blockEquiv jetPolynomial
  have hblockify :
      MvPolynomial.eval₂Hom c
          (Sum.elim
            (fun i => flatValue (Sum.inl (blockEquiv i)))
            (fun j => MvPolynomial.eval₂Hom c flatValue
              (jetPolynomial j))) P =
        MvPolynomial.eval₂Hom c flatValue (blockify P) := by
    let lhs : MvPolynomial (PaperRankRetainedSymbols m b) R →+* S :=
      MvPolynomial.eval₂Hom c
        (Sum.elim
          (fun i => flatValue (Sum.inl (blockEquiv i)))
          (fun j => MvPolynomial.eval₂Hom c flatValue
            (jetPolynomial j)))
    let rhs : MvPolynomial (PaperRankRetainedSymbols m b) R →+* S :=
      (MvPolynomial.eval₂Hom c flatValue).comp blockify.toRingHom
    have hhom : lhs = rhs := by
      apply MvPolynomial.ringHom_ext
      · intro r
        simp [lhs, rhs, blockify,
          paperRankClusterBlockificationHom]
      · rintro (i | j)
        · simp [lhs, rhs, blockify,
            paperRankClusterBlockificationHom]
        · simp [lhs, rhs, blockify,
            paperRankClusterBlockificationHom]
    exact DFunLike.congr_fun hhom P
  calc
    MvPolynomial.eval₂Hom c
          (Sum.elim
            (fun i => Sum.elim activeValue coefficientValue
              (splitClusterBlockSymbolEquiv Active Coeff dActive dCoeff
                (Sum.inl (blockEquiv i))))
            (fun j => MvPolynomial.eval₂Hom c
              (fun z => Sum.elim activeValue coefficientValue
                (splitClusterBlockSymbolEquiv Active Coeff dActive dCoeff z))
              (jetPolynomial j))) P =
        MvPolynomial.eval₂Hom c flatValue (blockify P) := hblockify
    _ = MvPolynomial.eval₂Hom
          (MvPolynomial.eval₂Hom c coefficientValue) activeValue
          (splitClusterCurryAlgEquiv R Active Coeff dActive dCoeff
            (blockify P)) :=
      eval₂Hom_splitClusterCurryAlgEquiv c Active Coeff dActive dCoeff
        activeValue coefficientValue (blockify P)
    _ = MvPolynomial.eval₂Hom
          (MvPolynomial.eval₂Hom c coefficientValue) activeValue
          (paperRankClusterCurryHom R Active Coeff dActive dCoeff
            blockEquiv jetPolynomial P) := rfl

/-- Map the actual ideal supplied by rank elimination through Hermite
blockification and then through the active/coefficient currying. -/
def paperRankClusterCurriedIdeal
    (R : Type u) [CommSemiring R]
    {m b : ℕ} (Active : Type v) (Coeff : Type w)
    (dActive : Active → ℕ) (dCoeff : Coeff → ℕ)
    (blockEquiv : Fin m ≃ Active ⊕ Coeff)
    (jetPolynomial : Fin b →
      MvPolynomial
        (SplitClusterBlockSymbol Active Coeff dActive dCoeff) R)
    (I : Ideal (MvPolynomial (PaperRankRetainedSymbols m b) R)) :
    Ideal (MvPolynomial (ClusterOperationSymbol Active dActive)
      (MvPolynomial (ClusterOperationSymbol Coeff dCoeff) R)) :=
  I.map (paperRankClusterCurryHom R Active Coeff dActive dCoeff
    blockEquiv jetPolynomial).toRingHom

/-- A displayed generating family for the rank ideal remains a displayed
generating family after blockification and cluster currying. -/
theorem span_paperRankClusterCurryHom_eq_curriedIdeal
    (R : Type u) [CommRing R]
    {m b : ℕ} (Active : Type v) (Coeff : Type w)
    (dActive : Active → ℕ) (dCoeff : Coeff → ℕ)
    (blockEquiv : Fin m ≃ Active ⊕ Coeff)
    (jetPolynomial : Fin b → MvPolynomial
      (SplitClusterBlockSymbol Active Coeff dActive dCoeff) R)
    {J : Type*} (g : J →
      MvPolynomial (PaperRankRetainedSymbols m b) R)
    (I : Ideal (MvPolynomial (PaperRankRetainedSymbols m b) R))
    (hspan : Ideal.span (Set.range g) = I) :
    Ideal.span (Set.range (fun j =>
        paperRankClusterCurryHom R Active Coeff dActive dCoeff
          blockEquiv jetPolynomial (g j))) =
      paperRankClusterCurriedIdeal R Active Coeff dActive dCoeff
        blockEquiv jetPolynomial I := by
  change Ideal.span (Set.range (fun j =>
      (paperRankClusterCurryHom R Active Coeff dActive dCoeff
        blockEquiv jetPolynomial).toRingHom (g j))) =
    I.map (paperRankClusterCurryHom R Active Coeff dActive dCoeff
      blockEquiv jetPolynomial).toRingHom
  rw [span_range_map_eq
    (paperRankClusterCurryHom R Active Coeff dActive dCoeff
      blockEquiv jetPolynomial).toRingHom g, hspan]

/-! ## Canonical relabeling supplied by an ordered cluster partition -/

/-- Representatives outside the active ordered cluster are precisely the
blocks retained in the coefficient ring at the first (largest-cluster)
stage. -/
abbrev OrderedClusterCoefficientBlock
    {m : ℕ} {time : ℕ → Fin m → ℝ}
    (data : RepresentativeClusterSubsequence time)
    (cluster : Fin data.orderedClusterCount) :=
  {i : Fin m // i ∉ data.orderedCluster cluster}

/-- The forward function underlying the canonical active/coefficient block
relabeling. -/
def orderedClusterBlockToSum
    {m : ℕ} {time : ℕ → Fin m → ℝ}
    (data : RepresentativeClusterSubsequence time)
    (cluster : Fin data.orderedClusterCount) (i : Fin m) :
    Fin (data.orderedCluster cluster).card ⊕
      OrderedClusterCoefficientBlock data cluster := by
  classical
  by_cases hi : i ∈ data.orderedCluster cluster
  · exact Sum.inl ((data.orderedCluster cluster).equivFin ⟨i, hi⟩)
  · exact Sum.inr ⟨i, hi⟩

/-- Canonically enumerate the active cluster by `Fin h` and send every
remaining representative to the coefficient side. -/
def orderedClusterBlockEquiv
    {m : ℕ} {time : ℕ → Fin m → ℝ}
    (data : RepresentativeClusterSubsequence time)
    (cluster : Fin data.orderedClusterCount) :
    Fin m ≃
      Fin (data.orderedCluster cluster).card ⊕
        OrderedClusterCoefficientBlock data cluster where
  toFun := orderedClusterBlockToSum data cluster
  invFun
    | Sum.inl i =>
        (((data.orderedCluster cluster).equivFin).symm i).1
    | Sum.inr i => i.1
  left_inv := by
    classical
    intro i
    by_cases hi : i ∈ data.orderedCluster cluster
    · simp [orderedClusterBlockToSum, hi]
    · simp [orderedClusterBlockToSum, hi]
  right_inv := by
    classical
    rintro (i | i)
    · have hi :
          (((data.orderedCluster cluster).equivFin).symm i).1 ∈
            data.orderedCluster cluster :=
        (((data.orderedCluster cluster).equivFin).symm i).2
      change orderedClusterBlockToSum data cluster
          (((data.orderedCluster cluster).equivFin).symm i).1 = Sum.inl i
      rw [orderedClusterBlockToSum, dite_eq_left hi]
      have hsub :
          (⟨(((data.orderedCluster cluster).equivFin).symm i).1, hi⟩ :
            data.orderedCluster cluster) =
            ((data.orderedCluster cluster).equivFin).symm i :=
        Subtype.ext rfl
      rw [hsub, Equiv.apply_symm_apply]
    · change orderedClusterBlockToSum data cluster i.1 = Sum.inr i
      simp only [orderedClusterBlockToSum, dite_eq_right i.2]

@[simp]
theorem orderedClusterBlockEquiv_apply_mem
    {m : ℕ} {time : ℕ → Fin m → ℝ}
    (data : RepresentativeClusterSubsequence time)
    (cluster : Fin data.orderedClusterCount)
    {i : Fin m} (hi : i ∈ data.orderedCluster cluster) :
    orderedClusterBlockEquiv data cluster i =
      Sum.inl ((data.orderedCluster cluster).equivFin ⟨i, hi⟩) := by
  classical
  change orderedClusterBlockToSum data cluster i = _
  simp only [orderedClusterBlockToSum, dite_eq_left hi]

@[simp]
theorem orderedClusterBlockEquiv_apply_not_mem
    {m : ℕ} {time : ℕ → Fin m → ℝ}
    (data : RepresentativeClusterSubsequence time)
    (cluster : Fin data.orderedClusterCount)
    {i : Fin m} (hi : i ∉ data.orderedCluster cluster) :
    orderedClusterBlockEquiv data cluster i = Sum.inr ⟨i, hi⟩ := by
  classical
  change orderedClusterBlockToSum data cluster i = _
  simp only [orderedClusterBlockToSum, dite_eq_right hi]

/-- Under the canonical ordered-cluster relabeling, the coefficient-variable
predicate says exactly that the symbol's representative is outside the
active cluster. -/
theorem isPaperRankOrderedClusterCoefficientVariable_iff
    {ι : Type*} {m : ℕ} {time : ℕ → Fin m → ℝ}
    (representative : ι → Fin m) (S : Finset (ι × ℕ))
    (data : RepresentativeClusterSubsequence time)
    (cluster : Fin data.orderedClusterCount)
    (z : PaperRankRetainedSymbols m S.card) :
    IsPaperRankClusterCoefficientVariable representative S
        (orderedClusterBlockEquiv data cluster) z ↔
      paperRankRetainedRepresentative representative S z ∉
        data.orderedCluster cluster := by
  rw [isPaperRankClusterCoefficientVariable_iff]
  by_cases hz : paperRankRetainedRepresentative representative S z ∈
      data.orderedCluster cluster
  · simp [orderedClusterBlockEquiv_apply_mem data cluster hz, hz]
  · simp [orderedClusterBlockEquiv_apply_not_mem data cluster hz, hz]

@[simp]
theorem isPaperRankOrderedClusterCoefficientVariable_free_iff
    {ι : Type*} {m : ℕ} {time : ℕ → Fin m → ℝ}
    (representative : ι → Fin m) (S : Finset (ι × ℕ))
    (data : RepresentativeClusterSubsequence time)
    (cluster : Fin data.orderedClusterCount) (i : Fin m) :
    IsPaperRankClusterCoefficientVariable representative S
        (orderedClusterBlockEquiv data cluster) (Sum.inl i) ↔
      i ∉ data.orderedCluster cluster := by
  simpa using isPaperRankOrderedClusterCoefficientVariable_iff
    representative S data cluster (Sum.inl i)

@[simp]
theorem isPaperRankOrderedClusterCoefficientVariable_jet_iff
    {ι : Type*} {m : ℕ} {time : ℕ → Fin m → ℝ}
    (representative : ι → Fin m) (S : Finset (ι × ℕ))
    (data : RepresentativeClusterSubsequence time)
    (cluster : Fin data.orderedClusterCount) (j : Fin S.card) :
    IsPaperRankClusterCoefficientVariable representative S
        (orderedClusterBlockEquiv data cluster) (Sum.inr j) ↔
      representative (restrictedJetEnumeration S j).1 ∉
        data.orderedCluster cluster := by
  simpa using isPaperRankOrderedClusterCoefficientVariable_iff
    representative S data cluster (Sum.inr j)

/-- Transport a global derivative-count function to the canonical active
cluster enumeration. -/
def orderedClusterActiveDerivativeCount
    {m : ℕ} {time : ℕ → Fin m → ℝ}
    (data : RepresentativeClusterSubsequence time)
    (cluster : Fin data.orderedClusterCount) (d : Fin m → ℕ) :
    Fin (data.orderedCluster cluster).card → ℕ :=
  fun i => d ((((data.orderedCluster cluster).equivFin).symm i).1)

/-- Restrict a global derivative-count function to the retained coefficient
blocks. -/
def orderedClusterCoefficientDerivativeCount
    {m : ℕ} {time : ℕ → Fin m → ℝ}
    (data : RepresentativeClusterSubsequence time)
    (cluster : Fin data.orderedClusterCount) (d : Fin m → ℕ) :
    OrderedClusterCoefficientBlock data cluster → ℕ :=
  fun i => d i.1

/-! ## Specialization to the algebraic cluster certificate -/

/-- The terminal weight used by the algebraic cluster reduction is literally
the shear used by the quantitative transfer theorem. -/
theorem negativeTerminalWeight_eq_centralTransferShear
    {h : ℕ} (d : Fin h → ℕ) :
    negativeTerminalWeight d (Fin h) = centralTransferShear d := by
  funext x j
  rcases x with ⟨i, r⟩ | i
  · by_cases hji : j = i
    · subst j
      simp [negativeTerminalWeight, signedTerminalWeight,
        centralTransferShear, terminalGlobalWeight]
    · simp [negativeTerminalWeight, signedTerminalWeight,
        centralTransferShear, terminalGlobalWeight, hji]
  · simp [negativeTerminalWeight, signedTerminalWeight,
      centralTransferShear, terminalGlobalWeight]

theorem clusterFirstCentralIdeal_eq_transfer
    {R : Type u} [CommRing R]
    {h : ℕ} (higher : Fin h → ℕ)
    (I : Ideal (MvPolynomial
      (Fin h ⊕ CentralPolynomialIndex (Fin h)
        (terminalTotalDerivativeCount higher) (Fin h)) R)) :
    clusterFirstCentralIdeal R higher I =
      centralIdealConstruction
        (centralTransferShear (terminalTotalDerivativeCount higher)) I := by
  rw [clusterFirstCentralIdeal,
    negativeTerminalWeight_eq_centralTransferShear]

/-- Number of finite coordinates used for the terminal Artinian iteration. -/
abbrev clusterTerminalReindexCard {h : ℕ} (higher : Fin h → ℕ) : ℕ :=
  Fintype.card (CentralPolynomialIndex (Fin h)
    (terminalTotalDerivativeCount higher) (Fin 1 ⊕ Fin h))

/-- A canonical finite enumeration sufficient to run the terminal algebraic
reduction for an active cluster. -/
def clusterTerminalFiniteReindex {h : ℕ} (higher : Fin h → ℕ) :
    TerminalFiniteReindex
      (n := clusterTerminalReindexCard higher)
      (terminalTotalDerivativeCount higher) (Fin 1 ⊕ Fin h) :=
  (Fintype.equivFin (CentralPolynomialIndex (Fin h)
    (terminalTotalDerivativeCount higher) (Fin 1 ⊕ Fin h))).symm

/-- Once the Hermite block polynomials have been supplied, the actual rank
ideal has exactly the input type required by the maintained one-cluster
algebraic reduction.  The finite reindexing and monomial order are chosen
canonically here rather than left as additional data. -/
theorem nonempty_paperRankClusterAlgebraicReductionCertificate
    {R : Type u} [CommRing R]
    {m b h krullDim : ℕ} (higher : Fin h → ℕ)
    (Coeff : Type w) [Fintype Coeff] (dCoeff : Coeff → ℕ)
    (blockEquiv : Fin m ≃ Fin h ⊕ Coeff)
    (jetPolynomial : Fin b → MvPolynomial
      (SplitClusterBlockSymbol (Fin h) Coeff
        (terminalTotalDerivativeCount higher) dCoeff) R)
    (I : Ideal (MvPolynomial (PaperRankRetainedSymbols m b) R))
    [Algebra ℚ (MvPolynomial (ClusterOperationSymbol Coeff dCoeff) R)]
    [IsNoetherianRing
      (MvPolynomial (ClusterOperationSymbol Coeff dCoeff) R)]
    [Ring.KrullDimLE krullDim
      (MvPolynomial (ClusterOperationSymbol Coeff dCoeff) R)] :
    Nonempty (ClusterAlgebraicReductionCertificate
      (MvPolynomial (ClusterOperationSymbol Coeff dCoeff) R) h higher
      (paperRankClusterCurriedIdeal R (Fin h) Coeff
        (terminalTotalDerivativeCount higher) dCoeff blockEquiv
        jetPolynomial I)) := by
  exact exists_clusterAlgebraicReductionCertificate
    (krullDim := krullDim) higher
    (MonomialOrder.lex :
      MonomialOrder (Fin (clusterTerminalReindexCard higher)))
    (clusterTerminalFiniteReindex higher)
    (paperRankClusterCurriedIdeal R (Fin h) Coeff
      (terminalTotalDerivativeCount higher) dCoeff blockEquiv
      jetPolynomial I)

/-- The terminalized part of any cluster certificate is already a
certificate for the central ideal formed with the quantitative transfer
shear. -/
def ClusterAlgebraicReductionCertificate.transferTerminalized
    {R : Type u} [CommRing R]
    {h : ℕ} {higher : Fin h → ℕ}
    {I : Ideal (MvPolynomial
      (Fin h ⊕ CentralPolynomialIndex (Fin h)
        (terminalTotalDerivativeCount higher) (Fin h)) R)}
    (certificate : ClusterAlgebraicReductionCertificate R h higher I) :
    TerminalizedClusterCertificate R h higher
      (centralIdealConstruction
        (centralTransferShear (terminalTotalDerivativeCount higher)) I) := by
  simpa only [clusterFirstCentralIdeal_eq_transfer] using
    certificate.terminalized

/-- Direct ordered-cluster specialization: the partition supplies the block
relabeling, and the maintained algebraic reduction constructs the cluster
certificate from the mapped rank ideal. -/
theorem nonempty_orderedClusterAlgebraicReductionCertificate
    {R : Type u} [CommRing R]
    {m b krullDim : ℕ} {time : ℕ → Fin m → ℝ}
    (data : RepresentativeClusterSubsequence time)
    (cluster : Fin data.orderedClusterCount)
    (higher : Fin (data.orderedCluster cluster).card → ℕ)
    (dCoeff : OrderedClusterCoefficientBlock data cluster → ℕ)
    (jetPolynomial : Fin b → MvPolynomial
      (SplitClusterBlockSymbol
        (Fin (data.orderedCluster cluster).card)
        (OrderedClusterCoefficientBlock data cluster)
        (terminalTotalDerivativeCount higher) dCoeff) R)
    (I : Ideal (MvPolynomial (PaperRankRetainedSymbols m b) R))
    [Algebra ℚ (MvPolynomial
      (ClusterOperationSymbol
        (OrderedClusterCoefficientBlock data cluster) dCoeff) R)]
    [IsNoetherianRing (MvPolynomial
      (ClusterOperationSymbol
        (OrderedClusterCoefficientBlock data cluster) dCoeff) R)]
    [Ring.KrullDimLE krullDim (MvPolynomial
      (ClusterOperationSymbol
        (OrderedClusterCoefficientBlock data cluster) dCoeff) R)] :
    Nonempty (ClusterAlgebraicReductionCertificate
      (MvPolynomial
        (ClusterOperationSymbol
          (OrderedClusterCoefficientBlock data cluster) dCoeff) R)
      (data.orderedCluster cluster).card higher
      (paperRankClusterCurriedIdeal R
        (Fin (data.orderedCluster cluster).card)
        (OrderedClusterCoefficientBlock data cluster)
        (terminalTotalDerivativeCount higher) dCoeff
        (orderedClusterBlockEquiv data cluster) jetPolynomial I)) := by
  exact nonempty_paperRankClusterAlgebraicReductionCertificate
    (krullDim := krullDim) higher
    (OrderedClusterCoefficientBlock data cluster) dCoeff
    (orderedClusterBlockEquiv data cluster) jetPolynomial I

/-- The evaluated central generator attached to a curried rank polynomial is
the evaluated lexicographic initial source polynomial for the same transfer
shear.  This specializes the maintained central identity to the exact output
of `paperRankClusterCurryHom`. -/
theorem eval₂Hom_paperRankClusterCentralGenerator_eq_initial
    {R : Type u} [CommRing R]
    {S : Type*} [CommRing S]
    {m b h : ℕ} (higher : Fin h → ℕ)
    (Coeff : Type w) (dCoeff : Coeff → ℕ)
    (blockEquiv : Fin m ≃ Fin h ⊕ Coeff)
    (jetPolynomial : Fin b → MvPolynomial
      (SplitClusterBlockSymbol (Fin h) Coeff
        (terminalTotalDerivativeCount higher) dCoeff) R)
    (c : MvPolynomial (ClusterOperationSymbol Coeff dCoeff) R →+* S)
    (z : CentralPolynomialIndex (Fin h)
      (terminalTotalDerivativeCount higher) (Fin h) → S)
    (P : MvPolynomial (PaperRankRetainedSymbols m b) R) :
    MvPolynomial.eval₂Hom c z
        (centralPolynomialPhi
          (MvPolynomial (ClusterOperationSymbol Coeff dCoeff) R)
          (Fin h) (terminalTotalDerivativeCount higher) (Fin h)
          (centralNormalizedInitialPolynomial
            (centralTransferShear (terminalTotalDerivativeCount higher))
            (paperRankClusterCurryHom R (Fin h) Coeff
              (terminalTotalDerivativeCount higher) dCoeff blockEquiv
              jetPolynomial P))) =
      MvPolynomial.eval₂Hom c (centralTransferPhiSourceValue c z)
        (lexicographicInitialForm
          (centralLaurentWeight
            (centralTransferShear (terminalTotalDerivativeCount higher)))
          (paperRankClusterCurryHom R (Fin h) Coeff
            (terminalTotalDerivativeCount higher) dCoeff blockEquiv
            jetPolynomial P)) := by
  exact eval₂Hom_centralGenerator_eq_initial c z
    (centralTransferShear (terminalTotalDerivativeCount higher))
    (paperRankClusterCurryHom R (Fin h) Coeff
      (terminalTotalDerivativeCount higher) dCoeff blockEquiv
      jetPolynomial P)

end AbelFormalization
