import AbelFormalization.RestrictedExpressionTower
import Mathlib.RingTheory.Adjoin.Polynomial.Basic

/-!
# Polynomial lifting of one adjoined function

An element of a function algebra after adjoining one function is a
polynomial in that function with coefficients in the previous algebra.  By
replacing the adjoined function with a new scalar coordinate, that polynomial
gives one fixed lifted expression on a product.  This is the algebraic step
used when the final exponential in a tower is replaced by an unrestricted
variable.
-/

noncomputable section

namespace AbelFormalization

set_option autoImplicit false

variable {X Y : Type*}

/-- Pullback of real-valued functions along an arbitrary map. -/
def functionPrecompAlgHom (phi : Y → X) :
    (X → ℝ) →ₐ[ℝ] (Y → ℝ) where
  toFun f := f ∘ phi
  map_one' := rfl
  map_mul' _ _ := rfl
  map_zero' := rfl
  map_add' _ _ := rfl
  commutes' _ := rfl

@[simp]
theorem functionPrecompAlgHom_apply (phi : Y → X) (f : X → ℝ) (y : Y) :
    functionPrecompAlgHom phi f y = f (phi y) :=
  rfl

/-- The subalgebra of functions obtained by evaluating polynomials over
`B` at `h`, viewed as a real subalgebra. -/
def polynomialEvaluationRange (B : Subalgebra ℝ (X → ℝ)) (h : X → ℝ) :
    Subalgebra ℝ (X → ℝ) :=
  ((Polynomial.aeval (R := B) h).restrictScalars ℝ).range

/-- The old coefficient algebra lies in the polynomial evaluation range. -/
theorem base_le_polynomialEvaluationRange
    (B : Subalgebra ℝ (X → ℝ)) (h : X → ℝ) :
    B ≤ polynomialEvaluationRange B h := by
  intro f hf
  rw [polynomialEvaluationRange, AlgHom.mem_range]
  refine ⟨Polynomial.C ⟨f, hf⟩, ?_⟩
  ext x
  simp [Polynomial.aeval_def]

/-- The adjoined function itself lies in the polynomial evaluation range. -/
theorem adjoined_mem_polynomialEvaluationRange
    (B : Subalgebra ℝ (X → ℝ)) (h : X → ℝ) :
    h ∈ polynomialEvaluationRange B h := by
  rw [polynomialEvaluationRange, AlgHom.mem_range]
  exact ⟨Polynomial.X, by simp⟩

/-- Every element of `B ⊔ ℝ[h]` is represented by a polynomial over `B`
evaluated at `h`. -/
theorem exists_polynomial_aeval_eq_of_mem_sup_adjoin_singleton
    (B : Subalgebra ℝ (X → ℝ)) (h f : X → ℝ)
    (hf : f ∈ B ⊔ Algebra.adjoin ℝ {h}) :
    ∃ P : Polynomial B, Polynomial.aeval h P = f := by
  have hle : B ⊔ Algebra.adjoin ℝ {h} ≤ polynomialEvaluationRange B h := by
    apply sup_le
    · exact base_le_polynomialEvaluationRange B h
    · apply Algebra.adjoin_le
      intro g hg
      rw [Set.mem_singleton_iff] at hg
      subst g
      exact adjoined_mem_polynomialEvaluationRange B h
  have hfrange := hle hf
  rw [polynomialEvaluationRange, AlgHom.mem_range] at hfrange
  exact hfrange

/-- Evaluation of a coefficient in `B` at one source point. -/
def subalgebraPointEval (B : Subalgebra ℝ (X → ℝ)) (x : X) : B →+* ℝ :=
  (Pi.evalRingHom (fun _ : X ↦ ℝ) x).comp B.val.toRingHom

@[simp]
theorem subalgebraPointEval_apply (B : Subalgebra ℝ (X → ℝ))
    (x : X) (b : B) : subalgebraPointEval B x b = (b : X → ℝ) x :=
  rfl

/-- Replace the distinguished function by a free scalar coordinate. -/
def graphPolynomialLift (B : Subalgebra ℝ (X → ℝ))
    (P : Polynomial B) : X × ℝ → ℝ :=
  fun p ↦ Polynomial.eval₂ (subalgebraPointEval B p.1) p.2 P

/-- The product algebra generated by pullbacks of old coefficients and the
new scalar coordinate. -/
def graphPolynomialLiftAlgebra (B : Subalgebra ℝ (X → ℝ)) :
    Subalgebra ℝ (X × ℝ → ℝ) :=
  B.map (functionPrecompAlgHom (fun p : X × ℝ ↦ p.1)) ⊔
    Algebra.adjoin ℝ {fun p : X × ℝ ↦ p.2}

theorem coefficient_pullback_mem_graphPolynomialLiftAlgebra
    (B : Subalgebra ℝ (X → ℝ)) (b : B) :
    (fun p : X × ℝ ↦ (b : X → ℝ) p.1) ∈
      graphPolynomialLiftAlgebra B := by
  apply (show B.map (functionPrecompAlgHom (fun p : X × ℝ ↦ p.1)) ≤
    graphPolynomialLiftAlgebra B from le_sup_left)
  rw [Subalgebra.mem_map]
  exact ⟨b, b.property, rfl⟩

theorem scalar_coordinate_mem_graphPolynomialLiftAlgebra
    (B : Subalgebra ℝ (X → ℝ)) :
    (fun p : X × ℝ ↦ p.2) ∈ graphPolynomialLiftAlgebra B := by
  apply (show Algebra.adjoin ℝ {fun p : X × ℝ ↦ p.2} ≤
    graphPolynomialLiftAlgebra B from le_sup_right)
  exact Algebra.subset_adjoin (Set.mem_singleton _)

/-- Every lifted polynomial belongs to the algebra generated by the old
coefficients and the new scalar coordinate. -/
theorem graphPolynomialLift_mem (B : Subalgebra ℝ (X → ℝ))
    (P : Polynomial B) :
    graphPolynomialLift B P ∈ graphPolynomialLiftAlgebra B := by
  induction P using Polynomial.induction_on' with
  | add P Q hP hQ =>
      have hadd := (graphPolynomialLiftAlgebra B).add_mem hP hQ
      have heq : graphPolynomialLift B (P + Q) =
          graphPolynomialLift B P + graphPolynomialLift B Q := by
        funext p
        exact Polynomial.eval₂_add _ _
      rw [heq]
      exact hadd
  | monomial n b =>
      have hb := coefficient_pullback_mem_graphPolynomialLiftAlgebra B b
      have hy := scalar_coordinate_mem_graphPolynomialLiftAlgebra B
      have hmul := (graphPolynomialLiftAlgebra B).mul_mem hb
        ((graphPolynomialLiftAlgebra B).pow_mem hy n)
      have heq : graphPolynomialLift B ((Polynomial.monomial n) b) =
          (fun p : X × ℝ ↦ (b : X → ℝ) p.1) *
            (fun p : X × ℝ ↦ p.2) ^ n := by
        funext p
        simp [graphPolynomialLift, Polynomial.eval₂_monomial]
      rw [heq]
      exact hmul

/-- Substituting the original function into the free coordinate recovers
ordinary polynomial evaluation in the function ring. -/
theorem graphPolynomialLift_on_graph
    (B : Subalgebra ℝ (X → ℝ)) (h : X → ℝ)
    (P : Polynomial B) (x : X) :
    graphPolynomialLift B P (x, h x) = (Polynomial.aeval h P : X → ℝ) x := by
  induction P using Polynomial.induction_on' with
  | add P Q hP hQ =>
      change Polynomial.eval₂ (subalgebraPointEval B x) (h x) P =
        (Polynomial.aeval h P : X → ℝ) x at hP
      change Polynomial.eval₂ (subalgebraPointEval B x) (h x) Q =
        (Polynomial.aeval h Q : X → ℝ) x at hQ
      change Polynomial.eval₂ (subalgebraPointEval B x) (h x) (P + Q) =
        (Polynomial.aeval h (P + Q) : X → ℝ) x
      rw [Polynomial.eval₂_add, map_add, Pi.add_apply, hP, hQ]
  | monomial n b =>
      simp [graphPolynomialLift, Polynomial.aeval_def,
        Polynomial.eval₂_monomial]

/-- A concrete polynomial lift for every expression using one newly
adjoined function. -/
theorem exists_graphPolynomialLift_of_mem_sup_adjoin_singleton
    (B : Subalgebra ℝ (X → ℝ)) (h f : X → ℝ)
    (hf : f ∈ B ⊔ Algebra.adjoin ℝ {h}) :
    ∃ P : Polynomial B,
      graphPolynomialLift B P ∈ graphPolynomialLiftAlgebra B ∧
      (∀ x, graphPolynomialLift B P (x, h x) = f x) := by
  obtain ⟨P, hP⟩ :=
    exists_polynomial_aeval_eq_of_mem_sup_adjoin_singleton B h f hf
  refine ⟨P, graphPolynomialLift_mem B P, ?_⟩
  intro x
  rw [graphPolynomialLift_on_graph B h P x, hP]

/-- Specialization to one step of a finite exponential tower: an expression
at level `i+1` lifts to a polynomial expression over level `i`, with the
new exponential generator replaced by a free variable. -/
theorem FiniteExponentialTower.exists_graphPolynomialLift_of_mem_level_succ
    {ell : ℕ} {base : Subalgebra ℝ (X → ℝ)}
    (T : FiniteExponentialTower base ell) (i : Fin ell)
    (f : X → ℝ) (hf : f ∈ T.level (i.val + 1)) :
    ∃ P : Polynomial (T.level i.val),
      graphPolynomialLift (T.level i.val) P ∈
        graphPolynomialLiftAlgebra (T.level i.val) ∧
      (∀ x, graphPolynomialLift (T.level i.val) P
        (x, T.generator i x) = f x) := by
  rw [T.level_succ_eq_adjoin i] at hf
  exact exists_graphPolynomialLift_of_mem_sup_adjoin_singleton
    (T.level i.val) (T.generator i) f hf

end AbelFormalization
