import AbelFormalization.PolynomialModuleLeadingTerm

set_option autoImplicit false

/-!
# The actual leading monomial submodule

A component exponent belongs to the leading upper family exactly when it
is the actual largest coefficient index of
some vector in the original polynomial submodule. Closure upwards is
proved by actual multiplication by a coefficient-one monomial.
-/

noncomputable section

namespace AbelFormalization

variable {K : Type*} [Field K] {n r : ℕ}

/-- The actual exponent upper set of all leading terms in one component. -/
def polynomialModuleLeadingUpperFamily (m : MonomialOrder (Fin n))
    (N : Submodule (MvPolynomial (Fin n) K) (Fin r → MvPolynomial (Fin n) K)) :
    Fin r → UpperSet (Fin n → ℕ) := fun k =>
  { carrier := {x | ∃ P ∈ N, IsPolynomialModuleLeadingTerm m P
      (k, Finsupp.equivFunOnFinite.symm x)}
    upper' := by
      intro x y hxy
      rintro ⟨P, hPN, hP⟩
      let d : Fin n →₀ ℕ := Finsupp.equivFunOnFinite.symm x
      let e : Fin n →₀ ℕ := Finsupp.equivFunOnFinite.symm y
      have hde : d ≤ e := hxy
      refine ⟨(MvPolynomial.monomial (e - d) (1 : K)) • P,
        N.smul_mem _ hPN, ?_⟩
      have h := hP.monomial_smul (e - d)
      change IsPolynomialModuleLeadingTerm m
        ((MvPolynomial.monomial (e - d) (1 : K)) • P) (k, e)
      change IsPolynomialModuleLeadingTerm m
        ((MvPolynomial.monomial (e - d) (1 : K)) • P) (k, e - d + d) at h
      rwa [tsub_add_cancel_of_le hde] at h }

/-- Membership of an actual exponent is exactly an original-vector
leading witness; no closure or generation hypothesis is needed. -/
theorem mem_polynomialModuleLeadingUpperFamily (m : MonomialOrder (Fin n))
    (N : Submodule (MvPolynomial (Fin n) K) (Fin r → MvPolynomial (Fin n) K))
    (k : Fin r) (d : Fin n →₀ ℕ) :
    (d : Fin n → ℕ) ∈ polynomialModuleLeadingUpperFamily m N k ↔
      ∃ P ∈ N, IsPolynomialModuleLeadingTerm m P (k, d) := by
  change (∃ P ∈ N, IsPolynomialModuleLeadingTerm m P
    (k, Finsupp.equivFunOnFinite.symm (d : Fin n → ℕ))) ↔ _
  rw [Finsupp.equivFunOnFinite_symm_coe]

/-- The leading family grows by literal exponent inclusion when the
original polynomial submodule grows. -/
theorem polynomialModuleLeadingUpperFamily_mono (m : MonomialOrder (Fin n))
    {N N' : Submodule (MvPolynomial (Fin n) K) (Fin r → MvPolynomial (Fin n) K)}
    (hNN' : N ≤ N') :
    ∀ k, (polynomialModuleLeadingUpperFamily m N k : Set (Fin n → ℕ)) ⊆
      polynomialModuleLeadingUpperFamily m N' k := by
  intro k x hx
  obtain ⟨P, hPN, hP⟩ := hx
  exact ⟨P, hNN' hPN, hP⟩

/-- The corresponding actual polynomial-ring submodule generated by its
componentwise coefficient-one monomials. -/
def polynomialModuleLeadingSubmodule (m : MonomialOrder (Fin n))
    (N : Submodule (MvPolynomial (Fin n) K) (Fin r → MvPolynomial (Fin n) K)) :
    Submodule (MvPolynomial (Fin n) K) (Fin r → MvPolynomial (Fin n) K) :=
  monomialUpperFamilySubmodule (polynomialModuleLeadingUpperFamily m N)

/-- The literal coefficient-one module monomial at an index. -/
def polynomialModuleMonomial (t : Fin r × (Fin n →₀ ℕ)) (c : K) :
    Fin r → MvPolynomial (Fin n) K :=
  Pi.single t.1 (MvPolynomial.monomial t.2 c)

/-- A coefficient-one module monomial belongs to the actual leading
submodule exactly when its exponent has an original leading witness. -/
theorem polynomialModuleMonomial_one_mem_leadingSubmodule
    (m : MonomialOrder (Fin n))
    (N : Submodule (MvPolynomial (Fin n) K) (Fin r → MvPolynomial (Fin n) K))
    (t : Fin r × (Fin n →₀ ℕ)) :
    polynomialModuleMonomial t (1 : K) ∈ polynomialModuleLeadingSubmodule m N ↔
      ∃ P ∈ N, IsPolynomialModuleLeadingTerm m P t := by
  classical
  rw [polynomialModuleLeadingSubmodule, polynomialModuleMonomial]
  change (∀ k ∈ (Set.univ : Set (Fin r)),
    (Pi.single t.1 (MvPolynomial.monomial t.2 (1 : K)) :
      Fin r → MvPolynomial (Fin n) K) k ∈
        monomialUpperSetIdeal (polynomialModuleLeadingUpperFamily m N k)) ↔ _
  constructor
  · intro h
    have ht := h t.1 (Set.mem_univ t.1)
    have hmem : (t.2 : Fin n → ℕ) ∈ polynomialModuleLeadingUpperFamily m N t.1 :=
      (monomial_one_mem_monomialUpperSetIdeal (R := K) _ _).mp (by simpa using ht)
    exact (mem_polynomialModuleLeadingUpperFamily m N t.1 t.2).mp hmem
  · intro h k _
    by_cases hk : k = t.1
    · subst k
      simpa only [Pi.single_eq_same] using
        (monomial_one_mem_monomialUpperSetIdeal (R := K) _ _).mpr
          ((mem_polynomialModuleLeadingUpperFamily m N t.1 t.2).mpr h)
    · simp [hk]

end AbelFormalization
