import AbelFormalization.CentralIdealConstruction
import Mathlib.Data.Fintype.EquivFin
import Mathlib.RingTheory.Noetherian.Defs

/-!
# Finite certificates for the central initial ideal

This scratch module isolates the finite algebra needed by the quantitative
transfer argument.  It makes two choices, both forced by Noetherianity:

* finitely many elements of the translated source ideal whose *actual*
  lexicographic initial forms generate the full initial ideal;
* the corresponding normalized weight-zero polynomials.

The second family is not chosen independently.  Its elements are obtained by
setting the independent Laurent variables equal to one in the initial forms.
The homogeneous group-algebra calculation below proves that these elements
generate the exact Laurent contraction.  Applying `centralPolynomialPhi`
therefore gives a compatible finite generating family for
`centralIdealConstruction`.

This file is intentionally confined to the algebraic certificate.  It makes
no claim about the later analytic evaluation or asymptotic estimates.
-/

noncomputable section

set_option autoImplicit false

namespace AbelFormalization

open Set

universe u v w

section GroupAlgebra

variable {A G : Type*} [CommRing A] [AddCommGroup G]

/-- Extension to a group algebra is faithfully contracted along its
coefficient inclusion. -/
theorem groupAlgebra_comap_map_C_eq (J : Ideal A) :
    (J.map (groupAlgebraC A G)).comap (groupAlgebraC A G) = J := by
  apply le_antisymm
  · intro a ha
    have hcoeff : (groupAlgebraC A G a).coeff (0 : G) ∈ J :=
      (groupAlgebra_mem_map_C_iff (G := G) J (groupAlgebraC A G a)).mp ha 0
    simpa [groupAlgebraC_apply] using hcoeff
  · exact Ideal.le_comap_map

variable {R σ κ : Type*} [CommRing R]

/-- A homogeneous generating family remains a generating family after
weighted group evaluation, up to multiplication of each generator by its
invertible group monomial.  The normalized coefficients are the ordinary
`eval₂` values of the homogeneous source polynomials. -/
theorem weightedGroupEvaluation_span_eq_normalized_map
    (c : R →+* A) (a : σ → A) (ν : σ → G)
    (p : κ → MvPolynomial σ R) (degree : κ → G)
    (hp : ∀ i, (p i).IsWeightedHomogeneous ν (degree i)) :
    (Ideal.span (Set.range p)).map (weightedGroupEvaluation c a ν) =
      (Ideal.span (Set.range (fun i => MvPolynomial.eval₂Hom c a (p i)))).map
        (groupAlgebraC A G) := by
  apply le_antisymm
  · rw [Ideal.map_le_iff_le_comap, Ideal.span_le]
    rintro _ ⟨i, rfl⟩
    change weightedGroupEvaluation c a ν (p i) ∈
      (Ideal.span (Set.range
        (fun j => MvPolynomial.eval₂Hom c a (p j)))).map
          (groupAlgebraC A G)
    rw [weightedGroupEvaluation_of_homogeneous c a ν (hp i)]
    have hnormalized : MvPolynomial.eval₂Hom c a (p i) ∈
        Ideal.span (Set.range
          (fun j => MvPolynomial.eval₂Hom c a (p j))) :=
      Ideal.subset_span ⟨i, rfl⟩
    have hconstant : groupAlgebraC A G (MvPolynomial.eval₂Hom c a (p i)) ∈
        (Ideal.span (Set.range
          (fun j => MvPolynomial.eval₂Hom c a (p j)))).map
            (groupAlgebraC A G) :=
      Ideal.mem_map_of_mem (groupAlgebraC A G) hnormalized
    have hmultiple :=
      ((Ideal.span (Set.range
        (fun j => MvPolynomial.eval₂Hom c a (p j)))).map
          (groupAlgebraC A G)).mul_mem_left
        (AddMonoidAlgebra.single (degree i) 1) hconstant
    simpa [groupAlgebraC_apply] using hmultiple
  · rw [Ideal.map_le_iff_le_comap, Ideal.span_le]
    rintro _ ⟨i, rfl⟩
    change groupAlgebraC A G (MvPolynomial.eval₂Hom c a (p i)) ∈
      (Ideal.span (Set.range p)).map (weightedGroupEvaluation c a ν)
    have himage : weightedGroupEvaluation c a ν (p i) ∈
        (Ideal.span (Set.range p)).map (weightedGroupEvaluation c a ν) :=
      Ideal.mem_map_of_mem (weightedGroupEvaluation c a ν)
        (Ideal.subset_span ⟨i, rfl⟩)
    rw [weightedGroupEvaluation_of_homogeneous c a ν (hp i)] at himage
    have hmultiple :=
      ((Ideal.span (Set.range p)).map
        (weightedGroupEvaluation c a ν)).mul_mem_left
          (AddMonoidAlgebra.single (-(degree i)) 1) himage
    simpa only [groupAlgebra_inverse_single_mul] using hmultiple

/-- Contracting the evaluated ideal recovers exactly the ideal generated by
the normalized coefficients of a homogeneous generating family. -/
theorem normalizedWeightedEvaluation_span_eq_contraction
    (c : R →+* A) (a : σ → A) (ν : σ → G)
    (p : κ → MvPolynomial σ R) (degree : κ → G)
    (hp : ∀ i, (p i).IsWeightedHomogeneous ν (degree i)) :
    Ideal.span (Set.range (fun i => MvPolynomial.eval₂Hom c a (p i))) =
      ((Ideal.span (Set.range p)).map
        (weightedGroupEvaluation c a ν)).comap (groupAlgebraC A G) := by
  rw [weightedGroupEvaluation_span_eq_normalized_map c a ν p degree hp]
  exact (groupAlgebra_comap_map_C_eq
    (G := G) (Ideal.span (Set.range
      (fun i => MvPolynomial.eval₂Hom c a (p i))))).symm

end GroupAlgebra

section FiniteInitialFamily

variable {R ι : Type*} [CommRing R]

/-- In a Noetherian polynomial ring, the full initial ideal admits a finite
generating family consisting of actual initial forms, with a retained source
witness in the original ideal for every generator. -/
theorem exists_lexicographicInitialForm_fin_generating_family
    [IsNoetherianRing R] [Finite ι]
    {h : ℕ} (ω : ι → Fin h → ℤ) (I : Ideal (MvPolynomial ι R)) :
    ∃ n : ℕ, ∃ f : Fin n → MvPolynomial ι R,
      (∀ i, f i ∈ I) ∧
      Ideal.span (Set.range (fun i => lexicographicInitialForm ω (f i))) =
        lexicographicInitialIdeal ω I := by
  classical
  let S : Set (MvPolynomial ι R) :=
    lexicographicInitialForm ω '' (I : Set (MvPolynomial ι R))
  have hfg : (Submodule.span (MvPolynomial ι R) S).FG := by
    exact Ideal.fg_of_isNoetherianRing (Ideal.span S)
  obtain ⟨s, hsS, hspan⟩ :=
    (Submodule.fg_span_iff_fg_span_finset_subset
      (R := MvPolynomial ι R) S).mp hfg
  let e : Fin s.card ≃ ↥s := s.equivFin.symm
  have hpreimage : ∀ i : Fin s.card,
      ∃ f : MvPolynomial ι R,
        f ∈ I ∧ lexicographicInitialForm ω f = (e i : MvPolynomial ι R) := by
    intro i
    have hei : (e i : MvPolynomial ι R) ∈ S := hsS (e i).property
    change (e i : MvPolynomial ι R) ∈
      lexicographicInitialForm ω '' (I : Set (MvPolynomial ι R)) at hei
    rcases hei with ⟨f, hf, hfi⟩
    exact ⟨f, hf, hfi⟩
  choose f hfI hfinit using hpreimage
  have hrange :
      Set.range (fun i : Fin s.card => lexicographicInitialForm ω (f i)) =
        (s : Set (MvPolynomial ι R)) := by
    ext q
    constructor
    · rintro ⟨i, rfl⟩
      change lexicographicInitialForm ω (f i) ∈ (s : Set (MvPolynomial ι R))
      rw [hfinit i]
      exact (e i).property
    · intro hq
      obtain ⟨i, hi⟩ := e.surjective ⟨q, hq⟩
      refine ⟨i, ?_⟩
      calc
        lexicographicInitialForm ω (f i) = (e i : MvPolynomial ι R) := hfinit i
        _ = q := congrArg Subtype.val hi
  refine ⟨s.card, f, hfI, ?_⟩
  rw [hrange, lexicographicInitialIdeal]
  exact hspan.symm

end FiniteInitialFamily

section CentralNormalization

variable {R ι : Type*} [CommRing R] {h : ℕ}

/-- The polynomial coefficient left after normalizing the Laurent degree of
an actual initial form.  Equivalently, set every independent `q` variable to
one and retain every other polynomial symbol. -/
def centralNormalizedInitialPolynomial
    (ω : ι → Fin h → ℤ)
    (f : MvPolynomial (Fin h ⊕ ι) R) : MvPolynomial ι R :=
  MvPolynomial.eval₂Hom MvPolynomial.C
    (Sum.elim (fun _ : Fin h => (1 : MvPolynomial ι R)) MvPolynomial.X)
    (lexicographicInitialForm (centralLaurentWeight ω) f)

/-- The rescaled Laurent image of an actual initial form is a single group
monomial whose coefficient is `centralNormalizedInitialPolynomial`. -/
theorem centralLaurentRescaledMap_initialForm_eq_single
    (ω : ι → Fin h → ℤ) (f : MvPolynomial (Fin h ⊕ ι) R) :
    centralLaurentRescaledMap ω
        (lexicographicInitialForm (centralLaurentWeight ω) f) =
      AddMonoidAlgebra.single
        (-(ofLex (lexicographicMinimumWeight (centralLaurentWeight ω) f)))
        (centralNormalizedInitialPolynomial ω f) := by
  rw [centralLaurentRescaledMap_eq_evaluation]
  have hhom := isWeightedHomogeneous_neg_group (centralLaurentWeight ω)
    (lexicographicInitialForm_isWeightedHomogeneous
      (centralLaurentWeight ω) f)
  simpa only [centralNormalizedInitialPolynomial] using
    (weightedGroupEvaluation_of_homogeneous MvPolynomial.C
      (Sum.elim (fun _ : Fin h => (1 : MvPolynomial ι R)) MvPolynomial.X)
      (fun i => -centralLaurentWeight ω i) hhom)

/-- Coefficient-zero presentation of the same normalization.  This is the
form used when the later quantitative argument separates the least-weight
term from all higher-weight terms. -/
theorem centralNormalizedInitialPolynomial_eq_coeff_zero
    (ω : ι → Fin h → ℤ) (f : MvPolynomial (Fin h ⊕ ι) R) :
    centralNormalizedInitialPolynomial ω f =
      ((AddMonoidAlgebra.single
          (ofLex (lexicographicMinimumWeight (centralLaurentWeight ω) f)) 1) *
        centralLaurentRescaledMap ω
          (lexicographicInitialForm (centralLaurentWeight ω) f)).coeff 0 := by
  rw [centralLaurentRescaledMap_initialForm_eq_single]
  simp

/-- Every normalized actual initial form belongs to the exact coefficient
contraction. -/
theorem centralNormalizedInitialPolynomial_mem_contraction
    (ω : ι → Fin h → ℤ)
    (I : Ideal (MvPolynomial (Fin h ⊕ ι) R))
    {f : MvPolynomial (Fin h ⊕ ι) R} (hf : f ∈ I) :
    centralNormalizedInitialPolynomial ω f ∈ centralLaurentContraction ω I := by
  rw [centralLaurentContraction_eq]
  change groupAlgebraC (MvPolynomial ι R) (Fin h → ℤ)
      (centralNormalizedInitialPolynomial ω f) ∈
    (lexicographicInitialIdeal (centralLaurentWeight ω) I).map
      (centralLaurentRescaledMap ω)
  have hinitial :
      lexicographicInitialForm (centralLaurentWeight ω) f ∈
        lexicographicInitialIdeal (centralLaurentWeight ω) I :=
    lexicographicInitialForm_mem_initialIdeal _ I hf
  have himage := Ideal.mem_map_of_mem (centralLaurentRescaledMap ω) hinitial
  rw [centralLaurentRescaledMap_initialForm_eq_single] at himage
  have hmultiple :=
    ((lexicographicInitialIdeal (centralLaurentWeight ω) I).map
      (centralLaurentRescaledMap ω)).mul_mem_left
        (AddMonoidAlgebra.single
          (ofLex (lexicographicMinimumWeight (centralLaurentWeight ω) f)) 1)
        himage
  simpa [groupAlgebraC_apply] using hmultiple

/-- If a displayed family of actual initial forms generates the full initial
ideal, its normalized coefficients generate the exact Laurent contraction. -/
theorem centralNormalizedInitialPolynomial_span_eq_contraction
    {κ : Type*} (ω : ι → Fin h → ℤ)
    (I : Ideal (MvPolynomial (Fin h ⊕ ι) R))
    (f : κ → MvPolynomial (Fin h ⊕ ι) R)
    (hspan :
      Ideal.span (Set.range (fun i =>
        lexicographicInitialForm (centralLaurentWeight ω) (f i))) =
        lexicographicInitialIdeal (centralLaurentWeight ω) I) :
    Ideal.span (Set.range (fun i =>
      centralNormalizedInitialPolynomial ω (f i))) =
        centralLaurentContraction ω I := by
  have hnormalized :=
    normalizedWeightedEvaluation_span_eq_contraction
      (c := MvPolynomial.C)
      (a := Sum.elim
        (fun _ : Fin h => (1 : MvPolynomial ι R)) MvPolynomial.X)
      (ν := fun i => -centralLaurentWeight ω i)
      (p := fun i =>
        lexicographicInitialForm (centralLaurentWeight ω) (f i))
      (degree := fun i =>
        -(ofLex (lexicographicMinimumWeight (centralLaurentWeight ω) (f i))))
      (fun i => isWeightedHomogeneous_neg_group (centralLaurentWeight ω)
        (lexicographicInitialForm_isWeightedHomogeneous
          (centralLaurentWeight ω) (f i)))
  rw [hspan, ← centralLaurentRescaledMap_eq_evaluation,
    ← centralLaurentContraction_eq] at hnormalized
  simpa only [centralNormalizedInitialPolynomial] using hnormalized

end CentralNormalization

section CentralCertificate

variable {R : Type u} [CommRing R]
variable {Block : Type v} {Time : Type w}
variable {d : Block → ℕ} {h : ℕ}

/-- Mapping a ranged generating family maps its span to the span of the
pointwise images. -/
theorem span_range_map_eq {S T κ : Type*} [CommRing S] [CommRing T]
    (φ : S →+* T) (g : κ → S) :
    Ideal.span (Set.range (fun i => φ (g i))) =
      (Ideal.span (Set.range g)).map φ := by
  rw [Ideal.map_span]
  congr 1
  ext y
  constructor
  · rintro ⟨i, rfl⟩
    exact ⟨g i, ⟨i, rfl⟩, rfl⟩
  · rintro ⟨x, ⟨i, rfl⟩, rfl⟩
    exact ⟨i, rfl⟩

/-- A finite source/central certificate for the complete central
construction.  Every `f i` belongs to the translated source ideal; its actual
least lexicographic form participates in a generating family of the full
initial ideal; its normalized coefficient generates the exact shifted
Laurent contraction; and its `Phi` image generates the literal central ideal.
-/
theorem exists_centralTransferGeneratingFamily
    [IsNoetherianRing R] [Finite Block] [Finite Time]
    (ω : CentralPolynomialIndex Block d Time → Fin h → ℤ)
    (I : Ideal (MvPolynomial
      (Fin h ⊕ CentralPolynomialIndex Block d Time) R)) :
    ∃ n : ℕ, ∃ f : Fin n → MvPolynomial
        (Fin h ⊕ CentralPolynomialIndex Block d Time) R,
      (∀ i, f i ∈ I.map
        (polynomialCoordinateTranslation
          (Sum.elim (fun _ : Fin h => (-1 : R))
            (fun _ : CentralPolynomialIndex Block d Time => 0))).toRingHom) ∧
      Ideal.span (Set.range (fun i =>
        lexicographicInitialForm (centralLaurentWeight ω) (f i))) =
        lexicographicInitialIdeal (centralLaurentWeight ω)
          (I.map (polynomialCoordinateTranslation
            (Sum.elim (fun _ : Fin h => (-1 : R))
              (fun _ : CentralPolynomialIndex Block d Time => 0))).toRingHom) ∧
      Ideal.span (Set.range (fun i =>
        centralNormalizedInitialPolynomial ω (f i))) =
          centralShiftedLaurentContraction ω I ∧
      Ideal.span (Set.range (fun i =>
        centralPolynomialPhi R Block d Time
          (centralNormalizedInitialPolynomial ω (f i)))) =
          centralIdealConstruction ω I := by
  let τ := polynomialCoordinateTranslation
    (Sum.elim (fun _ : Fin h => (-1 : R))
      (fun _ : CentralPolynomialIndex Block d Time => 0))
  let Iq := I.map τ.toRingHom
  obtain ⟨n, f, hfI, hinitial⟩ :=
    exists_lexicographicInitialForm_fin_generating_family
      (ω := centralLaurentWeight ω) Iq
  have hnormalized :
      Ideal.span (Set.range (fun i =>
        centralNormalizedInitialPolynomial ω (f i))) =
          centralShiftedLaurentContraction ω I := by
    have h := centralNormalizedInitialPolynomial_span_eq_contraction
      ω Iq f hinitial
    simpa only [centralShiftedLaurentContraction, Iq, τ] using h
  have hcentral :
      Ideal.span (Set.range (fun i =>
        centralPolynomialPhi R Block d Time
          (centralNormalizedInitialPolynomial ω (f i)))) =
          centralIdealConstruction ω I := by
    calc
      Ideal.span (Set.range (fun i =>
          centralPolynomialPhi R Block d Time
            (centralNormalizedInitialPolynomial ω (f i)))) =
          (Ideal.span (Set.range (fun i =>
            centralNormalizedInitialPolynomial ω (f i)))).map
              (centralPolynomialPhi R Block d Time).toRingHom :=
        span_range_map_eq (centralPolynomialPhi R Block d Time).toRingHom _
      _ = (centralShiftedLaurentContraction ω I).map
          (centralPolynomialPhi R Block d Time).toRingHom := by rw [hnormalized]
      _ = centralIdealConstruction ω I := rfl
  refine ⟨n, f, ?_, ?_, hnormalized, hcentral⟩
  · simpa only [Iq, τ] using hfI
  · simpa only [Iq, τ] using hinitial

end CentralCertificate

end AbelFormalization
