import AbelFormalization.LaurentRescaling
import AbelFormalization.LaurentIdealTools
import AbelFormalization.SaturatedSpecializationHeight

/-! # Actual weighted Laurent deformation and its height

The deformation is the contraction of the rescaled coefficient extension
from a Laurent polynomial ring. Its definition includes the whole ideal.
This module proves saturation and the height of that actual contraction and
its zero-parameter specialization. Identification of the specialization with
all least-weight forms is a further generator theorem.
-/

noncomputable section

namespace AbelFormalization

variable {R ι : Type*} [CommRing R]

/-- The full Laurent contraction for an integer weight on the variables. -/
def weightedDeformationIdeal (ω : ι → ℤ) (I : Ideal (MvPolynomial ι R)) :
    Ideal (Polynomial (MvPolynomial ι R)) :=
  ((I.map LaurentPolynomial.C).map (laurentWeightRescaling ω).toRingHom).comap
    Polynomial.toLaurent

/-- Saturation is a consequence of the actual Laurent contraction. -/
theorem weightedDeformationIdeal_cancel_X (ω : ι → ℤ) (I : Ideal (MvPolynomial ι R))
    (f : Polynomial (MvPolynomial ι R))
    (hf : Polynomial.X * f ∈ weightedDeformationIdeal ω I) :
    f ∈ weightedDeformationIdeal ω I :=
  laurentPolynomial_comap_cancel_X _ f hf

/-- Its actual zero-parameter fiber, pending identification with the full
weighted initial ideal generated by all least-weight forms. -/
def weightedDeformationSpecialization (ω : ι → ℤ) (I : Ideal (MvPolynomial ι R)) :
    Ideal (MvPolynomial ι R) :=
  (weightedDeformationIdeal ω I).map (Polynomial.evalRingHom 0)

section Height

variable [IsNoetherianRing R] [Finite ι]

/-- Laurent extension, the actual weight automorphism, and contraction
preserve the original ideal's height. -/
theorem weightedDeformationIdeal_height (ω : ι → ℤ) (I : Ideal (MvPolynomial ι R)) :
    (weightedDeformationIdeal ω I).height = I.height :=
  laurentPolynomial_automorphic_contraction_height I (laurentWeightRescaling ω).toRingEquiv

/-- The zero-parameter fiber has height at least that of the original ideal.
No flat-fiber dimension formula is assumed. -/
theorem weightedDeformationSpecialization_height (ω : ι → ℤ)
    (I : Ideal (MvPolynomial ι R)) :
    I.height ≤ (weightedDeformationSpecialization ω I).height := by
  rw [← weightedDeformationIdeal_height ω I]
  exact polynomial_height_le_eval_zero_of_saturated (weightedDeformationIdeal ω I)
    (weightedDeformationIdeal_cancel_X ω I)

end Height

/-- The contraction description of ordinary homogenization: each variable
is substituted by its product with the inverse Laurent parameter. -/
def ordinaryHomogenizationContraction (I : Ideal (MvPolynomial ι R)) :
    Ideal (Polynomial (MvPolynomial ι R)) := weightedDeformationIdeal (fun _ => -1) I

/-- The ordinary homogenization contraction is saturated in its homogenizing
parameter. Equality with the ideal generated by all ordinary homogenizations
will be supplied by the normalized-generator identity. -/
theorem ordinaryHomogenizationContraction_cancel_X (I : Ideal (MvPolynomial ι R))
    (f : Polynomial (MvPolynomial ι R))
    (hf : Polynomial.X * f ∈ ordinaryHomogenizationContraction I) :
    f ∈ ordinaryHomogenizationContraction I :=
  weightedDeformationIdeal_cancel_X (fun _ => -1) I f hf

/-- The contraction description of full ordinary homogenization has exactly
the original ideal's height. -/
theorem ordinaryHomogenizationContraction_height [IsNoetherianRing R] [Finite ι]
    (I : Ideal (MvPolynomial ι R)) :
    (ordinaryHomogenizationContraction I).height = I.height :=
  weightedDeformationIdeal_height (fun _ => -1) I

end AbelFormalization
