import AbelFormalization.LexicographicInitialIdeals
import AbelFormalization.MultivariateLaurentIdeal
import AbelFormalization.GroupLaurentRescaling

/-!
# Evaluation at actual group-homogeneous polynomial symbols

Polynomial symbols are sent to literal group monomials with specified
coefficients. A homogeneous polynomial evaluates
to a single group component. In particular the image of a full least
lexicographic initial ideal is homogeneous for the actual group grading.
-/

noncomputable section
set_option autoImplicit false

namespace AbelFormalization

variable {R A σ G : Type*} [CommRing R] [CommRing A] [AddCommGroup G]

/-- Actual polynomial evaluation at group monomials of prescribed weights. -/
def weightedGroupEvaluation (c : R →+* A) (a : σ → A) (ν : σ → G) :
    MvPolynomial σ R →+* AddMonoidAlgebra A G :=
  MvPolynomial.eval₂Hom ((groupAlgebraC A G).comp c)
    (fun i => AddMonoidAlgebra.single (ν i) (a i))

private theorem group_single_finset_prod {δ : Type*} (s : Finset δ)
    (g : δ → G) (a : δ → A) :
    (∏ i ∈ s, AddMonoidAlgebra.single (g i) (a i)) =
      AddMonoidAlgebra.single (∑ i ∈ s, g i) (∏ i ∈ s, a i) := by
  classical
  induction s using Finset.induction_on with
  | empty => simp [AddMonoidAlgebra.one_def]
  | @insert i s hi ih => simp [hi, ih]

@[simp]
theorem weightedGroupEvaluation_monomial (c : R →+* A) (a : σ → A)
    (ν : σ → G) (d : σ →₀ ℕ) (r : R) :
    weightedGroupEvaluation c a ν (MvPolynomial.monomial d r) =
      AddMonoidAlgebra.single (Finsupp.weight ν d)
        (MvPolynomial.eval₂Hom c a (MvPolynomial.monomial d r)) := by
  classical
  simp only [weightedGroupEvaluation, MvPolynomial.eval₂Hom_monomial,
    RingHom.comp_apply, groupAlgebraC_apply, AddMonoidAlgebra.single_pow,
    Finsupp.prod, group_single_finset_prod, AddMonoidAlgebra.single_mul_single,
    zero_add, Finsupp.weight_apply, Finsupp.sum]

@[simp]
theorem weightedGroupEvaluation_X (c : R →+* A) (a : σ → A)
    (ν : σ → G) (i : σ) :
    weightedGroupEvaluation c a ν (MvPolynomial.X i) =
      AddMonoidAlgebra.single (ν i) (a i) := by
  simp [weightedGroupEvaluation]

@[simp]
theorem weightedGroupEvaluation_C (c : R →+* A) (a : σ → A)
    (ν : σ → G) (r : R) :
    weightedGroupEvaluation c a ν (MvPolynomial.C r) =
      AddMonoidAlgebra.single 0 (c r) := by
  simp [weightedGroupEvaluation]

/-- This uses the actual support homogeneity of the input polynomial. -/
theorem weightedGroupEvaluation_of_homogeneous (c : R →+* A) (a : σ → A)
    (ν : σ → G) {α : G} {f : MvPolynomial σ R}
    (hf : f.IsWeightedHomogeneous ν α) :
    weightedGroupEvaluation c a ν f =
      AddMonoidAlgebra.single α (MvPolynomial.eval₂Hom c a f) := by
  classical
  rw [f.as_sum, map_sum, map_sum]
  rw [show AddMonoidAlgebra.single α
      (∑ d ∈ f.support, MvPolynomial.eval₂Hom c a (MvPolynomial.monomial d (f.coeff d))) =
      ∑ d ∈ f.support, AddMonoidAlgebra.single α
        (MvPolynomial.eval₂Hom c a (MvPolynomial.monomial d (f.coeff d))) from
      map_sum (AddMonoidAlgebra.singleAddHom α) _ _]
  apply Finset.sum_congr rfl
  intro d hd
  rw [weightedGroupEvaluation_monomial, hf (MvPolynomial.mem_support_iff.mp hd)]

/-- Mapping an ideal generated by actual homogeneous polynomials gives an
ideal homogeneous for the identity grading of the group algebra. -/
theorem weightedGroupEvaluation_span_isHomogeneous [DecidableEq G]
    (c : R →+* A) (a : σ → A) (ν : σ → G)
    (s : Set (MvPolynomial σ R))
    (hs : ∀ f ∈ s, ∃ α, f.IsWeightedHomogeneous ν α) :
    ((Ideal.span s).map (weightedGroupEvaluation c a ν)).IsHomogeneous
      (AddMonoidAlgebra.grade A) := by
  rw [Ideal.map_span]
  apply Ideal.homogeneous_span
  rintro _ ⟨f, hf, rfl⟩
  obtain ⟨α, hα⟩ := hs f hf
  rw [weightedGroupEvaluation_of_homogeneous c a ν hα]
  exact ⟨α, AddMonoidAlgebra.single_mem_grade α _⟩

/-- The underlying vector of a lexicographic weight is the literal vector
weight; ordering changes no coefficient or additive operation. -/
theorem lexicographicWeight_ofLex {h : ℕ} (ν : σ → Fin h → ℤ)
    (d : σ →₀ ℕ) :
    ofLex (Finsupp.weight (fun i => toLex (ν i)) d) = Finsupp.weight ν d := by
  funext j
  rw [lexicographicWeight_apply]
  simp only [Finsupp.weight_apply, Finsupp.sum, Finset.sum_apply, Pi.smul_apply]

theorem lexicographicInitialForm_isWeightedHomogeneous {h : ℕ}
    (ν : σ → Fin h → ℤ) (f : MvPolynomial σ R) :
    (lexicographicInitialForm ν f).IsWeightedHomogeneous ν
      (ofLex (lexicographicMinimumWeight ν f)) := by
  intro d hd
  have he := MvPolynomial.weightedHomogeneousComponent_isWeightedHomogeneous
    (lexicographicMinimumWeight ν f) f hd
  simpa only [lexicographicWeight_ofLex] using congrArg ofLex he

/-- No homogeneous-ideal premise is supplied here: all the generators are
the actual least lexicographic initial forms of the original ideal. -/
theorem weightedGroupEvaluation_lexicographicInitial_isHomogeneous {h : ℕ}
    (c : R →+* A) (a : σ → A) (ν : σ → Fin h → ℤ)
    (I : Ideal (MvPolynomial σ R)) :
    ((lexicographicInitialIdeal ν I).map
      (weightedGroupEvaluation c a ν)).IsHomogeneous (AddMonoidAlgebra.grade A) := by
  classical
  apply weightedGroupEvaluation_span_isHomogeneous
  rintro _ ⟨f, hf, rfl⟩
  exact ⟨_, lexicographicInitialForm_isWeightedHomogeneous ν f⟩

/-- Consequently the actual image is extended from its actual coefficient
contraction. This applies before any assumption of ideal invariance. -/
theorem weightedGroupEvaluation_lexicographicInitial_eq_map_comap {h : ℕ}
    (c : R →+* A) (a : σ → A) (ν : σ → Fin h → ℤ)
    (I : Ideal (MvPolynomial σ R)) :
    (lexicographicInitialIdeal ν I).map (weightedGroupEvaluation c a ν) =
      (((lexicographicInitialIdeal ν I).map (weightedGroupEvaluation c a ν)).comap
        (groupAlgebraC A (Fin h → ℤ))).map (groupAlgebraC A (Fin h → ℤ)) := by
  classical
  exact groupAlgebra_homogeneousIdeal_eq_map_comap _
    (weightedGroupEvaluation_lexicographicInitial_isHomogeneous c a ν I)

/-- Negating the degree labels preserves the same actual homogeneous
polynomial. It does not change the order used to form an initial ideal. -/
theorem isWeightedHomogeneous_neg_group (ν : σ → G) {α : G}
    {f : MvPolynomial σ R} (hf : f.IsWeightedHomogeneous ν α) :
    f.IsWeightedHomogeneous (fun i => -ν i) (-α) := by
  intro d hd
  rw [group_finsupp_weight_neg, hf hd]

/-- The shear convention in the central construction uses the negative
of the paper's degree, while the initial ideal here retains the paper's
original least lexicographic order. -/
theorem weightedGroupEvaluation_neg_lexicographicInitial_isHomogeneous {h : ℕ}
    (c : R →+* A) (a : σ → A) (ν : σ → Fin h → ℤ)
    (I : Ideal (MvPolynomial σ R)) :
    ((lexicographicInitialIdeal ν I).map
      (weightedGroupEvaluation c a (fun i => -ν i))).IsHomogeneous
      (AddMonoidAlgebra.grade A) := by
  classical
  apply weightedGroupEvaluation_span_isHomogeneous
  rintro _ ⟨f, hf, rfl⟩
  exact ⟨_, isWeightedHomogeneous_neg_group ν
    (lexicographicInitialForm_isWeightedHomogeneous ν f)⟩

end AbelFormalization
