import AbelFormalization.WeightedDeformation
import AbelFormalization.WeightedNormalization

/-!
# Full generators of the weighted deformation

The contracted Laurent deformation is generated by the normalized transforms
of every element of the original ideal. Its zero-parameter specialization is
therefore the full ideal of least-weight forms. The coefficient argument does
not require a domain: rescaling permutes exponent pairs, so each resulting
coefficient has exactly one original coefficient.
-/

noncomputable section

namespace AbelFormalization

variable {R ι : Type*} [CommRing R]

/-- If a rescaled Laurent polynomial is an ordinary polynomial, every nonzero
two-level coefficient has a nonnegative rescaled Laurent exponent. -/
theorem laurentWeightRescaling_exponent_nonneg_of_toLaurent
    (ω : ι → ℤ) (F : LaurentPolynomial (MvPolynomial ι R))
    (p : Polynomial (MvPolynomial ι R))
    (hF : laurentWeightRescaling ω F = p.toLaurent)
    (n : ℤ) (d : ι →₀ ℕ) (hd : (F.coeff n).coeff d ≠ 0) :
    0 ≤ n + Finsupp.weight ω d := by
  by_contra hn
  have hz := polynomial_toLaurent_coeff_neg p (n + Finsupp.weight ω d)
    (lt_of_not_ge hn)
  have hc := congrArg (fun f : MvPolynomial ι R => f.coeff d) hz
  rw [← hF, laurentWeightRescaling_coeff, add_sub_cancel_right] at hc
  exact hd (by simpa using hc)

/-- The least exponent of every nonzero original Laurent coefficient remains
nonnegative after the rescaling when the result is an ordinary polynomial. -/
theorem minimumSupportWeight_add_nonneg_of_toLaurent
    (ω : ι → ℤ) (F : LaurentPolynomial (MvPolynomial ι R))
    (p : Polynomial (MvPolynomial ι R))
    (hF : laurentWeightRescaling ω F = p.toLaurent)
    (n : ℤ) (hn : F.coeff n ≠ 0) :
    0 ≤ n + minimumSupportWeight ω (F.coeff n) := by
  obtain ⟨d, hd, hweight⟩ := exists_support_weight_eq_minimum ω hn
  rw [← hweight]
  exact laurentWeightRescaling_exponent_nonneg_of_toLaurent ω F p hF n d
    (by simpa only [MvPolynomial.mem_support_iff] using hd)

/-- Multiplying a normalized transform by the required nonnegative parameter
power recovers its original rescaled Laurent summand. -/
theorem weightedNormalize_mul_X_toLaurent (ω : ι → ℤ)
    (f : MvPolynomial ι R) (n : ℤ)
    (hn : 0 ≤ n + minimumSupportWeight ω f) :
    (Polynomial.X ^ (n + minimumSupportWeight ω f).toNat * weightedNormalize ω f).toLaurent =
      laurentWeightRescaling ω (LaurentPolynomial.C f * LaurentPolynomial.T n) := by
  rw [map_mul, Polynomial.toLaurent_X_pow, weightedNormalize_toLaurent,
    Int.toNat_of_nonneg hn, map_mul, laurentWeightRescaling_T]
  calc
    LaurentPolynomial.T (n + minimumSupportWeight ω f) *
        (LaurentPolynomial.T (-minimumSupportWeight ω f) *
          laurentWeightRescaling ω (LaurentPolynomial.C f)) =
      laurentWeightRescaling ω (LaurentPolynomial.C f) *
        (LaurentPolynomial.T (n + minimumSupportWeight ω f) *
          LaurentPolynomial.T (-minimumSupportWeight ω f)) := by ac_rfl
    _ = _ := by rw [← LaurentPolynomial.T_add]; simp

/-- Every normalized transform of an element of I belongs to its actual
contracted Laurent deformation. -/
theorem weightedNormalize_mem_weightedDeformationIdeal (ω : ι → ℤ)
    (I : Ideal (MvPolynomial ι R)) {f : MvPolynomial ι R} (hf : f ∈ I) :
    weightedNormalize ω f ∈ weightedDeformationIdeal ω I := by
  change (weightedNormalize ω f).toLaurent ∈
    (I.map LaurentPolynomial.C).map (laurentWeightRescaling ω).toRingHom
  rw [weightedNormalize_toLaurent]
  apply Ideal.mul_mem_left
  exact Ideal.mem_map_of_mem _ (Ideal.mem_map_of_mem _ hf)

/-- Every member of the Laurent contraction is a polynomial combination of
the normalized transforms of elements of I, with explicit finite support. -/
theorem weightedDeformationIdeal_mem_span_normalize (ω : ι → ℤ)
    (I : Ideal (MvPolynomial ι R))
    {p : Polynomial (MvPolynomial ι R)} (hp : p ∈ weightedDeformationIdeal ω I) :
    p ∈ Ideal.span (weightedNormalize ω '' (I : Set (MvPolynomial ι R))) := by
  classical
  let e := laurentWeightRescaling (R := R) ω
  change p.toLaurent ∈ (I.map LaurentPolynomial.C).map e.toRingHom at hp
  obtain ⟨F, hFI, hFp⟩ :=
    (Ideal.mem_map_iff_of_surjective e.toRingHom e.surjective).mp hp
  have hcoeff : ∀ n : ℤ, F.coeff n ∈ I :=
    (laurentPolynomial_mem_map_C_iff I F).mp hFI
  have hFp' : laurentWeightRescaling ω F = p.toLaurent := hFp
  let Q : Polynomial (MvPolynomial ι R) :=
    ∑ n ∈ F.coeff.support,
      Polynomial.X ^ (n + minimumSupportWeight ω (F.coeff n)).toNat *
        weightedNormalize ω (F.coeff n)
  have hQ : Q ∈ Ideal.span (weightedNormalize ω '' (I : Set (MvPolynomial ι R))) := by
    apply Ideal.sum_mem
    intro n hn
    apply Ideal.mul_mem_left
    exact Ideal.subset_span ⟨F.coeff n, hcoeff n, rfl⟩
  have hexpand :
      (∑ n ∈ F.coeff.support, LaurentPolynomial.C (F.coeff n) * LaurentPolynomial.T n) = F := by
    simpa only [Finsupp.sum, LaurentPolynomial.single_eq_C_mul_T] using
      AddMonoidAlgebra.sum_coeff_single F
  have hQp : Q = p := by
    apply Polynomial.toLaurent_injective
    change (∑ n ∈ F.coeff.support,
      Polynomial.X ^ (n + minimumSupportWeight ω (F.coeff n)).toNat *
        weightedNormalize ω (F.coeff n)).toLaurent = p.toLaurent
    rw [map_sum]
    calc
      (∑ n ∈ F.coeff.support,
        (Polynomial.X ^ (n + minimumSupportWeight ω (F.coeff n)).toNat *
          weightedNormalize ω (F.coeff n)).toLaurent) =
        ∑ n ∈ F.coeff.support,
          laurentWeightRescaling ω (LaurentPolynomial.C (F.coeff n) * LaurentPolynomial.T n) := by
            apply Finset.sum_congr rfl
            intro n hn
            apply weightedNormalize_mul_X_toLaurent
            exact minimumSupportWeight_add_nonneg_of_toLaurent ω F p hFp' n
              (Finsupp.mem_support_iff.mp hn)
      _ = laurentWeightRescaling ω F := by rw [← map_sum, hexpand]
      _ = p.toLaurent := hFp'
  exact hQp ▸ hQ

/-- The full deformation is generated by normalized transforms of all
elements of the original ideal, independently of any chosen generating list. -/
theorem weightedDeformationIdeal_eq_span_normalize (ω : ι → ℤ)
    (I : Ideal (MvPolynomial ι R)) :
    weightedDeformationIdeal ω I =
      Ideal.span (weightedNormalize ω '' (I : Set (MvPolynomial ι R))) := by
  apply le_antisymm
  · intro p hp
    exact weightedDeformationIdeal_mem_span_normalize ω I hp
  · apply Ideal.span_le.mpr
    rintro _ ⟨f, hf, rfl⟩
    exact weightedNormalize_mem_weightedDeformationIdeal ω I hf

/-- The full integer-weight initial ideal: it uses the least-weight component
of every element of I. -/
def weightedInitialIdeal (ω : ι → ℤ) (I : Ideal (MvPolynomial ι R)) :
    Ideal (MvPolynomial ι R) :=
  Ideal.span ((fun f => MvPolynomial.weightedHomogeneousComponent ω
    (minimumSupportWeight ω f) f) '' (I : Set (MvPolynomial ι R)))

/-- The actual zero-parameter specialization equals the full initial ideal. -/
theorem weightedDeformationSpecialization_eq_initialIdeal (ω : ι → ℤ)
    (I : Ideal (MvPolynomial ι R)) :
    weightedDeformationSpecialization ω I = weightedInitialIdeal ω I := by
  unfold weightedDeformationSpecialization weightedInitialIdeal
  rw [weightedDeformationIdeal_eq_span_normalize, Ideal.map_span, Set.image_image]
  apply congrArg Ideal.span
  apply congrArg (fun F : MvPolynomial ι R → MvPolynomial ι R =>
    F '' (I : Set (MvPolynomial ι R)))
  funext f
  exact weightedNormalize_eval_zero ω f

/-- Full integer-weight initial formation cannot decrease ideal height.
This is the scalar-weight case of the paper's Lemma height(2). -/
theorem weightedInitialIdeal_height [IsNoetherianRing R] [Finite ι]
    (ω : ι → ℤ) (I : Ideal (MvPolynomial ι R)) :
    I.height ≤ (weightedInitialIdeal ω I).height := by
  rw [← weightedDeformationSpecialization_eq_initialIdeal]
  exact weightedDeformationSpecialization_height ω I

end AbelFormalization
