import AbelFormalization.WilkieCase2RecursiveFixedMinorAlternative

/-!
# Reachable-stage Case 2 recursion

The stage predicate records exactly the maps generated by visible-coordinate
slices of a fixed original map. The recursive alternative below requires the
exceptional-set and smooth-selection inputs only at those stages.
-/

noncomputable section

namespace AbelFormalization

set_option autoImplicit false

/-- A map with `m` visible and `q` hidden coordinates. -/
abbrev WilkieCase2StageMap (m q : ℕ) :=
  ((Fin m → ℝ) × (Fin q → ℝ)) → RealEuclidean q

/-- The closure of an original map under arbitrary fixed visible-coordinate
slices. No regularity, exceptional-set, or outcome condition enters this class. -/
inductive WilkieCase2Reachable {n q : ℕ}
    (F₀ : WilkieCase2StageMap n q) :
    (m : ℕ) → WilkieCase2StageMap m q → Prop where
  | original : WilkieCase2Reachable F₀ n F₀
  | visibleSlice {m : ℕ} {G : WilkieCase2StageMap (m + 1) q}
      (hG : WilkieCase2Reachable F₀ (m + 1) G)
      (i : Fin (m + 1)) (b : ℝ) :
      WilkieCase2Reachable F₀ m
        (G ∘ wilkieCase2VisibleInsert i b)

/-- Conditional fixed-minor assembly at stages satisfying an affine-slice
closed predicate. The target `a₀` remains fixed throughout recursion. -/
theorem wilkieCase2_recursive_fixedMinorAlternative_of_predicate
    {C : EuclideanSetFamily}
    (hC : PositiveArityOMinimalWeakSetStructure C)
    {q : ℕ} (hq : 0 < q) (a₀ : RealEuclidean q)
    (P : ∀ m : ℕ, WilkieCase2StageMap m q → Prop)
    (hPslice : ∀ m (G : WilkieCase2StageMap (m + 1) q)
        (i : Fin (m + 1)) (b : ℝ),
      P (m + 1) G → P m (G ∘ wilkieCase2VisibleInsert i b))
    (hBmem : ∀ m (G : WilkieCase2StageMap (m + 1) q)
        (i : Fin (m + 1)),
      P (m + 1) G →
      {v : RealEuclidean 1 |
        v 0 ∈ Wilkie28MathlibOnly.exceptionalParameterSet
          G (fun x ↦ x.1 i) a₀} ∈ C 1)
    (hselection : ∀ m (G : WilkieCase2StageMap (m + 1) q)
        (i : Fin (m + 1)),
      P (m + 1) G → ContDiff ℝ 1 G →
      (∀ y, G y = a₀ → Function.Surjective (fderiv ℝ G y)) →
      Wilkie28MathlibOnly.SmoothSingularWitnessSelection
        G (fun x ↦ x.1 i) a₀) :
    ∀ m (G : WilkieCase2StageMap m q)
      (U : Set (RealEuclidean m)),
      P m G → ContDiff ℝ 1 G → IsOpen U → Convex ℝ U →
      (∀ y, G y = a₀ → Function.Surjective (fderiv ℝ G y)) →
      Bornology.IsBounded (wilkieCase2VisibleCylinderFiber G a₀ U) →
      (wilkieCase2VisibleCylinderFiber G a₀ U).Nonempty →
      wilkieCase2RecursiveAlternative G a₀ U := by
  intro m
  induction m with
  | zero =>
      intro F U hP hF hUopen hUconvex hregular hbounded hnonempty
      obtain ⟨y, hy⟩ := hnonempty
      let E := wilkieCase2ProductFlatEquiv 0 q
      let H := wilkieCase2Flatten F
      have hz : E y ∈ wilkieFiberOver H a₀ U := by
        rw [← wilkieCase2Flatten_cylinder_image]
        exact ⟨y, hy, rfl⟩
      have hFdiff : ∀ w, DifferentiableAt ℝ F w :=
        fun w ↦ (hF.differentiable (by simp)).differentiableAt
      have hH : ContDiff ℝ 1 H := hF.comp E.symm.contDiff
      have hHdiff : DifferentiableAt ℝ H (E y) :=
        (hH.differentiable (by simp)).differentiableAt
      have hHregular := wilkieCase2Flatten_regular F hFdiff a₀ hregular
      right
      exact ⟨E y, hz,
        wilkieZeroVisible_verticalMinor_ne_zero_of_regular
          hHdiff (hHregular (E y) hz.1)⟩
  | succ m ih =>
      intro F U hP hF hUopen hUconvex hregular hbounded hnonempty
      let E := wilkieCase2ProductFlatEquiv (m + 1) q
      let H := wilkieCase2Flatten F
      let X := wilkieCase2VisibleCylinderFiber F a₀ U
      have hFdiff : ∀ w, DifferentiableAt ℝ F w :=
        fun w ↦ (hF.differentiable (by simp)).differentiableAt
      have hH : ContDiff ℝ 1 H := hF.comp E.symm.contDiff
      have hHdiff : ∀ z ∈ wilkieFiberOver H a₀ U,
          DifferentiableAt ℝ H z := by
        intro z _
        exact (hH.differentiable (by simp)).differentiableAt
      have hHregular := wilkieCase2Flatten_regular F hFdiff a₀ hregular
      have hHbounded : Bornology.IsBounded (wilkieFiberOver H a₀ U) := by
        rw [← wilkieCase2Flatten_cylinder_image]
        exact E.lipschitzWith.isBounded_image hbounded
      obtain ⟨y, hy⟩ := hnonempty
      have hz : E y ∈ wilkieFiberOver H a₀ U := by
        rw [← wilkieCase2Flatten_cylinder_image]
        exact ⟨y, hy, rfl⟩
      by_cases hfinite : ((fun w : ((Fin (m + 1) → ℝ) ×
          (Fin q → ℝ)) ↦ w.1) '' X).Finite
      · have hfiniteFlat :
            (realEuclideanTakeLeft '' wilkieFiberOver H a₀ U).Finite := by
          rw [wilkieCase2Flatten_visible_image]
          exact hfinite
        obtain ⟨cols, η, hη, hinterval⟩ :=
          wilkieFiniteVisibleImage_sameMinor_squared_interval
            (Nat.succ_pos m) hH a₀ hUopen hHregular hHbounded
            hfiniteFlat hz
        left
        exact ⟨cols, η, hη, hinterval⟩
      · have hinfinite : ((fun w : ((Fin (m + 1) → ℝ) ×
            (Fin q → ℝ)) ↦ w.1) '' X).Infinite := hfinite
        have hbad (i : Fin (m + 1)) :
            (Wilkie28MathlibOnly.exceptionalParameterSet
              F (fun w ↦ w.1 i) a₀).Finite := by
          apply wilkie28_exceptionalCoordinateValues_finite_of_WS5_and_selection
            hC F (fun w ↦ w.1 i) a₀ hFdiff
          · intro w
            change DifferentiableAt ℝ (wilkieCase2VisiblePivot i) w
            exact (wilkieCase2VisiblePivot i).differentiableAt
          · exact hregular
          · exact hBmem m F i hP
          · exact hselection m F i hP hF hregular
        obtain ⟨i, x, hx, hb⟩ :=
          exists_fiber_point_with_good_visible_coordinate
            (fun w : ((Fin (m + 1) → ℝ) × (Fin q → ℝ)) ↦ w.1)
            hinfinite
            (fun i ↦ Wilkie28MathlibOnly.exceptionalParameterSet
              F (fun w ↦ w.1 i) a₀) hbad
        let b := x.1 i
        let F' := F ∘ wilkieCase2VisibleInsert i b
        let U' : Set (RealEuclidean m) :=
          (wilkieCase2_coordinateInsert i b) ⁻¹' U
        obtain ⟨_, hnonempty', hbounded', hUopen'⟩ :=
          wilkie_case2_visible_cylinder_slice_regular_nonempty_bounded
            F a₀ U hUopen hbounded hFdiff i b hb x hx rfl
        have hF' : ContDiff ℝ 1 F' :=
          hF.comp (wilkieCase2VisibleInsert_contDiff i b)
        have hUconvex' : Convex ℝ U' :=
          wilkieCase2VisibleSlice_convex U hUconvex i b
        have hregular' : ∀ w, F' w = a₀ →
            Function.Surjective (fderiv ℝ F' w) :=
          wilkieCase2VisibleInsert_globalRegular_of_good
            F a₀ i b hFdiff hb
        have hbounded'' : Bornology.IsBounded
            (wilkieCase2VisibleCylinderFiber F' a₀ U') := by
          simpa only [F', U', wilkieCase2VisibleCylinderFiber,
            wilkieCase2VisibleCylinderSliceFiber,
            wilkieCase2VisibleInsert, wilkieCase2_coordinateInsert,
            Function.comp_apply, Set.mem_preimage] using hbounded'
        have hnonempty'' :
            (wilkieCase2VisibleCylinderFiber F' a₀ U').Nonempty := by
          simpa only [F', U', wilkieCase2VisibleCylinderFiber,
            wilkieCase2VisibleCylinderSliceFiber,
            wilkieCase2VisibleInsert, wilkieCase2_coordinateInsert,
            Function.comp_apply, Set.mem_preimage] using hnonempty'
        have hUopen'' : IsOpen U' := hUopen'
        have hP' : P m F' := hPslice m F i b hP
        have hrec := ih F' U' hP' hF' hUopen'' hUconvex'
          hregular' hbounded'' hnonempty''
        rcases hrec with ⟨cols, η, hη, hinterval⟩ | ⟨z, hz', hminor'⟩
        · have hsliceEq := wilkieCase2Flatten_slice_eq F i b
          have hinterval' : Set.Icc (0 : ℝ) η ⊆
              (fun v ↦ (standardJacobianColumnMinor
                (H ∘ wilkieCase2FlatCastInsert i b) cols v) ^ 2) ''
                wilkieFiberOver (H ∘ wilkieCase2FlatCastInsert i b)
                  a₀ (wilkieCase2VisibleCylinderSlice i b U) := by
            simpa only [H, F', U', wilkieCase2VisibleCylinderSlice,
              wilkieCase2Flatten_slice_eq] using hinterval
          obtain ⟨_, hη', hlift⟩ :=
            wilkieCase2_cylinderSliceMinor_squared_interval_lift
              H a₀ i b U hUopen cols (Equiv.refl (Fin q))
              hHdiff hη hinterval'
          left
          exact ⟨cols.trans (wilkieCase2CylinderColumnInsert (q := q) i),
            η, hη', hlift⟩
        · have hzLower : z ∈
              wilkieFiberOver (H ∘ wilkieCase2FlatCastInsert i b)
                a₀ (wilkieCase2VisibleCylinderSlice i b U) := by
            simpa only [H, F', U', wilkieCase2VisibleCylinderSlice,
              wilkieCase2Flatten_slice_eq] using hz'
          have hzParent : wilkieCase2FlatCastInsert i b z ∈
              wilkieFiberOver H a₀ U :=
            wilkieCase2CylinderFiber_insert_image_subset H a₀ i b U
              ⟨z, hzLower, rfl⟩
          have hminorLower : standardJacobianColumnMinor
              (H ∘ wilkieCase2FlatCastInsert i b)
              (Fin.natAddEmb m) z ≠ 0 := by
            simpa only [H, F', wilkieCase2Flatten_slice_eq] using hminor'
          have hminorParent : standardJacobianColumnMinor H
              (Fin.natAddEmb (m + 1))
              (wilkieCase2FlatCastInsert i b z) ≠ 0 :=
            wilkieCase2_flatVerticalMinor_ne_zero_insert
              H i b z (hHdiff _ hzParent) hminorLower
          right
          exact ⟨wilkieCase2FlatCastInsert i b z,
            hzParent, hminorParent⟩


/-- The recursive alternative for one original map, with source inputs only
for maps reached by repeated visible-coordinate slicing. -/
theorem wilkieCase2_originalMap_fixedMinorAlternative
    {C : EuclideanSetFamily} {n q : ℕ}
    (hq : 0 < q) (F₀ : WilkieCase2StageMap n q)
    (a₀ : RealEuclidean q)
    (U : Set (RealEuclidean n))
    (hC : PositiveArityOMinimalWeakSetStructure C)
    (hBmemReachable : ∀ m (G : WilkieCase2StageMap (m + 1) q)
        (i : Fin (m + 1)),
      WilkieCase2Reachable F₀ (m + 1) G →
      {v : RealEuclidean 1 |
        v 0 ∈ Wilkie28MathlibOnly.exceptionalParameterSet
          G (fun x ↦ x.1 i) a₀} ∈ C 1)
    (hselectionReachable : ∀ m (G : WilkieCase2StageMap (m + 1) q)
        (i : Fin (m + 1)),
      WilkieCase2Reachable F₀ (m + 1) G → ContDiff ℝ 1 G →
      (∀ y, G y = a₀ → Function.Surjective (fderiv ℝ G y)) →
      Wilkie28MathlibOnly.SmoothSingularWitnessSelection
        G (fun x ↦ x.1 i) a₀)
    (hF₀ : ContDiff ℝ 1 F₀)
    (hUopen : IsOpen U) (hUconvex : Convex ℝ U)
    (hregular : ∀ y, F₀ y = a₀ →
      Function.Surjective (fderiv ℝ F₀ y))
    (hbounded : Bornology.IsBounded
      (wilkieCase2VisibleCylinderFiber F₀ a₀ U))
    (hnonempty : (wilkieCase2VisibleCylinderFiber F₀ a₀ U).Nonempty) :
    wilkieCase2RecursiveAlternative F₀ a₀ U := by
  exact wilkieCase2_recursive_fixedMinorAlternative_of_predicate
    hC hq a₀ (fun m G ↦ WilkieCase2Reachable F₀ m G)
    (fun m G i b hG ↦ WilkieCase2Reachable.visibleSlice hG i b)
    hBmemReachable hselectionReachable
    n F₀ U WilkieCase2Reachable.original
    hF₀ hUopen hUconvex hregular hbounded hnonempty

end AbelFormalization
