import AbelFormalization.CharbonnelBoundaryApproximation

#print axioms AbelFormalization.CharbonnelModulus.IsClosureBoundaryApproximation.mono_modulus
#print axioms AbelFormalization.CharbonnelModulus.ApproximatesFromAboveOnBoundedSets.mono_target
#print axioms AbelFormalization.CharbonnelModulus.IsTwoSidedApproximation.toClosureBoundaryApproximation
#print axioms AbelFormalization.CharbonnelModulus.IsClosureBoundaryApproximation.union
#print axioms AbelFormalization.CharbonnelModulus.exists_common_modulus_union
#print axioms AbelFormalization.CharbonnelModulus.isClosureBoundaryApproximation_iff_of_isClosed
#print axioms AbelFormalization.CharbonnelModulus.IsClosureBoundaryApproximation.exists_boundaryCarrier
