import AbelFormalization.HermiteRankOneClusterBackwardPropagation

open AbelFormalization
open AbelFormalization.RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary

#print axioms nonempty_individualMixedSourceCoefficientData
#print axioms individualMixedActiveValue_hasPolynomialUpperBound
#print axioms individualMixedCentralValue_hasPolynomialUpperBound
#print axioms individualMixedMainValue_hasPolynomialUpperBound
#print axioms individualMixedBeforeValue_lower_of_afterValue_lower
#print axioms individualMixedBoundaryValue_zero_lower_of_terminal
#print axioms simultaneousQuantitativeBoundaryScale_zero_eventuallyEq_individualMixedTerminal
#print axioms IndividualSimultaneousFiniteFamilyCompatibility.coordinateCompatibility
#print axioms individualMixedTerminalBoundary_lower_of_simultaneousFirstBefore_lower
#print axioms individualMixedInitialBoundary_lower_of_terminalSimultaneous_lower
