import AbelFormalization.AbelNumeratorRestrictedRegularZero
#print axioms AbelFormalization.mem_regularZeroSet_finiteExplicitGraphLift_iff
#print axioms AbelFormalization.AbelNumeratorSystemPolynomialPresentation.productToRestrictedGraphOutput_explicitGraphLiftSystem
#print axioms AbelFormalization.AbelNumeratorSystemPolynomialPresentation.differentiableAt_productLiftedNumerator_of_isAbel
#print axioms AbelFormalization.AbelNumeratorSystemPolynomialPresentation.mem_regularZeroSet_constraintMap_iff_restrictedAugmented
#print axioms AbelFormalization.IsAbel.abelNumeratorRegularZeroFinite_of_restrictedBase
#print axioms AbelFormalization.IsAbel.isZeroRegular_abelGeometricFamily_of_restrictedBase
