import AbelFormalization.HermiteRankBottomSimultaneousBoundaryBridge

#print axioms AbelFormalization.RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary.BottomTerminalSimultaneousCompatibility
#print axioms AbelFormalization.RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary.bottomSimultaneousTerminalAfterValue_lower
#print axioms AbelFormalization.RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary.bottomSimultaneousFirstBeforeValue_lower
