import AbelFormalization.CharbonnelSection5VerticalIncidence

open AbelFormalization

#print axioms AbelFormalization.polynomialSignConstructible_charbonnelVariableClosedBallRelation
#print axioms AbelFormalization.charbonnelVerticalIncidencePoint_mem_variableClosedBallRelation_iff
#print axioms AbelFormalization.literalZeroSet_charbonnelClosure_verticalIncidence_mem
#print axioms AbelFormalization.enatCard_connectedComponents_verticalImage_le_incidenceSection
#print axioms AbelFormalization.literalZeroSet_charbonnelClosure_uniformLocalVerticalComponentBound
