import AbelFormalization.WilkieSection4PartitionedEnrichedSelectorOutput

#print axioms AbelFormalization.charbonnelFiniteCellFamilyCommonRefinementProperty_of_partitioned
#print axioms AbelFormalization.exists_charbonnelPartitionedEnrichedEqualityBaseRefinement
#print axioms AbelFormalization.exists_charbonnelEnrichedLocalSelectorCoverRetained_overBase
#print axioms AbelFormalization.charbonnelFinitePartitionedEnrichedCellFamilyCommonRefinement_succ_retained
#print axioms AbelFormalization.exists_charbonnelFiniteProjectionCoherentEnrichedCellCover_succ
#print axioms AbelFormalization.compatible_target_of_compatible_enriched_relative_cover_cells
#print axioms AbelFormalization.exists_charbonnelFiniteProjectionCoherentEnrichedCellCover_of_enrichedRelativeCover
