import AbelFormalization.FiniteAnalyticNestedChangeOfGenerators
import AbelFormalization.HermiteRankPreprocessedSimultaneousQuantitativeTail

open AbelFormalization

#print axioms nestedMvPolynomialFlattening_span_le
#print axioms finiteAnalyticNestedChangeOfGeneratorsDataOfSpan
#print axioms FiniteAnalyticNestedChangeOfGeneratorsData.changeCoefficientValue_hasPolynomialUpperBound
#print axioms FiniteAnalyticNestedChangeOfGeneratorsData.eventually_targetValue_eq_sum

open AbelFormalization.RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary

#print axioms simultaneousNumericOperationJetSequence_error_superpolynomialDecay_of_hierarchy
#print axioms exists_simultaneousQuantitativeTail
#print axioms simultaneousQuantitativeReindex_tendsto_atTop
#print axioms simultaneousQuantitativePostLogScale_gt
#print axioms simultaneousReindexedTransferHierarchies
#print axioms simultaneousReindexedOperationJetSequence_error_superpolynomialDecay_of_hierarchy
#print axioms simultaneousQuantitativeSourceCoefficientValue_hasPolynomialUpperBound
#print axioms hermiteSimultaneousQuantitativeNumericData
#print axioms hermiteSimultaneousQuantitativeNumericSegmentData
#print axioms hermiteSimultaneousQuantitativeFirstBeforeValue_lower_of_terminalAfterValue_lower
