import AbelFormalization.CharbonnelSection53GlobalStratum

#print axioms AbelFormalization.charbonnelVerticalComponentBaseSupport_isCompact
#print axioms AbelFormalization.charbonnelVerticalComponentBaseSupport_isClosed
#print axioms AbelFormalization.literalZeroSet_charbonnelClosure_uniformAffineSectionComponentBound
#print axioms AbelFormalization.exists_charbonnelRelativeGlobalMaxCandidate
#print axioms AbelFormalization.charbonnelRelativeGlobalMaxCandidates_count_eq
#print axioms AbelFormalization.exists_charbonnelRelativeMinimalDefectGlobalCandidate
#print axioms AbelFormalization.charbonnelRelativeMinimalDefectGlobalCandidates_defect_eq
#print axioms AbelFormalization.charbonnelRelativeDefectiveSupportUnion_isClosed
#print axioms AbelFormalization.charbonnelSection53_noStationary_of_affineExplosion
#print axioms AbelFormalization.charbonnelSection53_ws5StationaryExclusion_of_affineExplosion
#print axioms AbelFormalization.literalZeroSet_charbonnelClosure_noStationaryNestedSequence_of_ws5Exclusion
