import AbelFormalization.TerminalTimeQuantitativeBridge

#print axioms AbelFormalization.ClusterAlgebraicReductionCertificate.centralTransferOutput_last
#print axioms AbelFormalization.finiteRealJetCentralEvaluationHom_retainedSourceHom
#print axioms AbelFormalization.ClusterAlgebraicReductionCertificate.FullCentralStepDisplayedData.nonempty_terminalLocalizationData
#print axioms AbelFormalization.ClusterAlgebraicReductionCertificate.FullCentralStepDisplayedData.terminal_lower_of_time_lower
