import AbelFormalization.FiniteAnalyticNestedCoefficientwiseEvaluation

open AbelFormalization

#print axioms analyticPolynomialGermHom_rename
#print axioms nestedMvPolynomialFlattening_monomial
#print axioms nestedMvPolynomialFlattening_eq_support_sum
#print axioms centralInitialMonomialBasis
#print axioms centralLeastWeightSupport
#print axioms coefficientwiseCentralPolynomial
#print axioms eval₂Hom_centralInitialMonomialBasis
#print axioms eval₂Hom_coefficientwiseCentralPolynomial
#print axioms centralPolynomialPhi_normalized_eq_coefficientwiseCentralPolynomial
#print axioms map_centralPolynomialPhi
#print axioms map_centralInitialMonomialBasis
#print axioms flattenedCentralMonomialBasis
#print axioms map_flattenedCentralMonomialBasis
#print axioms analyticPolynomialGermHom_map_algebraMap
#print axioms nestedMvPolynomialFlattening_C
#print axioms nestedMvPolynomialFlattening_map_C
#print axioms flattenedCentralGenerator_eq_support_sum
#print axioms nestedSupportedCoefficientValue
#print axioms eval_flattenedCentralMonomialBasis_of_central
#print axioms eventually_flattenedCentralRepresentativeEvaluation_eq_coefficientwise
#print axioms eventually_flattenedRepresentativeEvaluation_eq_coefficientwise
#print axioms FiniteAnalyticNestedChangeOfGeneratorsData.eventually_sourceValue_eq_coefficientwise
#print axioms FiniteAnalyticNestedChangeOfGeneratorsData.eventually_targetValue_eq_coefficientwise
#print axioms RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary.simultaneousSupportedCoefficientRepresentative
#print axioms RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary.simultaneousSupportedCoefficientRepresentative_germ_eq
#print axioms RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary.nestedSupportedCoefficientValue_eq_simultaneousQuantitative
#print axioms RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary.eventually_flattenedRepresentativeEvaluation_eq_simultaneousCoefficientwiseSource
