import AbelFormalization.CharbonnelSection53DeletedComponentReplacement

#print axioms AbelFormalization.charbonnelSection53_sameRank_forces_parentCollision
#print axioms AbelFormalization.charbonnelSection53_nextVerticalImage_subset_without_defectiveComponent
#print axioms AbelFormalization.charbonnelSection53_stationarySuccessor_avoids_defectiveComponent
