import AbelFormalization.OrderedClusterSimultaneousNumericQuantitativeTransfer

#print axioms AbelFormalization.RepresentativeClusterSubsequence.OrderedClusterPreprocessedAlgebraicStage.FullTransferTraceData.simultaneousBeforeValue_lower_of_afterValue_lower_numeric
#print axioms AbelFormalization.RepresentativeClusterSubsequence.OrderedClusterPreprocessedAlgebraicStage.FullTransferTraceData.simultaneousBeforeValue_lower_of_afterValue_lower_numeric_of_data
#print axioms AbelFormalization.RepresentativeClusterSubsequence.OrderedClusterPreprocessedAlgebraicStage.FullTransferTraceData.firstBeforeValue_lower_of_terminalAfterValue_lower_numeric
