import AbelFormalization.SmoothFamilyMaximalRankFiberFiniteness

#print axioms AbelFormalization.finite_connectedComponents_clopen_subtype
#print axioms AbelFormalization.reciprocalConstraintPatchHomeomorph
#print axioms AbelFormalization.reciprocalGraphConstraintSystem_constraintFDeriv_range_eq_top
#print axioms AbelFormalization.finite_connectedComponents_selectedMinorFiberPatch
#print axioms AbelFormalization.isClopen_fullFiberInSelectedMinorPatch_of_rank_le
#print axioms AbelFormalization.finite_connectedComponents_maximalRankFiberMinorPatch
#print axioms AbelFormalization.finite_connectedComponents_globalMaximalRankFiberPiece
#print axioms AbelFormalization.forall_target_finite_connectedComponents_globalMaximalRankFiberPiece
