import AbelFormalization.CharbonnelSardianProjectionRadialBranch

open AbelFormalization

#print axioms AbelFormalization.sardianProjectionRadialDenominator_append
#print axioms AbelFormalization.sardianProjectionRadialReciprocal_append_eq_iff
#print axioms AbelFormalization.mem_sardianProjectionRadialBranch_carrier_iff
#print axioms AbelFormalization.sardianProjectionRadialReciprocal_hidden_norm_le
#print axioms AbelFormalization.sardianProjectionRadialReciprocal_hidden_norm_le_of_eq
#print axioms AbelFormalization.sardianProjectionRadialReciprocal_escape
#print axioms AbelFormalization.mem_sardianProjectionRadialBranch_carrier_iff_bounded
