import AbelFormalization.CharbonnelSardianLiteralZeroLevelControls

open AbelFormalization

#print axioms AbelFormalization.exists_positive_level_close_to_zero_on_compact
#print axioms AbelFormalization.positive_squared_levels_on_short_segment
#print axioms AbelFormalization.exists_nonzero_near_literalZero_frontier
#print axioms AbelFormalization.exists_uniform_positive_level_near_frontier
#print axioms AbelFormalization.exists_literalZeroRadial_close_cutoff
#print axioms AbelFormalization.exists_literalZeroRadial_reach_cutoff
#print axioms AbelFormalization.exists_literalZeroRadial_first_level_bound
#print axioms AbelFormalization.exists_literalZeroRadial_joint_level_cutoff
#print axioms AbelFormalization.literalZeroRadialModulus
#print axioms AbelFormalization.literalZeroRadialModulus_levelControls
#print axioms AbelFormalization.charbonnelSardianLiteralZeroRadialLevelInput_of_smooth
#print axioms AbelFormalization.charbonnelSardianLiteralZeroBaseInput_of_smoothGeometric
