import AbelFormalization.CharbonnelSection5ElementaryInputs

open AbelFormalization

#print axioms AbelFormalization.polynomialSignConstructible_closedBall_zero
#print axioms AbelFormalization.literalZeroSet_charbonnelClosure_compactTruncationMembership
#print axioms AbelFormalization.UnaryPieceDecomposable.finite_of_interior_eq_empty
#print axioms AbelFormalization.PositiveArityOMinimalWeakSetStructure.charbonnelPPrime_one
#print axioms AbelFormalization.literalZeroSet_charbonnelClosure_approximationTraceSmallness_of_section5
