import AbelFormalization.OrderedClusterSimultaneousQuantitativeTransfer

#print axioms AbelFormalization.FiniteRealJetTransferHierarchies.scale_ge_two
#print axioms AbelFormalization.ClusterAlgebraicReductionCertificate.FullCentralStepDisplayedData.exists_leastWeight_bound
#print axioms AbelFormalization.ClusterAlgebraicReductionCertificate.FullCentralStepDisplayedData.realJet_source_lower_of_central_lower_direct_successor
#print axioms AbelFormalization.ClusterAlgebraicReductionCertificate.FullCentralStepDisplayedData.realJet_source_lower_of_central_lower_direct
#print axioms AbelFormalization.RepresentativeClusterSubsequence.orderedClusterSimultaneousPostLogScale_zero_eq_boundaryScale
#print axioms AbelFormalization.RepresentativeClusterSubsequence.OrderedClusterPreprocessedAlgebraicStage.coefficientSequenceHom_hasPolynomialUpperBound
#print axioms AbelFormalization.IsAbel.orderedClusterSimultaneousStep_transferHierarchies
#print axioms AbelFormalization.RepresentativeClusterSubsequence.OrderedClusterPreprocessedAlgebraicStage.FullTransferTraceData.simultaneousBeforeGenerator_lower_of_afterGenerator_lower
#print axioms AbelFormalization.RepresentativeClusterSubsequence.OrderedClusterPreprocessedAlgebraicStage.FullTransferTraceData.simultaneousBeforeGenerator_lower_of_afterGenerator_lower_of_data
#print axioms AbelFormalization.RepresentativeClusterSubsequence.OrderedClusterPreprocessedAlgebraicStage.FullTransferTraceData.firstSimultaneousBeforeGenerator_lower_of_afterGenerator_lower
#print axioms AbelFormalization.RepresentativeClusterSubsequence.OrderedClusterPreprocessedAlgebraicStage.FullTransferTraceData.extraRetainedBeforeGenerator_lower_of_afterGenerator_lower
#print axioms AbelFormalization.simultaneousCentralPreLogActiveAssignment_hasPolynomialUpperBound
#print axioms AbelFormalization.RepresentativeClusterSubsequence.OrderedClusterPreprocessedAlgebraicStage.FullTransferTraceData.simultaneousAfter_span_eq_nextBefore_span
#print axioms AbelFormalization.RepresentativeClusterSubsequence.OrderedClusterPreprocessedAlgebraicStage.FullTransferTraceData.simultaneousBeforeGenerator_lower_of_terminalAfterGenerator_lower
#print axioms AbelFormalization.RepresentativeClusterSubsequence.OrderedClusterPreprocessedAlgebraicStage.FullTransferTraceData.firstFlatBoundaryLower_of_simultaneousBeforeGenerator_lower
#print axioms AbelFormalization.RepresentativeClusterSubsequence.OrderedClusterPreprocessedAlgebraicStage.FullTransferTraceData.individualTerminalBoundaryLower_of_simultaneousBeforeGenerator_lower
#print axioms AbelFormalization.RepresentativeClusterSubsequence.OrderedClusterPreprocessedAlgebraicStage.FullTransferTraceData.individualTerminalBoundaryLower_of_terminalAfterGenerator_lower
