import AbelFormalization.CharbonnelSection53CountSaturation

open AbelFormalization

#print axioms AbelFormalization.charbonnelSection53_count_eq_of_noLocalLexDescent
#print axioms AbelFormalization.charbonnelSection53_globalCandidate_of_equalCount
#print axioms AbelFormalization.charbonnelSection53_exists_badAvoiding_globalMax_of_noDescent
#print axioms AbelFormalization.literalZeroSet_charbonnelClosure_exists_badAvoiding_globalMax_of_noDescent
