import AbelFormalization.HermiteRankTopIndividualBoundaryQuantitativeLower

open AbelFormalization
open AbelFormalization.RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary

#print axioms AbelFormalization.RepresentativeClusterSubsequence.OrderedClusterPreprocessedAlgebraicDescent.stageIdeal_eq_initial_of_eq_count
#print axioms topPrefixPaddedGeneratorAtLastCluster_span
#print axioms lastCluster_preprocessingInput_eq_topPrefixIdeal
#print axioms lastCluster_individualBoundaryZeroIdeal_eq_topPrefixIdeal
#print axioms lastCluster_individualBoundaryZero_span_le_topPrefixPadded
#print axioms topIndividualBoundaryAnalyticChange
#print axioms eventually_topIndividualBoundaryZeroValue_eq_changeTarget
#print axioms TopIndividualSelectedPaddedCompatibility
#print axioms topIndividualAnalyticSource_lower_of_mixedBoundaryZero_lower
#print axioms selectedPaddedTopPrefix_lower_of_topIndividualBoundaryZero_lower
#print axioms false_of_topIndividualBoundaryZero_lower
