import AbelFormalization.HermiteRankNonbottomClusterBackwardBridge

open AbelFormalization
open AbelFormalization.RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary

#print axioms clusterStage_next_currentIdeal_eq_current_nextIdeal
#print axioms individualBoundaryZeroIdeal_eq_nextCoefficientIdeal
#print axioms nextCoefficientFamilyFromIndividualBoundaryZero
#print axioms nonbottomCommonBalancingIndex_eq_simultaneous
#print axioms eventually_lowerInverse_lt_nextTerminalScale
#print axioms individualMixedInitialScale_le_nextTerminalScale
#print axioms nextTerminalFirstDerivative_hasScalarInversePowerLowerBound
#print axioms nextTerminalAnalyticSourceValue
#print axioms NextTerminalSourceValueCompatibility
#print axioms nextTerminalAnalyticSource_lower_of_individualMixedInitial_lower
