import AbelFormalization.LionRankPatchLocalRegularSubtupleReduction

#print axioms AbelFormalization.exists_null_badParameterSet_for_regular_fixedSlices
#print axioms AbelFormalization.exists_null_badCenters_regular_lagrangeCriticalSystem_at_target_on_regularLocus
#print axioms AbelFormalization.exists_commonCenter_regular_rankMinorLagrangeCharts_on_regularLocus
#print axioms AbelFormalization.canonicalRankMinorFiniteRegularLagrangeCover_of_localRegularSubtuplePresentations
#print axioms AbelFormalization.hasCanonicalRankMinorFiniteRegularLagrangeCoversForFamily_of_localRegularSubtuplePresentations
