import AbelFormalization.CharbonnelIntegerAffineSliceMetric

#print axioms AbelFormalization.one_le_abs_real_of_int_ne_zero
#print axioms AbelFormalization.integerAffineSliceCoefficientNorm_one_le
#print axioms AbelFormalization.isClosed_integerAffineSliceHyperplane
#print axioms AbelFormalization.integerAffineSliceHyperplane_eq_univ_of_coeff_zero
#print axioms AbelFormalization.integerAffineSliceHyperplane_eq_empty_of_coeff_zero
#print axioms AbelFormalization.integerAffineSlice_mem_thickening_of_coeff_zero_constant_zero
#print axioms AbelFormalization.no_small_integerAffineSliceLevel_of_coeff_zero_constant_ne
#print axioms AbelFormalization.integerAffineSliceCorrectAt_mem
#print axioms AbelFormalization.dist_integerAffineSliceCorrectAt_le_abs
#print axioms AbelFormalization.integerAffineSlice_mem_thickening_of_abs_lt
#print axioms AbelFormalization.integerAffineSlice_mem_thickening_of_sq_le
#print axioms AbelFormalization.exists_integerAffineSlice_sqLevel_thickening_scale
