import AbelFormalization.SeparatedDependentCoefficientwiseTrace
import AbelFormalization.OrderedClusterAlgebraicDescentTraceData
import AbelFormalization.TerminalizedClusterIterationTraceData
import AbelFormalization.IndividualCentralIdealTraceData
import AbelFormalization.FiniteFamilyFlattening

#print axioms AbelFormalization.separatedClustersBackwardTrace_of_coefficientwise_realJet_transfer_family
#print axioms AbelFormalization.separatedClustersBackwardTrace_of_realJet_transfer_family

#print axioms AbelFormalization.TerminalizedClusterCertificate.centralIterationIdeal_succ
#print axioms AbelFormalization.TerminalizedClusterCertificate.centralIterationIdeal_extraSteps
#print axioms AbelFormalization.ClusterAlgebraicReductionCertificate.centralIdealConstruction_input_eq_output
#print axioms AbelFormalization.ClusterAlgebraicReductionCertificate.FullCentralTransferData.central_span_eq_output

#print axioms AbelFormalization.individualCentralIdealBoundary_succ
#print axioms AbelFormalization.IndividualCentralIdealTraceData.retained_span_eq_boundary_succ

#print axioms AbelFormalization.RepresentativeClusterSubsequence.OrderedClusterPrefixAlgebraicDescent.stageAt
#print axioms AbelFormalization.RepresentativeClusterSubsequence.OrderedClusterPrefixAlgebraicStage.DisplayedGenerators.nonempty_backwardIdentity

#print axioms AbelFormalization.FiniteFamilyFlattening.flattenIndex_val
#print axioms AbelFormalization.FiniteFamilyFlattening.boundaryIndex_terminal_eq_initial
#print axioms AbelFormalization.FiniteFamilyFlattening.CompatibleBoundaryFamily.natFamily_succ_flattenIndex
#print axioms AbelFormalization.FiniteFamilyFlattening.orderedClusterTransferEquiv_clusterTransferIndex
