import AbelFormalization.HermiteBeforeRankPolynomialSubstitution

#check AbelFormalization.paperRankAllCoefficientCurryHom
#check AbelFormalization.hermiteBeforeRankRetainedHom
#check AbelFormalization.hermiteBeforeRankPolynomialHom
#check AbelFormalization.eval₂Hom_hermiteBeforeRankPolynomialHom

#print axioms AbelFormalization.paperRankAllCoefficientCurryHom_apply_X_free
#print axioms AbelFormalization.paperRankAllCoefficientCurryHom_apply_X_jet
#print axioms AbelFormalization.hermiteBeforeRankRetainedHom_apply_X_free
#print axioms AbelFormalization.hermiteBeforeRankRetainedHom_apply_X_jet
#print axioms AbelFormalization.hermiteBeforeRankPolynomialHom_apply_X_aux
#print axioms AbelFormalization.hermiteBeforeRankPolynomialHom_apply_X_free
#print axioms AbelFormalization.hermiteBeforeRankPolynomialHom_apply_X_jet
#print axioms AbelFormalization.eval₂Hom_extendRetainedPolynomialHom
#print axioms AbelFormalization.eval₂Hom_hermiteBeforeRankPolynomialHom
