import AbelFormalization.WilkieLionExactResidualPipeline

#print axioms AbelFormalization.charbonnelSection56CompactFiberReduction_of_closureInteriorRegularity
#print axioms AbelFormalization.charbonnelSection56CompactFiberReduction_of_maxwellMeagreSelection
#print axioms AbelFormalization.charbonnelSection57BoundedGraphReduction_of_stableClosureFiberBoundReduction
#print axioms AbelFormalization.CharbonnelStableLocalVerticalIntervalWitness.Icc_subset_fiber_of_mem_interval
#print axioms AbelFormalization.CharbonnelStableLocalVerticalIntervalWitness.fiber_encard_le_of_finite
#print axioms AbelFormalization.charbonnelSection57StableClosureFiberBoundReduction_of_openLocalization
#print axioms AbelFormalization.IsAbel.oMinimal_of_canonicalLagrange_stableGraphs_and_projectionTowers
#print axioms AbelFormalization.mainTheorem_of_canonicalLagrange_stableGraphs_and_projectionTowers
#print axioms AbelFormalization.IsAbel.oMinimal_of_canonicalLagrange_openLocalization_and_projectionTowers
#print axioms AbelFormalization.mainTheorem_of_canonicalLagrange_openLocalization_and_projectionTowers
