import AbelFormalization.CharbonnelSection53DirectDescentRank
import AbelFormalization.CharbonnelSection53CountSaturation
import AbelFormalization.CharbonnelSardianProjectionTopology

#print axioms AbelFormalization.charbonnelSection53_directLexDescent_strictlyLowersCount
#print axioms AbelFormalization.charbonnelSection53_count_eq_of_noLocalLexDescent
#print axioms AbelFormalization.charbonnelSection53_globalCandidate_of_equalCount
#print axioms AbelFormalization.charbonnelSection53_exists_badAvoiding_globalMax_of_noDescent
#print axioms AbelFormalization.literalZeroSet_charbonnelClosure_exists_badAvoiding_globalMax_of_noDescent
#print axioms AbelFormalization.realEuclideanExistentialProjection_eq_takeLeft_image
#print axioms AbelFormalization.realEuclideanExistentialProjection_closure_subset_closure
#print axioms AbelFormalization.closure_realEuclideanExistentialProjection_closure_eq
