import AbelFormalization.LionUpperNumbersCenterControl

#print axioms AbelFormalization.exists_open_target_preimages_in_of_contDiff_of_surjective_fderiv
#print axioms AbelFormalization.volume_criticalValues_eq_zero_of_contDiff
#print axioms AbelFormalization.upperNumbersControlNondegeneratePreimages_of_contDiff
#print axioms AbelFormalization.hasUniformRegularFiberBound_of_gabrielovUpperNumbers_of_contDiff
#print axioms AbelFormalization.hasUniformSquareRegularFiberBound_of_gabrielovUpperNumbers
