import AbelFormalization.OrderedClusterPrefixAlgebraicStep

#print axioms AbelFormalization.RepresentativeClusterSubsequence.nonempty_orderedClusterPrefixAlgebraicReductionCertificate
#print axioms AbelFormalization.RepresentativeClusterSubsequence.orderedClusterPrefixCurriedIdeal_height
#print axioms AbelFormalization.RepresentativeClusterSubsequence.orderedClusterPrefixAlgebraicReduction_preserves_baseHeight
