import AbelFormalization.HermiteRankPreprocessedIndividualMixedBoundary

open AbelFormalization
open AbelFormalization.RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary

#print axioms individualMixedBoundaryProcessed_succ_selected
#print axioms individualMixedBoundaryProcessed_succ_iff_of_ne
#print axioms individualHermiteBoundaryParameter_center_succ_eq_of_ne
#print axioms selectedBlockActiveAssignment_individualMixedBoundary_beforeStep
#print axioms selectedBlockActiveAssignment_individualMixedBoundary_afterStep
#print axioms individualMixedTraceJets_error_superpolynomialDecay
#print axioms individualMixedBoundarySymbolValue_hasPolynomialUpperBound
#print axioms individualMixedNumericBoundaryCompatibility
