import AbelFormalization.CharbonnelSardianRankConstructorReduction

open AbelFormalization

#print axioms AbelFormalization.CharbonnelModulus.IsClosureBoundaryApproximation.topologicalClosure
#print axioms AbelFormalization.CharbonnelSardianApproximationCertificate.topologicalClosure
#print axioms AbelFormalization.CharbonnelDescription.HasSardianApproximations.union
#print axioms AbelFormalization.CharbonnelDescription.HasSardianApproximations.topologicalClosure
#print axioms AbelFormalization.charbonnelSardianApproximationRankStep_of_constructorInputs
#print axioms AbelFormalization.CharbonnelDescription.hasSardianApproximations_of_constructorInputs
#print axioms AbelFormalization.literalZeroSet_charbonnelClosure_closedBoundaryCarrierProperty_of_constructorInputs
