import AbelFormalization.HermiteRankPreprocessedIndividualNumericData

open AbelFormalization

#print axioms RealCentralJetSubstitutionData.exp_mul_sourceJet_sub_exact_eq_error
#print axioms RealCentralJetSubstitutionData.sourceJet_eq_exact_iff_error_eq_zero
#print axioms RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary.individualQuantitativeHermite_sourceJet_eq_exact_iff_error_eq_zero
#print axioms RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary.IndividualNumericBoundaryCompatibility.boundaryLower_zero_of_last
