import AbelFormalization.CharbonnelSection5LocalVerticalStability

#print axioms AbelFormalization.exists_maximal_enat_value_of_bounded
#print axioms AbelFormalization.CharbonnelUniformLocalVerticalComponentBound.exists_maximalLocalVerticalBall
#print axioms AbelFormalization.charbonnelVerticalLastCoordinate_image_restriction
#print axioms AbelFormalization.charbonnelVerticalImageOver_isCompact
#print axioms AbelFormalization.realConnectedComponentCarrier_isCompact_of_isCompact
#print axioms AbelFormalization.realConnectedComponentCarriers_pairwiseDisjoint
#print axioms AbelFormalization.iUnion_realConnectedComponentCarrier_equiv
#print axioms AbelFormalization.exists_fin_equiv_connectedComponents_of_enatCard_eq
#print axioms AbelFormalization.surjective_charbonnelVerticalComponentInclusionMap_of_fullSupport
#print axioms AbelFormalization.enatCard_verticalComponents_le_of_fullSupport
#print axioms AbelFormalization.realConnectedComponentCarrier_subset_of_inclusionMap_eq
#print axioms AbelFormalization.CharbonnelFullSupportMaximalVerticalBall.componentCount_eq
#print axioms AbelFormalization.CharbonnelFullSupportMaximalVerticalBall.componentInclusion_bijective
#print axioms AbelFormalization.charbonnelStableLocalVerticalIntervalSeparation_of_uniformBound_of_fullSupportSelection
#print axioms AbelFormalization.CharbonnelStableLocalVerticalIntervalSeparation.intervalDecomposition
#print axioms AbelFormalization.CharbonnelStableLocalVerticalIntervalSeparation.intervals_isCompact
#print axioms AbelFormalization.CharbonnelStableLocalVerticalIntervalSeparation.existsUnique_component_in_interval
#print axioms AbelFormalization.CharbonnelStableLocalVerticalIntervalSeparation.stableComponentCount
#print axioms AbelFormalization.literalZeroSet_charbonnelClosure_stableLocalVerticalIntervalSeparation
#print axioms AbelFormalization.literalZeroSet_charbonnelClosure_stableLocalVerticalComponentCount
