import AbelFormalization.LionProperRegularCompactUpperBound

#print axioms AbelFormalization.finite_fullFiber_of_proper_regular_target
#print axioms AbelFormalization.finite_smoothRegularFiber_of_proper_regular_target
#print axioms AbelFormalization.exists_open_fullFiber_bound_of_proper_regular_center
#print axioms AbelFormalization.hasUpperNumberOfPreimagesAt_of_proper_regular_center
#print axioms AbelFormalization.exists_uniform_preimage_bound_on_compact_regular_targets
#print axioms AbelFormalization.hasUpperNumberOfPreimagesAt_of_proper_regular_target
#print axioms AbelFormalization.exists_uniform_preimage_bound_on_compact_regular_targets_of_proper
