import AbelFormalization.LionUniformPreimageReduction

#print axioms AbelFormalization.mem_nondegeneratePreimage_iff
#print axioms AbelFormalization.nondegeneratePreimage_eq_preimage_of_isRegularTargetValue
#print axioms AbelFormalization.isRegularTargetValue_iff_nondegeneratePreimage_eq_preimage
#print axioms AbelFormalization.smoothRegularFiber_eq_nondegeneratePreimage
#print axioms AbelFormalization.smoothRegularFiber_eq_preimage_of_isRegularTargetValue
#print axioms AbelFormalization.HasUpperNumberOfPreimagesAt.mono
#print axioms AbelFormalization.HasUpperNumberOfPreimagesAt.exists_open_upperNumbers
#print axioms AbelFormalization.HasUpperNumberOfPreimagesAt.enatCard_preimage_le
#print axioms AbelFormalization.hasGabrielovUniformUpperNumberProperty_iff
#print axioms AbelFormalization.hasGabrielovUniformUpperNumberProperty_of_uniformNondegeneratePreimageBound
#print axioms AbelFormalization.uniformNondegeneratePreimageBound_of_gabrielovUpperNumbers
#print axioms AbelFormalization.hasUniformRegularFiberBound_iff_uniformNondegeneratePreimageBound
#print axioms AbelFormalization.hasUniformRegularFiberBound_of_gabrielovUpperNumbers
#print axioms AbelFormalization.HasUniformRegularFiberBound.hasGabrielovUniformUpperNumberProperty
#print axioms AbelFormalization.hasUniformSquareRegularFiberBound_iff_fixed
#print axioms AbelFormalization.IsZeroRegularFunctionFamily.hasPointwiseFiniteRegularFibers
#print axioms AbelFormalization.HasUniformRegularFiberBound.hasPointwiseFiniteRegularFibers
