import AbelFormalization.HermiteRankPreprocessedSimultaneousNumericData

#print axioms AbelFormalization.RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary.FiniteMovingCoefficientData.polynomialValueAlong_hasPolynomialUpperBound
#print axioms AbelFormalization.RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary.nonempty_simultaneousSourceCoefficientData
#print axioms AbelFormalization.RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary.simultaneousSourceCoefficientValue_hasPolynomialUpperBound
#print axioms AbelFormalization.RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary.simultaneousNumericTransferHierarchies
#print axioms AbelFormalization.RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary.hermiteSimultaneousNumericQuantitativeData
#print axioms AbelFormalization.RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary.hermiteSimultaneousBeforeValue_lower_of_afterValue_lower
#print axioms AbelFormalization.RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary.hermiteSimultaneousNumericSegmentQuantitativeData
#print axioms AbelFormalization.RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary.hermiteSimultaneousFirstBeforeValue_lower_of_terminalAfterValue_lower
