import AbelFormalization.CharbonnelSection5AnalyticReduction

#print axioms AbelFormalization.charbonnelCompactPositiveVolumeInterior_of_exceptionalFiberBase
#print axioms AbelFormalization.not_mem_charbonnelPositiveZeroTrace_of_finiteVerticalGraphChartAt
#print axioms AbelFormalization.charbonnelSection5AnalyticStep_of_fiberAndGraphReductions
#print axioms AbelFormalization.IsAbel.oMinimal_of_charbonnelSourceSteps_automaticProjection_and_boundedCellCovers_and_section5Reductions
