import AbelFormalization.CharbonnelSection57GraphExtraction

open AbelFormalization

#print axioms charbonnelFiniteContinuousVerticalGraphsAlong_of_compact_closedLabels
#print axioms CharbonnelStableLocalVerticalIntervalWitness.exists_mem_fiber_interval
#print axioms CharbonnelStableLocalVerticalIntervalWitness.existsUnique_mem_fiber_interval_of_encard_le
#print axioms CharbonnelStableLocalVerticalIntervalWitness.finiteContinuousVerticalGraphsAlong_innerBall
#print axioms CharbonnelFiniteContinuousVerticalGraphsAlong.remove_zero_branch_of_trace
#print axioms charbonnelSection57BoundedGraphReduction_of_stableClosureFiberBoundReduction
