import AbelFormalization.OrderedClusterSimultaneousRealJetEvaluation

#print axioms AbelFormalization.finiteRealJetSourceEvaluationHom_eq_realJetSourceEvaluationHom
#print axioms AbelFormalization.finiteRealJetCentralEvaluationHom_eq_realJetCentralEvaluationHom
#print axioms AbelFormalization.eval₂Hom_simultaneousCentralSourceTranslation_symm_preLog
#print axioms AbelFormalization.eval₂Hom_rename_inr_simultaneousCentralPostLog
#print axioms AbelFormalization.ClusterAlgebraicReductionCertificate.FullCentralStepDisplayedData.before_span
#print axioms AbelFormalization.ClusterAlgebraicReductionCertificate.FullCentralStepDisplayedData.after_span
#print axioms AbelFormalization.ClusterAlgebraicReductionCertificate.FullCentralStepDisplayedData.eval_beforeGenerator_preLog
#print axioms AbelFormalization.ClusterAlgebraicReductionCertificate.FullCentralStepDisplayedData.eval_afterGenerator_postLog
#print axioms AbelFormalization.RepresentativeClusterSubsequence.simultaneousCentralPreLogActiveAssignment_q_eq_boundary
#print axioms AbelFormalization.RepresentativeClusterSubsequence.OrderedClusterPreprocessedAlgebraicStage.FullTransferTraceData.firstFlatBefore_span
#print axioms AbelFormalization.RepresentativeClusterSubsequence.OrderedClusterPreprocessedAlgebraicStage.FullTransferTraceData.extraRetainedBefore_span
#print axioms AbelFormalization.RepresentativeClusterSubsequence.OrderedClusterPreprocessedAlgebraicStage.FullTransferTraceData.eval_simultaneousBeforeGenerator_preLog
#print axioms AbelFormalization.RepresentativeClusterSubsequence.OrderedClusterPreprocessedAlgebraicStage.FullTransferTraceData.eval_simultaneousAfterGenerator_postLog
#print axioms AbelFormalization.RepresentativeClusterSubsequence.OrderedClusterPreprocessedAlgebraicStage.FullTransferTraceData.eval_firstSimultaneousBeforeGenerator_preLog
#print axioms AbelFormalization.RepresentativeClusterSubsequence.OrderedClusterPreprocessedAlgebraicStage.FullTransferTraceData.eval_firstSimultaneousAfterGenerator_postLog
#print axioms AbelFormalization.RepresentativeClusterSubsequence.OrderedClusterPreprocessedAlgebraicStage.FullTransferTraceData.eval_extraRetainedBeforeGenerator_preLog
#print axioms AbelFormalization.RepresentativeClusterSubsequence.OrderedClusterPreprocessedAlgebraicStage.FullTransferTraceData.eval_extraRetainedAfterGenerator_postLog
