import AbelFormalization.HermiteRankPreprocessedRealJetData

open AbelFormalization

#print axioms IsAbel.exists_fullHermiteLemmaSpec_of_commonStripFamily
#print axioms paperRankHermiteNodes_mem_hermiteNodeNeighborhood
#print axioms FullHermiteLemmaSpec.coe_paperRankRealJetSequence_sourceJet
#print axioms FullHermiteLemmaSpec.paperRankRealJetSequence_sourceJet_eq_coefficientValue
#print axioms FullHermiteLemmaSpec.paperRankRealJetSequence_error_superpolynomialDecay
#print axioms FullHermiteLemmaSpec.paperRankRealJetTailSequence_error_superpolynomialDecay
#print axioms RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary.individualRealJetSequence_sourceJet_eq_coefficientValue
#print axioms RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary.individualRealJetSequence_error_superpolynomialDecay_of_hierarchy
#print axioms RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary.individualRealJetSequence_sourceJet_hasPolynomialUpperBound_of_domination
#print axioms RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary.individualTransferCoordinateError_superpolynomialDecay_of_hierarchy
#print axioms RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary.simultaneousRealJetSequence_sourceJet_eq_coefficientValue
#print axioms RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary.simultaneousRealJetSequence_error_superpolynomialDecay_of_hierarchy
#print axioms RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary.simultaneousRealJetSequence_sourceJet_hasPolynomialUpperBound_of_domination
#print axioms RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary.simultaneousTransferCoordinateError_superpolynomialDecay_of_hierarchy
