import AbelFormalization.HermiteRankTopPrefixSequenceBoundary

#print axioms AbelFormalization.RepresentativeClusterSubsequence.paperRankHermiteTopPrefixPaddedFamily_spec
#print axioms AbelFormalization.IsAbel.exists_restrictedBaseHermiteRankTopPrefixSequenceBoundary
