import AbelFormalization.HermiteRankIndividualSimultaneousBoundaryCompatibility

#print axioms AbelFormalization.RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary.individualMixedBoundaryProcessed_terminal_finalBlock_iff
#print axioms AbelFormalization.RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary.individualMixedTerminalParameterOnSimultaneousTail_eq
#print axioms AbelFormalization.RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary.individualMixedTerminalFinalActiveValue_eq_simultaneousFirstMixed
#print axioms AbelFormalization.RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary.individualMixedTerminalCoefficientValue_eventuallyEq_simultaneousFirst
#print axioms AbelFormalization.RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary.simultaneousQuantitativeBoundaryScale_zero_tendsto_atTop
#print axioms AbelFormalization.RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary.simultaneousQuantitativeBoundaryScale_zero_eventuallyEq_individualMixedTerminal
#print axioms AbelFormalization.RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary.individualSimultaneousBoundaryCompatibility
