import AbelFormalization.CharbonnelSardianApproximationCertificate

#print axioms AbelFormalization.CharbonnelSardianApproximationCertificate.carrier_isProjectedZeroSet
#print axioms AbelFormalization.CharbonnelSardianApproximationCertificate.carrier_mem_literalZeroSet_charbonnelClosure
#print axioms AbelFormalization.CharbonnelSardianApproximationCertificate.exists_rank_one_description
#print axioms AbelFormalization.CharbonnelSardianApproximationCertificate.carrier_interior_eq_empty
#print axioms AbelFormalization.CharbonnelSardianApproximationCertificate.exists_closed_emptyInterior_boundaryCarrier
