import AbelFormalization.GeneralCodimensionLagrangeGenericMorse

#print axioms AbelFormalization.lagrangePrimalProjectionCLM_apply
#print axioms AbelFormalization.lagrangeStationarityEquation_standardSquaredDistance_apply
#print axioms AbelFormalization.lagrangeSquaredDistanceCriticalFamily_castAdd
#print axioms AbelFormalization.lagrangeSquaredDistanceCriticalFamily_natAdd
#print axioms AbelFormalization.lagrangeSquaredDistanceCriticalFamilyCenterDerivative_castAdd
#print axioms AbelFormalization.lagrangeSquaredDistanceCriticalFamilyCenterDerivative_natAdd
#print axioms AbelFormalization.hasStrictFDerivAt_lagrangeSquaredDistanceCriticalFamily_center
#print axioms AbelFormalization.contDiff_lagrangeSquaredDistanceCriticalFamily
#print axioms AbelFormalization.lagrangeSquaredDistanceCriticalFamily_fixed_center
#print axioms AbelFormalization.fderiv_lagrangeSquaredDistanceCriticalFamily_fixed_center
#print axioms AbelFormalization.lagrangeSquaredDistanceCriticalFamily_fderiv_range_eq_top
#print axioms AbelFormalization.exists_standardSquaredDistanceCenter_regular_lagrangeCriticalSystem
#print axioms AbelFormalization.IsEverywhereSmoothFunctionFamily.exists_standardSquaredDistanceCenter_regular_lagrangeCriticalSystem
