import AbelFormalization.CharbonnelSection53RelativeLexDescent

#print axioms AbelFormalization.charbonnelRelativeClosedBall_nonempty
#print axioms AbelFormalization.charbonnelRelativeClosedBall_isClosed
#print axioms AbelFormalization.charbonnelRelativeClosedBall_isCompact
#print axioms AbelFormalization.charbonnelRelativeClosedBall_subset_base
#print axioms AbelFormalization.charbonnelVerticalImageOver_relativeBall_eq_ambient
#print axioms AbelFormalization.charbonnelVerticalImageOver_relativeBall_isCompact
#print axioms AbelFormalization.CharbonnelUniformLocalVerticalComponentBound.relative_of_baseSupported
#print axioms AbelFormalization.literalZeroSet_charbonnelClosure_relativeUniformLocalVerticalComponentBound
#print axioms AbelFormalization.CharbonnelRelativeLocalMaxCandidate.fullSupport_of_defect_zero
#print axioms AbelFormalization.exists_charbonnelRelativeLocalMaxCandidate
#print axioms AbelFormalization.exists_fullSupport_relativeLocalMaxCandidate_of_strictLexRefinement
#print axioms AbelFormalization.CharbonnelRelativeLocalMaxCandidate.stableIntervalSeparation_of_defect_zero
#print axioms AbelFormalization.literalZeroSet_charbonnelClosure_relativeStableLocalVerticalIntervalSeparation
