import AbelFormalization.FiniteAnalyticChangeOfGenerators

#print axioms AbelFormalization.nonempty_finiteAnalyticChangeOfGeneratorsData
#print axioms AbelFormalization.finiteAnalyticChangeOfGeneratorsDataOfSpan
#print axioms AbelFormalization.FiniteAnalyticChangeOfGeneratorsData.coefficientValue_hasPolynomialUpperBound
#print axioms AbelFormalization.FiniteAnalyticChangeOfGeneratorsData.coefficientValue_hasUniformPolynomialUpperBound
#print axioms AbelFormalization.FiniteAnalyticChangeOfGeneratorsData.eventually_targetValue_eq_sum
#print axioms AbelFormalization.FiniteAnalyticChangeOfGeneratorsData.sourceValue_lower_of_targetValue_lower
