import AbelFormalization.HermiteRankTopIndividualBoundaryCompatibility

open AbelFormalization
open AbelFormalization.RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary

#print axioms clusterPrefixParameter_zero_eq_selectedTranslated_of_pos
#print axioms individualHermiteBoundaryParameter_zero_on_commonTail_eventuallyEq
#print axioms individualMixedBoundarySymbolValue_zero_eventuallyEq_hermite
#print axioms paperRankHermiteTopPrefixSymbolEquiv_eq_direct
#print axioms paperRankHermiteTopPrefixSymbolEquiv_apply_free
#print axioms paperRankHermiteTopPrefixSymbolEquiv_apply_positiveDerivative
#print axioms paperRankHermiteTopPrefixSymbolEquiv_apply_time
#print axioms paperRankHermitePrefixValue_top_eq_topPrefixValue
#print axioms selectedTopPrefixSequenceValue_eq_topPrefixAssignment
#print axioms orderedClusterPrefixAssignment_transport_congr
#print axioms topIndividualBoundarySymbolValueOnCommonTail_eventuallyEq_selected
#print axioms topPrefixPaddedGeneratorAtIndex_germ
#print axioms eventually_topIndividualChangeSourceRepresentative_eq_padded
#print axioms eval_transport_orderedClusterPrefix
#print axioms topIndividualSelectedPaddedCompatibility
#print axioms nonempty_topIndividualSelectedPaddedCompatibility
#print axioms selectedPaddedTopPrefix_lower_of_topIndividualBoundaryZero_lower_auto
#print axioms false_of_topIndividualBoundaryZero_lower_auto
