import AbelFormalization.LionUniformRegularFiberEncoding

#print axioms AbelFormalization.enatCard_connectedComponents_le_lifts
#print axioms AbelFormalization.enatCard_connectedComponents_le_lifted_componentMinimizers
#print axioms AbelFormalization.enatCard_connectedComponents_le_of_lifted_componentMinimizers_bound
#print axioms AbelFormalization.mem_preimage_parameterRecordingMap_singleton
#print axioms AbelFormalization.parameterRecordingCLM_apply
#print axioms AbelFormalization.surjective_parameterRecordingCLM_of_surjective_fstPartial
#print axioms AbelFormalization.hasFDerivAt_parameterRecordingMap
#print axioms AbelFormalization.fderiv_parameterRecordingMap
#print axioms AbelFormalization.surjective_fderiv_parameterRecordingMap_of_surjective_fstPartial
#print axioms AbelFormalization.FixedSquareRegularFiberComponentEncoding.enatCard_le_regularFiber
#print axioms AbelFormalization.FixedSquareRegularFiberComponentEncoding.finite_connectedComponents
#print axioms AbelFormalization.FixedSquareRegularFiberComponentEncoding.exists_uniform_component_bound
#print axioms AbelFormalization.HasUniformSquareRegularFiberBound.isZeroRegularFunctionFamily
