import AbelFormalization.OrderedClusterIndividualRealJetEvaluation

open AbelFormalization

#print axioms selectedBlockActiveAssignment_joined
#print axioms selectedBlockCoefficientAssignment_joined
#print axioms RepresentativeClusterSubsequence.orderedClusterIndividualPostLogScale_apply
#print axioms RepresentativeClusterSubsequence.orderedClusterIndividualPostLogScale_apply_of_plan
#print axioms RepresentativeClusterSubsequence.selectedBlockActiveAssignment_orderedClusterIndividualPreLog
#print axioms RepresentativeClusterSubsequence.selectedBlockActiveAssignment_orderedClusterIndividualPostLog
#print axioms RepresentativeClusterSubsequence.orderedClusterIndividualPreLogFlatAssignment_eq_base
#print axioms RepresentativeClusterSubsequence.selectedBlockCoefficientEvaluationHom_orderedClusterIndividualPreLog
#print axioms RepresentativeClusterSubsequence.selectedBlockCoefficientEvaluationHom_orderedClusterIndividualPostLog
#print axioms RepresentativeClusterSubsequence.orderedClusterIndividualPreLog_selected_q
#print axioms RepresentativeClusterSubsequence.OrderedClusterIndividualDisplayedTraceData.eval_beforeGenerator_preLog
#print axioms RepresentativeClusterSubsequence.OrderedClusterIndividualDisplayedTraceData.eval_afterGenerator_postLog
