import AbelFormalization.CharbonnelSardianIntegerAffineSliceSections

#print axioms AbelFormalization.literalZeroRadialReciprocal_exists_iff_visible_bound
#print axioms AbelFormalization.mem_wilkieAffineSliceConstituent_carrier_iff_witnesses
#print axioms AbelFormalization.mem_wilkieAffineSliceConstituent_carrier_iff_bounded_section
#print axioms AbelFormalization.wilkieAffineSliceConstituent_section_eq
