import AbelFormalization.CharbonnelSardianCertificatePadding

open AbelFormalization

#print axioms AbelFormalization.charbonnelParameterPad_refl
#print axioms AbelFormalization.mem_charbonnelParameterPad_appendLastParameter_iff
#print axioms AbelFormalization.CharbonnelPaddedSardianConstituent.carrier_succPad
#print axioms AbelFormalization.CharbonnelFiniteSardianFamily.carrier_succPad
#print axioms AbelFormalization.CharbonnelModulus.isBounded_appendUnit_iff
#print axioms AbelFormalization.CharbonnelModulus.IsClosureBoundaryApproximation.succParameterPad
#print axioms AbelFormalization.CharbonnelSardianApproximationCertificate.AtHiddenArity.succPad
#print axioms AbelFormalization.CharbonnelSardianApproximationCertificate.AtHiddenArity.padTo
#print axioms AbelFormalization.CharbonnelSardianApproximationCertificate.AtHiddenArity.unionPadded
#print axioms AbelFormalization.CharbonnelSardianApproximationCertificate.unionOfAnyHiddenArity
