import AbelFormalization.CharbonnelSemiClosed

#print axioms AbelFormalization.realEuclideanCoordinateReindex_symm_apply
#print axioms AbelFormalization.realEuclideanCoordinateReindex_finAddAssoc_symm_append
#print axioms AbelFormalization.mem_charbonnelWitnessReassociation_append_iff
#print axioms AbelFormalization.realEuclideanExistentialProjection_witnessReassociation
#print axioms AbelFormalization.realEuclideanExistentialProjection_zero
#print axioms AbelFormalization.realEuclideanExistentialProjection_union
#print axioms AbelFormalization.realEuclideanExistentialProjection_product_univ
#print axioms AbelFormalization.realEuclideanExistentialProjection_inter_product_univ
#print axioms AbelFormalization.isClosed_realEuclideanSetProduct
#print axioms AbelFormalization.isClosed_charbonnelWitnessReassociation
#print axioms AbelFormalization.mem_charbonnelWitnessPad_append_iff
#print axioms AbelFormalization.charbonnelWitnessPad_zero
#print axioms AbelFormalization.realEuclideanExistentialProjection_witnessPad
#print axioms AbelFormalization.isClosed_charbonnelWitnessPad
#print axioms AbelFormalization.PositiveArityWeakSetStructure.exists_witnessPad_description
#print axioms AbelFormalization.PositiveArityWeakSetStructure.exists_closed_projection_padding
#print axioms AbelFormalization.PositiveArityWeakSetStructure.exists_closed_projection_description
#print axioms AbelFormalization.PositiveArityWeakSetStructure.charbonnelClosure_semiClosed
