import AbelFormalization.CharbonnelComplementPipeline

#print axioms AbelFormalization.literalZeroSet_charbonnelClosure_positiveArityOMinimalWeakSetStructure
#print axioms AbelFormalization.literalZeroSet_charbonnelClosure_approximationTraceTameness_of_section5Inputs
#print axioms AbelFormalization.literalZeroSet_charbonnelClosure_complementPipelineInputs
#print axioms AbelFormalization.CharbonnelDescription.hasSardianApproximations_of_rankStep
#print axioms AbelFormalization.CharbonnelSardianApproximationCertificate.exists_closed_emptyInterior_boundaryCarrier_of_section5Inputs
#print axioms AbelFormalization.CharbonnelDescription.exists_closed_emptyInterior_boundaryCarrier_of_rankStep
#print axioms AbelFormalization.literalZeroSet_charbonnelClosure_exists_closed_emptyInterior_boundaryCarrier
#print axioms AbelFormalization.literalZeroSet_charbonnelClosure_closedBoundaryCarrierProperty
#print axioms AbelFormalization.positiveArityEuclideanSetFamilyCompletion_of_pos
#print axioms AbelFormalization.positiveArityEuclideanSetFamilyCompletion_zero
#print axioms AbelFormalization.projectedZeroComplementEnvelope_of_literalZeroSet_charbonnelClosure_compl
#print axioms AbelFormalization.projectedZeroComplementEnvelope_of_charbonnelApproximation_and_cellAssembly
