import AbelFormalization.WilkieLionSourceExactResidualPipeline
import AbelFormalization.CharbonnelSection53RankOneBase
import AbelFormalization.CharbonnelSection57OpenBaseRelativeBridge
import AbelFormalization.WilkieSection4GraphInduction

#check AbelFormalization.IsAbel.hasUniformFiberFiniteness
#check AbelFormalization.IsAbel.oMinimal_of_stableGraphs_and_projectionTowers
#check AbelFormalization.IsAbel.oMinimal_of_openLocalization_and_projectionTowers
#check AbelFormalization.mainTheorem_of_openLocalization_and_projectionTowers

#print axioms AbelFormalization.hasUniformFiberFiniteness_of_standingFamilyHypotheses
#print axioms AbelFormalization.IsAbel.hasUniformFiberFiniteness
#print axioms AbelFormalization.IsAbel.oMinimal_of_stableGraphs_and_projectionTowers
#print axioms AbelFormalization.IsAbel.oMinimal_of_openLocalization_and_projectionTowers
#print axioms AbelFormalization.mainTheorem_of_openLocalization_and_projectionTowers
#print axioms AbelFormalization.charbonnelSection53_noStationary_of_globalCount_one
#print axioms AbelFormalization.literalZeroSet_charbonnelClosure_exists_stableClosureWitness_inside_open_of_strictLexRefinement
#print axioms AbelFormalization.exists_stableLocalVerticalIntervalWitness_inside_open_of_openBaseBound_of_strictLexRefinement
#print axioms AbelFormalization.wilkieSection4_graphInductionDatum
