import AbelFormalization.TerminalLocalizationAnalyticAdapter

#print axioms AbelFormalization.analyticPolynomialGermHom_terminalFirstDerivativeProduct
#print axioms AbelFormalization.TerminalGeneratorBackwardIdentity.nonempty_analyticRepresentativeData
#print axioms AbelFormalization.TerminalGeneratorBackwardIdentity.AnalyticRepresentativeData.eventually_numeric_identity
#print axioms AbelFormalization.TerminalGeneratorBackwardIdentity.AnalyticRepresentativeData.terminalValue_lower_of_contractedValue_lower
