import AbelFormalization.RestrictedPairMergeDenominatorClearedRegularZero
#print axioms AbelFormalization.restrictedPairMergeExceptionalCommonJetGenerators_eq_common
#print axioms AbelFormalization.restrictedPairMergeExceptionalFiniteGraphLift_mem_commonJetDomain
#print axioms AbelFormalization.IsAbel.differentiableAt_constraintMap_restrictedPairMergeDenominatorClearedAugmented
#print axioms AbelFormalization.fderiv_coordinatewise_mul_at_zero_of_source
#print axioms AbelFormalization.mem_regularZeroSet_coordinatewise_mul_of_source_iff
#print axioms AbelFormalization.IsAbel.restrictedPairMergeDenominatorClearedCompressedEquation_on_graphLift_eq_scale_mul
#print axioms AbelFormalization.IsAbel.mem_regularZeroSet_denominatorCleared_graphSubstitution_iff
