import AbelFormalization.CharbonnelSardianProjectionConstituentAlgebra

open AbelFormalization

#print axioms AbelFormalization.sardianProjectionOldTuple_inFamily
#print axioms AbelFormalization.sardianProjectionRadialDenominator_pos
#print axioms AbelFormalization.sardianProjectionRadialDenominator_mem
#print axioms AbelFormalization.sardianProjectionRadialReciprocal_mem
#print axioms AbelFormalization.sardianProjectionLastEquation_mem
#print axioms AbelFormalization.sardianProjectionAlgebraicConstituent
#print axioms AbelFormalization.sardianProjectionAlgebraicConstituent_equation_castSucc
#print axioms AbelFormalization.sardianProjectionAlgebraicConstituent_equation_last
#print axioms AbelFormalization.mem_sardianProjectionAlgebraicConstituent_carrier_iff
#print axioms AbelFormalization.sardianProjectionAlgebraicFamily
#print axioms AbelFormalization.sardianProjectionAlgebraicFamily_isProjectedZeroSet
