import AbelFormalization.CharbonnelClosureNullityWitnesses

open AbelFormalization

#print axioms literalZeroSet_charbonnelClosure_semiClosed
#print axioms literalZeroSet_charbonnelClosure_liftCylinder_mem
#print axioms charbonnelClosureNullityCarrier_eq_projection
#print axioms literalZeroSet_charbonnelClosure_nullityCarrier_mem
#print axioms isClosed_charbonnelClosureNullityCarrierAtLeast
#print axioms charbonnelClosureNullityCarrier_relativelyClosed
#print axioms volume_dropLast_preimage_eq_zero
#print axioms volume_charbonnelClosureNullityCarrier_eq_zero
#print axioms charbonnelAppendLastCoordinate_zero_mem_closure_nullityCarrier
#print axioms charbonnelPositiveZeroTrace_nullityCarrier
#print axioms literalZeroSet_charbonnelClosure_nullityWitness
#print axioms literalZeroSet_charbonnelClosure_hasClosureNullityWitnesses
#print axioms literalZeroSet_charbonnelClosure_approximationTraceSmallness_of_section5Inputs
