import AbelFormalization.OrderedClusterPreprocessedAlgebraicDescentTraceData

open AbelFormalization

#print axioms AbelFormalization.RepresentativeClusterSubsequence.OrderedClusterPreprocessedAlgebraicDescent.nonempty_fullTransferTraceData
#print axioms AbelFormalization.RepresentativeClusterSubsequence.OrderedClusterPreprocessedAlgebraicDescent.operationAt_individual
#print axioms AbelFormalization.RepresentativeClusterSubsequence.OrderedClusterPreprocessedAlgebraicDescent.operationAt_firstSimultaneous
#print axioms AbelFormalization.RepresentativeClusterSubsequence.OrderedClusterPreprocessedAlgebraicDescent.operationAt_extraRetained
#print axioms AbelFormalization.RepresentativeClusterSubsequence.OrderedClusterPreprocessedAlgebraicDescent.totalTransferCount_eq_sum
#print axioms AbelFormalization.RepresentativeClusterSubsequence.OrderedClusterPreprocessedAlgebraicDescent.FullTransferTraceData.operationViewAt_individual
#print axioms AbelFormalization.RepresentativeClusterSubsequence.OrderedClusterPreprocessedAlgebraicDescent.FullTransferTraceData.operationViewAt_firstSimultaneous
#print axioms AbelFormalization.RepresentativeClusterSubsequence.OrderedClusterPreprocessedAlgebraicDescent.FullTransferTraceData.operationViewAt_extraRetained
