import AbelFormalization.HermiteRankBottomTerminalSimultaneousCompatibility

open AbelFormalization
open AbelFormalization.RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary

#print axioms nestedMvPolynomialFlattening_rename_map_of_C_comp
#print axioms nestedMvPolynomialFlattening_rename_inr_map_of_C_comp
#print axioms nestedMvPolynomialFlattening_rename_inr_map_isEmpty
#print axioms bottomTerminalSimultaneousVariableEmbedding
#print axioms bottomTerminalSimultaneousFlattenedGenerator_eq
#print axioms bottomTerminalSimultaneousTerminalTarget_eq_embeddedGenerator
#print axioms bottomTerminalSourceRepresentativeInSimultaneousVariables
#print axioms bottomTerminalSourceRepresentativeInSimultaneousVariables_germ_eq
#print axioms eventually_bottomTerminalSourceRepresentative_eq_simultaneousTerminal
#print axioms bottomTerminalParameter_simultaneousQuantitativeReindex_eq
#print axioms bottomTerminalSymbolValue_eq_simultaneousTerminalAfter
#print axioms bottomTerminalSimultaneousQuantitativeCompatibility
#print axioms bottomSimultaneousQuantitativeTerminalAfterValue_lower_auto
#print axioms bottomSimultaneousQuantitativeFirstBeforeValue_lower_auto
