import AbelFormalization.HermiteRankBottomNumericQuantitativeSeed

#print axioms AbelFormalization.hasInversePowerLowerBound_of_nonzeroPolynomial_linearCombination
#print axioms AbelFormalization.RepresentativeClusterSubsequence.PaddedIdealGeneratorFamily.spanCoefficientOfMem
#print axioms AbelFormalization.RepresentativeClusterSubsequence.PaddedIdealGeneratorFamily.sum_spanCoefficientOfMem_mul_generator
#print axioms AbelFormalization.RepresentativeClusterSubsequence.PaperRankHermiteTopPrefixPreprocessedTraceData.bottomTimeSpanCoefficient
#print axioms AbelFormalization.RepresentativeClusterSubsequence.PaperRankHermiteTopPrefixPreprocessedTraceData.bottomEmbedding_eq_sum_spanCoefficient
#print axioms AbelFormalization.RepresentativeClusterSubsequence.PaperRankHermiteTopPrefixPreprocessedTraceData.bottomTimeLower_of_numeric_identity
#print axioms AbelFormalization.RepresentativeClusterSubsequence.PaperRankHermiteTopPrefixPreprocessedTraceData.nonempty_bottomTimeSpanCoefficientRepresentatives
#print axioms AbelFormalization.RepresentativeClusterSubsequence.PaperRankHermiteTopPrefixPreprocessedTraceData.bottomTimeLower_of_analytic_spanCoefficientRepresentatives
#print axioms AbelFormalization.RepresentativeClusterSubsequence.PaperRankHermiteTopPrefixPreprocessedTraceData.bottomLastCentralLower_of_numeric_identities
#print axioms AbelFormalization.RepresentativeClusterSubsequence.PaperRankHermiteTopPrefixPreprocessedTraceData.bottomLastCentralLower_of_analytic_bottomCoefficients
