import AbelFormalization.CharbonnelSection57InfiniteFiberBridge

open AbelFormalization

#print axioms CharbonnelStableLocalVerticalIntervalWitness.Icc_subset_fiber_of_mem_interval
#print axioms CharbonnelStableLocalVerticalIntervalWitness.fiber_encard_le_of_finite
#print axioms charbonnelSection57StableClosureFiberBoundWitness_of_stable_off_infiniteFiberLocusClosure
#print axioms charbonnelSection57StableClosureFiberBoundReduction_of_openLocalization
#print axioms charbonnelSection57StableClosureFiberBoundReduction_of_maxwellMeagreSelection_and_openLocalization
#print axioms charbonnelSection57BoundedGraphReduction_of_openLocalization
