import AbelFormalization.CharbonnelCompactRadialIntegerAffineSliceBelow

#print axioms AbelFormalization.exists_compactRadial_integerAffineSlice_below_scales_of_nonzero
#print axioms AbelFormalization.exists_compactRadial_integerAffineSlice_below_scales_of_zero_zero
#print axioms AbelFormalization.exists_compactRadial_integerAffineSlice_below_scales_of_zero_nonzero
#print axioms AbelFormalization.exists_compactRadial_integerAffineSlice_below_scales
#print axioms AbelFormalization.exists_compactRadial_integerAffineSlice_section_below_scales
