import AbelFormalization.CharbonnelSardianProjectionFromBelowAssembly

open AbelFormalization

#print axioms AbelFormalization.sardianProjectionParameterPrefix_eq_init
#print axioms AbelFormalization.CharbonnelModulus.isBounded_appendUnit_sardianProjectionParameterPrefix
#print axioms AbelFormalization.approximatesFromBelow_sardianProjectionAlgebraicPaddedFamily
#print axioms AbelFormalization.approximatesFromBelow_sardianProjectionAlgebraicPaddedFamily_of_certificate
