import AbelFormalization.OrderedClusterBottomPolynomial
#print axioms AbelFormalization.RepresentativeClusterSubsequence.exists_bottom_certificate_height
#print axioms AbelFormalization.RepresentativeClusterSubsequence.exists_bottom_timePolynomial
