import AbelFormalization.HermiteRankBottomTerminalQuantitativeLower

open AbelFormalization
open AbelFormalization.RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary

#print axioms bottomTerminalScale_simultaneousQuantitativeReindex_eq
#print axioms BottomTerminalSimultaneousQuantitativeCompatibility
#print axioms bottomSimultaneousQuantitativeTerminalAfterValue_lower
#print axioms bottomSimultaneousQuantitativeFirstBeforeValue_lower
