import AbelFormalization.CharbonnelSection56InfiniteFiberLocus

#print axioms AbelFormalization.charbonnelVerticalFiber_finite_of_not_mem_infiniteLocus
#print axioms AbelFormalization.charbonnelInfiniteVerticalFiberLocus_interior_lift_of_ws5
#print axioms AbelFormalization.infinite_maxwellScalarFiber_iff_encard_ge_succ_of_component_bound
#print axioms AbelFormalization.infiniteVerticalFiberLocus_eq_cardinalityAtLeast_succ_of_component_bound
#print axioms AbelFormalization.charbonnelInfiniteVerticalFiberLocus_mem_charbonnelClosure_of_ws5
#print axioms AbelFormalization.charbonnelSection56InfiniteFiberLocusReduction_of_regularity
#print axioms AbelFormalization.charbonnelSection56InfiniteFiberLocusReduction_of_locallyClosed
#print axioms AbelFormalization.charbonnelSection56CompactFiberReduction_of_infiniteFiberLocus
#print axioms AbelFormalization.charbonnelSection5AnalyticStep_of_infiniteFiberLocusRegularity_and_graphReduction
#print axioms AbelFormalization.charbonnelSection5AnalyticStep_of_infiniteFiberLocusLocallyClosed_and_graphReduction
#print axioms AbelFormalization.IsAbel.oMinimal_of_charbonnelSourceSteps_automaticProjection_and_boundedCellCovers_and_infiniteFiberLocusRegularity
#print axioms AbelFormalization.IsAbel.oMinimal_of_charbonnelSourceSteps_automaticProjection_and_boundedCellCovers_and_infiniteFiberLocusLocallyClosed
