import AbelFormalization.CharbonnelSardianIntegerAffineSliceLift

#print axioms AbelFormalization.wilkieAffineSliceExtraInputLinearMap_append
#print axioms AbelFormalization.wilkieAffineSliceOldEquationLift_mem
#print axioms AbelFormalization.wilkieAffineSliceOldEquationLift_append
#print axioms AbelFormalization.wilkieAffineSliceRadialEquationLift_mem
#print axioms AbelFormalization.wilkieAffineSliceRadialEquationLift_append
#print axioms AbelFormalization.wilkieAffineSliceLevelEquationLift_mem
#print axioms AbelFormalization.wilkieAffineSliceLevelEquationLift_append
#print axioms AbelFormalization.wilkiePrependTwoParameters_radial
#print axioms AbelFormalization.wilkiePrependTwoParameters_slice
#print axioms AbelFormalization.wilkiePrependTwoParameters_old
#print axioms AbelFormalization.wilkiePrependTwoParameters_pos_iff
#print axioms AbelFormalization.wilkieAffineSliceConstituent_equation_radial
#print axioms AbelFormalization.wilkieAffineSliceConstituent_equation_level
#print axioms AbelFormalization.wilkieAffineSliceConstituent_equation_old
#print axioms AbelFormalization.CharbonnelPaddedSardianConstituent.wilkieAffineSliceLift
#print axioms AbelFormalization.CharbonnelFiniteSardianFamily.wilkieAffineSliceLift
