import AbelFormalization.HermiteRankCanonicalSeparatedContradiction

open AbelFormalization

#print axioms IsAbel.restrictedAllUnboundedNormalizedSeparatedContradiction
#print axioms IsAbel.restrictedBaseRegularZeroFiniteForRepresentativeCount_all_of_canonicalBackwardPropagation
#print axioms IsAbel.abelNumeratorRegularZeroFinite_of_canonicalBackwardPropagation
#print axioms IsAbel.isZeroRegular_abelGeometricFamily_of_canonicalBackwardPropagation
