import AbelFormalization.HermiteRankBottomAnalyticChangeQuantitativeSeed

#print axioms AbelFormalization.analyticPolynomialGermHom_scalarUnivariateEmbedding
#print axioms AbelFormalization.RepresentativeClusterSubsequence.PaperRankHermiteTopPrefixPreprocessedTraceData.bottomPolynomialTargetOverGerms_eq_sum
#print axioms AbelFormalization.RepresentativeClusterSubsequence.PaperRankHermiteTopPrefixPreprocessedTraceData.bottomPolynomialTarget_span_le
#print axioms AbelFormalization.RepresentativeClusterSubsequence.PaperRankHermiteTopPrefixPreprocessedTraceData.bottomTargetRepresentative_eventually_eq
#print axioms AbelFormalization.RepresentativeClusterSubsequence.PaperRankHermiteTopPrefixPreprocessedTraceData.bottomTargetValue_lower
#print axioms AbelFormalization.RepresentativeClusterSubsequence.PaperRankHermiteTopPrefixPreprocessedTraceData.bottomTimeSourceValue_lower
#print axioms AbelFormalization.RepresentativeClusterSubsequence.PaperRankHermiteTopPrefixPreprocessedTraceData.bottomLastCentralLower_of_analyticChange
