import AbelFormalization.CharbonnelClosureComponentBound

#print axioms AbelFormalization.maxwellUniversalAffinePolynomial_map_int
#print axioms AbelFormalization.maxwellAffineRowPolynomial_eval_append
#print axioms AbelFormalization.maxwellUniversalAffinePolynomial_eval_eq_zero_iff
#print axioms AbelFormalization.exists_maxwellUniversalAffinePolynomial_fiber_eq_affineSubspace
#print axioms AbelFormalization.polynomialSignConstructible_maxwellThickening
#print axioms AbelFormalization.isProjectedZeroSet_maxwellThickening
#print axioms AbelFormalization.exists_rank_one_description_maxwellThickening
#print axioms AbelFormalization.exists_maxwellClosureReplacement
