import AbelFormalization.HermiteRankPreprocessedSimultaneousAnalyticData

open AbelFormalization
open AbelFormalization.RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary

#print axioms simultaneousQuantitativeAnalyticParameter_tendsto
#print axioms simultaneousQuantitativePostLogScale_eq_E_succ
#print axioms simultaneousQuantitativeAnalyticAfterValue_central
#print axioms simultaneousQuantitativeAnalyticPrefixValue_eq
#print axioms simultaneousQuantitativeSourceAnalyticChange
#print axioms simultaneousQuantitativeCentralAnalyticChange
#print axioms simultaneousQuantitativeAdjacentAnalyticChange
#print axioms eventually_simultaneousQuantitativeAnalyticSourceIdentity
#print axioms eventually_simultaneousQuantitativeAnalyticCentralIdentity
#print axioms eventually_simultaneousQuantitativeAnalyticAdjacentIdentity
#print axioms simultaneousQuantitativeAnalyticSourceSymbolValue_bound_of_first
#print axioms simultaneousQuantitativeFiniteAnalyticChangeDataOfBounds
#print axioms simultaneousQuantitativeFiniteAnalyticSegmentDataOfBounds
#print axioms nonempty_simultaneousQuantitativeFiniteAnalyticSegmentData_of_bounds
