import AbelFormalization.IndividualCentralNumericQuantitativeTransfer

#print axioms AbelFormalization.IndividualCentralTransferData.DisplayedData.realJet_source_lower_of_central_lower_numeric
#print axioms AbelFormalization.IndividualCentralDisplayedTraceData.boundaryLower_zero_of_last_numeric
#print axioms AbelFormalization.RepresentativeClusterSubsequence.OrderedClusterIndividualDisplayedTraceData.beforeGenerator_lower_of_afterGenerator_lower_numeric
