import AbelFormalization.HermiteRankPreprocessedIndividualQuantitativeInputs

open AbelFormalization

#print axioms RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary.selectedTranslatedParameter_box_tendsto_zero
#print axioms RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary.individualQuantitative_transferHierarchies
#print axioms RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary.individualQuantitativeRealJetSequence_error_superpolynomialDecay
#print axioms RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary.nonempty_finiteMovingCoefficientData
#print axioms RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary.FiniteMovingCoefficientData.coefficientValue_hasPolynomialUpperBound
#print axioms RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary.IndividualBoundaryChain.boundaryData
#print axioms RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary.IndividualBoundaryChain.centralValue_hasPolynomialUpperBound
#print axioms RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary.IndividualBoundaryChain.mainValue_hasPolynomialUpperBound
#print axioms RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary.IndividualBoundaryChain.sourceValue_hasPolynomialUpperBound
#print axioms RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary.IndividualBoundaryChain.jetError_superpolynomialDecay
#print axioms RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary.IndividualBoundaryChain.basepointQuantitativeInputs
