import AbelFormalization.HermiteRankBottomTerminalAnalyticLocalization

#print axioms AbelFormalization.RepresentativeClusterSubsequence.PaperRankHermiteTopPrefixPreprocessedTraceData.bottomClearedTimeTargetOverGerms_eq_sum
#print axioms AbelFormalization.RepresentativeClusterSubsequence.PaperRankHermiteTopPrefixPreprocessedTraceData.bottomClearedTargetRepresentative_eventually_eq
#print axioms AbelFormalization.RepresentativeClusterSubsequence.PaperRankHermiteTopPrefixPreprocessedTraceData.bottomTerminalSourceValue_lower
