import AbelFormalization.HermiteRankIndividualSimultaneousFiniteFamilyCompatibility

open AbelFormalization
open AbelFormalization.RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary

#print axioms eval₂Hom_nestedMvPolynomialFlatteningAlgEquiv
#print axioms analyticPolynomialGermHom_ringHom_of_representative
#print axioms individualSimultaneousForwardNestedPolynomialHom
#print axioms map_individualSimultaneousForwardFlattenedPolynomialHom
#print axioms analyticPolynomialGermHom_individualSimultaneousForward_of
#print axioms individualSimultaneousTransformedTerminal_span_eq_firstSource
#print axioms individualSimultaneousFiniteAnalyticChange
#print axioms eventually_eval_individualSimultaneousForwardFlattened_eq_terminal
#print axioms eventually_individualSimultaneousSourceValue_eq_terminalBoundaryValue
#print axioms eventually_individualSimultaneousTargetValue_eq_firstBeforeValue
#print axioms individualSimultaneousFiniteFamilyCoefficient_hasPolynomialUpperBound
#print axioms eventually_individualSimultaneousFiniteFamilyIdentity
#print axioms individualSimultaneousFiniteFamilyCompatibility
#print axioms nonempty_individualSimultaneousFiniteFamilyCompatibility
