import AbelFormalization.HermiteRankAllClusterBackwardContradiction

open AbelFormalization
open AbelFormalization.RestrictedBaseHermiteRankTopPrefixPreprocessedSequenceBoundary
open AbelFormalization.DiagonalHermiteRankPreprocessedQuantitativeData

#print axioms bottomTerminalLocalizationData
#print axioms individualMixedInitialBoundary_lower_of_terminalSimultaneous_lower_auto
#print axioms bottomSimultaneousQuantitativeFirstBeforeValue_lower_canonical
#print axioms bottomClusterIndividualMixedInitialBoundary_lower
#print axioms nextClusterIndividualMixedInitialBoundary_lower
#print axioms topOrderedCluster
#print axioms topOrderedCluster_val_add_one
#print axioms individualMixedInitialBoundary_lower_all_clusters
#print axioms false_of_allClusterBackwardPropagation
#print axioms false_of_canonicalBackwardPropagation
