import AbelFormalization.CharbonnelSection53GlobalDichotomy

#print axioms AbelFormalization.exists_relativeClosedBall_subset_diff_of_open_point
#print axioms AbelFormalization.exists_localMax_relativeBall_inside
#print axioms AbelFormalization.exists_badAvoiding_localMax_count_le
#print axioms AbelFormalization.charbonnelSection53_stationaryChain_of_noDescentSuccessorChoice
#print axioms AbelFormalization.charbonnelSection53_globalDichotomy_of_successorChoice
#print axioms AbelFormalization.literalZeroSet_charbonnelClosure_section53_globalDichotomy
