import AbelFormalization.CharbonnelSection53StationaryLimitSupport
import AbelFormalization.CharbonnelSardianIntegerAffineSliceLift

open AbelFormalization

#print axioms AbelFormalization.exists_charbonnelSection53_stationaryLimitPoint
#print axioms AbelFormalization.charbonnelSection53_stationaryLimitPoint_unique
#print axioms AbelFormalization.charbonnelSection53_compact_verticalImage_eventually_subset_open
#print axioms AbelFormalization.charbonnelSection53_stationary_verticalImage_eventually_subset_open
#print axioms AbelFormalization.charbonnelSection53_preconnected_subset_one_disjointOpenCover
#print axioms AbelFormalization.exists_charbonnelSection53_stationaryBall_subset_fiberOpenProjections
#print axioms AbelFormalization.charbonnelSection53_stationaryLimit_not_mem_defectiveSupport
#print axioms AbelFormalization.charbonnelSection53_support_eq_ball_of_outside_defectiveUnion
#print axioms AbelFormalization.charbonnelSection53_defect_zero_of_limit_hits_all_components
#print axioms AbelFormalization.charbonnelSection53_noStationary_of_noLimitComponentCollapse
#print axioms AbelFormalization.wilkieAffineSliceExtraInputLinearMap_append
#print axioms AbelFormalization.wilkieAffineSliceOldEquationLift_append
#print axioms AbelFormalization.wilkiePrependTwoParameters_pos_iff
#print axioms AbelFormalization.CharbonnelFiniteSardianFamily.wilkieAffineSliceLift
