import AbelFormalization.OrderedClusterIndividualTraceData

open AbelFormalization

#print axioms AbelFormalization.RepresentativeClusterSubsequence.orderedClusterPrefixIndividualSteps_get
#print axioms AbelFormalization.RepresentativeClusterSubsequence.orderedClusterIndividualIdealBoundary_last
#print axioms AbelFormalization.RepresentativeClusterSubsequence.nonempty_orderedClusterIndividualIdealTraceData
#print axioms AbelFormalization.RepresentativeClusterSubsequence.nonempty_orderedClusterIndividualDisplayedTraceData
#print axioms AbelFormalization.RepresentativeClusterSubsequence.OrderedClusterIndividualDisplayedTraceData.before_span
#print axioms AbelFormalization.RepresentativeClusterSubsequence.OrderedClusterIndividualDisplayedTraceData.after_span_boundary_succ
