import AbelFormalization.WilkieFixedMinorConnectedInterval

#print axioms AbelFormalization.interval_image_of_preconnected_zero_positive
#print axioms AbelFormalization.eq_of_nonempty_relatively_clopen_of_preconnected
#print axioms AbelFormalization.eq_singleton_of_preconnected_finite_inter_open
#print axioms AbelFormalization.squared_interval_image_of_preconnected_minor
#print axioms AbelFormalization.squared_standardJacobianColumnMinor_interval
#print axioms AbelFormalization.squared_standardJacobianColumnMinor_interval_on_levelFiber
