import AbelFormalization.CharbonnelFiniteLocallyClosedReduction

#print axioms AbelFormalization.CharbonnelDescription.hasFiniteLocallyClosedDecomposition
#print axioms AbelFormalization.charbonnelClosure_finiteLocallyClosedDecomposition_of_projection
#print axioms AbelFormalization.literalZeroSet_charbonnelClosure_finiteLocallyClosedDecomposition_of_closedProjection
#print axioms AbelFormalization.charbonnelClosureInteriorRegularity_of_finiteLocallyClosedDecomposition
#print axioms AbelFormalization.charbonnelApproximationTraceSmallness_of_section5Induction_and_closureInteriorRegularity
#print axioms AbelFormalization.literalZeroSet_charbonnelClosure_approximationTraceSmallness_of_section5ClosureRegularity
