import AbelFormalization.CharbonnelClosureInteriorRegularity

#print axioms AbelFormalization.maxwellClosedLiftProjectionTruncation_eq_image
#print axioms AbelFormalization.maxwellClosedLiftProjectionTruncation_isCompact
#print axioms AbelFormalization.iUnion_maxwellClosedLiftProjectionTruncation
#print axioms AbelFormalization.realEuclideanExistentialProjection_isCountableUnionOfClosedSets
#print axioms AbelFormalization.isCountableUnionOfClosedSets_of_closedLift
#print axioms AbelFormalization.IsCountableUnionOfClosedSets.isMeagre_of_interior_eq_empty
#print axioms AbelFormalization.literalZeroSet_charbonnelClosure_isCountableUnionOfClosedSets
#print axioms AbelFormalization.PositiveArityOMinimalWeakSetStructure.isCountableUnionOfClosedSets
#print axioms AbelFormalization.PositiveArityOMinimalWeakSetStructure.isMeagre_of_interior_eq_empty
#print axioms AbelFormalization.maxwellInteriorGapComponentSelection_of_countableUnionClosed
#print axioms AbelFormalization.not_enatCard_connectedComponents_le_of_fin_succ_injection
#print axioms AbelFormalization.maxwellInteriorGapComponentSelection_iff_explosion
#print axioms AbelFormalization.interior_closure_eq_empty_of_maxwellComponentSelection
#print axioms AbelFormalization.maxwellInteriorGapComponentSelection_iff_closureInteriorRegularity
#print axioms AbelFormalization.PositiveArityOMinimalWeakSetStructure.maxwellFiniteAffineSectionComponentBound
#print axioms AbelFormalization.charbonnelClosureInteriorRegularity_of_ws5_and_maxwellComponentSelection
#print axioms AbelFormalization.charbonnelClosureInteriorRegularity_of_ws5_ws6_and_maxwellMeagreSelection
#print axioms AbelFormalization.literalZeroSet_charbonnelClosure_closureInteriorRegularity_of_maxwellComponentSelection
#print axioms AbelFormalization.literalZeroSet_charbonnelClosure_closureInteriorRegularity_of_maxwellMeagreSelection
