import AbelFormalization.CharbonnelWeakStructure

#print axioms AbelFormalization.realEuclideanCoordinatePermutation
#print axioms AbelFormalization.ProjectedZeroWeakStructureCertificate.toPositiveArityOMinimalWeakStructure
#print axioms AbelFormalization.ProjectedZeroWeakStructureCertificate.toPositiveArityDCAllOrders
#print axioms AbelFormalization.ProjectedZeroWeakStructureCertificate.toPositiveArityComplementInput
#print axioms AbelFormalization.projectedZeroPositiveArityComplementInput
#print axioms AbelFormalization.IsAbel.projectedZeroPositiveArityComplementInput
#print axioms AbelFormalization.exists_rank_zero_charbonnelDescription_of_mem
#print axioms AbelFormalization.PositiveArityWeakSetStructure.exists_rank_zero_inter_description
#print axioms AbelFormalization.PositiveArityWeakSetStructure.exists_rank_zero_polynomialSign_description
#print axioms AbelFormalization.PositiveArityWeakSetStructure.exists_rank_zero_prod_description
#print axioms AbelFormalization.PositiveArityWeakSetStructure.exists_rank_zero_linearEquiv_description
#print axioms AbelFormalization.PositiveArityWeakSetStructure.exists_rank_zero_coordinatePermutation_description
#print axioms AbelFormalization.ProjectedZeroWeakStructureCertificate.exists_rank_zero_linearEquiv_description
#print axioms AbelFormalization.PositiveArityOMinimalWeakSetStructure.exists_closed_rank_zero_lift
#print axioms AbelFormalization.PositiveArityDCAllOrders.exists_rank_zero_graph_descriptions
#print axioms AbelFormalization.projectedZeroCharbonnelClosure_union
#print axioms AbelFormalization.projectedZeroCharbonnelClosure_integerAffineInter
#print axioms AbelFormalization.projectedZeroCharbonnelClosure_projection
#print axioms AbelFormalization.projectedZeroCharbonnelClosure_topologicalClosure
#print axioms AbelFormalization.projectedZeroCharbonnelClosure_zero
