import AbelFormalization.CharbonnelClosureNullityWitnesses

#print axioms AbelFormalization.literalZeroSet_charbonnelClosure_semiClosed
#print axioms AbelFormalization.literalZeroSet_charbonnelClosure_nullityCarrier_mem
#print axioms AbelFormalization.charbonnelClosureNullityCarrier_relativelyClosed
#print axioms AbelFormalization.volume_charbonnelClosureNullityCarrier_eq_zero
#print axioms AbelFormalization.charbonnelPositiveZeroTrace_nullityCarrier
#print axioms AbelFormalization.literalZeroSet_charbonnelClosure_hasClosureNullityWitnesses
#print axioms AbelFormalization.literalZeroSet_charbonnelClosure_approximationTraceSmallness_of_section5Inputs
