import AbelFormalization.SmoothFamilyRankStratumLocalFiber

#print axioms AbelFormalization.standardJacobianColumnMinor_selectedOutputMap
#print axioms AbelFormalization.fderiv_selectedOutputMap_surjective_of_standardJacobianMinor_ne_zero
#print axioms AbelFormalization.exists_localProjectionChart_of_standardJacobianMinor_ne_zero
#print axioms AbelFormalization.exists_selectedOutput_localProjectionChart_of_mem_standardJacobianRankLocus
