import AbelFormalization.SeparatedClustersReduction
import AbelFormalization.ClusterLocalizationIdentities
import AbelFormalization.PolynomialGermSymbolMaps
import AbelFormalization.FiniteSupportCoefficientPerturbation

#check MvPolynomial.eval_eq
#check MvPolynomial.eval₂_eq
#check MvPolynomial.eval₂Hom_eq
#check MvPolynomial.eval₂Hom_eq_eval₂
#check MvPolynomial.eval_eq_eval₂
#check MvPolynomial.eval₂Hom_apply
#check MvPolynomial.support_sum_monomial_coeff
#check Finset.sum_subset
#check AbelFormalization.analyticFiniteSupportCoefficientFamily_hasPolynomialUpperBound
#check AbelFormalization.HasPolynomialUpperBound.of_analyticOnNhd_comp
#check Filter.Eventually.filter_mono
#check Filter.Tendsto.eventually
#check Filter.EventuallyLE.filter_mono
