import AbelFormalization.RestrictedBaseSeparatedContradictionInduction

#print axioms AbelFormalization.IsAbel.restrictedBaseRegularZeroFiniteForRepresentativeCount_one_of_separated
#print axioms AbelFormalization.IsAbel.restrictedBaseRegularZeroFiniteForRepresentativeCount_q_add_two_of_separated
#print axioms AbelFormalization.IsAbel.restrictedBaseRegularZeroFiniteForRepresentativeCount_all_of_separatedAtRank
#print axioms AbelFormalization.IsAbel.restrictedBaseRegularZeroFiniteForRepresentativeCount_all_of_separated
#print axioms AbelFormalization.IsAbel.restrictedRegularZeroFiniteForRepresentativeCount_all_levels_of_separated
#print axioms AbelFormalization.restrictedAllUnboundedSeparationSet_infinite_fin_one
#print axioms AbelFormalization.IsAbel.restrictedBaseRegularZeroFiniteForRepresentativeCount_one_of_normalizedSeparated
#print axioms AbelFormalization.IsAbel.restrictedBaseRegularZeroFiniteForRepresentativeCount_q_add_two_of_normalizedSeparated
#print axioms AbelFormalization.IsAbel.restrictedBaseRegularZeroFiniteForRepresentativeCount_all_of_normalizedSeparated
#print axioms AbelFormalization.IsAbel.restrictedRegularZeroFiniteForRepresentativeCount_all_levels_of_normalizedSeparated
