import AbelFormalization.RestrictedPairMergeExceptionalJetGraphLift
import AbelFormalization.OrdinaryHomogenization
#check MvPolynomial.eval₂_eq_sum
#check MvPolynomial.eval₂_monomial
#check MvPolynomial.le_totalDegree
#check Finset.prod_mul_distrib
#check Finset.prod_pow
#check Finset.prod_const
#check Finset.prod_erase_mul
#check Finset.mul_prod_erase
#check Finsupp.sum
#check Finsupp.sum_fintype
#check Finset.le_sup
#check Finset.le_sup_of_mem
#check Finset.sup_le
#check Nat.pow_add
#check pow_add
#check Nat.sub_add_cancel
#check Nat.sub_add_cancel
