import AbelFormalization.CharbonnelApproximationTraceSmallness

#print axioms AbelFormalization.closure_eq_iUnion_closure_charbonnelCompactTruncation
#print axioms AbelFormalization.interior_iUnion_eq_empty_of_closed
#print axioms AbelFormalization.IsLocallyClosed.interior_closure_eq_empty
#print axioms AbelFormalization.charbonnelZeroSection_closure_interior_eq_empty_of_truncations
#print axioms AbelFormalization.volume_prod_eq_zero_of_verticalSections_eq_zero
#print axioms AbelFormalization.volume_prod_eq_zero_of_finite_verticalSections
#print axioms AbelFormalization.volume_prod_eq_zero_of_base_eq_zero_of_sections_off
#print axioms AbelFormalization.volume_base_eq_zero_of_prod_eq_zero_of_sections_ne_zero
#print axioms AbelFormalization.volume_prod_eq_zero_iff_base_eq_zero_of_fiber_dichotomy
#print axioms AbelFormalization.literalZeroSet_charbonnelClosure_section5TraceMembership
#print axioms AbelFormalization.charbonnelQ_of_boundedQ
#print axioms AbelFormalization.charbonnelPPrime_of_compactPositiveVolumeInterior
#print axioms AbelFormalization.charbonnelPPrime_all_of_one_and_analyticStep
#print axioms AbelFormalization.charbonnelInteriorNullity_of_pPrime_and_finiteLocallyClosed
#print axioms AbelFormalization.charbonnelQ_all_of_one_and_analyticStep
#print axioms AbelFormalization.charbonnelP_of_pPrime_Q_and_closureWitness
#print axioms AbelFormalization.charbonnelTheorem21_of_interiorNullity_and_P
#print axioms AbelFormalization.charbonnelTheorem22_of_Q
#print axioms AbelFormalization.charbonnelApproximationTraceSmallness_of_theorems21_22
#print axioms AbelFormalization.charbonnelApproximationTraceSmallness_of_section5
#print axioms AbelFormalization.charbonnelApproximationTraceSmallness_of_section5Induction
