import AbelFormalization.SmoothFamilyJacobianRankStrata

#print axioms AbelFormalization.matrix_le_rank_iff_exists_square_minor_ne_zero
#print axioms AbelFormalization.matrix_rank_le_iff_all_succ_square_minors_eq_zero
#print axioms AbelFormalization.matrix_rank_eq_iff_square_minors
#print axioms AbelFormalization.IsGeometricFunctionFamily.standardJacobianMinor_mem
#print axioms AbelFormalization.standardRectangularJacobian_rank_eq_finrank_range_fderiv
#print axioms AbelFormalization.finrank_range_fderiv_eq_iff_standardJacobianMinors
#print axioms AbelFormalization.IsEverywhereSmoothFunctionFamily.mem_standardJacobianRankLocus_iff
