import AbelFormalization.SmoothFamilyRectangularRankLocus

#print axioms AbelFormalization.standardJacobianRegularLocus_eq_iUnion
#print axioms AbelFormalization.standardJacobianSingularLocus_eq_iInter
#print axioms AbelFormalization.standardJacobianSingularLocus_eq_compl_regularLocus
#print axioms AbelFormalization.IsEverywhereSmoothFunctionFamily.mem_smoothRegularFiber_iff_exists_standardJacobianColumnMinor_ne_zero
#print axioms AbelFormalization.IsEverywhereSmoothFunctionFamily.smoothRegularFiber_eq_fiber_inter_standardJacobianRegularLocus
#print axioms AbelFormalization.IsEverywhereSmoothFunctionFamily.isOpen_standardJacobianRegularLocus
#print axioms AbelFormalization.IsEverywhereSmoothFunctionFamily.isClosed_standardJacobianSingularLocus
#print axioms AbelFormalization.IsEverywhereSmoothFunctionFamily.fiber_diff_smoothRegularFiber_eq_inter_standardJacobianSingularLocus
