import AbelFormalization.WilkieFiniteVisibleProjectionFork

#print axioms AbelFormalization.wilkieFullFiberComponent_compact_of_finite_visible_image
#print axioms AbelFormalization.wilkieFullFiberComponent_localComplementaryNeighborhood_of_squareChart
#print axioms AbelFormalization.wilkieFiniteVisibleImage_sameMinor_zero_of_squareChart
#print axioms AbelFormalization.wilkieFiniteVisibleImage_sameMinor_squared_interval_of_squareChart
