import AbelFormalization.SmoothFamilyRectangularJacobianMinors

#print axioms AbelFormalization.matrix_mulVecLin_surjective_iff_exists_column_minor_ne_zero
#print axioms AbelFormalization.fderiv_eq_standardRectangularJacobian_mulVec
#print axioms AbelFormalization.fderiv_surjective_iff_exists_standardJacobianColumnMinor_ne_zero
#print axioms AbelFormalization.IsGeometricFunctionFamily.standardJacobianColumnMinor_mem
#print axioms AbelFormalization.IsEverywhereSmoothFunctionFamily.fderiv_surjective_iff_exists_standardJacobianColumnMinor_ne_zero
