import AbelFormalization.AbelGeometricFamily

#print axioms AbelFormalization.eval_affinePolynomial
#print axioms AbelFormalization.AbelNumerator.coordinateFDeriv_mem
#print axioms AbelFormalization.isGeometricFunctionFamily_abelGeometricFamily
#print axioms AbelFormalization.IsAbel.isEverywhereSmooth_abelGeometricFamily
#print axioms AbelFormalization.IsAbel.isCoordinateDerivativeClosed_abelGeometricFamily
#print axioms AbelFormalization.IsAbel.geometric_smooth_derivativeClosed_abelGeometricFamily
#print axioms AbelFormalization.Cr_firstCoordinate_mem_abelGeometricFamily
#print axioms AbelFormalization.C0_firstCoordinate_mem_abelGeometricFamily
#print axioms AbelFormalization.affine_sub_Cr_comp_affine_mem_abelGeometricFamily
