import AbelFormalization.GeneralCodimensionLagrangeGenericMorse

#print axioms AbelFormalization.hasStrictFDerivAt_lagrangeSquaredDistanceCriticalFamily_center
#print axioms AbelFormalization.contDiff_lagrangeSquaredDistanceCriticalFamily
#print axioms AbelFormalization.lagrangeSquaredDistanceCriticalFamily_fderiv_range_eq_top
#print axioms AbelFormalization.exists_standardSquaredDistanceCenter_regular_lagrangeCriticalSystem
#print axioms AbelFormalization.IsEverywhereSmoothFunctionFamily.exists_standardSquaredDistanceCenter_regular_lagrangeCriticalSystem
