import AbelFormalization.ProjectedZeroMatrixSections

#print axioms AbelFormalization.matrixFiberMulVecPolynomial_eval_append
#print axioms AbelFormalization.functionTupleInFamily_projectedZeroMatrixFiberMap
#print axioms AbelFormalization.projectedZeroMatrixFiberMap_append_eq_target_iff
#print axioms AbelFormalization.flatProjectedFiberSet_projectedZeroMatrixFiberMap
#print axioms AbelFormalization.exists_projectedZero_matrixSection_component_bound
#print axioms AbelFormalization.IsProjectedZeroSet.exists_matrixSection_component_bound
#print axioms AbelFormalization.exists_abelProjectedZero_matrixSection_component_bound
