import AbelFormalization.GeneralCodimensionLagrange

#print axioms AbelFormalization.lagrangeCriticalSystemMap_append_eq_zero_iff
#print axioms AbelFormalization.IsGeometricFunctionFamily.lagrangeCriticalSystemMap_mem
#print axioms AbelFormalization.IsGeometricFunctionFamily.lagrangeSquaredDistanceCriticalSystemMap_mem
#print axioms AbelFormalization.linearIndependent_constraintFDeriv_components_of_surjective
#print axioms AbelFormalization.exists_lagrangeStationarityCovector_eq_zero_of_isLocalExtrOn
#print axioms AbelFormalization.exists_lagrangeCriticalSystemMap_eq_zero_of_isLocalExtrOn
#print axioms AbelFormalization.lagrangeStationarityCovector_eq_zero_unique_of_surjective
