import AbelFormalization.PaperRankClusterCurrying

#print axioms AbelFormalization.isClusterCoefficientVariable_iff
#print axioms AbelFormalization.eval₂Hom_splitClusterCurryAlgEquiv
#print axioms AbelFormalization.isPaperRankClusterCoefficientVariable_iff
#print axioms AbelFormalization.eval₂Hom_paperRankClusterCurryHom
#print axioms AbelFormalization.span_paperRankClusterCurryHom_eq_curriedIdeal
#print axioms AbelFormalization.isPaperRankOrderedClusterCoefficientVariable_iff
#print axioms AbelFormalization.negativeTerminalWeight_eq_centralTransferShear
#print axioms AbelFormalization.clusterFirstCentralIdeal_eq_transfer
#print axioms AbelFormalization.nonempty_paperRankClusterAlgebraicReductionCertificate
#print axioms AbelFormalization.ClusterAlgebraicReductionCertificate.transferTerminalized
#print axioms AbelFormalization.nonempty_orderedClusterAlgebraicReductionCertificate
#print axioms AbelFormalization.eval₂Hom_paperRankClusterCentralGenerator_eq_initial
