import AbelFormalization.LionRegularCodimensionOne

#print axioms AbelFormalization.IsGeometricFunctionFamily.squaredDistanceCriticalEquation_mem
#print axioms AbelFormalization.IsZeroRegularFunctionFamily.regularZeroSet_univ_finite
#print axioms AbelFormalization.finite_connectedComponents_closed_regular_codimensionOne_locus
#print axioms AbelFormalization.finite_connectedComponents_zeroLocus_codimensionOne
#print axioms AbelFormalization.finite_connectedComponents_fiber_of_surjective_codimensionOne
#print axioms AbelFormalization.forall_exists_component_bound_of_surjective_codimensionOne
#print axioms AbelFormalization.IsAbel.finite_connectedComponents_abelGeometricFiber_of_numerator
