import AbelFormalization.OrderedClusterPreprocessedQuantitativeTrace

#print axioms AbelFormalization.finLastOfZeroOfSucc
#print axioms AbelFormalization.finLastOfBoundaryOfSucc
#print axioms AbelFormalization.RepresentativeClusterSubsequence.OrderedClusterPreprocessedAlgebraicDescent.FullTransferTraceData.clusterBoundaryLower_last_of_boundary
#print axioms AbelFormalization.RepresentativeClusterSubsequence.OrderedClusterPreprocessedAlgebraicDescent.FullTransferTraceData.clusterBoundaryLower_last_of_bottom
#print axioms AbelFormalization.RepresentativeClusterSubsequence.OrderedClusterPreprocessedAlgebraicDescent.FullTransferTraceData.clusterBoundaryLower_last_of_one
