import AbelFormalization.GeneralCodimensionRegularComponents

#print axioms AbelFormalization.exists_injective_connectedComponents_to_lifts
#print axioms AbelFormalization.finite_connectedComponents_of_finite_lifted_componentMinimizers
#print axioms AbelFormalization.componentMinimizer_isLocalMinOn_constraintZeroLocus
#print axioms AbelFormalization.existsUnique_lagrangeCriticalSystemMap_eq_zero_of_componentMinimizer
#print axioms AbelFormalization.finite_connectedComponents_constraintZeroLocus_generalCodimension
#print axioms AbelFormalization.finite_connectedComponents_fiber_of_surjective_generalCodimension
#print axioms AbelFormalization.IsAbel.finite_connectedComponents_abelGeometricFiber_of_numerator_generalCodimension
