import AbelFormalization.SmoothFamilyMaximalRankLocalFiber

#print axioms AbelFormalization.MaximalDerivativeRankCertificate.exists_standardJacobianMinor_ne_zero
#print axioms AbelFormalization.MaximalDerivativeRankCertificate.exists_local_selectedOutput_eq_iff
#print axioms AbelFormalization.MaximalDerivativeRankCertificate.exists_local_fiber_eq_selectedOutput_fiber
#print axioms AbelFormalization.MaximalDerivativeRankCertificate.exists_open_nhds_const_of_rank_zero
