import AbelFormalization.SmoothFamilyConstantRankLocalFiber

#print axioms AbelFormalization.selectedOutputLinearMap_apply
#print axioms AbelFormalization.fderiv_selectedOutputMap_eq_comp
#print axioms AbelFormalization.ker_fderiv_eq_ker_fderiv_selectedOutputMap_of_rank_le
#print axioms AbelFormalization.continuous_standardJacobianMinor_of_contDiff_one
#print axioms AbelFormalization.fderiv_const_fst_openPartialHomeomorph_eq_zero
#print axioms AbelFormalization.exists_open_nhds_eq_of_selectedOutputMap_eq_of_rank_le
#print axioms AbelFormalization.exists_open_nhds_eq_of_fderiv_rank_zero
