import AbelFormalization.OrderedClusterPreprocessedTransferTraceData

open AbelFormalization

#print axioms AbelFormalization.RepresentativeClusterSubsequence.OrderedClusterPreprocessedAlgebraicStage.nonempty_fullTransferTraceData
#print axioms AbelFormalization.RepresentativeClusterSubsequence.OrderedClusterPreprocessedAlgebraicStage.FullTransferTraceData.individual_initial_boundary
#print axioms AbelFormalization.RepresentativeClusterSubsequence.OrderedClusterPreprocessedAlgebraicStage.FullTransferTraceData.individual_terminal_boundary
#print axioms AbelFormalization.RepresentativeClusterSubsequence.OrderedClusterPreprocessedAlgebraicStage.FullTransferTraceData.simultaneous_first_input
#print axioms AbelFormalization.RepresentativeClusterSubsequence.OrderedClusterPreprocessedAlgebraicStage.FullTransferTraceData.simultaneous_first_source_span
