import AbelFormalization.AbelNumeratorRestrictedGraphSystem
import AbelFormalization.RestrictedPairMergeExceptionalFlatSystem
#check ContinuousLinearEquiv.prodComm
#check ContinuousLinearEquiv.prodCongr
#check ContinuousLinearEquiv.trans
#check ContinuousLinearEquiv.refl
#check AbelFormalization.finFunctionProductContinuousLinearEquiv
