import AbelFormalization.WilkieCase2SliceRegularity
import AbelFormalization.WilkieCase2MinorTransport
import AbelFormalization.WilkieCase2FlatJacobianInsertion
import AbelFormalization.WilkieCase2FlatBallMinorIntervalLift
import AbelFormalization.Wilkie28WeakSelectionIncidence
import AbelFormalization.WilkieZeroVisibleVerticalMinor

#print axioms AbelFormalization.wilkie_case2_visible_ball_slice_regular_nonempty_bounded
#print axioms AbelFormalization.wilkieCase2_sliceMinor_squared_interval_transport
#print axioms AbelFormalization.wilkieCase2_flatJacobian_coordinateInsert
#print axioms AbelFormalization.wilkieCase2_ballSliceMinor_squared_interval_lift
#print axioms AbelFormalization.wilkie28WeakSelectionIncidence_sourceData
#print axioms AbelFormalization.wilkieZeroVisible_verticalMinor_ne_zero_of_regular
