import AbelFormalization.CharbonnelSardianEmptyInterior

#print axioms AbelFormalization.CharbonnelSardianConstituent.graphMap
#print axioms AbelFormalization.CharbonnelSardianConstituent.graphMap_contDiff
#print axioms AbelFormalization.CharbonnelSardianConstituent.graphMap_differentiable
#print axioms AbelFormalization.CharbonnelSardianConstituent.graphMap_finrank_lt
#print axioms AbelFormalization.CharbonnelSardianConstituent.carrier_subset_range_graphMap
#print axioms AbelFormalization.CharbonnelSardianConstituent.graphMap_range_hausdorffMeasure_eq_zero
#print axioms AbelFormalization.CharbonnelSardianConstituent.carrier_hausdorffMeasure_eq_zero
#print axioms AbelFormalization.CharbonnelSardianConstituent.carrier_interior_eq_empty
#print axioms AbelFormalization.CharbonnelSardianSet.carrier_hausdorffMeasure_eq_zero
#print axioms AbelFormalization.CharbonnelSardianSet.carrier_interior_eq_empty
#print axioms AbelFormalization.CharbonnelPaddedSardianConstituent.graphInput
#print axioms AbelFormalization.CharbonnelPaddedSardianConstituent.graphInput_contDiff
#print axioms AbelFormalization.CharbonnelPaddedSardianConstituent.trailingInputIndex
#print axioms AbelFormalization.CharbonnelPaddedSardianConstituent.graphMap
#print axioms AbelFormalization.CharbonnelPaddedSardianConstituent.graphMap_contDiff
#print axioms AbelFormalization.CharbonnelPaddedSardianConstituent.graphMap_differentiable
#print axioms AbelFormalization.CharbonnelPaddedSardianConstituent.graphMap_finrank_lt
#print axioms AbelFormalization.CharbonnelPaddedSardianConstituent.graphWitnessInput
#print axioms AbelFormalization.CharbonnelPaddedSardianConstituent.carrier_subset_range_graphMap
#print axioms AbelFormalization.CharbonnelPaddedSardianConstituent.graphMap_range_hausdorffMeasure_eq_zero
#print axioms AbelFormalization.CharbonnelPaddedSardianConstituent.carrier_hausdorffMeasure_eq_zero
#print axioms AbelFormalization.CharbonnelPaddedSardianConstituent.carrier_interior_eq_empty
#print axioms AbelFormalization.CharbonnelFiniteSardianFamily.carrier_hausdorffMeasure_eq_zero
#print axioms AbelFormalization.CharbonnelFiniteSardianFamily.carrier_interior_eq_empty
