import AbelFormalization.WilkieVerticalMinorProjectionFork

#print axioms AbelFormalization.closure_connectedComponentIn_inter_of_closed
#print axioms AbelFormalization.relatively_closed_image_of_bounded_relatively_closed
#print axioms AbelFormalization.relatively_open_image_of_local_projected_neighborhoods
#print axioms AbelFormalization.wilkieVerticalMinor_component_projection_eq_of_localOpen
