import AbelFormalization.SmoothFamilyRankStratumFiberReduction

#print axioms AbelFormalization.connectedComponentsCoverMap_surjective
#print axioms AbelFormalization.finite_connectedComponents_of_finite_iUnion_cover
#print axioms AbelFormalization.enatCard_connectedComponents_le_coverSigma
#print axioms AbelFormalization.iUnion_standardJacobianRankFiberPiece_eq_univ
#print axioms AbelFormalization.finite_connectedComponents_fiber_of_finite_rank_pieces
#print axioms AbelFormalization.forall_target_finite_connectedComponents_fiber_of_targetwise_rank_pieces
#print axioms AbelFormalization.exists_uniform_fiber_component_bound_of_uniform_rank_piece_cover_bound
#print axioms AbelFormalization.forall_target_finite_connectedComponents_fiber_of_family_rank_pieces
#print axioms AbelFormalization.HasUniformRankFiberPieceCoverBoundsForFamily.hasUniformFiberFiniteness
