import AbelFormalization.WilkieCase2CombinatorialDescent
import AbelFormalization.Wilkie28SelectionComposition
import AbelFormalization.CharbonnelSardianProjectionRadialFiniteCover

#print axioms AbelFormalization.case2_induction
#print axioms AbelFormalization.exists_fiber_point_with_good_visible_coordinate
#print axioms AbelFormalization.wilkie28_smoothSingularWitnessSelection_of_weakSelection_and_aeSmooth
#print axioms AbelFormalization.exists_finiteCover_radial_projected_small_levels
