import AbelFormalization.ClosedZeroSetCharbonnelBridge

#print axioms AbelFormalization.IsLiteralZeroSet
#print axioms AbelFormalization.literalZeroSetFamily
#print axioms AbelFormalization.literalZeroSet_polynomial_mem
#print axioms AbelFormalization.IsLiteralZeroSet.isClosed
#print axioms AbelFormalization.literalZeroSetFamily_isClosed
#print axioms AbelFormalization.IsLiteralZeroSet.inter
#print axioms AbelFormalization.IsLiteralZeroSet.prod
#print axioms AbelFormalization.IsLiteralZeroSet.linearEquiv_image
#print axioms AbelFormalization.literalZeroSetFamily_linearEquiv_image_mem
#print axioms AbelFormalization.IsLiteralZeroSet.coordinateReindex_image
#print axioms AbelFormalization.literalZeroSetFamily_finAddAssoc_reindex_mem
#print axioms AbelFormalization.literalZeroSetFamily_finAddFlip_reindex_mem
#print axioms AbelFormalization.literalZeroSetFamily_descriptionReindexBase
#print axioms AbelFormalization.literalZeroSetFamily_closedDescriptionBase
#print axioms AbelFormalization.literalZeroSetFamily_exists_coordinateReindex_description
#print axioms AbelFormalization.literalZeroSetFamily_exists_product_description
#print axioms AbelFormalization.literalZeroSetFamily_exists_inter_description
#print axioms AbelFormalization.IsProjectedZeroSet.exists_literalZeroSet_projection
#print axioms AbelFormalization.IsProjectedZeroSet.exists_closed_literalZeroSet_projection
#print axioms AbelFormalization.IsProjectedZeroSet.exists_rank_one_literalZero_description
#print axioms AbelFormalization.IsProjectedZeroSet.mem_literalZeroSet_charbonnelClosure
#print axioms AbelFormalization.projectedZeroSetFamily_subset_literalZeroSet_charbonnelClosure
#print axioms AbelFormalization.projectedZeroSetFamily_closedLiteralCharbonnelBridge
#print axioms AbelFormalization.literalZeroSet_charbonnelClosure_product
#print axioms AbelFormalization.literalZeroSet_charbonnelClosure_inter
