import AbelFormalization.CharbonnelDescriptionAlgebra

#print axioms AbelFormalization.realEuclideanCoordinateReindex
#print axioms AbelFormalization.IsIntegerAffineSet.coordinateReindex_image
#print axioms AbelFormalization.IsIntegerAffineSet.inter
#print axioms AbelFormalization.IsIntegerAffineSet.prod_univ_right
#print axioms AbelFormalization.IsIntegerAffineSet.univ_prod_left
#print axioms AbelFormalization.sum_realEuclideanDiagonalIntegerCoeff
#print axioms AbelFormalization.isIntegerAffineSet_realEuclideanDiagonal
#print axioms AbelFormalization.IsIntegerAffineSet.isClosed
#print axioms AbelFormalization.PositiveArityWeakSetStructure.toDescriptionReindexBase
#print axioms AbelFormalization.PositiveArityWeakSetStructure.toClosedDescriptionBase
#print axioms AbelFormalization.PositiveArityDescriptionReindexBase.exists_coordinateReindex_description
#print axioms AbelFormalization.PositiveArityWeakSetStructure.exists_coordinateReindex_description
#print axioms AbelFormalization.closure_realEuclideanSetProduct
#print axioms AbelFormalization.ClosedPositiveArityDescriptionBase.exists_product_description
#print axioms AbelFormalization.ClosedPositiveArityDescriptionBase.exists_inter_description
#print axioms AbelFormalization.PositiveArityWeakSetStructure.exists_product_description
#print axioms AbelFormalization.PositiveArityWeakSetStructure.exists_inter_description
#print axioms AbelFormalization.ClosedPositiveArityDescriptionBase.charbonnelClosure_product
#print axioms AbelFormalization.ClosedPositiveArityDescriptionBase.charbonnelClosure_inter
#print axioms AbelFormalization.charbonnelClosure_product
#print axioms AbelFormalization.charbonnelClosure_inter
