import AbelFormalization.RestrictedExpressionTower
import Mathlib.Algebra.MvPolynomial.Variables

/-!
# Finite polynomial representations of generated expression algebras

Membership in an algebra generated by an arbitrary set uses only finitely
many actual generators.  This file packages that consequence of mathlib's
multivariate-polynomial description of `Algebra.adjoin`, and specializes it
to the restricted expression base.
-/

noncomputable section

open Set

namespace AbelFormalization

set_option autoImplicit false

/-- Every element of an algebra generated by an arbitrary set is the value
of a polynomial in a finite subset of the actual generators. -/
theorem exists_finite_aeval_of_mem_adjoin
    {R A : Type*} [CommSemiring R] [CommSemiring A] [Algebra R A]
    {s : Set A} {x : A} (hx : x ∈ Algebra.adjoin R s) :
    ∃ t : Finset s, ∃ P : MvPolynomial t R,
      MvPolynomial.aeval (fun i : t ↦ (i.1.1 : A)) P = x := by
  rw [Algebra.adjoin_eq_range, AlgHom.mem_range] at hx
  obtain ⟨P, hP⟩ := hx
  obtain ⟨Q, hQ⟩ := P.exists_rename_coe_vars_eq
  refine ⟨P.vars, Q, ?_⟩
  calc
    MvPolynomial.aeval (fun i : P.vars ↦ (i.1.1 : A)) Q =
        MvPolynomial.aeval ((↑) : s → A)
          (MvPolynomial.rename ((↑) : P.vars → s) Q) := by
      symm
      calc
        MvPolynomial.aeval ((↑) : s → A)
            (MvPolynomial.rename ((↑) : P.vars → s) Q) =
            MvPolynomial.aeval
              (((↑) : s → A) ∘ ((↑) : P.vars → s)) Q :=
          MvPolynomial.aeval_rename
            ((↑) : P.vars → s) ((↑) : s → A) Q
        _ = MvPolynomial.aeval
            (fun i : P.vars ↦ (i.1.1 : A)) Q := by rfl
    _ = x := by rw [hQ, hP]

/-- Every member of a restricted expression base is a polynomial in a
finite subset of its fixed and special generators. -/
theorem exists_finite_aeval_of_mem_restrictedExpressionBase
    {m p a : ℕ} (D : RestrictedBox p)
    (specialGenerators : Set (RestrictedSource m p a → ℝ))
    {f : RestrictedSource m p a → ℝ}
    (hf : f ∈ restrictedExpressionBase D specialGenerators) :
    ∃ t : Finset
        {g : RestrictedSource m p a → ℝ //
          g ∈ restrictedFixedGenerators D ∪ specialGenerators},
      ∃ P : MvPolynomial t ℝ,
        MvPolynomial.aeval
          (fun i : t ↦ (i.1.1 : RestrictedSource m p a → ℝ)) P = f := by
  change f ∈ Algebra.adjoin ℝ
    (restrictedFixedGenerators D ∪ specialGenerators) at hf
  exact exists_finite_aeval_of_mem_adjoin hf

end AbelFormalization
